const QUESTIONS = Array.isArray(window.LOCAL_QUESTIONS) ? window.LOCAL_QUESTIONS : [];
const ESSAYS = Array.isArray(window.ESSAY_PROMPTS) ? window.ESSAY_PROMPTS : [];
const TERMS = Array.isArray(window.TERM_PROMPTS) ? window.TERM_PROMPTS : [];
const SOURCES = Array.isArray(window.EXAM_SOURCES) ? window.EXAM_SOURCES : [];
const STORAGE_KEY = 'musicTeacherExamStatsV1';
const THEME_KEY = 'musicTeacherExamThemeV1';
const $ = id => document.getElementById(id);
const views = ['homeView','quizView','termView','essayView','resultView'];
let quiz = [], quizIndex = 0, quizCorrect = 0, lastMode = 'random10', currentEssay = null, currentTerm = null, questionLocked=false;
function defaultStats(){ return { attempts:{}, wrong:[], unknown:[], daily:{}, topics:{} }; }
function loadStats(){ try { const s={...defaultStats(), ...(JSON.parse(localStorage.getItem(STORAGE_KEY)) || {})};s.wrong=Array.isArray(s.wrong)?s.wrong:[];s.unknown=Array.isArray(s.unknown)?s.unknown:[];return s; } catch { return defaultStats(); } }
function saveStats(stats){ localStorage.setItem(STORAGE_KEY, JSON.stringify(stats)); }
function todayKey(){ const d=new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; }
function shuffle(items){ const a=[...items]; for(let i=a.length-1;i>0;i--){ const j=Math.floor(Math.random()*(i+1)); [a[i],a[j]]=[a[j],a[i]]; } return a; }
function masteryLevel(q,stats=loadStats()){const a=stats.attempts?.[q.id];if(!a)return 0;if((stats.unknown||[]).includes(q.id)||(stats.wrong||[]).includes(q.id))return 0;const total=a.total||0,acc=total?(a.correct||0)/total:0,streak=a.streak||0;if(total>=5&&acc>=.9&&streak>=5)return 3;if(total>=3&&acc>=.8&&streak>=3)return 2;if(total>=2&&acc>=.7&&streak>=2)return 1;return 0;}
function smartOrder(items,stats=loadStats()){return [...items].map(q=>{const m=masteryLevel(q,stats);const unknown=(stats.unknown||[]).includes(q.id),wrong=(stats.wrong||[]).includes(q.id);let weight=unknown?12:wrong?9:m===0?6:m===1?3:m===2?1.3:.45;return{q,key:Math.pow(Math.random(),1/weight)}}).sort((a,b)=>b.key-a.key).map(x=>x.q);}
function showView(id){ views.forEach(v => $(v)?.classList.toggle('active', v===id)); window.scrollTo({top:0,behavior:'smooth'}); }
function calcAccuracy(filter){ const stats=loadStats(); let correct=0,total=0; QUESTIONS.filter(filter).forEach(q=>{ const a=stats.attempts[q.id]; if(a){ correct+=a.correct||0; total+=a.total||0; } }); return total ? Math.round(correct/total*100) : null; }
function escapeHtml(s=''){ return String(s).replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c])); }
function renderHome(){const stats=loadStats();$('totalQuestions').textContent=QUESTIONS.length;const sourced=QUESTIONS.filter(q=>q.source_type&&q.source_type!=='自編練習').length;$('dataStatus').textContent=`目前 ${QUESTIONS.length} 題選擇題＋${TERMS.length} 題名詞解釋＋${ESSAYS.length} 題申論／試教挑戰，其中 ${sourced} 題選擇題具近年考點來源標示。`;$('todayPractice').textContent=stats.daily?.[todayKey()]||0;$('juniorAccuracy').textContent=calcAccuracy(q=>q.subject==='國中音樂')??'--';$('seniorAccuracy').textContent=calcAccuracy(q=>q.subject==='高中音樂')??'--';$('eduAccuracy').textContent=calcAccuracy(q=>q.subject==='教育專業')??'--';$('wrongCount').textContent=(stats.wrong||[]).length;const u=$('unknownCount');if(u)u.textContent=(stats.unknown||[]).length;const topicEntries=Object.entries(stats.topics||{}).filter(([,v])=>v.total>0).map(([topic,v])=>({topic,total:v.total,correct:v.correct,acc:Math.round(v.correct/v.total*100)})).sort((a,b)=>a.acc-b.acc||b.total-a.total);$('weakestTopic').textContent=topicEntries.length?`${topicEntries[0].topic} ${topicEntries[0].acc}%`:'尚無資料';const box=$('weaknessList');if(!topicEntries.length){box.innerHTML='<p class="muted">作答後會開始分析。</p>';return;}box.innerHTML=topicEntries.slice(0,8).map(x=>`<div class="weak-row"><div class="weak-label">${escapeHtml(x.topic)}</div><div class="weak-bar"><span style="width:${x.acc}%"></span></div><div class="weak-score">${x.acc}% · ${x.total}題次</div></div>`).join('');}
function filteredPool(){const year=$('yearFilter')?.value||'',subject=$('subjectFilter')?.value||'',topic=$('topicFilter')?.value||'';return QUESTIONS.filter(q=>(!year||q.year===year)&&(!subject||q.subject===subject)&&(!topic||q.topic===topic));}
function populateFilters(){const yearEl=$('yearFilter'),topicEl=$('topicFilter');if(!yearEl||!topicEl)return;const years=[...new Set(QUESTIONS.map(q=>q.year).filter(Boolean))].sort((a,b)=>Number(b)-Number(a));const topics=[...new Set(QUESTIONS.map(q=>q.topic).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'zh-Hant'));yearEl.innerHTML='<option value="">全部年度</option>'+years.map(y=>`<option value="${escapeHtml(y)}">${escapeHtml(y)} 年</option>`).join('');topicEl.innerHTML='<option value="">全部主題</option>'+topics.map(t=>`<option value="${escapeHtml(t)}">${escapeHtml(t)}</option>`).join('');}
function updateFilterCount(){if($('filterCount'))$('filterCount').textContent=`目前條件可練習 ${filteredPool().length} 題。`;}
function renderSourceIndex(){const box=$('sourceIndex');if(!box)return;if(!SOURCES.length){box.innerHTML='<p class="muted">官方來源索引整理中。</p>';return;}box.innerHTML=SOURCES.map(s=>`<a class="mode-card" href="${escapeHtml(s.url)}" target="_blank" rel="noopener noreferrer"><b>${escapeHtml(s.year)}｜${escapeHtml(s.level)}</b><small>${escapeHtml(s.school)}<br>${escapeHtml(s.status)}</small></a>`).join('');}
function startQuiz(mode){lastMode=mode;const stats=loadStats();let pool=QUESTIONS;if(mode==='junior')pool=QUESTIONS.filter(q=>q.subject==='國中音樂');if(mode==='senior')pool=QUESTIONS.filter(q=>q.subject==='高中音樂');if(mode==='education')pool=QUESTIONS.filter(q=>q.subject==='教育專業');if(mode==='wrong')pool=QUESTIONS.filter(q=>(stats.wrong||[]).includes(q.id));if(mode==='unknown')pool=QUESTIONS.filter(q=>(stats.unknown||[]).includes(q.id));if(mode==='filtered')pool=filteredPool();if(mode==='wrong'&&!pool.length){alert('目前沒有錯題，先去做幾題吧！');return;}if(mode==='unknown'&&!pool.length){alert('目前沒有「不知道」的題目。遇到沒把握的題目時，按 ❓ 我不知道，就會收進這裡。');return;}if(mode==='filtered'&&!pool.length){alert('目前篩選條件沒有題目，請調整年度、學段或主題。');return;}quiz=(mode==='wrong'||mode==='unknown')?shuffle(pool):smartOrder(pool,stats);if(mode==='random10')quiz=quiz.slice(0,Math.min(10,quiz.length));quizIndex=0;quizCorrect=0;showView('quizView');renderQuestion();}
function startCustomQuiz(pool,label='自訂練習',limit=10){const cleaned=[...new Map((Array.isArray(pool)?pool:[]).filter(Boolean).map(q=>[q.id,q])).values()];if(!cleaned.length){alert('目前沒有符合條件的題目。');return;}lastMode='custom';quiz=smartOrder(cleaned).slice(0,Math.min(limit||cleaned.length,cleaned.length));quizIndex=0;quizCorrect=0;showView('quizView');renderQuestion();if($('quizScore'))$('quizScore').textContent=`${label} · 答對 0`;}
window.MusicTeacherExam={questions:QUESTIONS,essays:ESSAYS,terms:TERMS,loadStats,startQuiz,startCustomQuiz,showView,masteryLevel,smartOrder};
function renderQuestion(){const q=quiz[quizIndex];if(!q){finishQuiz();return;}questionLocked=false;$('questionProgress').textContent=`${quizIndex+1} / ${quiz.length}`;$('quizScore').textContent=`答對 ${quizCorrect}`;$('progressBar').style.width=`${quizIndex/quiz.length*100}%`;$('questionSubject').textContent=q.subject;$('questionTopic').textContent=q.topic;$('questionLevel').textContent=q.year?`${q.level} · ${q.year}年`:q.level;$('questionText').textContent=q.question;$('feedback').classList.add('hidden');$('nextBtn').classList.add('hidden');const options=[['A',q.option_a],['B',q.option_b],['C',q.option_c],['D',q.option_d]];$('options').innerHTML=options.map(([k,t])=>`<button class="option-btn" data-choice="${k}"><b>${k}.</b> ${escapeHtml(t)}</button>`).join('')+`<button class="ghost wide unknown-btn" id="unknownBtn" type="button" style="margin-top:10px">❓ 我不知道／先列入複習</button>`;document.querySelectorAll('.option-btn').forEach(btn=>btn.addEventListener('click',()=>answerQuestion(btn.dataset.choice)));$('unknownBtn')?.addEventListener('click',markUnknown);}
function showFeedback(q,title){$('feedbackTitle').textContent=title;$('explanation').textContent=q.explanation;const meta=[q.year?`${q.year}年`:null,q.exam,q.source_type].filter(Boolean).map(escapeHtml).join('｜');const sourceTitle=escapeHtml(q.source_title||'練習題');const sourceLink=q.source_url?`<br><a href="${escapeHtml(q.source_url)}" target="_blank" rel="noopener noreferrer">🔗 查看來源／核對考點</a>`:'';$('sourceBox').innerHTML=`${meta?`<b>${meta}</b><br>`:''}來源標示：${sourceTitle}<br>題號：${escapeHtml(q.id)}${sourceLink}`;$('feedback').classList.remove('hidden');$('nextBtn').classList.remove('hidden');}
function lockOptions(q,choice=''){document.querySelectorAll('.option-btn').forEach(btn=>{btn.disabled=true;if(btn.dataset.choice===q.answer)btn.classList.add('correct');if(choice&&btn.dataset.choice===choice&&choice!==q.answer)btn.classList.add('wrong');});const u=$('unknownBtn');if(u)u.disabled=true;}
function answerQuestion(choice){if(questionLocked)return;questionLocked=true;const q=quiz[quizIndex],correct=choice===q.answer;if(correct)quizCorrect++;lockOptions(q,choice);showFeedback(q,correct?'✅ 答對了':`❌ 正確答案是 ${q.answer}`);recordAttempt(q,correct,'answer');}
function markUnknown(){if(questionLocked)return;questionLocked=true;const q=quiz[quizIndex];lockOptions(q);showFeedback(q,`❓ 已列入「我不知道」｜正確答案是 ${q.answer}`);recordAttempt(q,false,'unknown');}
function recordAttempt(q,correct,status='answer'){const stats=loadStats();stats.attempts[q.id]=stats.attempts[q.id]||{total:0,correct:0,unknown:0,streak:0};const a=stats.attempts[q.id];a.total++;if(correct)a.correct++;if(status==='unknown')a.unknown=(a.unknown||0)+1;a.streak=correct?(a.streak||0)+1:0;a.lastStatus=status==='unknown'?'unknown':correct?'correct':'wrong';a.lastAt=Date.now();stats.topics[q.topic]=stats.topics[q.topic]||{total:0,correct:0};stats.topics[q.topic].total++;if(correct)stats.topics[q.topic].correct++;stats.daily=stats.daily||{};stats.daily[todayKey()]=(stats.daily[todayKey()]||0)+1;const wrong=new Set(stats.wrong||[]),unknown=new Set(stats.unknown||[]);if(status==='unknown'){unknown.add(q.id);wrong.delete(q.id);}else if(correct){wrong.delete(q.id);unknown.delete(q.id);}else{wrong.add(q.id);unknown.delete(q.id);}stats.wrong=[...wrong];stats.unknown=[...unknown];saveStats(stats);}
function nextQuestion(){quizIndex++;if(quizIndex>=quiz.length)finishQuiz();else renderQuestion();}
function finishQuiz(){const pct=quiz.length?Math.round(quizCorrect/quiz.length*100):0;$('resultScore').textContent=pct;$('resultEmoji').textContent=pct>=90?'🏆':pct>=70?'🎉':pct>=50?'💪':'🌱';$('resultTitle').textContent=pct>=80?'這輪很穩！':'完成一輪了！';$('resultSummary').textContent=`本次 ${quiz.length} 題，答對 ${quizCorrect} 題。答錯與「不知道」會優先再出；連續答對且正確率穩定的題目會逐步降低出題機率。`;$('progressBar').style.width='100%';showView('resultView');renderHome();}
function drawTerm(){if(!TERMS.length)return;const choices=TERMS.filter(x=>!currentTerm||x.id!==currentTerm.id);currentTerm=(choices.length?choices:TERMS)[Math.floor(Math.random()*(choices.length||TERMS.length))];$('termLevel').textContent=currentTerm.level;$('termTopic').textContent=currentTerm.topic;$('termName').textContent=currentTerm.term;$('termZh').textContent=currentTerm.zh||'';$('termAnswer').classList.add('hidden');$('termAnswer').innerHTML='';}
function openTerms(){drawTerm();showView('termView');}
function showTermAnswer(){if(!currentTerm)return;$('termAnswer').innerHTML=`<div class="feedback-title">📖 核心定義</div><p>${escapeHtml(currentTerm.definition)}</p><div class="feedback-title">🎯 教甄答題重點</div><p>${escapeHtml(currentTerm.exam)}</p><div class="source-box">相關：${escapeHtml(currentTerm.related||'')}</div>`;$('termAnswer').classList.remove('hidden');}
function drawEssay(){if(!ESSAYS.length)return;const choices=ESSAYS.filter(x=>!currentEssay||x.id!==currentEssay.id);currentEssay=(choices.length?choices:ESSAYS)[Math.floor(Math.random()*(choices.length||ESSAYS.length))];$('essayLevel').textContent=currentEssay.level;$('essayTopic').textContent=currentEssay.topic;$('essayQuestion').textContent=currentEssay.question;$('essayAnswer').value='';$('essayHint').classList.add('hidden');$('essayHint').innerHTML='';}
function openEssay(){drawEssay();showView('essayView');}
function showEssayHint(){if(!currentEssay)return;$('essayHint').innerHTML=`<div class="feedback-title">💡 答題提示</div><p>${escapeHtml(currentEssay.hint)}</p>`;$('essayHint').classList.remove('hidden');}
function applyTheme(){const dark=localStorage.getItem(THEME_KEY)==='dark';document.body.classList.toggle('dark',dark);$('themeBtn').textContent=dark?'☀️':'🌙';}
function toggleTheme(){localStorage.setItem(THEME_KEY,document.body.classList.contains('dark')?'light':'dark');applyTheme();}
window.addEventListener('DOMContentLoaded',()=>{applyTheme();populateFilters();renderSourceIndex();updateFilterCount();renderHome();document.querySelectorAll('[data-mode]').forEach(btn=>btn.addEventListener('click',()=>startQuiz(btn.dataset.mode)));['yearFilter','subjectFilter','topicFilter'].forEach(id=>$(id)?.addEventListener('change',updateFilterCount));$('filteredQuizBtn')?.addEventListener('click',()=>startQuiz('filtered'));$('nextBtn').addEventListener('click',nextQuestion);$('quitBtn').addEventListener('click',()=>{showView('homeView');renderHome();});$('homeBtn').addEventListener('click',()=>{showView('homeView');renderHome();});$('retryBtn').addEventListener('click',()=>lastMode==='custom'?showView('homeView'):startQuiz(lastMode));$('termBtn')?.addEventListener('click',openTerms);$('termBackBtn')?.addEventListener('click',()=>{showView('homeView');renderHome();});$('showTermBtn')?.addEventListener('click',showTermAnswer);$('nextTermBtn')?.addEventListener('click',drawTerm);$('essayBtn').addEventListener('click',openEssay);$('essayBackBtn').addEventListener('click',()=>{showView('homeView');renderHome();});$('showHintBtn').addEventListener('click',showEssayHint);$('nextEssayBtn').addEventListener('click',drawEssay);$('themeBtn').addEventListener('click',toggleTheme);$('resetBtn').addEventListener('click',()=>{if(confirm('確定要清除這個裝置上的所有作答紀錄嗎？')){localStorage.removeItem(STORAGE_KEY);renderHome();}});});