// 115 高頻衝刺｜易混淆追蹤與弱點診斷
(function(){
  if(window.__CONFUSION115_LOADED__) return;
  window.__CONFUSION115_LOADED__=true;
  var KEY='musicTeacherExamConfusions115V1';
  function load(){try{return JSON.parse(localStorage.getItem(KEY))||{}}catch(e){return {}}}
  function save(s){localStorage.setItem(KEY,JSON.stringify(s||{}))}
  function pairKey(a,b){return [String(a||''),String(b||'')].sort().join(' ↔ ')}
  function bump(a,b,status){var s=load(),k=pairKey(a,b),x=s[k]||{confused:0,mastered:0,last:null};if(status==='confused')x.confused++;else x.mastered++;x.last=status;x.updatedAt=Date.now();s[k]=x;save(s);renderDiagnosis()}
  function topConfusions(){return Object.entries(load()).map(function(e){return {pair:e[0],confused:e[1].confused||0,mastered:e[1].mastered||0,last:e[1].last}}).sort(function(a,b){return (b.confused-b.mastered)-(a.confused-a.mastered)||b.confused-a.confused}).filter(function(x){return x.confused>0}).slice(0,3)}
  function esc(s){return String(s||'').replace(/[&<>\"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]})}
  function renderDiagnosis(){var sec=document.getElementById('hf115Section');if(!sec)return;var old=document.getElementById('hf115Diagnosis');if(old)old.remove();var top=topConfusions();var box=document.createElement('div');box.id='hf115Diagnosis';box.className='hf115-oral-card';box.style.marginTop='12px';box.innerHTML='<span class="eyebrow">自學診斷</span><h3>👹 最常搞混 TOP 3</h3>'+(top.length?top.map(function(x,i){var net=Math.max(0,x.confused-x.mastered);return '<div style="padding:10px 0;border-bottom:1px solid rgba(127,127,127,.12)"><b>#'+(i+1)+' '+esc(x.pair)+'</b><div class="hf115-note">混淆 '+x.confused+' 次｜已掌握 '+x.mastered+' 次｜目前需加強指數 '+net+'</div></div>'}).join(''):'<p class="muted">完成幾組「易混淆PK」後，這裡會開始診斷。</p>');var grid=sec.querySelector('#hf115Grid');if(grid)sec.querySelector('.hf115-wrap').insertBefore(box,grid)}
  function enhanceBattle(){var sec=document.getElementById('hf115Section');if(!sec)return false;var battle=sec.querySelector('#hf115Battle');if(!battle)return false;if(battle.querySelector('#hf115ConfusedBtn'))return true;var actions=battle.querySelector('.hf115-oral-actions');if(!actions)return false;var confused=document.createElement('button');confused.id='hf115ConfusedBtn';confused.className='ghost';confused.textContent='😵 還會搞混';var mastered=document.createElement('button');mastered.id='hf115MasteredBtn';mastered.className='ghost';mastered.textContent='✅ 我會了';actions.appendChild(confused);actions.appendChild(mastered);function currentPair(){var fs=battle.querySelectorAll('.hf115-fighter');return fs.length>=2?[fs[0].textContent,fs[1].textContent]:['','']}confused.addEventListener('click',function(){var p=currentPair();bump(p[0],p[1],'confused');confused.textContent='😵 已記錄';setTimeout(function(){confused.textContent='😵 還會搞混'},900)});mastered.addEventListener('click',function(){var p=currentPair();bump(p[0],p[1],'mastered');mastered.textContent='✅ 已記錄';setTimeout(function(){mastered.textContent='✅ 我會了'},900)});renderDiagnosis();return true}
  function confusionTokens(){return topConfusions().flatMap(function(x){return x.pair.split(' ↔ ').map(function(s){return s.toLowerCase()})})}
  function questionText(q){return [q.topic,q.question,q.explanation,q.source_title,q.exam].filter(Boolean).join(' ').toLowerCase()}
  function prioritizePool(pool){var toks=confusionTokens();if(!toks.length)return pool;return (pool||[]).map(function(q){var txt=questionText(q),m=toks.reduce(function(n,t){return n+(txt.includes(t)?1:0)},0);return{q:q,m:m}}).sort(function(a,b){return b.m-a.m||Math.random()-.5}).map(function(x){return x.q})}
  function patchQuizApi(){var api=window.MusicTeacherExam;if(!api||!api.startCustomQuiz||api.__confusionPatched)return false;var original=api.startCustomQuiz;api.startCustomQuiz=function(pool,label,limit){if(String(label||'').includes('高頻'))pool=prioritizePool(pool);return original.call(api,pool,label,limit)};api.__confusionPatched=true;return true}
  function boot(){var tries=0,t=setInterval(function(){tries++;var a=enhanceBattle(),b=patchQuizApi();if(a&&b)clearInterval(t);if(tries>60)clearInterval(t)},120)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
  window.Confusion115={load:load,top:topConfusions,tokens:confusionTokens,prioritize:prioritizePool};
})();
