(()=>{
 if(window.__DAILY_MISSION_V6__)return;window.__DAILY_MISSION_V6__=true;
 const STATS='musicTeacherExamStatsV1',SRS='musicTeacherExamSpacedReviewV1',FOCUS='musicTeacherExamNoteFocusV1',PROGRESS='musicTeacherExamDailyMissionProgressV1';
 const load=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}},save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
 const qs=()=>window.MusicTeacherExam?.questions||[],subjects=['國中音樂','高中音樂','教育專業'];
 const dayKey=()=>{const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
 function hash(s){let h=2166136261;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0} function dailyScore(q,s=''){return hash(`${dayKey()}|${s}|${q.id}`)}
 function readProgress(){const x=load(PROGRESS,{});return x.date===dayKey()?{results:{},...x}:{date:dayKey(),planned:[],completed:[],results:{},active:false,startedAt:null,updatedAt:null}} function writeProgress(x){x.date=dayKey();x.updatedAt=Date.now();x.results=x.results||{};save(PROGRESS,x);return x}
 function context(){const s=load(STATS,{attempts:{},wrong:[],unknown:[],topics:{}}),r=load(SRS,{}),f=load(FOCUS,{}),now=new Date(),all=qs(),unknown=new Set(s.unknown||[]),wrong=new Set(s.wrong||[]),focus=new Set(Object.keys(f||{})),weakTopics=new Set(Object.entries(s.topics||{}).filter(([,v])=>v.total>=2&&v.correct/v.total<.7).map(([k])=>k));function why(q){const flags=[];if(unknown.has(q.id))flags.push(['unknown','❓ 不知道']);if(wrong.has(q.id))flags.push(['wrong','❌ 錯題']);if(r[q.id]?.due&&new Date(r[q.id].due)<=now)flags.push(['due','🧠 間隔到期']);if(focus.has(String(q.id))||r[q.id]?.noteFocus)flags.push(['focus','⭐ 我的重點']);if(weakTopics.has(q.topic))flags.push(['weak','🩹 弱點主題']);if(!s.attempts?.[q.id])flags.push(['fresh','🆕 新題探索']);const first=flags[0]||['mix','🎯 綜合維持'],rank={unknown:0,wrong:1,due:2,focus:3,weak:4,fresh:5,mix:6}[first[0]],detail={unknown:'你曾按過「不知道」，今天優先重新建立概念。',wrong:'最近仍在錯題本，先把錯因釐清。',due:'系統判定已到適合再次提取的時間。',focus:'你從自己的筆記標記為重點。',weak:'這個主題近期正確率偏低。',fresh:'尚未作答，用來擴大題庫覆蓋。',mix:'補足三科配比與題感。'}[first[0]];return{key:first[0],label:first[1],rank,detail,all:flags}}return{all,s,r,why}}
 function decorate(pool){const c=context(),items=pool.map(x=>x.q?{q:x.q,why:c.why(x.q)}:{q:x,why:c.why(x)}),groups=[['unknown','❓ 不知道'],['wrong','❌ 錯題'],['due','🧠 間隔到期'],['focus','⭐ 我的重點'],['weak','🩹 弱點主題'],['fresh','🆕 新題探索'],['mix','🎯 綜合維持']].map(([key,label])=>({key,label,items:items.filter(x=>x.why.key===key)})).filter(x=>x.items.length),counts=Object.fromEntries(subjects.map(sub=>[sub,items.filter(x=>x.q.subject===sub).length]));return{pool:items.map(x=>x.q),items,groups,counts}}
 function build(){const c=context(),ordered=c.all.map(q=>({q,why:c.why(q)})).sort((a,b)=>a.why.rank-b.why.rank||(a.why.key==='due'&&b.why.key==='due'?new Date(c.r[a.q.id].due)-new Date(c.r[b.q.id].due):dailyScore(a.q,a.why.key)-dailyScore(b.q,b.why.key))),pool=[],used=new Set(),target={'國中音樂':7,'高中音樂':7,'教育專業':6};
  // Phase 1: high-risk questions are admitted first, regardless of 7/7/6 quotas.
  for(const x of ordered){if(pool.length>=20||x.why.rank>2)break;if(!used.has(x.q.id)){used.add(x.q.id);pool.push(x)}}
  // Phase 2: use remaining seats to move each subject toward 7/7/6 without removing risk items.
  for(const sub of subjects){for(const x of ordered){if(pool.length>=20)break;const have=pool.filter(y=>y.q.subject===sub).length;if(have>=target[sub])break;if(x.q.subject===sub&&!used.has(x.q.id)){used.add(x.q.id);pool.push(x)}}}
  // Phase 3: fill any remaining seats by overall priority.
  for(const x of ordered){if(pool.length>=20)break;if(!used.has(x.q.id)){used.add(x.q.id);pool.push(x)}}return decorate(pool)}
 function mission(){const p=readProgress();if(p.planned?.length){const map=new Map(qs().map(q=>[String(q.id),q])),pool=p.planned.map(id=>map.get(String(id))).filter(Boolean);if(pool.length)return{...decorate(pool),progress:p}}return{...build(),progress:p}}
 function startOrResume(){let p=readProgress(),m=mission();if(!p.planned.length){p={...p,planned:m.pool.map(q=>q.id),completed:[],results:{},active:true,startedAt:Date.now()};writeProgress(p);m=mission()}else{p.active=true;writeProgress(p)}const done=new Set((p.completed||[]).map(String)),remaining=m.pool.filter(q=>!done.has(String(q.id)));if(!remaining.length){p.active=false;writeProgress(p);render();return}window.MusicTeacherExam?.startCustomQuiz(remaining,'📅 今日上岸任務',remaining.length)}
 function markCurrentDone(){let p=readProgress();if(!p.active||!p.planned?.length)return;const id=document.getElementById('sourceBox')?.textContent?.match(/題號：([^\s]+)/)?.[1];if(!id||!p.planned.map(String).includes(String(id)))return;const q=qs().find(x=>String(x.id)===String(id)),title=document.getElementById('feedbackTitle')?.textContent||'',status=title.includes('我不知道')?'unknown':title.includes('答對')?'correct':'wrong',done=new Set((p.completed||[]).map(String));done.add(String(id));p.completed=[...done];p.results[String(id)]={status,correct:status==='correct',subject:q?.subject||'',topic:q?.topic||'',at:Date.now()};if(p.completed.length>=p.planned.length){p.active=false;p.completedAt=Date.now()}writeProgress(p);setTimeout(render,100)}
 function completion(p,m){const rows=p.planned.map(id=>{const q=m.pool.find(x=>String(x.id)===String(id)),r=p.results?.[String(id)];return q&&r?{q,r}:null}).filter(Boolean),correct=rows.filter(x=>x.r.correct).length,total=rows.length,bySubject=Object.fromEntries(subjects.map(sub=>{const a=rows.filter(x=>x.q.subject===sub),c=a.filter(x=>x.r.correct).length;return[sub,{total:a.length,correct:c,acc:a.length?Math.round(c/a.length*100):null}]})),tm={};rows.forEach(({q,r})=>{const k=q.topic||q.subject||'綜合';tm[k]=tm[k]||{total:0,correct:0,unknown:0,wrong:0};tm[k].total++;r.correct?tm[k].correct++:r.status==='unknown'?tm[k].unknown++:tm[k].wrong++});const takeaway=Object.entries(tm).map(([topic,x])=>({topic,...x,acc:Math.round(x.correct/x.total*100),risk:x.unknown*3+x.wrong*2+(100-Math.round(x.correct/x.total*100))/25})).sort((a,b)=>b.risk-a.risk||a.acc-b.acc||b.total-a.total)[0];return{total,correct,acc:total?Math.round(correct/total*100):0,bySubject,takeaway,unknown:rows.filter(x=>x.r.status==='unknown').length,wrong:rows.filter(x=>x.r.status==='wrong').length}}
 function completionHtml(p,m){const c=completion(p,m),take=c.takeaway,label=s=>s==='國中音樂'?'🎵 國中':s==='高中音樂'?'🎓 高中':'📚 教育',tip=!take?'今天沒有足夠作答資料。':take.unknown?`${take.topic} 有 ${take.unknown} 題按了「不知道」，先把核心定義與辨識線索補起來。`:take.wrong?`${take.topic} 今天仍有 ${take.wrong} 題答錯，建議回看四選項錯因與自己的筆記。`:`${take.topic} 是今天相對需要再鞏固的考點，可等下一次間隔複習再主動提取一次。`;return`<div style="padding:14px;border:1px solid var(--border);border-radius:14px;background:var(--soft);margin:12px 0"><div style="display:flex;justify-content:space-between;gap:10px;align-items:center"><b style="font-size:18px">🎉 今日任務完成</b><b style="font-size:28px">${c.acc}%</b></div><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-top:11px">${subjects.map(sub=>{const x=c.bySubject[sub];return`<div style="padding:9px;border:1px solid var(--line);border-radius:10px;background:var(--card)"><small>${label(sub)}</small><div style="font-weight:900;font-size:20px">${x.acc==null?'--':x.acc+'%'}</div><small class="muted">${x.correct}/${x.total} 題</small></div>`}).join('')}</div><div style="margin-top:11px;padding:10px;border:1px dashed var(--border);border-radius:11px;background:var(--card)"><b>🎯 今天最需要再帶走的一個考點</b><div>${take?.topic||'—'}</div><small class="muted">${tip}</small></div><div class="muted" style="font-size:12px;margin-top:8px">${c.unknown||c.wrong?`今天還留下 ❓不知道 ${c.unknown} 題、❌答錯 ${c.wrong} 題；它們會接著進入複習排程。`:'今天沒有留下新的「不知道」或錯題，下一步交給間隔複習維持記憶。'}</div></div>`}
 function render(){const home=document.getElementById('homeView');if(!home)return;const m=mission(),p=m.progress,planned=p.planned?.length?p.planned.length:m.pool.length,doneSet=new Set((p.completed||[]).map(String)),done=p.planned?.length?p.planned.filter(id=>doneSet.has(String(id))).length:0,remain=Math.max(0,planned-done),pct=planned?Math.round(done/planned*100):0,finished=!!(p.planned?.length&&!remain),highRisk=m.items.filter(x=>x.why.rank<=2).length,slot=document.getElementById('todayPrimarySlot');let sec=document.getElementById('dailyMission');if(!sec){sec=document.createElement('section');sec.id='dailyMission';sec.className='card section-card'}sec.innerHTML=`<div class="section-title"><div><span class="eyebrow">${finished?'今天完成後，留下最值得記住的一件事':'高風險先保送，再補三科平衡'}</span><h3>📅 今日上岸任務</h3></div><span class="pill">${done}/${planned} 題</span></div><div style="height:8px;background:var(--soft);border-radius:999px;overflow:hidden;margin:10px 0 8px"><div style="height:100%;width:${pct}%;background:var(--primary)"></div></div><p class="muted">${finished?'今天的任務已完成。':`先收進 ❓不知道、❌錯題、🧠到期題，再用剩餘名額盡量靠近國中 7／高中 7／教育 6；若高風險題很多，三科比例會主動讓位。`}</p><div style="display:flex;gap:7px;flex-wrap:wrap;margin:10px 0"><span class="pill">🔥 高風險 ${highRisk}</span><span class="pill">🎵 國中 ${m.counts['國中音樂']||0}</span><span class="pill">🎓 高中 ${m.counts['高中音樂']||0}</span><span class="pill">📚 教育 ${m.counts['教育專業']||0}</span></div>${finished?completionHtml(p,m):`<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(145px,1fr));gap:8px;margin:12px 0">${m.groups.map(g=>`<div style="border:1px solid var(--line);border-radius:12px;padding:10px"><b>${g.label}</b><div style="font-size:22px;font-weight:850">${g.items.length}<small style="font-size:12px;color:var(--muted)"> 題</small></div></div>`).join('')}</div>`}<button id="startDailyMission" class="primary wide" ${finished?'disabled':''}>${finished?'✅ 今日任務完成':done?`▶️ 繼續今日任務（剩 ${remain} 題）`:'🚀 開始今天的上岸任務'}</button>`;if(slot){slot.innerHTML='';slot.appendChild(sec)}else if(!sec.isConnected)home.prepend(sec);sec.querySelector('#startDailyMission')?.addEventListener('click',startOrResume);window.HomeCategoryOrganizer?.apply?.()}
 function bind(){const fb=document.getElementById('feedback');if(fb&&!fb.dataset.dailyMissionObserved){fb.dataset.dailyMissionObserved='1';new MutationObserver(()=>{if(!fb.classList.contains('hidden'))setTimeout(markCurrentDone,20)}).observe(fb,{attributes:true,attributeFilter:['class']})}document.addEventListener('click',e=>{if(e.target.closest('[data-mode],#filteredQuizBtn,.pp-practice')&&!e.target.closest('#startDailyMission')){const p=readProgress();if(p.active){p.active=false;writeProgress(p)}}})}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{render();bind()},900));else setTimeout(()=>{render();bind()},100);window.DailyExamMission={build,mission,render,startOrResume,progress:readProgress};
})();