(()=>{
 if(window.__DAILY_MISSION_BACKLOG_UI_V5__)return;window.__DAILY_MISSION_BACKLOG_UI_V5__=true;
 const BACKLOG='musicTeacherExamRiskBacklogV1',STATS='musicTeacherExamStatsV1',SRS='musicTeacherExamSpacedReviewV1',PROGRESS='musicTeacherExamDailyMissionProgressV1';
 const load=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}},save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const qs=()=>window.MusicTeacherExam?.questions||[],idSet=a=>new Set((a||[]).map(String));
 function riskState(){const s=load(STATS,{wrong:[],unknown:[]}),r=load(SRS,{});return{s,r,wrong:idSet(s.wrong),unknown:idSet(s.unknown),now:new Date()}}
 function currentRisk(q,state=riskState()){const x=state.r[q.id]||{},id=String(q.id),streak=x.correctStreak||0,shared=window.MusicTeacherSRS?.effectiveRisk?.(q,state.r,state.s);if(shared)return shared;if(x.lastResult==='unknown')return'unknown';if(x.lastResult==='wrong')return'wrong';if(streak>=2)return null;if(!x.lastResult&&state.unknown.has(id))return'unknown';if(!x.lastResult&&state.wrong.has(id))return'wrong';return null}
 function reason(q,state=riskState()){const risk=currentRisk(q,state);if(risk==='unknown')return'❓ 不知道';if(risk==='wrong')return'❌ 錯題';if(state.r[q.id]?.due&&new Date(state.r[q.id].due)<=state.now)return'🧠 間隔到期';return'🟡 已解除高風險'}
 function backlogRows(){const back=load(BACKLOG,{ids:[]}),map=new Map(qs().map(q=>[String(q.id),q])),state=riskState(),kept=[],resolved=[];(back.ids||[]).map(String).forEach(id=>{const q=map.get(id);if(!q)return;const label=reason(q,state);if(label.includes('不知道')||label.includes('錯題')||label.includes('到期'))kept.push(q);else resolved.push(q)});if(resolved.length){save(BACKLOG,{...back,ids:kept.map(q=>q.id),updatedAt:Date.now(),lastUiPrunedResolved:resolved.length});setTimeout(()=>window.DailyExamMission?.render?.(),0)}return kept}
 function topicSummary(rows){const state=riskState(),m=new Map();rows.forEach(q=>{const k=q.topic||q.subject||'綜合';if(!m.has(k))m.set(k,{topic:k,total:0,unknown:0,wrong:0,due:0});const x=m.get(k);x.total++;const r=reason(q,state);if(r.includes('不知道'))x.unknown++;else if(r.includes('錯題'))x.wrong++;else if(r.includes('到期'))x.due++});return[...m.values()].sort((a,b)=>b.total-a.total||b.unknown-a.unknown||b.wrong-a.wrong)}
 function startTopic(topic){const rows=backlogRows().filter(q=>(q.topic||q.subject||'綜合')===topic);if(!rows.length)return;const p=load(PROGRESS,{});if(p.active){p.active=false;save(PROGRESS,p)}window.RiskTopicDrillProgress?.begin?.(topic,rows.map(q=>q.id));window.MusicTeacherExam?.startCustomQuiz(rows,`🔥 高風險專練｜${topic}`,rows.length)}
 function render(){const mission=document.getElementById('dailyMission');if(!mission)return;let box=document.getElementById('dailyRiskBacklogDetails');const rows=backlogRows();if(!rows.length){box?.remove();return}const state=riskState(),topics=topicSummary(rows),top=topics[0];if(!box){box=document.createElement('details');box.id='dailyRiskBacklogDetails';box.style.margin='10px 0';mission.querySelector('#startDailyMission')?.insertAdjacentElement('beforebegin',box)}box.innerHTML=`<summary style="cursor:pointer;font-weight:850">⏭️ 查看待接續高風險題（${rows.length} 題）</summary><div class="muted" style="font-size:12px;margin:6px 0 8px">只顯示目前仍屬高風險的題目；連續答對 2 次解除高風險後，會自動從這裡消失。</div><div style="padding:10px 11px;border:1px dashed var(--border);border-radius:11px;background:var(--soft);margin-bottom:9px"><b>📊 高風險主要卡在哪裡？</b><div style="display:flex;gap:6px;flex-wrap:wrap;margin-top:7px">${topics.slice(0,6).map(x=>`<button class="ghost small risk-topic-drill" data-topic="${esc(x.topic)}" type="button">🎯 練 ${esc(x.topic)} ${x.total} 題</button>`).join('')}</div>${top?`<div class="muted" style="font-size:12px;margin-top:6px">目前最多的是「${esc(top.topic)}」${top.total} 題${top.unknown?`，❓不知道 ${top.unknown}`:''}${top.wrong?`、❌錯題 ${top.wrong}`:''}${top.due?`、🧠到期 ${top.due}`:''}。</div>`:''}</div><div style="display:grid;gap:7px">${rows.slice(0,20).map((q,i)=>`<div style="padding:8px 10px;border:1px solid var(--line);border-radius:10px"><div style="display:flex;justify-content:space-between;gap:8px"><b>${i+1}. ${esc(q.topic||q.subject||'考點')}</b><span style="font-size:12px">${reason(q,state)}</span></div><div class="muted" style="font-size:12px;margin-top:3px">${esc(q.question||'')}</div><div class="muted" style="font-size:11px;margin-top:2px">${esc(q.subject||'')}｜題號 ${esc(q.id)}</div></div>`).join('')}</div>${rows.length>20?`<div class="muted" style="font-size:12px;margin-top:7px">另有 ${rows.length-20} 題未展開；仍會保留在佇列中。</div>`:''}`;box.querySelectorAll('.risk-topic-drill').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();startTopic(b.dataset.topic)}))}
 function watch(){render();window.addEventListener('storage',e=>{if([BACKLOG,STATS,SRS].includes(e.key))render()});window.addEventListener('musicExamLearningSynced',render);window.addEventListener('musicExamRiskBacklogSynced',render)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(watch,150),{once:true});else setTimeout(watch,150);window.DailyMissionBacklogUI={render,topicSummary,startTopic,reason,currentRisk};
})();