(()=>{
 if(window.__DAILY_MISSION_V4__)return;window.__DAILY_MISSION_V4__=true;
 const STATS='musicTeacherExamStatsV1',SRS='musicTeacherExamSpacedReviewV1',FOCUS='musicTeacherExamNoteFocusV1',PROGRESS='musicTeacherExamDailyMissionProgressV1';
 const load=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}},save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
 const qs=()=>window.MusicTeacherExam?.questions||[];
 const subjects=['國中音樂','高中音樂','教育專業'];
 const dayKey=()=>{const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
 function hash(s){let h=2166136261;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
 function dailyScore(q,salt=''){return hash(`${dayKey()}|${salt}|${q.id}`)}
 function readProgress(){const x=load(PROGRESS,{});return x.date===dayKey()?x:{date:dayKey(),planned:[],completed:[],active:false,startedAt:null,updatedAt:null}}
 function writeProgress(x){x.date=dayKey();x.updatedAt=Date.now();save(PROGRESS,x);return x}
 function build(){
  const s=load(STATS,{attempts:{},wrong:[],unknown:[],topics:{}}),r=load(SRS,{}),focus=load(FOCUS,{}),now=new Date(),all=qs(),used=new Set();
  const unknownSet=new Set(s.unknown||[]),wrongSet=new Set(s.wrong||[]),focusSet=new Set(Object.keys(focus||{}));
  const dueSet=new Set(all.filter(q=>r[q.id]?.due&&new Date(r[q.id].due)<=now).map(q=>q.id));
  const weakTopics=new Set(Object.entries(s.topics||{}).filter(([,v])=>v.total>=2&&v.correct/v.total<.7).map(([k])=>k));
  const weakSet=new Set(all.filter(q=>weakTopics.has(q.topic)).map(q=>q.id));
  const freshSet=new Set(all.filter(q=>!s.attempts?.[q.id]).map(q=>q.id));
  function flags(q){const id=q.id,out=[];if(unknownSet.has(id))out.push(['unknown','❓ 不知道']);if(wrongSet.has(id))out.push(['wrong','❌ 錯題']);if(dueSet.has(id))out.push(['due','🧠 間隔到期']);if(focusSet.has(String(id))||r[id]?.noteFocus)out.push(['focus','⭐ 我的重點']);if(weakSet.has(id))out.push(['weak','🩹 弱點主題']);if(freshSet.has(id))out.push(['fresh','🆕 新題探索']);return out}
  function reason(q){const f=flags(q),id=q.id;if(unknownSet.has(id))return{key:'unknown',label:'❓ 不知道',detail:'你曾按過「不知道」，今天優先重新建立概念。',rank:0,all:f};if(wrongSet.has(id))return{key:'wrong',label:'❌ 錯題',detail:'最近仍在錯題本，先把錯因釐清。',rank:1,all:f};if(dueSet.has(id))return{key:'due',label:'🧠 間隔到期',detail:'系統判定已到適合再次提取的時間。',rank:2,all:f};if(focusSet.has(String(id))||r[id]?.noteFocus)return{key:'focus',label:'⭐ 我的重點',detail:'你從自己的筆記標記為重點。',rank:3,all:f};if(weakSet.has(id))return{key:'weak',label:'🩹 弱點主題',detail:'這個主題近期正確率偏低。',rank:4,all:f};if(freshSet.has(id))return{key:'fresh',label:'🆕 新題探索',detail:'尚未作答，用來擴大題庫覆蓋。',rank:5,all:f};return{key:'mix',label:'🎯 綜合維持',detail:'補足三科配比與題感。',rank:6,all:f}}
  const ordered=all.map(q=>({q,why:reason(q)})).sort((a,b)=>a.why.rank-b.why.rank||(a.why.key==='due'&&b.why.key==='due'?new Date(r[a.q.id].due)-new Date(r[b.q.id].due):dailyScore(a.q,a.why.key)-dailyScore(b.q,b.why.key)));
  const target={'國中音樂':7,'高中音樂':7,'教育專業':6},pool=[];
  const takeSubject=(sub,n)=>{for(const x of ordered){if(pool.length>=20||pool.filter(y=>y.q.subject===sub).length>=n)break;if(x.q.subject===sub&&!used.has(x.q.id)){used.add(x.q.id);pool.push(x)}}};
  subjects.forEach(sub=>takeSubject(sub,target[sub]));for(const x of ordered){if(pool.length>=20)break;if(!used.has(x.q.id)){used.add(x.q.id);pool.push(x)}}
  return decorate(pool);
 }
 function decorate(pool){const s=load(STATS,{attempts:{},wrong:[],unknown:[],topics:{}}),r=load(SRS,{}),focus=load(FOCUS,{}),now=new Date(),unknown=new Set(s.unknown||[]),wrong=new Set(s.wrong||[]),focusSet=new Set(Object.keys(focus||{})),weakTopics=new Set(Object.entries(s.topics||{}).filter(([,v])=>v.total>=2&&v.correct/v.total<.7).map(([k])=>k));
  function why(q){const all=[];if(unknown.has(q.id))all.push(['unknown','❓ 不知道']);if(wrong.has(q.id))all.push(['wrong','❌ 錯題']);if(r[q.id]?.due&&new Date(r[q.id].due)<=now)all.push(['due','🧠 間隔到期']);if(focusSet.has(String(q.id))||r[q.id]?.noteFocus)all.push(['focus','⭐ 我的重點']);if(weakTopics.has(q.topic))all.push(['weak','🩹 弱點主題']);if(!s.attempts?.[q.id])all.push(['fresh','🆕 新題探索']);const first=all[0]||['mix','🎯 綜合維持'];const detail={unknown:'你曾按過「不知道」，今天優先重新建立概念。',wrong:'最近仍在錯題本，先把錯因釐清。',due:'系統判定已到適合再次提取的時間。',focus:'你從自己的筆記標記為重點。',weak:'這個主題近期正確率偏低。',fresh:'尚未作答，用來擴大題庫覆蓋。',mix:'補足三科配比與題感。'}[first[0]];return{key:first[0],label:first[1],detail,all}}
  const items=pool.map(x=>x.q?{q:x.q,why:why(x.q)}:{q:x,why:why(x)}),groups=[['unknown','❓ 不知道'],['wrong','❌ 錯題'],['due','🧠 間隔到期'],['focus','⭐ 我的重點'],['weak','🩹 弱點主題'],['fresh','🆕 新題探索'],['mix','🎯 綜合維持']].map(([key,label])=>({key,label,items:items.filter(x=>x.why.key===key)})).filter(x=>x.items.length),counts=Object.fromEntries(subjects.map(sub=>[sub,items.filter(x=>x.q.subject===sub).length]));return{pool:items.map(x=>x.q),items,groups,counts}}
 function mission(){let p=readProgress();if(p.planned?.length){const map=new Map(qs().map(q=>[String(q.id),q])),pool=p.planned.map(id=>map.get(String(id))).filter(Boolean);if(pool.length)return{...decorate(pool),progress:p}}const fresh=build();return{...fresh,progress:p}}
 function startOrResume(){let p=readProgress(),m=mission();if(!p.planned.length){p={...p,planned:m.pool.map(q=>q.id),completed:[],active:true,startedAt:Date.now()};writeProgress(p);m=mission()}else{p.active=true;writeProgress(p)}const done=new Set(p.completed||[]),remaining=m.pool.filter(q=>!done.has(q.id));if(!remaining.length){p.active=false;writeProgress(p);render();return}window.MusicTeacherExam?.startCustomQuiz(remaining,'📅 今日上岸任務',remaining.length)}
 function markCurrentDone(){let p=readProgress();if(!p.active||!p.planned?.length)return;const id=document.getElementById('sourceBox')?.textContent?.match(/題號：([^\s]+)/)?.[1];if(!id||!p.planned.map(String).includes(String(id)))return;const done=new Set((p.completed||[]).map(String));done.add(String(id));p.completed=[...done];if(p.completed.length>=p.planned.length)p.active=false;writeProgress(p);setTimeout(render,100)}
 function render(){const home=document.getElementById('homeView');if(!home)return;const m=mission(),p=m.progress,planned=p.planned?.length?p.planned.length:m.pool.length,doneSet=new Set((p.completed||[]).map(String)),done=p.planned?.length?p.planned.filter(id=>doneSet.has(String(id))).length:0,remain=Math.max(0,planned-done),pct=planned?Math.round(done/planned*100):0,slot=document.getElementById('todayPrimarySlot');let sec=document.getElementById('dailyMission');if(!sec){sec=document.createElement('section');sec.id='dailyMission';sec.className='card section-card'}sec.innerHTML=`<div class="section-title"><div><span class="eyebrow">今天做到哪裡，回來就從哪裡繼續</span><h3>📅 今日上岸任務</h3></div><span class="pill">${done}/${planned} 題</span></div><div style="height:8px;background:var(--soft);border-radius:999px;overflow:hidden;margin:10px 0 8px"><div style="height:100%;width:${pct}%;background:var(--primary);transition:width .25s"></div></div><p class="muted">${done?`今天已完成 ${done} 題，還剩 ${remain} 題。離開後再回來會接著做，不會重新從第 1 題開始。`:'優先順序：❓不知道 → ❌錯題 → 🧠間隔到期 → ⭐我的重點 → 🩹弱點 → 🆕新題。第一次開始後，今天這份任務會固定下來。'}</p><div style="display:flex;gap:7px;flex-wrap:wrap;margin:10px 0 12px"><span class="pill">🎵 國中 ${m.counts['國中音樂']||0}</span><span class="pill">🎓 高中 ${m.counts['高中音樂']||0}</span><span class="pill">📚 教育 ${m.counts['教育專業']||0}</span></div><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(145px,1fr));gap:8px;margin:12px 0">${m.groups.map(g=>`<div style="border:1px solid var(--line);border-radius:12px;padding:10px"><b>${g.label}</b><div style="font-size:22px;font-weight:850;margin-top:4px">${g.items.length}<small style="font-size:12px;color:var(--muted)"> 題</small></div></div>`).join('')}</div>${m.items.length?`<details style="margin:10px 0"><summary style="cursor:pointer;font-weight:800">查看今天前 8 題為什麼被選中</summary><div style="display:grid;gap:7px;margin-top:8px">${m.items.slice(0,8).map(x=>{const secondary=(x.why.all||[]).filter(([k])=>k!==x.why.key).map(([,l])=>l);return`<div style="padding:8px 10px;border:1px solid var(--line);border-radius:10px"><b>${x.why.label}</b>｜${x.q.topic||x.q.subject}<div class="muted" style="font-size:12px;margin-top:2px">${x.why.detail}${secondary.length?`<br>同時符合：${secondary.join('、')}`:''}</div></div>`}).join('')}</div></details>`:''}<button id="startDailyMission" class="primary wide" ${planned&&remain===0?'disabled':''}>${planned&&remain===0?'✅ 今日任務完成':done?`▶️ 繼續今日任務（剩 ${remain} 題）`:'🚀 開始今天的上岸任務'}</button>`;if(slot){slot.innerHTML='';slot.appendChild(sec)}else if(!sec.isConnected){const first=home.querySelector('.stats-grid')?.nextElementSibling;first?.insertAdjacentElement('beforebegin',sec)}sec.querySelector('#startDailyMission')?.addEventListener('click',startOrResume);window.HomeCategoryOrganizer?.apply?.()}
 function bind(){const fb=document.getElementById('feedback');if(fb&&!fb.dataset.dailyMissionObserved){fb.dataset.dailyMissionObserved='1';new MutationObserver(()=>{if(!fb.classList.contains('hidden'))setTimeout(markCurrentDone,20)}).observe(fb,{attributes:true,attributeFilter:['class']})}document.addEventListener('click',e=>{if(e.target.closest('[data-mode],#filteredQuizBtn,.pp-practice')&&!e.target.closest('#startDailyMission')){const p=readProgress();if(p.active){p.active=false;writeProgress(p)}}})}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{render();bind()},900));else setTimeout(()=>{render();bind()},100);window.DailyExamMission={build,mission,render,startOrResume,progress:readProgress};
})();