(()=>{
 if(window.__DAILY_MISSION_COMPLETION__)return;window.__DAILY_MISSION_COMPLETION__=true;
 const PROGRESS='musicTeacherExamDailyMissionProgressV1';
 const subjects=['國中音樂','高中音樂','教育專業'];
 const load=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}};
 const qs=()=>window.MusicTeacherExam?.questions||[];
 function dayKey(){const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
 function data(){const p=load(PROGRESS,{});if(p.date!==dayKey()||!p.planned?.length)return null;const byId=new Map(qs().map(q=>[String(q.id),q]));const rows=p.planned.map(id=>{const q=byId.get(String(id)),r=p.results?.[String(id)];return q&&r?{q,r}:null}).filter(Boolean);if(rows.length<p.planned.length)return null;const correct=rows.filter(x=>x.r.correct).length,total=rows.length;const bySubject=Object.fromEntries(subjects.map(sub=>{const a=rows.filter(x=>x.q.subject===sub),c=a.filter(x=>x.r.correct).length;return[sub,{total:a.length,correct:c,acc:a.length?Math.round(c/a.length*100):null}]}));const tm={};rows.forEach(({q,r})=>{const k=q.topic||q.subject||'綜合';tm[k]=tm[k]||{total:0,correct:0,unknown:0,wrong:0};tm[k].total++;if(r.correct)tm[k].correct++;else if(r.status==='unknown')tm[k].unknown++;else tm[k].wrong++});const topics=Object.entries(tm).map(([topic,x])=>({topic,...x,acc:Math.round(x.correct/x.total*100),risk:x.unknown*3+x.wrong*2+(100-Math.round(x.correct/x.total*100))/25})).sort((a,b)=>b.risk-a.risk||a.acc-b.acc||b.total-a.total);return{acc:Math.round(correct/total*100),correct,total,bySubject,takeaway:topics[0],unknown:rows.filter(x=>x.r.status==='unknown').length,wrong:rows.filter(x=>x.r.status==='wrong').length}}
 function render(){const d=data(),sec=document.getElementById('dailyMission');if(!d||!sec)return;let box=document.getElementById('dailyMissionCompletionReport');if(box)return;const take=d.takeaway,tip=!take?'今天沒有足夠作答資料。':take.unknown?`${take.topic} 有 ${take.unknown} 題按了「不知道」，先補核心定義與辨識線索。`:take.wrong?`${take.topic} 今天仍有 ${take.wrong} 題答錯，建議回看四選項錯因與自己的筆記。`:`${take.topic} 是今天相對需要再鞏固的考點，可交給下一輪間隔複習。`;const label=s=>s==='國中音樂'?'🎵 國中':s==='高中音樂'?'🎓 高中':'📚 教育';box=document.createElement('div');box.id='dailyMissionCompletionReport';box.innerHTML=`<div style="padding:14px;border:1px solid var(--border);border-radius:14px;background:var(--soft);margin:12px 0"><div style="display:flex;justify-content:space-between;align-items:center;gap:10px"><div><b style="font-size:18px">🎉 今日成果</b><div class="muted" style="font-size:12px">完成之外，也留下今天真正需要帶走的內容。</div></div><b style="font-size:28px">${d.acc}%</b></div><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-top:10px">${subjects.map(sub=>{const x=d.bySubject[sub];return`<div style="padding:9px;border:1px solid var(--line);border-radius:10px;background:var(--card)"><small>${label(sub)}</small><div style="font-weight:900;font-size:20px">${x.acc==null?'--':x.acc+'%'}</div><small class="muted">${x.correct}/${x.total} 題</small></div>`}).join('')}</div><div style="margin-top:10px;padding:10px;border:1px dashed var(--border);border-radius:11px;background:var(--card)"><b>🎯 今天最需要再帶走的一個考點</b><div style="margin-top:4px">${take?.topic||'—'}</div><div class="muted" style="font-size:12px;margin-top:3px">${tip}</div></div><div class="muted" style="font-size:12px;margin-top:8px">${d.unknown||d.wrong?`今天留下 ❓不知道 ${d.unknown} 題、❌答錯 ${d.wrong} 題；它們會進入後續複習。`:'今天沒有留下新的「不知道」或錯題，交給間隔複習維持。'}</div></div>`;const btn=sec.querySelector('#startDailyMission');btn?.insertAdjacentElement('beforebegin',box)}
 function hook(){const dm=window.DailyExamMission;if(dm?.render&&!dm.__completionWrapped){const original=dm.render.bind(dm);dm.render=()=>{original();setTimeout(render,0)};dm.__completionWrapped=true}render()}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(hook,1100),{once:true});else setTimeout(hook,150);window.addEventListener('musicExamLearningSynced',()=>setTimeout(render,0));
})();