// 115 首頁｜今日任務完成感與連續紀錄
(function(){
 if(window.__DAILY_DONE115__)return;window.__DAILY_DONE115__=true;
 var KEY='musicTeacherExamDaily115V1',PENDING='musicTeacherExamHighFreqPending115';
 function load(){try{return JSON.parse(localStorage.getItem(KEY))||{days:{}}}catch(e){return{days:{}}}}
 function save(s){localStorage.setItem(KEY,JSON.stringify(s||{days:{}}))}
 function today(){var d=new Date(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return d.getFullYear()+'-'+m+'-'+day}
 function dayStart(){var d=new Date();d.setHours(0,0,0,0);return d.getTime()}
 function ensure(){var s=load();s.days=s.days||{};s.days[today()]=s.days[today()]||{quiz:false,weak:false,grid:false,manual:false,needWeak:null,updatedAt:Date.now()};return s}
 function requiresWeak(){try{var api=window.MusicTeacherExam,st=api&&api.loadStats?api.loadStats():{wrong:[],unknown:[]},c=window.Confusion115&&window.Confusion115.top?window.Confusion115.top():[];return ((st.wrong||[]).length+(st.unknown||[]).length)>0||(c&&c.length>0)}catch(e){return false}}
 function mark(type){var s=ensure(),x=s.days[today()];x[type]=true;if(type==='quiz')x.needWeak=requiresWeak();if(type==='weak'||type==='grid')x.needWeak=true;x.updatedAt=Date.now();s.days[today()]=x;save(s);render()}
 function dayDone(x){if(!x)return false;if(x.manual)return true;if(!x.quiz)return false;if(x.needWeak===false)return true;return !!(x.weak||x.grid)}
 function streak(){var s=load(),d=new Date(),n=0;for(var i=0;i<366;i++){var m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0'),k=d.getFullYear()+'-'+m+'-'+day;if(dayDone((s.days||{})[k]))n++;else if(i===0){}else break;d.setDate(d.getDate()-1)}return n}
 function progress(){var s=ensure(),x=s.days[today()];if(x.quiz&&x.needWeak===null)x.needWeak=requiresWeak();var need=x.needWeak!==false,done=x.quiz?1:0,total=need?2:1;if(need&&(x.weak||x.grid))done++;return{done:done,total:total,complete:dayDone(x),needWeak:need,state:x}}
 function render(){var host=document.getElementById('hf115GuideStart');if(!host)return false;document.getElementById('hf115DailyDone')?.remove();var p=progress(),box=document.createElement('div');box.id='hf115DailyDone';box.style.cssText='padding:14px;border-radius:16px;border:1px solid rgba(127,127,127,.16);background:rgba(127,127,127,.035);margin-bottom:12px';
 if(p.complete){var doneText=p.needWeak?'今天已完成一次主動提取，也真的做過一次弱點補強；不需要把所有功能都做一遍。':'今天的短測驗沒有留下需要急救的弱點，做到這裡就夠了；不用為了完成清單硬找弱點。';box.innerHTML='<span class="eyebrow">今天可以收工了</span><h3 style="margin:5px 0">✅ 今日任務完成</h3><p class="muted" style="margin:0">'+doneText+'</p><div class="hf115-badges"><span class="hf115-badge">最近完成 '+streak()+' 天</span><span class="hf115-badge">今天 '+p.done+'/'+p.total+' 核心任務</span></div>'}
 else{var instruction=p.needWeak?'今天只要完成「1次短測驗」＋「1次真正的弱點補強」就夠了；只是打開工具不會算完成。':'今天先完成一次短測驗即可；如果沒有留下弱點，就不需要額外補強。';box.innerHTML='<span class="eyebrow">今日任務</span><h3 style="margin:5px 0">'+p.done+'/'+p.total+' 已完成</h3><p class="muted" style="margin:0">'+instruction+'</p><div class="hf115-badges"><span class="hf115-badge">'+(p.state.quiz?'✅':'⬜')+' 完成短測驗</span>'+(p.needWeak?'<span class="hf115-badge">'+((p.state.weak||p.state.grid)?'✅':'⬜')+' 完成弱點補強</span>':'')+'</div><button id="hf115ManualDone" class="ghost" style="margin-top:8px">今天內容已足夠，手動標記完成</button>'}
 var rec=document.getElementById('hf115DailyRec');if(rec)rec.after(box);else host.insertBefore(box,host.firstChild);var b=document.getElementById('hf115ManualDone');if(b)b.onclick=function(){mark('manual')};return true}
 function patchQuiz(){var api=window.MusicTeacherExam;if(api&&api.startCustomQuiz&&!api.__dailyDonePatched){var orig=api.startCustomQuiz;api.startCustomQuiz=function(pool,label,limit){if(String(label||'').includes('高頻'))sessionStorage.setItem(PENDING,'1');return orig.call(api,pool,label,limit)};api.__dailyDonePatched=true}}
 function detectQuizFinish(){if(sessionStorage.getItem(PENDING)==='1'&&document.getElementById('resultView')?.classList.contains('active')){sessionStorage.removeItem(PENDING);mark('quiz')}}
 function hasTodayEvidence(storageKey,mode){var start=dayStart();try{var data=JSON.parse(localStorage.getItem(storageKey)||'{}');if(mode==='confusion')return Object.values(data||{}).some(function(x){return x&&x.updatedAt>=start});if(mode==='mission')return Object.values(data||{}).some(function(x){return x&&x.updatedAt>=start&&Array.isArray(x.done)&&x.done.length>0});return false}catch(e){return false}}
 function syncPersistedEvidence(){var s=ensure(),x=s.days[today()],changed=false;if(!x.weak&&hasTodayEvidence('musicTeacherExamConfusions115V1','confusion')){x.weak=true;x.needWeak=true;changed=true}if(!x.grid&&hasTodayEvidence('musicTeacherExamSelfStudy115V1','mission')){x.grid=true;x.needWeak=true;changed=true}if(changed){x.updatedAt=Date.now();s.days[today()]=x;save(s)}}
 function loadWeekly(){if(document.querySelector('script[data-weekly-rhythm115]'))return;var s=document.createElement('script');s.src='weekly_learning_rhythm_115.js?v=20260820e';s.dataset.weeklyRhythm115='1';document.head.appendChild(s)}
 function boot(){var n=0,t=setInterval(function(){n++;patchQuiz();detectQuizFinish();syncPersistedEvidence();render();if(n>4)loadWeekly();if(n>100)clearInterval(t)},220)}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
 window.DailyCompletion115={load:load,mark:mark,progress:progress,streak:streak,render:render,sync:syncPersistedEvidence,requiresWeak:requiresWeak};
})();