(()=>{
 if(window.__DAILY_MISSION_BACKLOG_UI__)return;window.__DAILY_MISSION_BACKLOG_UI__=true;
 const BACKLOG='musicTeacherExamRiskBacklogV1',STATS='musicTeacherExamStatsV1',SRS='musicTeacherExamSpacedReviewV1';
 const load=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}};
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const qs=()=>window.MusicTeacherExam?.questions||[];
 function reason(q){const s=load(STATS,{wrong:[],unknown:[]}),r=load(SRS,{});if((s.unknown||[]).includes(q.id))return'❓ 不知道';if((s.wrong||[]).includes(q.id))return'❌ 錯題';if(r[q.id]?.due&&new Date(r[q.id].due)<=new Date())return'🧠 間隔到期';return'🔥 高風險';}
 function render(){const mission=document.getElementById('dailyMission');if(!mission)return;let box=document.getElementById('dailyRiskBacklogDetails');const back=load(BACKLOG,{ids:[]}),ids=(back.ids||[]).map(String),map=new Map(qs().map(q=>[String(q.id),q])),rows=ids.map(id=>map.get(id)).filter(Boolean);if(!rows.length){box?.remove();return}if(!box){box=document.createElement('details');box.id='dailyRiskBacklogDetails';box.style.margin='10px 0';const btn=mission.querySelector('#startDailyMission');btn?.insertAdjacentElement('beforebegin',box)}box.innerHTML=`<summary style="cursor:pointer;font-weight:850">⏭️ 查看待接續高風險題（${rows.length} 題）</summary><div class="muted" style="font-size:12px;margin:6px 0 8px">這些題不是被刪掉，而是因每日 20 題上限延後；隔天會從較早被延後的題目優先接續。</div><div style="display:grid;gap:7px">${rows.slice(0,20).map((q,i)=>`<div style="padding:8px 10px;border:1px solid var(--line);border-radius:10px"><div style="display:flex;justify-content:space-between;gap:8px"><b>${i+1}. ${esc(q.topic||q.subject||'考點')}</b><span style="font-size:12px">${reason(q)}</span></div><div class="muted" style="font-size:12px;margin-top:3px">${esc(q.question||'')}</div><div class="muted" style="font-size:11px;margin-top:2px">${esc(q.subject||'')}｜題號 ${esc(q.id)}</div></div>`).join('')}</div>${rows.length>20?`<div class="muted" style="font-size:12px;margin-top:7px">另有 ${rows.length-20} 題未展開；仍會保留在佇列中。</div>`:''}`}
 function watch(){render();const home=document.getElementById('homeView');if(home&&!home.dataset.backlogUiObserved){home.dataset.backlogUiObserved='1';new MutationObserver(()=>setTimeout(render,30)).observe(home,{childList:true,subtree:true})}window.addEventListener('storage',e=>{if([BACKLOG,STATS,SRS].includes(e.key))render()});window.addEventListener('musicExamLearningSynced',()=>render())}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(watch,150),{once:true});else setTimeout(watch,150);
 window.DailyMissionBacklogUI={render};
})();