(()=>{
 if(window.__DAILY_MISSION_BACKLOG_UI_V2__)return;window.__DAILY_MISSION_BACKLOG_UI_V2__=true;
 const BACKLOG='musicTeacherExamRiskBacklogV1',STATS='musicTeacherExamStatsV1',SRS='musicTeacherExamSpacedReviewV1';
 const load=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}};
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const qs=()=>window.MusicTeacherExam?.questions||[];
 function reason(q){const s=load(STATS,{wrong:[],unknown:[]}),r=load(SRS,{});if((s.unknown||[]).includes(q.id))return'❓ 不知道';if((s.wrong||[]).includes(q.id))return'❌ 錯題';if(r[q.id]?.due&&new Date(r[q.id].due)<=new Date())return'🧠 間隔到期';return'🔥 高風險'}
 function topicSummary(rows){const m=new Map();rows.forEach(q=>{const k=q.topic||q.subject||'綜合';if(!m.has(k))m.set(k,{topic:k,total:0,junior:0,senior:0,edu:0,unknown:0,wrong:0,due:0});const x=m.get(k);x.total++;if(q.subject==='國中音樂')x.junior++;else if(q.subject==='高中音樂')x.senior++;else if(q.subject==='教育專業')x.edu++;const r=reason(q);if(r.includes('不知道'))x.unknown++;else if(r.includes('錯題'))x.wrong++;else if(r.includes('到期'))x.due++});return[...m.values()].sort((a,b)=>b.total-a.total||b.unknown-a.unknown||b.wrong-a.wrong)}
 function render(){const mission=document.getElementById('dailyMission');if(!mission)return;let box=document.getElementById('dailyRiskBacklogDetails');const back=load(BACKLOG,{ids:[]}),ids=(back.ids||[]).map(String),map=new Map(qs().map(q=>[String(q.id),q])),rows=ids.map(id=>map.get(id)).filter(Boolean);if(!rows.length){box?.remove();return}const topics=topicSummary(rows),top=topics[0];if(!box){box=document.createElement('details');box.id='dailyRiskBacklogDetails';box.style.margin='10px 0';mission.querySelector('#startDailyMission')?.insertAdjacentElement('beforebegin',box)}box.innerHTML=`<summary style="cursor:pointer;font-weight:850">⏭️ 查看待接續高風險題（${rows.length} 題）</summary><div class="muted" style="font-size:12px;margin:6px 0 8px">這些題不是被刪掉，而是因每日 20 題上限延後；隔天會從較早被延後的題目優先接續。</div><div style="padding:10px 11px;border:1px dashed var(--border);border-radius:11px;background:var(--soft);margin-bottom:9px"><b>📊 高風險主要卡在哪裡？</b><div style="display:flex;gap:6px;flex-wrap:wrap;margin-top:7px">${topics.slice(0,6).map(x=>`<span class="pill">${esc(x.topic)} ${x.total}</span>`).join('')}</div>${top?`<div class="muted" style="font-size:12px;margin-top:6px">目前最多的是「${esc(top.topic)}」${top.total} 題${top.unknown?`，其中 ❓不知道 ${top.unknown}`:''}${top.wrong?`、❌錯題 ${top.wrong}`:''}${top.due?`、🧠到期 ${top.due}`:''}。</div>`:''}</div><div style="display:grid;gap:7px">${rows.slice(0,20).map((q,i)=>`<div style="padding:8px 10px;border:1px solid var(--line);border-radius:10px"><div style="display:flex;justify-content:space-between;gap:8px"><b>${i+1}. ${esc(q.topic||q.subject||'考點')}</b><span style="font-size:12px">${reason(q)}</span></div><div class="muted" style="font-size:12px;margin-top:3px">${esc(q.question||'')}</div><div class="muted" style="font-size:11px;margin-top:2px">${esc(q.subject||'')}｜題號 ${esc(q.id)}</div></div>`).join('')}</div>${rows.length>20?`<div class="muted" style="font-size:12px;margin-top:7px">另有 ${rows.length-20} 題未展開；仍會保留在佇列中。</div>`:''}`}
 function watch(){render();const home=document.getElementById('homeView');if(home&&!home.dataset.backlogUiObserved){home.dataset.backlogUiObserved='1';new MutationObserver(()=>setTimeout(render,30)).observe(home,{childList:true,subtree:true})}window.addEventListener('storage',e=>{if([BACKLOG,STATS,SRS].includes(e.key))render()});window.addEventListener('musicExamLearningSynced',()=>render())}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(watch,150),{once:true});else setTimeout(watch,150);
 window.DailyMissionBacklogUI={render,topicSummary};
})();