// 115 備考首頁導引：今天開始／弱點補強／進階工具
(function(){
 if(window.__HOMEPAGE_FLOW115__)return;window.__HOMEPAGE_FLOW115__=true;
 function qs(s,r){return (r||document).querySelector(s)}
 function esc(s){return String(s||'').replace(/[&<>\"]/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]})}
 function injectStyle(){if(qs('#hf115FlowStyle'))return;var st=document.createElement('style');st.id='hf115FlowStyle';st.textContent=`
.hf115-guide{display:grid;gap:12px;margin-bottom:14px}.hf115-guide-main{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.hf115-guide-card{border:1px solid rgba(127,127,127,.18);border-radius:18px;padding:16px;background:rgba(127,127,127,.035);cursor:pointer;text-align:left}.hf115-guide-card b{display:block;font-size:1.02rem;margin-bottom:6px}.hf115-guide-card small{display:block;line-height:1.5;opacity:.72}.hf115-guide-card.recommended{border-color:rgba(107,79,163,.45);box-shadow:0 6px 18px rgba(107,79,163,.08)}.hf115-guide-pane{display:none;padding:14px;border:1px solid rgba(127,127,127,.15);border-radius:16px;background:rgba(127,127,127,.025)}.hf115-guide-pane.open{display:block}.hf115-guide-steps{display:grid;gap:8px}.hf115-guide-step{display:grid;grid-template-columns:34px 1fr;gap:10px;align-items:start;padding:10px;border-radius:13px;background:rgba(127,127,127,.05)}.hf115-guide-num{width:28px;height:28px;border-radius:50%;display:grid;place-items:center;background:rgba(107,79,163,.13);font-weight:800}.hf115-guide-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.hf115-secondary-tools{display:none}.hf115-secondary-tools.open{display:grid}.hf115-collapse-note{font-size:.86rem;opacity:.72;margin-top:8px}.hf115-guide-actions button:disabled{opacity:.48;cursor:not-allowed}@media(max-width:680px){.hf115-guide-main{grid-template-columns:1fr}.hf115-guide-card{padding:14px}}
`;document.head.appendChild(st)}
 function clickId(id){var b=document.getElementById(id);if(b){b.click();setTimeout(function(){b.scrollIntoView({behavior:'smooth',block:'center'})},120);return true}return false}
 function currentConfusion(){try{var c=window.Confusion115&&window.Confusion115.top?window.Confusion115.top():[];return c.length?c[0]:null}catch(e){return null}}
 function diagnosisState(){var c=currentConfusion();if(c)return{kind:'confusion',text:'目前最需要補強：'+c.pair+'。先做PK確認差異，再進九宮格。'};try{var st=window.MusicTeacherExam&&window.MusicTeacherExam.loadStats?window.MusicTeacherExam.loadStats():{wrong:[],unknown:[]},w=(st.wrong||[]).length,u=(st.unknown||[]).length;if(w+u>0)return{kind:'answers',text:'目前已有 '+w+' 題錯題、'+u+' 題「不知道」，但還沒有形成概念層級診斷。可以先做一組PK並標記「我會了／還會搞混」，系統才會開始建立弱點。'}catch(e){}return{kind:'empty',text:'目前還沒有足夠資料。先完成一輪高頻10題即可；弱點補強不用現在做。'}}
 function refreshWeakPane(){var t=qs('#hf115GuideWeakText'),grid=qs('#hf115GuideGrid'),pk=qs('#hf115GuidePK');if(!t||!grid||!pk)return;var s=diagnosisState();t.textContent=s.text;grid.disabled=s.kind!=='confusion';grid.title=s.kind==='confusion'?'':'先建立概念弱點後，九宮格才會開放';pk.textContent=s.kind==='confusion'?'👹 練這個易混淆PK':'👹 先做一組概念辨析'}
 function build(){var sec=qs('#hf115Section');if(!sec||qs('#hf115Guide'))return false;injectStyle();var wrap=qs('.hf115-wrap',sec),actions=qs('.hf115-actions',sec);if(!wrap||!actions)return false;
  actions.classList.add('hf115-secondary-tools');
  var g=document.createElement('div');g.id='hf115Guide';g.className='hf115-guide';g.innerHTML=`<div><span class="eyebrow">先不用想太多</span><h3 style="margin:4px 0 6px">今天從哪裡開始？</h3><p class="muted" style="margin:0">先選一條路；需要時再打開其他工具。系統會保留原本所有功能。</p></div><div class="hf115-guide-main"><button class="hf115-guide-card recommended" data-pane="start"><b>▶️ 今天開始</b><small>不知道讀什麼時，直接從高頻10題開始。</small></button><button class="hf115-guide-card" data-pane="weak"><b>🩹 弱點補強</b><small>有作答或辨析紀錄後，再專攻最常搞混的概念。</small></button><button class="hf115-guide-card" data-pane="advanced"><b>🧰 進階工具</b><small>名詞口試、30分鐘衝刺、高頻卡與學習作品。</small></button></div><div id="hf115GuideStart" class="hf115-guide-pane open"><div class="hf115-guide-steps"><div class="hf115-guide-step"><span class="hf115-guide-num">1</span><div><b>先做10題</b><div class="hf115-note">系統優先抽115高頻、曾答錯與不知道的題。</div></div></div><div class="hf115-guide-step"><span class="hf115-guide-num">2</span><div><b>看哪裡卡住</b><div class="hf115-note">答錯後不要急著開新範圍，先看弱點與易混淆概念。</div></div></div><div class="hf115-guide-step"><span class="hf115-guide-num">3</span><div><b>再補一輪</b><div class="hf115-note">PK或九宮格完成後，再回高頻題驗證。</div></div></div></div><div class="hf115-guide-actions"><button class="primary" id="hf115GuideQuiz">🎯 直接開始高頻10題</button></div></div><div id="hf115GuideWeak" class="hf115-guide-pane"><p id="hf115GuideWeakText" class="hf115-cue"></p><div class="hf115-guide-actions"><button class="primary" id="hf115GuidePK">👹 先做一組概念辨析</button><button class="ghost" id="hf115GuideGrid">🧩 開始弱點九宮格</button></div></div><div id="hf115GuideAdvanced" class="hf115-guide-pane"><p class="muted">這些工具不是每天都要全部用。依時間與狀態挑一個即可。</p><div class="hf115-guide-actions"><button class="ghost" id="hf115GuideOral">🎙️ 60秒名詞口試</button><button class="ghost" id="hf115GuideSprint">⏱️ 考前30分鐘</button><button class="ghost" id="hf115GuideTop">🔥 必讀高頻</button><button class="ghost" id="hf115GuidePortfolio">📂 我的學習作品</button></div><button class="hf115-btn" id="hf115MoreTools" style="margin-top:10px"><b>展開全部工具</b><small>需要完整功能清單時再打開。</small></button></div><div class="hf115-collapse-note">建議動線：做題 → 發現弱點 → PK辨析 → 九宮格補強 → 再測一次。</div>`;
  wrap.insertBefore(g,actions);
  function openPane(name){['Start','Weak','Advanced'].forEach(function(n){qs('#hf115Guide'+n)?.classList.remove('open')});qs('#hf115Guide'+name.charAt(0).toUpperCase()+name.slice(1))?.classList.add('open');if(name==='weak')refreshWeakPane()}
  g.querySelectorAll('[data-pane]').forEach(function(b){b.onclick=function(){openPane(b.dataset.pane)}});
  qs('#hf115GuideQuiz').onclick=function(){clickId('hf115QuizBtn')};qs('#hf115GuidePK').onclick=function(){clickId('hf115BattleBtn')};qs('#hf115GuideGrid').onclick=function(){if(this.disabled)return;if(!clickId('selfStudy115Btn'))alert('弱點九宮格尚未就緒，先做一組PK並留下判斷。')};qs('#hf115GuideOral').onclick=function(){clickId('hf115OralBtn')};qs('#hf115GuideSprint').onclick=function(){clickId('hf115SprintBtn')};qs('#hf115GuideTop').onclick=function(){clickId('hf115TopBtn')};qs('#hf115GuidePortfolio').onclick=function(){if(!clickId('ss115PortfolioBtn'))alert('目前還沒有可顯示的學習作品。先完成一格九宮格即可。')};qs('#hf115MoreTools').onclick=function(){actions.classList.toggle('open');this.querySelector('b').textContent=actions.classList.contains('open')?'收起全部工具':'展開全部工具'};
  refreshWeakPane();
  if(!document.querySelector('script[data-dailyrec115]')){var s=document.createElement('script');s.src='daily_recommendation_115.js?v=20260820f';s.dataset.dailyrec115='1';document.head.appendChild(s)}
  return true}
 function boot(){var n=0,t=setInterval(function(){n++;if(build())clearInterval(t);if(n>80)clearInterval(t)},150)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
 window.HomepageFlow115={refreshWeakPane:refreshWeakPane,diagnosisState:diagnosisState};
})();