(()=>{
 if(window.__LATEST_LOADER_BOOTSTRAP__)return;window.__LATEST_LOADER_BOOTSTRAP__=true;
 const files=[
  'navigation_state.js','home_organizer.js',
  'questions_108_110_backfill_batch21.js','questions_106_107_backfill_batch22.js','questions_107_highschool_depth_batch23.js','questions_107_music_education_batch24.js','questions_108_highschool_depth_batch25.js','questions_111_highschool_depth_batch26.js','questions_112_113_highschool_depth_batch27.js','questions_114_junior_senior_depth_batch28.js','questions_115_junior_senior_depth_batch29.js','questions_115_analysis_depth_batch30.js',
  'terms_108_110_backfill.js','terms_109_highschool_backfill.js','terms_110_highschool_depth.js','terms_111_112_highschool_backfill.js','terms_113_highschool_backfill.js','terms_115_highschool_depth.js','terms_115_moe_changhua_batch31.js',
  'essay_107_lioujia_backfill.js','essay_108_changhua_girls_detailed.js','essay_110_highschool_detailed.js','essay_111_112_highschool_detailed.js','essay_113_highschool_detailed.js','essay_114_highschool_detailed.js','essay_115_junior_senior_detailed.js','essay_115_moe_changhua_batch31.js',
  'content_adapter_v1.js','radar_106_115_priority_v1.js','question_quality_rules_v1.js','canonical_concepts_v1.js','high_frequency_ladder_v2.js','difficulty_ladder_v1.js','concept_mastery_v1.js','duplicate_ladder_v2.js','option_explanations_curated_115_batch1.js','option_explanations_curated_115_batch2.js','option_explanations_curated_114_batch2.js','option_explanations_curated_112_113_batch4.js','option_explanations_curated_111_batch5.js','option_explanations_curated_108_110_batch6.js','option_explanations_curated_108_depth_batch7.js','option_explanations_curated_107_depth_batch8.js','option_explanations_curated_107_education_batch9.js','option_explanations_curated_106_107_backfill_batch10.js','option_explanations_v1.js','option_explanation_ui_v1.js','study_notes_library.js','personal_priority.js','daily_mission.js','daily_mission_completion.js','risk_topic_drill_progress.js','daily_mission_backlog_ui.js','wrong_book_views.js','unknown_book_views.js','learning_progress.js','learning_sync.js'
 ];
 const loaded=new Set([...document.scripts].map(s=>(s.getAttribute('src')||'').split('?')[0]));
 function load(src){return new Promise(resolve=>{if(loaded.has(src)){resolve();return}const s=document.createElement('script');s.src=src+'?v=20260819as';s.onload=()=>{loaded.add(src);resolve()};s.onerror=()=>resolve();document.body.appendChild(s)})}
 (async()=>{for(const src of files)await load(src);window.dispatchEvent(new CustomEvent('musicExamLatestModulesReady'))})();
})();