(()=>{
 const STATS='musicTeacherExamStatsV1';
 const load=()=>{try{return JSON.parse(localStorage.getItem(STATS))||{}}catch{return{}}};
 const questions=()=>window.MusicTeacherExam?.questions||[];
 const dayKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
 function sumDays(daily,from,to){let n=0;for(let i=from;i<to;i++){const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()-i);n+=daily?.[dayKey(d)]||0}return n}
 function metrics(){const s=load(),attempts=s.attempts||{},daily=s.daily||{},subs=['國中音樂','高中音樂','教育專業'];const subject={};subs.forEach(sub=>{let total=0,correct=0;questions().filter(q=>q.subject===sub).forEach(q=>{const a=attempts[q.id];if(a){total+=a.total||0;correct+=a.correct||0}});subject[sub]={total,acc:total?Math.round(correct/total*100):null}});const total=Object.values(attempts).reduce((n,a)=>n+(a.total||0),0),recent=sumDays(daily,0,7),previous=sumDays(daily,7,14),delta=previous?Math.round((recent-previous)/previous*100):(recent?100:0);return{total,recent,previous,delta,subject}}
 function mount(){const home=document.getElementById('homeView');if(!home||document.getElementById('learningProgressPanel'))return;const sec=document.createElement('section');sec.id='learningProgressPanel';sec.className='card section-card';sec.style.display='none';const stats=home.querySelector('.stats-grid');(stats||home.firstElementChild)?.insertAdjacentElement('afterend',sec);render()}
 function render(){const box=document.getElementById('learningProgressPanel');if(!box)return;const m=metrics(),trend=m.recent===m.previous?'→ 持平':m.recent>m.previous?'↗ 增加':'↘ 減少',delta=Math.abs(m.delta);box.innerHTML=`<div class="section-title"><div><span class="eyebrow">只看進步，不混入記憶排程</span><h3>📈 我的進步</h3></div></div><p class="muted">這裡回答「最近有沒有變強？」；熟練度與到期複習請到旁邊的 🧠 熟練。</p><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(145px,1fr));gap:9px;margin:12px 0"><div class="card" style="padding:13px"><small class="muted">累積作答</small><div style="font-size:26px;font-weight:850">${m.total}<small style="font-size:12px"> 題次</small></div></div><div class="card" style="padding:13px"><small class="muted">近 7 天</small><div style="font-size:26px;font-weight:850">${m.recent}<small style="font-size:12px"> 題</small></div><small class="muted">${trend}${m.previous?` ${delta}%`:''}</small></div>${Object.entries(m.subject).map(([sub,x])=>`<div class="card" style="padding:13px"><small class="muted">${sub}</small><div style="font-size:26px;font-weight:850">${x.acc??'--'}<small style="font-size:12px">%</small></div><small class="muted">${x.total} 題次</small></div>`).join('')}</div>`}
 function bind(){mount();const fb=document.getElementById('feedback');if(fb)new MutationObserver(()=>{if(!fb.classList.contains('hidden'))setTimeout(render,50)}).observe(fb,{attributes:true,attributeFilter:['class']});window.HomeCategoryOrganizer?.apply?.()}
 document.addEventListener('DOMContentLoaded',()=>setTimeout(bind,1000));window.LearningProgress={metrics,render};
})();