(()=>{
const $=id=>document.getElementById(id),TERM_KEY='musicTeacherTermLearningV1';
const loadTerms=()=>{try{return JSON.parse(localStorage.getItem(TERM_KEY))||{}}catch{return{}}};
function ensureStyles(){if($('nonchoiceCenterStyles'))return;const s=document.createElement('style');s.id='nonchoiceCenterStyles';s.textContent=`
.nc-center{margin-bottom:18px}.nc-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:12px}.nc-card{border:1px solid var(--line);background:var(--panel);color:inherit;border-radius:16px;padding:16px;text-align:left;cursor:pointer;transition:.18s}.nc-card:hover{border-color:var(--brand);transform:translateY(-1px)}.nc-card b{display:block;font-size:17px;margin:6px 0}.nc-card small{display:block;color:var(--muted);line-height:1.55}.nc-icon{font-size:28px}.nc-count{margin-top:8px;font-size:12px;font-weight:800;color:var(--brand)}.nc-status{margin-top:10px;padding:9px 10px;border-radius:10px;background:var(--soft);font-size:12px;line-height:1.5}.nc-note{margin-top:12px;padding:11px 13px;border-radius:12px;background:var(--soft);font-size:13px;color:var(--muted);line-height:1.55}.nc-hidden-original{display:none!important}@media(max-width:720px){.nc-grid{grid-template-columns:1fr}.nc-card{padding:13px 14px;display:grid;grid-template-columns:38px 1fr;column-gap:9px;align-items:start}.nc-icon{grid-row:1/5;font-size:25px}.nc-card b{margin:1px 0 4px;font-size:16px}.nc-card small{line-height:1.4}.nc-card .nc-count,.nc-card .nc-status{grid-column:2}.nc-status{margin-top:6px;padding:7px 9px}.nc-note{font-size:12px}}
`;document.head.appendChild(s)}
function findOriginalCards(){const termBtn=$('termBtn'),essayBtn=$('essayBtn');return{termCard:termBtn?.closest('.section-card')||null,essayCard:essayBtn?.closest('.section-card')||null}}
function termSummary(){const all=window.MusicTeacherExam?.terms||window.TERM_PROMPTS||[],data=loadTerms(),now=Date.now();let seen=0,due=0,mastered=0;all.forEach(t=>{const r=data[t.id];if(!r)return;seen++;if(r.mastery)mastered++;if(r.due&&new Date(r.due).getTime()<=now)due++});return{total:all.length,seen,due,mastered}}
function revealAndScroll(target){if(!target)return false;target.classList.remove('hidden');target.style.display='';setTimeout(()=>target.scrollIntoView({behavior:'smooth',block:'start'}),80);return true}
function openTrial(){const trial=$('mtTrialPractice')||$('mtTrialSimulator')||$('mtTrialPrompt')?.closest('.card')||$('mtTrialPrompt')?.closest('section');if(revealAndScroll(trial))return;const essay=$('essayBtn');if(essay){essay.click();setTimeout(()=>revealAndScroll($('mtTrialPractice')||$('mtTrialSimulator')||$('mtTrialPrompt')?.closest('section')),120)}}
function openTerm(){const btn=$('termBtn');if(btn){btn.click();setTimeout(()=>revealAndScroll($('termView')||$('termName')?.closest('section')||$('termName')?.closest('.card')),100)}}
function openEssay(){const btn=$('essayBtn');if(btn){btn.click();setTimeout(()=>revealAndScroll($('essayView')||$('essayQuestion')?.closest('section')||$('essayQuestion')?.closest('.card')),100)}}
function renderStatus(){const s=termSummary(),term=$('ncTermStatus');if(term)term.innerHTML=`已練 ${s.seen}/${s.total}｜🏆 ${s.mastered} 題真正掌握｜今天到期 ${s.due} 題`;const ec=$('ncEssayCount');if(ec)ec.textContent=`目前 ${window.MusicTeacherExam?.essays?.length||window.ESSAY_PROMPTS?.length||0} 題`}
function mount(){if($('nonchoiceCenter')){renderStatus();return}ensureStyles();const home=$('homeView'),{termCard,essayCard}=findOriginalCards();if(!home||!termCard||!essayCard)return;const center=document.createElement('section');center.id='nonchoiceCenter';center.className='card section-card nc-center';const termCount=window.MusicTeacherExam?.terms?.length||window.TERM_PROMPTS?.length||0,essayCount=window.MusicTeacherExam?.essays?.length||window.ESSAY_PROMPTS?.length||0;center.innerHTML=`<div class="section-title"><div><span class="eyebrow">非選題學習中心</span><h3>名詞解釋・申論題・試教</h3></div></div><p class="muted">把「知道」練成考場上真的能寫、能說、能教。三種輸出都從這裡進入。</p><div class="nc-grid"><button class="nc-card" id="ncTermBtn" type="button"><span class="nc-icon">📖</span><b>名詞解釋</b><small>原文主動提取、5W／人事時地物、三力成長、間隔複習。</small><div class="nc-count">目前 ${termCount} 題</div><div class="nc-status" id="ncTermStatus">正在讀取學習狀態…</div></button><button class="nc-card" id="ncEssayBtn" type="button"><span class="nc-icon">✍️</span><b>申論題</b><small>自己先寫，再看答題架構、詳細擬答與教甄得分重點。</small><div class="nc-count" id="ncEssayCount">目前 ${essayCount} 題</div><div class="nc-status">建議：先列 3～5 個關鍵點，再展開成完整段落。</div></button><button class="nc-card" id="ncTrialBtn" type="button"><span class="nc-icon">🎤</span><b>試教練習</b><small>10 分鐘試教、目標－活動－評量，練口語結構與教學轉化。</small><div class="nc-count">試教模式</div><div class="nc-status">建議：1 分鐘想目標，8 分鐘教學，1 分鐘形成性評量。</div></button></div><div class="nc-note">建議順序：📖 名詞建立專業表達 → ✍️ 申論整合知識 → 🎤 試教把專業轉成學生能參與的課堂。</div>`;termCard.parentElement.insertBefore(center,termCard);termCard.classList.add('nc-hidden-original');essayCard.classList.add('nc-hidden-original');$('ncTermBtn')?.addEventListener('click',openTerm);$('ncEssayBtn')?.addEventListener('click',openEssay);$('ncTrialBtn')?.addEventListener('click',openTrial);renderStatus();window.addEventListener('storage',renderStatus)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(mount,160));else setTimeout(mount,160);
})();