(()=>{
const $=id=>document.getElementById(id);
function ensureStyles(){if($('nonchoiceCenterStyles'))return;const s=document.createElement('style');s.id='nonchoiceCenterStyles';s.textContent=`
.nc-center{margin-bottom:18px}.nc-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:12px}.nc-card{border:1px solid var(--line);background:var(--panel);color:inherit;border-radius:16px;padding:16px;text-align:left;cursor:pointer;transition:.18s}.nc-card:hover{border-color:var(--brand);transform:translateY(-1px)}.nc-card b{display:block;font-size:17px;margin:6px 0}.nc-card small{display:block;color:var(--muted);line-height:1.55}.nc-icon{font-size:28px}.nc-count{margin-top:8px;font-size:12px;font-weight:800;color:var(--brand)}.nc-note{margin-top:12px;padding:11px 13px;border-radius:12px;background:var(--soft);font-size:13px;color:var(--muted);line-height:1.55}.nc-hidden-original{display:none!important}@media(max-width:720px){.nc-grid{grid-template-columns:1fr}}
`;document.head.appendChild(s)}
function findOriginalCards(){const termBtn=$('termBtn'),essayBtn=$('essayBtn');return{termCard:termBtn?.closest('.section-card')||null,essayCard:essayBtn?.closest('.section-card')||null}}
function openTrial(){const trial=$('mtTrialPractice')||$('mtTrialPrompt')?.closest('.card')||$('mtTrialPrompt')?.closest('section');if(trial){trial.scrollIntoView({behavior:'smooth',block:'start'});return}const essay=$('essayBtn');if(essay)essay.click()}
function mount(){if($('nonchoiceCenter'))return;ensureStyles();const home=$('homeView'),{termCard,essayCard}=findOriginalCards();if(!home||!termCard||!essayCard)return;
 const center=document.createElement('section');center.id='nonchoiceCenter';center.className='card section-card nc-center';const termCount=window.MusicTeacherExam?.terms?.length||window.TERM_PROMPTS?.length||0;const essayCount=window.MusicTeacherExam?.essays?.length||window.ESSAY_PROMPTS?.length||0;
 center.innerHTML=`<div class="section-title"><div><span class="eyebrow">非選題學習中心</span><h3>名詞解釋・申論題・試教</h3></div></div><p class="muted">非選題不要再散著找。從這裡選你今天要練的輸出形式。</p><div class="nc-grid"><button class="nc-card" id="ncTermBtn" type="button"><span class="nc-icon">📖</span><b>名詞解釋</b><small>原文主動提取、5W／人事時地物、三力成長、間隔複習。</small><div class="nc-count">目前 ${termCount} 題</div></button><button class="nc-card" id="ncEssayBtn" type="button"><span class="nc-icon">✍️</span><b>申論題</b><small>自己先寫，再看答題架構、詳細擬答與教甄得分重點。</small><div class="nc-count">目前 ${essayCount} 題</div></button><button class="nc-card" id="ncTrialBtn" type="button"><span class="nc-icon">🎤</span><b>試教練習</b><small>10 分鐘試教、目標－活動－評量，練口語結構與教學轉化。</small><div class="nc-count">試教模式</div></button></div><div class="nc-note">建議順序：先練「名詞解釋」建立專業表達，再用「申論題」整合知識，最後用「試教」把專業轉成學生真的能參與的課堂。</div>`;
 termCard.parentElement.insertBefore(center,termCard);termCard.classList.add('nc-hidden-original');essayCard.classList.add('nc-hidden-original');
 $('ncTermBtn')?.addEventListener('click',()=>$('termBtn')?.click());$('ncEssayBtn')?.addEventListener('click',()=>$('essayBtn')?.click());$('ncTrialBtn')?.addEventListener('click',openTrial);
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(mount,160));else setTimeout(mount,160);
})();