(() => {
  const KEY='musicTeacherExamNotationPracticeV1';
  const EX=[
    {id:'N01',type:'終止式',key:'C大調',title:'判斷終止式',prompt:'觀察最後兩個和弦的外聲部與和弦構成。請寫出羅馬數字，並判斷終止式種類。',notes:[{s:'G4',a:'D4',t:'B3',b:'G2',roman:'?'},{s:'C5',a:'E4',t:'C4',b:'C3',roman:'?'}],answer:'V－I；兩個和弦皆根音位置，最高聲部最後到主音 C，因此為完全正格終止（PAC）。',check:['寫出 V－I','辨識兩個和弦皆根音位置','指出最高聲部落在主音','判斷為 PAC']},
    {id:'N02',type:'羅馬數字',key:'G大調',title:'辨識和弦與轉位',prompt:'請依低音與各聲部音高，寫出兩個和弦的羅馬數字與轉位。',notes:[{s:'E5',a:'C5',t:'G4',b:'C3',roman:'?'},{s:'F#5',a:'D5',t:'A4',b:'D3',roman:'?'}],answer:'第一個和弦 C–E–G，低音 C：IV；第二個和弦 D–F♯–A，低音 D：V。',check:['辨識 C–E–G 為 IV','辨識 D–F♯–A 為 V','調號中的 F♯ 有納入判讀','轉位判斷正確']},
    {id:'N03',type:'羅馬數字',key:'a小調',title:'屬七和弦解決',prompt:'請寫出兩個和弦的功能，並說明 G♯ 與 D 在進行中的典型解決方向。',notes:[{s:'G#4',a:'D4',t:'B3',b:'E3',roman:'?'},{s:'A4',a:'C4',t:'A3',b:'A2',roman:'?'}],answer:'V7－i。G♯ 是導音，典型向上解決到 A；D 是 V7 的七音，典型向下解決到 C。',check:['寫出 V7－i','G♯→A','D→C','知道兩者分別是導音與和弦七音']},
    {id:'N04',type:'終止式',key:'C大調',title:'半終止辨識',prompt:'下列片段停在屬和弦。請判斷最後和聲功能與終止式，並說明為何不能稱 PAC。',notes:[{s:'F4',a:'D4',t:'A3',b:'D3',roman:'?'},{s:'G4',a:'D4',t:'B3',b:'G2',roman:'?'}],answer:'ii－V，最後停在 V，因此為半終止（HC）；PAC 必須以 V－I 收束。',check:['辨識 ii－V','最後和弦是 V','判斷為 HC','能說明 PAC 必須解決到 I']},
    {id:'N05',type:'非和弦音',key:'C大調',title:'經過音／鄰音',prompt:'旋律 E4–F4–G4 發生在同一個 C 大三和弦延長背景上。若 E 與 G 為和弦音，F 最可能是哪一種非和弦音？',melody:['E4','F4','G4'],answer:'F 是級進連接兩個和弦音 E 與 G 的經過音（passing tone）。',check:['確認 E、G 為和弦音','F 以級進進入','F 以同方向級進離開','判斷為經過音']},
    {id:'N06',type:'非和弦音',key:'G大調',title:'掛留音辨識',prompt:'前一和弦中的 C5 延留到 D 大三和弦上形成不協和，之後下行解決至 B4。請判斷此 C5 的非和弦音類型。',melody:['C5','C5','B4'],bass:['C3','D3','D3'],answer:'C5 由前一和弦保留（prepared）、在新和弦形成不協和，再下行解決至 B4，屬掛留音（suspension）；可視語境分析為 4–3 suspension。',check:['有準備音','跨和弦延留','形成不協和','下行解決，判斷為 suspension']},
    {id:'N07',type:'調性',key:'D大調',title:'調性與屬功能',prompt:'旋律末端出現 C♯–D，同時低音 A–D。請指出 C♯ 的調性角色，以及 A–D 的功能意義。',melody:['A4','C#5','D5'],bass:['D3','A2','D3'],answer:'C♯ 是 D 大調的導音，向上解決至 D；低音 A–D 對應屬到主（V–I）的根音運動，強化主調確認。',check:['C♯ 是導音','C♯→D','A 是 D 大調屬音','A→D 支持 V－I']},
    {id:'N08',type:'轉調',key:'C→G',title:'樞紐和弦概念',prompt:'若 C 大調中的 Am 和弦之後出現 D7，接著到 G，請嘗試做雙重羅馬數字分析，指出可能的樞紐理解。',notes:[{s:'E5',a:'C5',t:'A4',b:'A2',roman:'?'},{s:'F#5',a:'C5',t:'A4',b:'D3',roman:'?'},{s:'G5',a:'D5',t:'B4',b:'G2',roman:'?'}],answer:'Am 在 C 大調可作 vi，在 G 大調可作 ii，因此可作 vi(C)=ii(G) 的樞紐和弦；之後 D7 是 G 大調的 V7，解決到 I(G)。',check:['Am＝C大調 vi','Am＝G大調 ii','D7＝G大調 V7','G＝新調 I，形成調性確認']}
  ];
  let current=0;
  const $=id=>document.getElementById(id);
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const load=()=>{try{return JSON.parse(localStorage.getItem(KEY))||{done:{}}}catch{return{done:{}}}};
  const save=x=>localStorage.setItem(KEY,JSON.stringify(x));
  const pitchIndex=p=>{const m=String(p).match(/^([A-G])([#b]?)(\d)$/);if(!m)return 0;const di={C:0,D:1,E:2,F:3,G:4,A:5,B:6};return Number(m[3])*7+di[m[1]]};
  const yTreble=p=>92-(pitchIndex(p)-pitchIndex('E4'))*6;
  const yBass=p=>178-(pitchIndex(p)-pitchIndex('G2'))*6;
  function note(x,y,stem=true){return `<ellipse cx="${x}" cy="${y}" rx="6" ry="4.5" fill="currentColor" transform="rotate(-15 ${x} ${y})"/>${stem?`<line x1="${x+5}" y1="${y}" x2="${x+5}" y2="${y-28}" stroke="currentColor" stroke-width="1.8"/>`:''}`}
  function accidental(p,x,y){if(p.includes('#'))return `<text x="${x-13}" y="${y+4}" font-size="15">♯</text>`;if(p.includes('b'))return `<text x="${x-13}" y="${y+4}" font-size="15">♭</text>`;return ''}
  function staffLines(y0){return [0,1,2,3,4].map(i=>`<line x1="28" y1="${y0+i*12}" x2="392" y2="${y0+i*12}" stroke="currentColor" stroke-width="1" opacity=".72"/>`).join('')}
  function chordSvg(ex){const chords=ex.notes||[];return `<svg viewBox="0 0 420 225" role="img" aria-label="和聲五線譜題" style="width:100%;height:auto;display:block;color:currentColor">${staffLines(52)}${staffLines(142)}<text x="8" y="78" font-size="13">高</text><text x="8" y="168" font-size="13">低</text>${chords.map((c,i)=>{const x=95+i*(260/Math.max(1,chords.length-1));const pts=[[c.s,yTreble(c.s)],[c.a,yTreble(c.a)],[c.t,yBass(c.t)],[c.b,yBass(c.b)]];return pts.map(([p,y])=>accidental(p,x,y)+note(x,y)).join('')+`<text x="${x-13}" y="214" font-size="14" font-weight="700">${esc(c.roman)}</text>`}).join('')}<line x1="400" y1="52" x2="400" y2="190" stroke="currentColor" stroke-width="2"/></svg>`}
  function melodySvg(ex){const mel=ex.melody||[],bass=ex.bass||[];return `<svg viewBox="0 0 420 225" role="img" aria-label="旋律五線譜題" style="width:100%;height:auto;display:block;color:currentColor">${staffLines(52)}${bass.length?staffLines(142):''}<text x="8" y="78" font-size="13">高</text>${bass.length?'<text x="8" y="168" font-size="13">低</text>':''}${mel.map((p,i)=>{const x=90+i*110,y=yTreble(p);return accidental(p,x,y)+note(x,y)}).join('')}${bass.map((p,i)=>{const x=90+i*110,y=yBass(p);return accidental(p,x,y)+note(x,y)}).join('')}</svg>`}
  function styles(){if($('notationStyles'))return;const s=document.createElement('style');s.id='notationStyles';s.textContent=`.notation-card{margin-top:18px;padding:22px}.notation-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.notation-score{margin:14px 0;padding:12px;border:1px solid var(--line);border-radius:14px;background:var(--panel);overflow:auto}.notation-meta{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0}.notation-answer{width:100%;min-height:110px;border:1px solid var(--line);border-radius:12px;padding:12px;background:var(--panel);color:inherit;font:inherit;line-height:1.6;resize:vertical}.notation-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.notation-actions button{border:1px solid var(--line);background:var(--panel);color:inherit;border-radius:10px;padding:9px 12px;font-weight:800;cursor:pointer}.notation-actions .primary{background:var(--brand);color:#fff;border-color:var(--brand)}.notation-solution{margin-top:12px;padding:14px;border-radius:12px;background:var(--soft);line-height:1.65}.notation-checks{display:grid;gap:7px;margin-top:10px}.notation-progress{font-size:13px;color:var(--muted)}@media(max-width:700px){.notation-head{flex-direction:column}}`;document.head.appendChild(s)}
  function ensure(){if($('notationPractice'))return;const wrap=document.querySelector('.written-wrap');if(!wrap)return;const sec=document.createElement('section');sec.id='notationPractice';sec.className='card notation-card';sec.innerHTML=`<div class="notation-head"><div><span class="eyebrow">視覺快判</span><h2 style="margin:5px 0 0">🎼 五線譜／和聲分析</h2></div><span id="notationProgress" class="notation-progress"></span></div><p class="muted">先看譜寫答案，再展開解析。這一區練「看到譜面就能快速說出功能與證據」。</p><div class="notation-meta"><span id="notationType" class="written-pill"></span><span id="notationKey" class="written-pill"></span><span id="notationTitle" class="written-pill"></span></div><div id="notationScore" class="notation-score"></div><div id="notationPrompt" class="written-prompt"></div><textarea id="notationAnswer" class="notation-answer" placeholder="請寫：判斷結果＋至少一個譜面證據…"></textarea><div class="notation-actions"><button id="notationPrev">← 上一題</button><button id="notationNext">下一題 →</button><button id="notationReveal" class="primary">看解析／自評</button></div><div id="notationSolution" class="notation-solution" hidden></div>`;wrap.appendChild(sec)}
  function render(){const ex=EX[current],data=load();$('notationType').textContent=ex.type;$('notationKey').textContent=ex.key;$('notationTitle').textContent=ex.title;$('notationPrompt').textContent=ex.prompt;$('notationScore').innerHTML=ex.notes?chordSvg(ex):melodySvg(ex);$('notationAnswer').value='';$('notationSolution').hidden=true;$('notationSolution').innerHTML='';$('notationProgress').textContent=`${current+1}/${EX.length}｜已完成 ${Object.keys(data.done||{}).length} 題`;}
  function reveal(){const ex=EX[current],d=load();d.done=d.done||{};d.done[ex.id]={at:new Date().toISOString(),answer:$('notationAnswer').value};save(d);$('notationSolution').innerHTML=`<b>參考解析</b><div style="margin-top:6px">${esc(ex.answer)}</div><div class="notation-checks">${ex.check.map(x=>`<label><input type="checkbox"> ${esc(x)}</label>`).join('')}</div>`;$('notationSolution').hidden=false;$('notationProgress').textContent=`${current+1}/${EX.length}｜已完成 ${Object.keys(d.done).length} 題`;}
  function bind(){$('notationPrev')?.addEventListener('click',()=>{current=(current-1+EX.length)%EX.length;render()});$('notationNext')?.addEventListener('click',()=>{current=(current+1)%EX.length;render()});$('notationReveal')?.addEventListener('click',reveal)}
  document.addEventListener('DOMContentLoaded',()=>{styles();ensure();bind();render()});
})();