(()=>{const bank={
'sh107-b23-01':{A:'正確。Gregorian chant 以中世紀拉丁禮儀單聲部素歌為核心；文藝復興則高度發展彌撒、經文歌等複音聲樂。',B:'大鍵琴主要與文藝復興晚期、巴洛克鍵盤文化相關；Gregorian chant 本質上不是以大鍵琴伴奏為核心，文藝復興也絕非沒有聲樂。',C:'十二音列是20世紀 Schoenberg 等人的音高組織技法，與中世紀、文藝復興相隔數百年。',D:'Gregorian chant 屬中世紀，文藝復興複音約15、16世紀；兩者都不是19世紀音樂。'},
'sh107-b23-02':{A:'正確。可先記 Swing（1930s）→ Bebop（1940s）→ Cool Jazz（1940末–50s）→ Free Jazz（1950末–60s）→ Fusion（1960末後）。',B:'Bebop 是對 Swing 時代商業大樂團語法的重要突破，歷史上晚於 Swing；Fusion 又比 Cool Jazz、Free Jazz 更晚。',C:'Cool Jazz 晚於 Swing 與 Bebop，因此不能放在最前。',D:'Fusion 是較晚期爵士與搖滾、電子聲響等融合的發展，不可能早於 Swing、Bebop。'},
'sh107-b23-03':{A:'正確。G 小調的 ♭II 是 A♭，因此拿坡里和弦為 A♭–C–E♭ 大三和弦，典型 N6 採第一轉位 C–E♭–A♭。',B:'A 大三和弦以 A 自然音為根音，並非 G 小調的降二級。',C:'E♭ 大三和弦是 G 小調的 VI 級相關和弦，不是 ♭II 拿坡里和弦。',D:'D 大三和弦是 G 小調中常見的 V 級屬和弦，功能與前屬性的 N6 不同。'},
'sh107-b23-04':{A:'正確。David J. Elliott 是 Praxial Music Education 的代表學者，強調 musicing、listening 與具情境性的音樂實踐。',B:'Carl Orff 代表 Orff Schulwerk，重視語言、律動、即興與器樂活動，不是 Praxialism 理論的提出者。',C:'Howard Gardner 以多元智能理論著名，可應用於教育，但不是音樂教育實踐主義的代表人物。',D:'John Curwen 與 tonic sol-fa、手號等視唱教育傳統密切相關。'},
'sh107-b23-05':{A:'正確。Audiation 是 Gordon 音樂學習理論核心：即使外在聲音不存在，也能在心中聽見、理解、預期並組織音樂意義。',B:'視譜速度只是可能的技能表現，不能等同 audiation，更不能單獨代表整體音樂能力。',C:'固定手勢較容易聯想到 Curwen／Kodály 手號系統，Gordon 並不以手勢取代所有歌唱。',D:'逐步加快速度是一種練習策略，不是 Gordon 對 audiation 的定義。'},
'sh107-b23-06':{A:'正確。Kodály 教學常用的手號承接 John Curwen 的 tonic sol-fa hand signs，再融入其音樂教育體系。',B:'Lowell Mason 是美國學校音樂教育的重要推動者，但不是 Kodály 手號最直接的來源。',C:'Dalcroze 核心是 Eurhythmics、solfège、improvisation，以身體律動感受音樂，不是這套手號的來源。',D:'Edwin Gordon 以 Music Learning Theory、audiation 等概念著名。'},
'sh107-b23-07':{A:'正確。〈桃花泣血記〉由王雲峰作曲、詹天馬作詞，是臺灣早期流行歌曲史的重要作品。',B:'鄧雨賢代表作常見〈望春風〉、〈雨夜花〉、〈月夜愁〉、〈四季紅〉等，容易被拿來與早期臺語歌曲互相干擾。',C:'呂泉生在合唱、兒童歌曲與音樂教育等領域貢獻深遠，但不是〈桃花泣血記〉作曲者。',D:'郭芝苑是臺灣重要作曲家，創作橫跨管弦、室內樂、歌曲等，世代與作品脈絡不同。'},
'sh107-b23-08':{A:'正確。Tala 是印度古典音樂的節奏循環與拍點組織系統；複習時應與旋律框架 Raga 成對比較。',B:'Raga 也不能簡化為「固定七聲音階名稱」；它是具有音高材料、典型行進、重要音與情緒規範的旋律框架。',C:'北印度弓弦樂器可想到 sarangi 等；Tala 本身不是樂器名稱。',D:'Tala 是節奏概念，可存在於多種印度古典音樂實踐中，不是專指宗教合唱曲。'},
'sh107-b23-09':{A:'正確。Idiophone 的聲音主要由樂器本體材料振動產生，例如鐘、鈸、木魚等。',B:'以拉緊膜振動發聲的是 membranophone 膜鳴樂器，例如多數鼓類。',C:'以弦振動發聲的是 chordophone 弦鳴樂器，例如小提琴、古箏等。',D:'以空氣柱或氣流振動發聲的是 aerophone 氣鳴樂器，例如笛、塤、號等。'}
};function apply(){const qs=window.MusicTeacherExam?.questions||window.LOCAL_QUESTIONS||[];qs.forEach(q=>{if(bank[q.id])q.option_explanations={...(q.option_explanations||{}),...bank[q.id]}})}apply();window.addEventListener('musicExamLatestModulesReady',apply);})();