(()=>{const bank={
'sh107-b24-01':{A:'這與 Pestalozzian／Mason 的由具體到抽象原則相反；不應先塞入抽象符號再讓學生接觸聲響。',B:'正確。Lowell Mason 受 Pestalozzian 教育思想影響，強調先有聲音與實際經驗，再逐步歸納規則、名稱與符號。',C:'Mason 對美國學校歌唱教育影響深遠，並非排除歌唱、只做器樂合奏。',D:'十二音技法到20世紀才形成，與19世紀 Mason 的兒童音樂教育思想無關。'},
'sh107-b24-02':{A:'正確。Contemporary Music Project（CMP）與 Comprehensive Musicianship 密切相關，主張整合演奏、創作、分析、聆聽等音樂能力。',B:'Juilliard Repertory Project 主要關注學校音樂教材與曲目資源，不是 Comprehensive Musicianship 最直接的計畫來源。',C:'Manhattanville Music Curriculum Program（MMCP）也是1960年代重要課程改革，強調概念、螺旋課程與探索，但與本題名詞的直接連結不如 CMP。',D:'Tanglewood Symposium 關注音樂教育的社會角色、廣泛音樂文化與未來方向，並非 Comprehensive Musicianship 的直接計畫名稱。'},
'sh107-b24-03':{A:'Dalcroze 以律動、視唱與即興著名，不是 Kodály 手號的直接來源。',B:'正確。John Curwen 發展 tonic sol-fa 手號傳統，後來被 Kodály 體系吸收與運用。',C:'Gordon 代表 Music Learning Theory 與 audiation，不是 Curwen hand signs 的來源。',D:'Lowell Mason 是美國學校音樂教育先驅之一，但不是這套手號的直接來源。'},
'sh107-b24-04':{A:'正確。David J. Elliott 是 Praxial Music Education 的重要代表，強調 musicing、listening、情境與音樂實踐中的知識。',B:'Howard Gardner 以多元智能理論著名，雖與藝術教育應用有關，但不是 Praxialism 的代表學者。',C:'Carl Orff 代表 Orff Schulwerk 教學體系，重視語言、律動、即興與器樂活動。',D:'Benjamin Bloom 與教育目標分類學密切相關，不是音樂教育實踐主義的代表人物。'},
'sh107-b24-05':{A:'默讀樂譜可能運用內在聽覺，但 audiation 不等於「只看譜不出聲」這個外在行為。',B:'正確。Audiation 是在外在聲響不存在時，仍能內在聽見、理解、預期並賦予音樂意義。',C:'固定唱名或首調唱名是視唱系統選擇，不能等同 Gordon 的 audiation。',D:'用身體感受節拍更容易聯想到 Dalcroze Eurhythmics；它可以促進音樂理解，但不是 audiation 的定義。'},
'sh107-b24-06':{A:'正確。「審美感知」屬藝術領域學習重點中的重要關鍵內涵，應辨識正式課綱層級與用語。',B:'「音樂欣賞」是常見教學活動或課程內容稱呼，但不是此處所問的核心關鍵內涵名稱。',C:'樂器分類可以成為教材內容，但層級較具體，不能取代課綱的上位學習內涵。',D:'曲式分析也是具體音樂知識與學習活動，不是藝術領域上位關鍵內涵名稱。'},
'sh107-b24-07':{A:'題幹要求使用音樂語彙賞析作品與文化，不是在檢核單純演奏技巧。',B:'正確。學生需要描述、分析、詮釋並體會作品文化意義，核心落在音樂鑑賞與審美理解。',C:'行政活動規劃不是題幹所描述的學生藝術學習表現。',D:'數位科技可成為學習媒介，但題幹沒有把目標限定為工具操作；真正目標是賞析與審美理解。'},
'sh107-b24-08':{A:'背誦可以是基礎知識的一部分，但若停在生卒年記憶，沒有情境運用與整合，不足以代表素養導向。',B:'正確。素養導向強調在真實或模擬情境中整合知識、技能、態度，完成任務並能遷移應用。',C:'教師講述與筆記可作為部分策略，但若每堂都只有被動抄寫，難以呈現自主、實踐與整合。',D:'單次選擇題可以測部分知識，但素養評量通常需要更多元的任務、歷程、作品、表現與反思證據。'},
'sh107-b24-09':{A:'兩科先後各講各的只是並置（multidisciplinary-like juxtaposition），缺乏共同問題與知識方法的真正整合。',B:'正確。以共同真實問題／任務為核心，要求學生調用不同領域的方法完成作品並反思，才真正呈現跨領域整合。',C:'把講義裝訂在一起只改變教材外觀，沒有改變學習任務與知識關係。',D:'兩科各自考試再平均仍是分科評量，無法證明學生能整合不同領域解決共同問題。'}
};function apply(){const qs=window.MusicTeacherExam?.questions||window.LOCAL_QUESTIONS||[];qs.forEach(q=>{if(bank[q.id])q.option_explanations={...(q.option_explanations||{}),...bank[q.id]}})}apply();window.addEventListener('musicExamLatestModulesReady',apply);})();