(()=>{
 if(window.__OPTION_EXPLANATION_UI_V3__)return;window.__OPTION_EXPLANATION_UI_V3__=true;
 const NOTE_KEY='musicTeacherExamOptionNotesV1',QNOTE_KEY='musicTeacherExamQuestionNotesV1';
 function esc(s){return String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
 const clean=s=>String(s??'').replace(/\s+/g,' ').trim();
 const allQuestions=()=>window.MusicTeacherExam?.questions||window.LOCAL_QUESTIONS||[];
 function visibleOptions(){return [...document.querySelectorAll('#options .option-btn')].map(b=>({key:b.dataset.choice,text:clean(b.textContent.replace(/^\s*[A-D][.．]\s*/,''))}))}
 function currentQuestion(){const id=document.querySelector('#sourceBox')?.textContent?.match(/題號：([^\s]+)/)?.[1];if(id){const hit=allQuestions().find(q=>String(q.id)===String(id));if(hit)return hit}const stem=clean(document.getElementById('questionText')?.textContent||''),opts=visibleOptions(),candidates=allQuestions().filter(q=>clean(q.question)===stem);if(candidates.length===1)return candidates[0];if(opts.length){const exact=(candidates.length?candidates:allQuestions()).find(q=>clean(q.question)===stem&&opts.every(x=>clean(q[`option_${x.key.toLowerCase()}`])===x.text));if(exact)return exact}return candidates[0]||null}
 const loadKey=k=>{try{return JSON.parse(localStorage.getItem(k))||{}}catch{return{}}};
 const saveKey=(k,x)=>localStorage.setItem(k,JSON.stringify(x));
 const getOptionNote=(qid,key)=>loadKey(NOTE_KEY)?.[qid]?.[key]||'';
 function setOptionNote(qid,key,value){const n=loadKey(NOTE_KEY);n[qid]=n[qid]||{};if(clean(value))n[qid][key]=value.trim();else delete n[qid][key];if(!Object.keys(n[qid]).length)delete n[qid];saveKey(NOTE_KEY,n)}
 const getQuestionNote=qid=>loadKey(QNOTE_KEY)?.[qid]||'';
 function setQuestionNote(qid,value){const n=loadKey(QNOTE_KEY);if(clean(value))n[qid]=value.trim();else delete n[qid];saveKey(QNOTE_KEY,n)}
 function noteCount(){const a=Object.values(loadKey(NOTE_KEY)).reduce((n,x)=>n+Object.values(x||{}).filter(v=>clean(v)).length,0),b=Object.values(loadKey(QNOTE_KEY)).filter(v=>clean(v)).length;return a+b}
 function exportNotes(){const options=loadKey(NOTE_KEY),questions=loadKey(QNOTE_KEY),ids=new Set([...Object.keys(options),...Object.keys(questions)]),payload={version:2,exported_at:new Date().toISOString(),note_count:noteCount(),notes:[...ids].map(question_id=>{const q=allQuestions().find(x=>String(x.id)===String(question_id));return{question_id,subject:q?.subject||'',topic:q?.topic||'',question:q?.question||'',answer:q?.answer||'',source:q?.source_title||q?.exam||'',question_note:questions[question_id]||'',options:Object.fromEntries(Object.entries(options[question_id]||{}).filter(([,v])=>clean(v)))}}).filter(x=>clean(x.question_note)||Object.keys(x.options).length)};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`music-teacher-study-notes-${new Date().toISOString().slice(0,10)}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),500)}
 function render(){const feedback=document.getElementById('feedback'),exp=document.getElementById('explanation');if(!feedback||!exp||feedback.classList.contains('hidden'))return;const q=currentQuestion();if(!q)return;let box=document.getElementById('optionExplanationBox');if(!box){box=document.createElement('div');box.id='optionExplanationBox';exp.insertAdjacentElement('afterend',box)}const rows=window.getMusicOptionExplanations?window.getMusicOptionExplanations(q):[];box.dataset.questionId=q.id;box.innerHTML=`<div class="feedback-title" style="margin-top:16px">🔎 四個選項逐項複習</div><div class="source-box" style="margin:7px 0 9px"><b>目前核對題號：</b>${esc(q.id)}${q.source_title||q.exam?`｜${esc(q.source_title||q.exam)}`:''}</div><div style="display:grid;gap:9px">${rows.map(x=>`<div class="option-review-row" data-key="${x.key}" style="padding:11px 12px;border:1px solid var(--line);border-radius:12px;line-height:1.6"><b>${x.correct?'✅':'▫️'} ${x.key}. ${esc(x.text)}</b><div style="margin-top:4px">${esc(x.explanation)}</div><details style="margin-top:8px"><summary style="cursor:pointer;font-weight:800">📝 這個選項的補充${getOptionNote(q.id,x.key)?' ✓':''}</summary><textarea class="option-note-input" data-key="${x.key}" rows="3" placeholder="例如：這個選項在考什麼？為什麼錯？和哪個名詞容易混淆？" style="width:100%;margin-top:8px;padding:9px 10px;border:1px solid var(--line);border-radius:10px;background:var(--card);color:var(--text);resize:vertical">${esc(getOptionNote(q.id,x.key))}</textarea><div style="display:flex;gap:7px;justify-content:flex-end;margin-top:6px"><button class="ghost small option-note-clear" data-key="${x.key}" type="button">清除</button><button class="primary small option-note-save" data-key="${x.key}" type="button">💾 儲存</button></div></details></div>`).join('')}</div>${q.review_focus?`<div class="source-box" style="margin-top:10px"><b>🧠 本題複習核心：</b>${esc(q.review_focus)}</div>`:''}<details class="question-note-panel" style="margin-top:12px;padding:11px 12px;border:1px solid var(--line);border-radius:12px"><summary style="cursor:pointer;font-weight:900">📒 本題總筆記${getQuestionNote(q.id)?' ✓':''}</summary><p class="muted" style="margin:6px 0">可以寫口訣、延伸概念、查證提醒，或把四個選項整理成自己的比較表。</p><textarea id="questionNoteInput" rows="5" placeholder="我的本題筆記……" style="width:100%;padding:10px;border:1px solid var(--line);border-radius:10px;background:var(--card);color:var(--text);resize:vertical">${esc(getQuestionNote(q.id))}</textarea><div style="display:flex;gap:7px;justify-content:flex-end;margin-top:7px"><button id="clearQuestionNote" class="ghost small" type="button">清除</button><button id="saveQuestionNote" class="primary small" type="button">💾 儲存本題筆記</button></div></details><div style="display:flex;justify-content:space-between;gap:8px;align-items:center;margin-top:12px;flex-wrap:wrap"><small class="muted">個人筆記存在此瀏覽器；匯出後可交給我整理、核對並併入正式題庫。</small><button id="exportOptionNotesBtn" class="ghost small" type="button">📦 匯出學習筆記（${noteCount()}則）</button></div>`;
 box.querySelectorAll('.option-note-save').forEach(btn=>btn.onclick=()=>{const input=box.querySelector(`.option-note-input[data-key="${btn.dataset.key}"]`);setOptionNote(q.id,btn.dataset.key,input?.value||'');btn.textContent='✅ 已儲存';setTimeout(render,450)});box.querySelectorAll('.option-note-clear').forEach(btn=>btn.onclick=()=>{setOptionNote(q.id,btn.dataset.key,'');render()});box.querySelector('#saveQuestionNote')?.addEventListener('click',()=>{setQuestionNote(q.id,box.querySelector('#questionNoteInput')?.value||'');render()});box.querySelector('#clearQuestionNote')?.addEventListener('click',()=>{setQuestionNote(q.id,'');render()});box.querySelector('#exportOptionNotesBtn')?.addEventListener('click',exportNotes)}
 const obs=new MutationObserver(()=>setTimeout(render,0));function mount(){const f=document.getElementById('feedback');if(f&&!f.dataset.optionExplanationObserved){f.dataset.optionExplanationObserved='1';obs.observe(f,{attributes:true,childList:true,subtree:true})}document.addEventListener('click',e=>{if(e.target.closest('.option-btn,.unknown-btn'))setTimeout(render,20)})}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();window.MusicTeacherOptionNotes={load:()=>({options:loadKey(NOTE_KEY),questions:loadKey(QNOTE_KEY)}),saveOption:setOptionNote,saveQuestion:setQuestionNote,export:exportNotes,count:noteCount};
})();