(()=>{
 const STATS_KEY='musicTeacherExamStatsV1';
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
 const norm=s=>String(s??'').toLowerCase().replace(/[\s\-_/／()（）・,.，。:：;；'"《》〈〉]/g,'');
 const loadStats=()=>{try{const s=JSON.parse(localStorage.getItem(STATS_KEY))||{};return{attempts:s.attempts||{},wrong:Array.isArray(s.wrong)?s.wrong:[],unknown:Array.isArray(s.unknown)?s.unknown:[],daily:s.daily||{},topics:s.topics||{}}}catch{return{attempts:{},wrong:[],unknown:[],daily:{},topics:{}}}};
 const qs=()=>window.MusicTeacherExam?.questions||[];
 function termRows(level=''){if(!window.PreciseTermRadar?.build)return[];const high=window.PreciseTermRadar.build(level,'high'),rising=window.PreciseTermRadar.build(level,'rising'),rare=window.PreciseTermRadar.build(level,'rare'),riseMap=new Map(rising.map(x=>[norm(x.term),x])),rareMap=new Map(rare.map(x=>[norm(x.term),x])),stats=loadStats(),wrong=new Set(stats.wrong||[]),unknown=new Set(stats.unknown||[]),attempts=stats.attempts||{};return high.map(x=>{const tokens=[x.term,...(x.variants||[])].map(norm).filter(Boolean),related=qs().filter(q=>{if(level&&q.subject!==level)return false;const text=norm(`${q.topic||''} ${q.tags||''} ${q.question||''} ${q.explanation||''}`);return tokens.some(t=>t.length>=2&&text.includes(t))});let wrongN=0,unknownN=0,attemptN=0,correctN=0,unknownAttempts=0,masteredQ=0,bestStreak=0;related.forEach(q=>{const a=attempts[q.id];if(a){attemptN+=a.total||0;correctN+=a.correct||0;unknownAttempts+=a.unknown||0;bestStreak=Math.max(bestStreak,a.streak||0);const acc=(a.total||0)?(a.correct||0)/(a.total||1):0;if((a.streak||0)>=3&&a.total>=3&&acc>=.8&&!wrong.has(q.id)&&!unknown.has(q.id))masteredQ++}if(wrong.has(q.id))wrongN++;if(unknown.has(q.id))unknownN++});const acc=attemptN?Math.round(correctN/attemptN*100):null,topicWeak=related.reduce((n,q)=>{const t=stats.topics?.[q.topic];return n+(t&&t.total>=2&&t.correct/t.total<.7?1:0)},0),risingHit=riseMap.get(norm(x.term)),rareHit=rareMap.get(norm(x.term)),personal=unknownN*32+unknownAttempts*7+wrongN*18+(acc!==null?Math.max(0,75-acc):4)+topicWeak*5,masteryPenalty=unknownN||wrongN?0:Math.min(36,masteredQ*9+(bestStreak>=5?10:bestStreak>=3?5:0)+(acc!==null&&attemptN>=5&&acc>=85?8:0)),priority=x.score+personal+(risingHit?Math.min(20,risingHit.score/3):0)+(rareHit?6:0)-masteryPenalty;return{...x,related,wrongN,unknownN,unknownAttempts,attemptN,acc,masteredQ,bestStreak,masteryPenalty,personal,priority,rising:!!risingHit,rare:!!rareHit}}).sort((a,b)=>b.priority-a.priority||b.unknownN-a.unknownN||b.wrongN-a.wrongN||a.masteryPenalty-b.masteryPenalty||b.score-a.score)}
 function label(x){const a=[];if(x.unknownN)a.push(`❓ ${x.unknownN} 題目前不知道`);if(x.wrongN)a.push(`❌ ${x.wrongN} 題仍在錯題本`);if(x.acc!==null&&x.acc<70)a.push(`📉 相關題正確率 ${x.acc}%`);if(x.masteryPenalty>=10&&!x.unknownN&&!x.wrongN)a.push(`✅ 已熟練，降權 ${x.masteryPenalty}`);if(x.yearN>=3)a.push('🔥 十年高頻');if(x.rising)a.push('🚀 近年升溫');if(x.rare)a.push('🧊 高鑑別');if(!x.attemptN)a.push('🆕 尚未建立熟練度');return a.slice(0,5).join('　')}
 function render(level=''){const box=document.getElementById('personalPriorityList'),meta=document.getElementById('personalPriorityMeta');if(!box)return;const data=termRows(level).slice(0,15),s=loadStats(),attemptTotal=Object.values(s.attempts||{}).reduce((n,a)=>n+(a.total||0),0),unknownTotal=(s.unknown||[]).length,wrongTotal=(s.wrong||[]).length;if(meta)meta.textContent=attemptTotal?`已依 ${attemptTotal} 題次作答紀錄重新排序：❓不知道 ${unknownTotal} 題 > ❌錯題 ${wrongTotal} 題；連續答對且正確率穩定的考點會自動降權，不再一直佔據主要複習。`:'目前還沒有足夠個人作答紀錄，先依考古題重要度排序；開始刷題後會逐漸變成你的個人榜。';box.innerHTML=data.map((x,i)=>`<div style="border:1px solid var(--line);border-radius:13px;padding:12px 13px;margin:8px 0"><div style="display:flex;justify-content:space-between;gap:10px"><b>${i+1}. ${esc(x.term)}</b><small style="color:var(--muted);white-space:nowrap">${x.yearN}年 · ${x.examN}卷</small></div><div style="font-size:12px;line-height:1.7;margin-top:5px">${label(x)}</div>${x.related.length?`<button class="ghost small pp-practice" data-term="${esc(x.term)}" style="margin-top:7px">🎯 練這個考點</button>`:''}</div>`).join('')||'<p class="muted">目前資料不足。</p>';box.querySelectorAll('.pp-practice').forEach(btn=>btn.onclick=()=>{const x=data.find(r=>r.term===btn.dataset.term);if(x?.related?.length)window.MusicTeacherExam?.startCustomQuiz(x.related,`優先複習｜${x.term}`,10)})}
 function mount(){const home=document.getElementById('homeView');if(!home||document.getElementById('personalPriorityRadar'))return;const radar=document.getElementById('preciseTermRadar'),s=document.createElement('section');s.id='personalPriorityRadar';s.className='card section-card';s.innerHTML=`<div class="section-title"><div><span class="eyebrow">考古題重要度 × 你的作答紀錄</span><h3>🎯 我的上岸優先讀書清單</h3></div></div><p id="personalPriorityMeta" class="muted"></p><div style="display:flex;gap:7px;flex-wrap:wrap;margin-bottom:10px"><button class="ghost small pp-level active" data-l="">全部</button><button class="ghost small pp-level" data-l="國中音樂">🎵 國中</button><button class="ghost small pp-level" data-l="高中音樂">🎓 高中</button><button class="ghost small pp-level" data-l="教育專業">📚 教育</button></div><div id="personalPriorityList"></div>`;(radar||home.lastElementChild)?.insertAdjacentElement(radar?'beforebegin':'afterend',s);let level='';s.querySelectorAll('.pp-level').forEach(b=>b.onclick=()=>{level=b.dataset.l;s.dataset.level=level;s.querySelectorAll('.pp-level').forEach(x=>x.classList.toggle('active',x===b));render(level)});s.dataset.level='';render(level)}
 function refreshAfterAnswer(){const fb=document.getElementById('feedback');if(!fb)return;new MutationObserver(()=>{if(!fb.classList.contains('hidden'))setTimeout(()=>{const s=document.getElementById('personalPriorityRadar');if(s)render(s.dataset.level||'')},80)}).observe(fb,{attributes:true,attributeFilter:['class']})}
 document.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{mount();refreshAfterAnswer()},650));window.PersonalExamPriority={termRows,render};
})();

(()=>{
 const GROUPS={today:'🏠 今天',practice:'📝 練習',radar:'📡 考點',learning:'📊 我的學習',written:'✍️ 非選題'};let active='today',radarMode='must';
 function classify(el){const id=el.id||'',t=(el.textContent||'').replace(/\s+/g,' ');if(id==='dailyMission'||id==='mtSrs'||/每日任務|今日上岸|待學習題庫/.test(t))return'today';if(id==='preciseTermRadar'||id==='mtFrequency'||/高頻考點|精準考點|知識鏈/.test(t))return'radar';if(id==='personalPriorityRadar'||id==='mtWeakTraining'||/弱點分析|上岸優先讀書清單|記憶狀態/.test(t))return'learning';if(id==='mtTrial'||/名詞解釋|申論|試教挑戰|試教模擬/.test(t))return'written';if(id==='mtHighSchoolCenter'||/依目標練習|篩選練習|國中、高中分開準備|高中音樂專業特訓/.test(t))return'practice';return''}
 function radarApply(){const radar=document.getElementById('preciseTermRadar');if(!radar)return;const buttons=[...radar.querySelectorAll('button')];const want=radarMode==='must'?/高頻|必考|high/i:radarMode==='trend'?/升溫|趨勢|rising/i:radarMode==='rare'?/冷門|鑑別|rare/i:/知識鏈|chain/i;const hit=buttons.find(b=>want.test(b.textContent||''));if(hit&&!hit.classList.contains('active'))hit.click()}
 function apply(){const home=document.getElementById('homeView');if(!home)return;home.querySelectorAll(':scope > .section-card, :scope > .mt-advanced, :scope > .mt-srs').forEach(el=>{const g=classify(el);if(g){el.dataset.homeGroup=g;el.style.display=g===active?'':'none'}});const stats=home.querySelector(':scope > .stats-grid');if(stats)stats.style.display=active==='learning'?'grid':'none';const pc=document.getElementById('practiceSubNav');if(pc)pc.style.display=active==='practice'?'':'none';const rc=document.getElementById('radarSubNav');if(rc)rc.style.display=active==='radar'?'':'none';if(active==='radar')setTimeout(radarApply,50)}
 function buildPracticeNav(nav){if(document.getElementById('practiceSubNav'))return;const p=document.createElement('div');p.id='practiceSubNav';p.className='sub-nav-panel';p.innerHTML=`<div class="sub-head"><b>你今天想怎麼練？</b><small>先選目的，不用在一堆功能裡找按鈕。</small></div><div class="sub-grid"><button data-kind="quick"><b>⚡ 快速刷題</b><small>今日10題、錯題、❓不知道</small></button><button data-kind="level"><b>🎵 依學段</b><small>國中音樂／高中音樂／教育專業</small></button><button data-kind="filter"><b>🗂️ 依年度・主題</b><small>指定年度、學段、考點篩選</small></button><button data-kind="special"><b>🎯 專項特訓</b><small>高中和聲、曲式、音樂史等</small></button></div>`;nav.insertAdjacentElement('afterend',p);p.querySelectorAll('button').forEach(b=>b.onclick=()=>{const kind=b.dataset.kind;if(kind==='quick')return window.MusicTeacherExam?.startQuiz('random10');if(kind==='level')return document.querySelector('[data-mode="junior"]')?.scrollIntoView({behavior:'smooth',block:'center'});if(kind==='filter')return document.getElementById('yearFilter')?.scrollIntoView({behavior:'smooth',block:'center'});document.getElementById('mtHighSchoolCenter')?.scrollIntoView({behavior:'smooth',block:'start'})})}
 function buildRadarNav(nav){if(document.getElementById('radarSubNav'))return;const r=document.createElement('div');r.id='radarSubNav';r.className='sub-nav-panel';r.innerHTML=`<div class="sub-head"><b>考點雷達</b><small>一次只看一種訊號，避免所有分析同時塞在畫面上。</small></div><div class="sub-grid radar-grid"><button data-r="must" class="active"><b>🔥 必讀</b><small>十年反覆出現，先建立基本盤</small></button><button data-r="trend"><b>🚀 趨勢</b><small>近年升溫，注意新命題方向</small></button><button data-r="rare"><b>🧊 冷門</b><small>低頻但高鑑別，防教甄突襲</small></button><button data-r="chain"><b>🧠 知識鏈</b><small>把相近概念串起來理解</small></button></div>`;const anchor=document.getElementById('practiceSubNav')||nav;r.style.display='none';anchor.insertAdjacentElement('afterend',r);r.querySelectorAll('button').forEach(b=>b.onclick=()=>{radarMode=b.dataset.r;r.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));radarApply();document.getElementById('preciseTermRadar')?.scrollIntoView({behavior:'smooth',block:'start'})})}
 function mount(){const home=document.getElementById('homeView'),hero=home?.querySelector('.hero');if(!home||!hero||document.getElementById('homeCategoryNav'))return;const st=document.createElement('style');st.textContent=`#homeCategoryNav{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin:12px 0 10px}#homeCategoryNav button,.sub-nav-panel button{border:1px solid var(--line);background:var(--panel);color:inherit;border-radius:12px;padding:10px 6px;font-weight:800;cursor:pointer}#homeCategoryNav button.active,.sub-nav-panel button.active{background:var(--brand);color:#fff;border-color:var(--brand)}.sub-nav-panel{display:none;margin:0 0 18px;padding:14px;border:1px solid var(--line);border-radius:16px;background:var(--panel)}.sub-head{display:flex;justify-content:space-between;gap:12px;align-items:end;margin-bottom:10px}.sub-head small,.sub-grid small{display:block;color:var(--muted);font-weight:500;margin-top:4px}.sub-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.sub-grid button{text-align:left;padding:12px}.sub-grid button:hover{border-color:var(--brand)}.sub-grid button.active small{color:inherit;opacity:.85}@media(max-width:720px){#homeCategoryNav{grid-template-columns:repeat(3,1fr)}.sub-grid{grid-template-columns:1fr 1fr}.sub-head{display:block}.sub-head small{margin-top:4px}}`;document.head.appendChild(st);const nav=document.createElement('nav');nav.id='homeCategoryNav';nav.innerHTML=Object.entries(GROUPS).map(([k,v])=>`<button data-g="${k}" class="${k===active?'active':''}">${v}</button>`).join('');hero.insertAdjacentElement('afterend',nav);buildPracticeNav(nav);buildRadarNav(nav);nav.querySelectorAll('button').forEach(b=>b.onclick=()=>{active=b.dataset.g;nav.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));apply();window.scrollTo({top:0,behavior:'smooth'})});apply();new MutationObserver(()=>apply()).observe(home,{childList:true,subtree:false})}
 document.addEventListener('DOMContentLoaded',()=>setTimeout(mount,1200));window.HomeCategoryOrganizer={apply,getActive:()=>active};
})();