(()=>{
 if(window.__PERSONAL_PRIORITY_V2__)return;window.__PERSONAL_PRIORITY_V2__=true;
 const STATS_KEY='musicTeacherExamStatsV1',LOG_KEY='musicTeacherExamAttemptLogV1';
 const ready=fn=>document.readyState==='loading'?document.addEventListener('DOMContentLoaded',fn,{once:true}):fn();
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
 const norm=s=>String(s??'').toLowerCase().replace(/[\s\-_/／()（）・,.，。:：;；'"《》〈〉]/g,'');
 const load=k=>{try{return JSON.parse(localStorage.getItem(k))||{}}catch{return{}}};
 const loadStats=()=>{const s=load(STATS_KEY);return{attempts:s.attempts||{},wrong:Array.isArray(s.wrong)?s.wrong:[],unknown:Array.isArray(s.unknown)?s.unknown:[],daily:s.daily||{},topics:s.topics||{}}};
 const qs=()=>window.MusicTeacherExam?.questions||[];
 function recentTopicMap(){const api=window.WeaknessTrend;if(api?.metrics)return new Map(api.metrics().map(x=>[x.topic,x]));const log=(()=>{try{return JSON.parse(localStorage.getItem(LOG_KEY))||[]}catch{return[]}})(),cut=Date.now()-14*86400000,m=new Map();log.filter(x=>x.at>=cut).forEach(x=>{const k=x.topic||'綜合',v=m.get(k)||{topic:k,recentTotal:0,recentCorrect:0};v.recentTotal++;if(x.correct)v.recentCorrect++;m.set(k,v)});for(const v of m.values())v.recentAcc=v.recentTotal?Math.round(v.recentCorrect/v.recentTotal*100):null;return m}
 function trendWeight(t){if(!t)return 0;const n=t.recentTotal||0;if(n<3)return 0;if(t.state==='declining')return 24;if(t.state==='weak')return 18;if(t.state==='improving')return-16;const a=t.recentAcc;return a!=null&&a<70?14:a!=null&&a>=85?-8:0}
 function termRows(level=''){if(!window.PreciseTermRadar?.build)return[];const high=window.PreciseTermRadar.build(level,'high'),rising=window.PreciseTermRadar.build(level,'rising'),rare=window.PreciseTermRadar.build(level,'rare'),riseMap=new Map(rising.map(x=>[norm(x.term),x])),rareMap=new Map(rare.map(x=>[norm(x.term),x])),stats=loadStats(),wrong=new Set((stats.wrong||[]).map(String)),unknown=new Set((stats.unknown||[]).map(String)),attempts=stats.attempts||{},recent=recentTopicMap();return high.map(x=>{const tokens=[x.term,...(x.variants||[])].map(norm).filter(Boolean),related=qs().filter(q=>{if(level&&q.subject!==level)return false;const text=norm(`${q.topic||''} ${q.tags||''} ${q.question||''} ${q.explanation||''}`);return tokens.some(t=>t.length>=2&&text.includes(t))});let wrongN=0,unknownN=0,attemptN=0,correctN=0,unknownAttempts=0,masteredQ=0,bestStreak=0,trendScore=0,trendTopic=null;related.forEach(q=>{const a=attempts[q.id],id=String(q.id);if(a){attemptN+=a.total||0;correctN+=a.correct||0;unknownAttempts+=a.unknown||0;bestStreak=Math.max(bestStreak,a.streak||0);const acc=(a.total||0)?(a.correct||0)/(a.total||1):0;if((a.streak||0)>=3&&a.total>=3&&acc>=.8&&!wrong.has(id)&&!unknown.has(id))masteredQ++}if(wrong.has(id))wrongN++;if(unknown.has(id))unknownN++;const t=recent.get(q.topic||q.subject||'綜合'),w=trendWeight(t);if(Math.abs(w)>Math.abs(trendScore)){trendScore=w;trendTopic=t}});const acc=attemptN?Math.round(correctN/attemptN*100):null,topicWeak=related.reduce((n,q)=>{const t=stats.topics?.[q.topic];return n+(t&&t.total>=2&&t.correct/t.total<.7?1:0)},0),risingHit=riseMap.get(norm(x.term)),rareHit=rareMap.get(norm(x.term)),personal=unknownN*32+unknownAttempts*7+wrongN*18+(acc!==null?Math.max(0,75-acc):4)+topicWeak*5,masteryPenalty=unknownN||wrongN?0:Math.min(36,masteredQ*9+(bestStreak>=5?10:bestStreak>=3?5:0)+(acc!==null&&attemptN>=5&&acc>=85?8:0)),priority=x.score+personal+trendScore+(risingHit?Math.min(20,risingHit.score/3):0)+(rareHit?6:0)-masteryPenalty;return{...x,related,wrongN,unknownN,unknownAttempts,attemptN,acc,masteredQ,bestStreak,masteryPenalty,personal,priority,rising:!!risingHit,rare:!!rareHit,trendScore,trendTopic}}).sort((a,b)=>b.priority-a.priority||b.trendScore-a.trendScore||b.unknownN-a.unknownN||b.wrongN-a.wrongN||a.masteryPenalty-b.masteryPenalty||b.score-a.score)}
 function label(x){const a=[];if(x.unknownN)a.push(`❓ ${x.unknownN} 題目前不知道`);if(x.wrongN)a.push(`❌ ${x.wrongN} 題目前不穩`);if(x.trendTopic?.recentTotal>=3){if(x.trendScore>=18)a.push(`↘ ${x.trendTopic.topic} 近14天需優先`);else if(x.trendScore<0)a.push(`↗ ${x.trendTopic.topic} 正在進步，已降權`)}if(x.acc!==null&&x.acc<70)a.push(`📉 相關題整體 ${x.acc}%`);if(x.masteryPenalty>=10&&!x.unknownN&&!x.wrongN)a.push(`✅ 已熟練，降權 ${x.masteryPenalty}`);if(x.yearN>=3)a.push('🔥 十年高頻');if(x.rising)a.push('🚀 近年升溫');if(x.rare)a.push('🧊 高鑑別');if(!x.attemptN)a.push('🆕 尚未建立熟練度');return a.slice(0,5).join('　')}
 function render(level=''){const box=document.getElementById('personalPriorityList'),meta=document.getElementById('personalPriorityMeta');if(!box)return;const data=termRows(level).slice(0,15),s=loadStats(),attemptTotal=Object.values(s.attempts||{}).reduce((n,a)=>n+(a.total||0),0);if(meta)meta.textContent=attemptTotal?'排序已同時考慮：目前不知道／答錯、近14天弱點趨勢、歷屆重要度與熟練降權。近期正在進步的主題會適度讓位；最近下滑或持續低分的主題會提前。':'目前還沒有足夠個人作答紀錄，先依考古題重要度排序；開始刷題後會逐漸變成你的個人榜。';box.innerHTML=data.map((x,i)=>`<div style="border:1px solid var(--line);border-radius:13px;padding:12px 13px;margin:8px 0"><div style="display:flex;justify-content:space-between;gap:10px"><b>${i+1}. ${esc(x.term)}</b><small style="color:var(--muted);white-space:nowrap">${x.yearN}年 · ${x.examN}卷</small></div><div style="font-size:12px;line-height:1.7;margin-top:5px">${label(x)}</div>${x.related.length?`<button class="ghost small pp-practice" data-term="${esc(x.term)}" style="margin-top:7px">🎯 練這個考點</button>`:''}</div>`).join('')||'<p class="muted">目前資料不足。</p>';box.querySelectorAll('.pp-practice').forEach(btn=>btn.onclick=()=>{const x=data.find(r=>r.term===btn.dataset.term);if(x?.related?.length)window.MusicTeacherExam?.startCustomQuiz(x.related,`優先複習｜${x.term}`,10)})}
 function mount(){const home=document.getElementById('homeView');if(!home||document.getElementById('personalPriorityRadar'))return;const radar=document.getElementById('preciseTermRadar'),s=document.createElement('section');s.id='personalPriorityRadar';s.className='card section-card';s.innerHTML=`<div class="section-title"><div><span class="eyebrow">考古題重要度 × 目前弱點 × 近14天趨勢</span><h3>🎯 我的上岸優先讀書清單</h3></div></div><p id="personalPriorityMeta" class="muted"></p><div style="display:flex;gap:7px;flex-wrap:wrap;margin-bottom:10px"><button class="ghost small pp-level active" data-l="">全部</button><button class="ghost small pp-level" data-l="國中音樂">🎵 國中</button><button class="ghost small pp-level" data-l="高中音樂">🎓 高中</button><button class="ghost small pp-level" data-l="教育專業">📚 教育</button></div><div id="personalPriorityList"></div>`;(radar||home.lastElementChild)?.insertAdjacentElement(radar?'beforebegin':'afterend',s);let level='';s.querySelectorAll('.pp-level').forEach(b=>b.onclick=()=>{level=b.dataset.l;s.dataset.level=level;s.querySelectorAll('.pp-level').forEach(x=>x.classList.toggle('active',x===b));render(level)});s.dataset.level='';render(level);window.HomeCategoryOrganizer?.apply?.()}
 function refresh(){const s=document.getElementById('personalPriorityRadar');if(s)render(s.dataset.level||'')}
 function bind(){const fb=document.getElementById('feedback');if(fb&&!fb.dataset.personalPriorityObserved){fb.dataset.personalPriorityObserved='1';new MutationObserver(()=>{if(!fb.classList.contains('hidden'))setTimeout(refresh,100)}).observe(fb,{attributes:true,attributeFilter:['class']})}window.addEventListener('musicExamLearningSynced',refresh);window.addEventListener('storage',e=>{if([STATS_KEY,LOG_KEY].includes(e.key))refresh()})}
 ready(()=>setTimeout(()=>{mount();bind()},80));window.PersonalExamPriority={termRows,render,recentTopicMap};
})();