(()=>{
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const YEAR_MAX=115;
 const norm=s=>String(s??'').toLowerCase().replace(/[\s\-_/／()（）・,.，。:：;；'"《》〈〉]/g,'');
 const CHAINS=[
  {name:'Vygotsky 社會文化學習鏈',keys:['vygotsky','zpd','近側發展區','最近發展區','鷹架','scaffolding','動態評量']},
  {name:'Bandura 社會學習與自我效能鏈',keys:['bandura','班杜拉','觀察學習','社會學習','自我效能','selfefficacy']},
  {name:'評量與測驗核心鏈',keys:['形成性評量','總結性評量','安置性評量','診斷性評量','效標參照','信度','效度','irt','試題反應']},
  {name:'課程理論與素養導向鏈',keys:['潛在課程','goodlad','統整課程','素養導向','核心素養','差異化教學','ubd','逆向設計']},
  {name:'教育哲學核心人物鏈',keys:['dewey','杜威','實用主義','重建主義','存在主義','foucault','傅柯','工具理性']},
  {name:'學生輔導與管教法規鏈',keys:['學生輔導法','輔導管教','正向管教','比例原則','三級預防','介入性輔導','教師法','國民教育法']},
  {name:'音樂教育法鏈',keys:['dalcroze','達克羅士','eurhythmics','solfège','solfege','orff','奧福','kodály','kodaly','柯大宜','suzuki','鈴木']},
  {name:'臺灣傳統與本土音樂鏈',keys:['南管','北管','歌仔','客家','原住民','鄧雨賢','呂泉生','陳達','月琴','工尺譜']},
  {name:'西洋和聲高鑑別鏈',keys:['neapolitan','拿坡里','augmentedsixth','增六','終止','cadence','掛留音','經過音','先現音','半減七']},
  {name:'音樂科技與 AI 新興鏈',keys:['ai','人工智慧','spectrogram','頻譜','數位音樂','creativecommons','podcast','採樣率','音樂科技']}
 ];
 function rawRows(){const a=(window.PRECISE_EXAM_TERMS||[]).map(x=>({...x,exam:x.exam||x.school||'未標示考卷',aliases:x.aliases||[]}));const b=(window.PRECISE_TERM_OCCURRENCES||[]).map(x=>({...x,exam:x.exam||x.school||'未標示考卷',aliases:x.aliases||[]}));return [...a,...b].filter(x=>x.term&&Number(x.year)>=106&&Number(x.year)<=115)}
 function canonicalize(rows){const parent=rows.map((_,i)=>i),find=i=>parent[i]===i?i:(parent[i]=find(parent[i])),union=(a,b)=>{a=find(a);b=find(b);if(a!==b)parent[b]=a},owner=new Map();rows.forEach((r,i)=>[r.term,...(r.aliases||[])].forEach(v=>{const k=norm(v);if(!k)return;if(owner.has(k))union(i,owner.get(k));else owner.set(k,i)}));const groups=new Map();rows.forEach((r,i)=>{const root=find(i);if(!groups.has(root))groups.set(root,[]);groups.get(root).push(r)});return [...groups.values()].map(g=>{const counts=new Map();g.forEach(r=>counts.set(r.term,(counts.get(r.term)||0)+1));const term=[...counts.entries()].sort((a,b)=>b[1]-a[1]||a[0].length-b[0].length)[0][0];return{term,variants:[...new Set(g.flatMap(r=>[r.term,...(r.aliases||[])]))].filter(v=>v!==term),rows:g}})}
 function build(level='',mode='high'){let rows=rawRows().filter(x=>!level||x.level===level);return canonicalize(rows).map(g=>{const years=new Set(),recentYears=new Set(),exams=new Map(),recentExams=new Map(),levels=new Set();let latest=0,count=0;g.rows.forEach(x=>{count++;const y=Number(x.year);years.add(y);if(y>=113)recentYears.add(y);levels.add(x.level);latest=Math.max(latest,y||0);const key=y+'|'+x.exam;exams.set(key,x);if(y>=113)recentExams.set(key,x)});const yearN=years.size,examN=exams.size,recentYearN=recentYears.size,recentExamN=recentExams.size,recency=Math.max(0,6-(YEAR_MAX-latest)),crossLevel=levels.size>1?4:0,highScore=yearN*8+examN*4+recency+crossLevel,risingScore=recentYearN*12+recentExamN*7+recency*2+(latest===115?8:0)+crossLevel-Math.max(0,yearN-recentYearN)*2,rareScore=(yearN===1?14:0)+(examN<=2?8:0)+(latest>=113?8:0)+(g.variants.length?2:0)+(crossLevel?3:0);return{...g,count,years,recentYears,exams,recentExams,levels,latest,yearN,examN,recentYearN,recentExamN,recency,crossLevel,score:mode==='rising'?risingScore:mode==='rare'?rareScore:highScore}}).filter(x=>mode!=='rare'||(x.yearN<=2&&x.examN<=3)).sort((a,b)=>b.score-a.score||b.latest-a.latest||a.term.localeCompare(b.term,'zh-Hant'))}
 function buildChains(level=''){const rows=rawRows().filter(x=>!level||x.level===level);return CHAINS.map(c=>{const hits=rows.filter(r=>{const text=norm([r.term,...(r.aliases||[]),r.group||'',r.domain||''].join(' '));return c.keys.some(k=>text.includes(norm(k)))}),years=new Set(hits.map(x=>Number(x.year))),exams=new Set(hits.map(x=>x.year+'|'+x.exam)),terms=[...new Set(hits.map(x=>x.term))],latest=hits.reduce((m,x)=>Math.max(m,Number(x.year)||0),0);return{...c,hits,years,exams,terms,latest,score:years.size*10+exams.size*4+(latest>=113?5:0)+(latest===115?5:0)}}).filter(x=>x.hits.length).sort((a,b)=>b.score-a.score)}
 function badge(x,mode){const b=[];if(mode==='rising'){if(x.recentYearN>=2)b.push('🚀近三年升溫');if(x.latest===115)b.push('⚡115仍在考')}else if(mode==='rare'){b.push('🧊冷門高鑑別');if(x.latest>=113)b.push('🆕近年出現')}else{if(x.yearN>=3)b.push('🔥跨年高頻');else if(x.yearN>=2)b.push('⭐跨年')}if(x.levels.size>1)b.push('🎯跨學段');return b.join('　')}
 function render(level='',mode='high'){const box=document.getElementById('preciseTermList'),meta=document.getElementById('preciseTermMeta');if(!box)return;const data=build(level,mode);if(meta)meta.textContent=mode==='rising'?'🚀 近三年快速升溫：優先看 113～115 年重複出現、115 仍在考的精準名詞。':mode==='rare'?'🧊 冷門高鑑別：只出現少數年份／考卷，但題目細、容易拉開差距；近年新出的冷門概念會提高順位。':'🔥 十年高頻必讀：106～115 跨年度、不同考卷與近年再考優先；教育專業與音樂資料已統一合併，同義詞不再拆開灌次數。';box.innerHTML=data.slice(0,30).map((x,i)=>`<details style="border:1px solid var(--line);border-radius:12px;padding:10px 12px;margin:7px 0"><summary style="cursor:pointer;font-weight:850">${i+1}. ${esc(x.term)} <small style="color:var(--muted)">${mode==='rising'?`｜近3年 ${x.recentYearN} 年｜${x.recentExamN} 卷`:`｜${x.yearN} 年｜${x.examN} 卷`}｜最近 ${x.latest} 年</small></summary><div style="padding-top:8px;font-size:13px;line-height:1.7"><div style="font-weight:800;margin-bottom:5px">${badge(x,mode)||'持續蒐集'}</div>${x.variants.length?`<div style="color:var(--muted);margin-bottom:5px">同義／相關寫法：${x.variants.slice(0,8).map(esc).join('、')}</div>`:''}${[...x.exams.values()].sort((a,b)=>Number(b.year)-Number(a.year)).map(e=>`<div><b>${esc(e.year)}｜${esc(e.level)}</b>｜${e.url?`<a href="${esc(e.url)}" target="_blank" rel="noopener">${esc(e.exam)}</a>`:esc(e.exam)}</div>`).join('')}</div></details>`).join('')||'<p class="muted">尚無資料。</p>'}
 function renderChains(level=''){const box=document.getElementById('knowledgeChainList');if(!box)return;const data=buildChains(level);box.innerHTML=data.slice(0,12).map((x,i)=>`<details style="border:1px solid var(--line);border-radius:12px;padding:10px 12px;margin:7px 0"><summary style="cursor:pointer;font-weight:850">${i+1}. ${esc(x.name)} <small style="color:var(--muted)">｜${x.years.size} 年｜${x.exams.size} 卷｜最近 ${x.latest}</small></summary><div style="padding-top:8px;font-size:13px;line-height:1.7"><b>🧠 換情境也要認得：</b>${x.terms.slice(0,16).map(esc).join('、')}</div></details>`).join('')||'<p class="muted">尚無足夠資料。</p>'}
 function mountUnknown(){const home=document.getElementById('homeView');if(!home||document.getElementById('unknownReviewCard'))return;const stats=window.MusicTeacherExam?.loadStats?.()||{},count=(stats.unknown||[]).length,s=document.createElement('section');s.id='unknownReviewCard';s.className='card section-card';s.innerHTML=`<div class="section-title"><div><span class="eyebrow">不要把「不知道」混成一般錯題</span><h3>❓ 待學習題庫</h3></div><div style="font-size:30px;font-weight:900">${count}</div></div><p class="muted">按過「❓ 我不知道」的題目會集中在這裡。重新答對後，系統會自動移出待學習清單。</p><button id="unknownReviewBtn" class="primary wide">❓ 重練我不知道的題目</button>`;const anchor=document.getElementById('mtWeakTraining')||document.getElementById('preciseTermRadar')||home.lastElementChild;anchor?.insertAdjacentElement('beforebegin',s);s.querySelector('#unknownReviewBtn')?.addEventListener('click',()=>window.MusicTeacherExam?.startQuiz?.('unknown'))}
 function mount(){const home=document.getElementById('homeView');if(!home||document.getElementById('preciseTermRadar'))return;const s=document.createElement('section');s.id='preciseTermRadar';s.className='card section-card';s.innerHTML=`<div class="section-title"><div><span class="eyebrow">106～115 阿摩考古題人工精標</span><h3>📡 教甄精準考點雷達</h3></div></div><div style="display:flex;gap:7px;flex-wrap:wrap;margin-bottom:8px"><button class="ghost small trend active" data-mode="high">🔥 十年高頻必讀</button><button class="ghost small trend" data-mode="rising">🚀 近三年快速升溫</button><button class="ghost small trend" data-mode="rare">🧊 冷門高鑑別</button></div><p id="preciseTermMeta" class="muted"></p><div style="display:flex;gap:7px;flex-wrap:wrap;margin-bottom:10px"><button class="ghost small ptr active" data-l="">上岸總榜</button><button class="ghost small ptr" data-l="國中音樂">🎵 國中音樂</button><button class="ghost small ptr" data-l="高中音樂">🎓 高中音樂</button><button class="ghost small ptr" data-l="教育專業">📚 教育專業</button></div><div id="preciseTermList"></div><hr style="border:0;border-top:1px solid var(--line);margin:18px 0"><div class="section-title"><div><span class="eyebrow">不是只背單字</span><h3>🧠 換情境重複考・知識鏈</h3></div></div><p class="muted">把不同名詞串成同一核心概念，辨識教甄「換一個情境、其實考同一件事」的命題方式。</p><div id="knowledgeChainList"></div>`;home.appendChild(s);let level='',mode='high';s.querySelectorAll('.ptr').forEach(b=>b.onclick=()=>{level=b.dataset.l;s.querySelectorAll('.ptr').forEach(x=>x.classList.toggle('active',x===b));render(level,mode);renderChains(level)});s.querySelectorAll('.trend').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;s.querySelectorAll('.trend').forEach(x=>x.classList.toggle('active',x===b));render(level,mode)});render(level,mode);renderChains(level)}
 function loadScript(src,next){const s=document.createElement('script');s.src=src;s.onload=()=>next&&next();document.body.appendChild(s)}
 function loadDetailedAnswers(){if(window.__DETAIL_ANSWERS_LOADING__)return;window.__DETAIL_ANSWERS_LOADING__=true;loadScript('detailed_answers.js?v=20260818d',()=>loadScript('detailed_answer_ui.js?v=20260818d'))}
 function loadLatestModules(){if(window.__LATEST_MODULES_LOADING__)return;window.__LATEST_MODULES_LOADING__=true;loadScript('latest_loader_bootstrap.js?v=20260818r')}
 function start(){setTimeout(mount,300);setTimeout(mountUnknown,520);setTimeout(loadLatestModules,560);setTimeout(loadDetailedAnswers,50)}
 if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',start);else start();window.PreciseTermRadar={build,buildChains,rawRows};
})();