(()=>{
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const YEAR_MAX=115;
 function build(level='',mode='high'){
  const rows=(window.PRECISE_EXAM_TERMS||[]).filter(x=>!level||x.level===level),m=new Map();
  rows.forEach(x=>{if(!m.has(x.term))m.set(x.term,{term:x.term,count:0,years:new Set(),recentYears:new Set(),exams:new Map(),recentExams:new Map(),levels:new Set(),latest:0});const a=m.get(x.term);a.count++;a.years.add(Number(x.year));if(Number(x.year)>=113)a.recentYears.add(Number(x.year));a.levels.add(x.level);a.latest=Math.max(a.latest,Number(x.year)||0);a.exams.set(x.year+'|'+x.exam,x);if(Number(x.year)>=113)a.recentExams.set(x.year+'|'+x.exam,x)});
  return [...m.values()].map(x=>{const yearN=x.years.size,examN=x.exams.size,recentYearN=x.recentYears.size,recentExamN=x.recentExams.size,recency=Math.max(0,6-(YEAR_MAX-x.latest)),crossLevel=x.levels.size>1?4:0;const highScore=yearN*8+examN*4+recency+crossLevel;const risingScore=recentYearN*12+recentExamN*7+recency*2+(x.latest===115?8:0)+crossLevel-Math.max(0,yearN-recentYearN)*2;return {...x,yearN,examN,recentYearN,recentExamN,recency,crossLevel,score:mode==='rising'?risingScore:highScore};}).sort((a,b)=>b.score-a.score||b.latest-a.latest||a.term.localeCompare(b.term,'zh-Hant'));
 }
 function badge(x,mode){const b=[];if(mode==='rising'){if(x.recentYearN>=2)b.push('🚀近三年升溫');if(x.latest===115)b.push('⚡115仍在考');}else{if(x.yearN>=3)b.push('🔥跨年高頻');else if(x.yearN>=2)b.push('⭐跨年');}if(x.levels.size>1)b.push('🎯跨學段');return b.join('　');}
 function render(level='',mode='high'){
  const box=document.getElementById('preciseTermList'),meta=document.getElementById('preciseTermMeta');if(!box)return;const data=build(level,mode);
  if(meta)meta.textContent=mode==='rising'?`🚀 近三年快速升溫：優先看 113～115 年重複出現、115 仍在考的精準名詞；避免新趨勢被十年總次數淹沒。`:`🔥 十年高頻必讀：排名優先看 106～115 跨年度、不同考卷與近年再考；同一考卷重複標記不重複計卷。`;
  box.innerHTML=data.slice(0,30).map((x,i)=>`<details style="border:1px solid var(--line);border-radius:12px;padding:10px 12px;margin:7px 0"><summary style="cursor:pointer;font-weight:850">${i+1}. ${esc(x.term)} <small style="color:var(--muted)">${mode==='rising'?`｜近3年 ${x.recentYearN} 年｜${x.recentExamN} 卷`:`｜${x.yearN} 年｜${x.examN} 卷`}｜最近 ${x.latest} 年</small></summary><div style="padding-top:8px;font-size:13px;line-height:1.7"><div style="font-weight:800;margin-bottom:5px">${badge(x,mode)||'持續蒐集'}</div>${[...x.exams.values()].sort((a,b)=>Number(b.year)-Number(a.year)).map(e=>`<div><b>${esc(e.year)}｜${esc(e.level)}</b>｜<a href="${esc(e.url)}" target="_blank" rel="noopener">${esc(e.exam)}</a></div>`).join('')}</div></details>`).join('')||'<p class="muted">尚無資料。</p>';
 }
 function mount(){const home=document.getElementById('homeView');if(!home||document.getElementById('preciseTermRadar'))return;const s=document.createElement('section');s.id='preciseTermRadar';s.className='card section-card';s.innerHTML=`<div class="section-title"><div><span class="eyebrow">106～115 阿摩考古題人工精標</span><h3>📡 教甄精準考點雷達</h3></div></div><div style="display:flex;gap:7px;flex-wrap:wrap;margin-bottom:8px"><button class="ghost small trend active" data-mode="high">🔥 十年高頻必讀</button><button class="ghost small trend" data-mode="rising">🚀 近三年快速升溫</button></div><p id="preciseTermMeta" class="muted"></p><div style="display:flex;gap:7px;flex-wrap:wrap;margin-bottom:10px"><button class="ghost small ptr active" data-l="">上岸總榜</button><button class="ghost small ptr" data-l="國中音樂">🎵 國中音樂</button><button class="ghost small ptr" data-l="高中音樂">🎓 高中音樂</button><button class="ghost small ptr" data-l="教育專業">📚 教育專業</button></div><div id="preciseTermList"></div>`;home.appendChild(s);let level='',mode='high';s.querySelectorAll('.ptr').forEach(b=>b.onclick=()=>{level=b.dataset.l;s.querySelectorAll('.ptr').forEach(x=>x.classList.toggle('active',x===b));render(level,mode)});s.querySelectorAll('.trend').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;s.querySelectorAll('.trend').forEach(x=>x.classList.toggle('active',x===b));render(level,mode)});render(level,mode)}
 function loadScript(src,next){const s=document.createElement('script');s.src=src;s.onload=()=>next&&next();document.body.appendChild(s)}
 function loadDetailedAnswers(){if(window.__DETAIL_ANSWERS_LOADING__)return;window.__DETAIL_ANSWERS_LOADING__=true;loadScript('detailed_answers.js?v=20260818d',()=>loadScript('detailed_answer_ui.js?v=20260818d'));}
 window.addEventListener('DOMContentLoaded',()=>{setTimeout(mount,300);setTimeout(loadDetailedAnswers,50)});window.PreciseTermRadar={build};
})();