window.QUESTIONS = window.QUESTIONS || [];
window.QUESTIONS.push(
{year:"114",level:"教育專業",exam:"新北市立國民中學教師聯合甄選",topic:"教育行政",difficulty:"中",question:"教育行政的混沌理論常以何種效應說明：系統中極小的初始變化，可能造成後續巨大而難以預測的差異？",options:["霍桑效應","蝴蝶效應","月暈效應","比馬龍效應"],answer:1,explanation:"混沌理論強調非線性與對初始條件的敏感性，典型比喻即蝴蝶效應。",source:"阿摩114新北教育專業第5題考點改寫"},
{year:"114",level:"教育專業",exam:"新北市立國民中學教師聯合甄選",topic:"衝突管理",difficulty:"中",question:"Thomas 的衝突處理模式，以哪兩個向度區分競爭、合作、逃避、遷就與妥協？",options:["果決程度與合作程度","權力距離與不確定性規避","任務導向與關係導向","內控與外控"],answer:0,explanation:"Thomas 模式以 assertiveness（果決）與 cooperativeness（合作）兩向度區分五種衝突處理方式。",source:"阿摩114新北教育專業第6題考點改寫"},
{year:"114",level:"教育專業",exam:"臺南市立國民中學正式教師聯合甄選",topic:"教育行政",difficulty:"中",question:"校長透過明確獎賞與後效酬賞，引導教師達成既定目標，最符合哪種領導理論？",options:["轉型領導","分布式領導","交易領導","服務領導"],answer:2,explanation:"交易領導強調交換關係、目標達成與獎酬連結。",source:"阿摩114臺南教育專業第2題考點改寫"},
{year:"114",level:"教育專業",exam:"臺南市立國民中學正式教師聯合甄選",topic:"組織行為",difficulty:"中",question:"霍桑效應對學校行政最直接的啟示是什麼？",options:["薪資是唯一動機來源","被關注本身可能提升工作表現","物理環境一定決定績效","嚴格監督必然提升效率"],answer:1,explanation:"霍桑效應指出，個體意識到自己正受到注意或研究時，行為表現可能因此改變。",source:"阿摩114臺南教育專業第3題考點改寫"},
{year:"114",level:"教育專業",exam:"臺南市立國民中學正式教師聯合甄選",topic:"特殊教育",difficulty:"中高",question:"一位聽覺障礙但具高創造力與抽象推理潛能的學生，最適合的支持策略組合為何？",options:["只強化口語演說","提供字幕與視覺化內容，並安排能展現優勢的創作活動","降低所有課程難度","取消小組合作以避免溝通負擔"],answer:1,explanation:"雙重特殊需求學生需同時補償障礙造成的學習限制，並發展其資優潛能。",source:"阿摩114臺南教育專業第89題考點改寫"},
{year:"114",level:"教育專業",exam:"臺南市立國民中學正式教師聯合甄選",topic:"學習障礙",difficulty:"中高",question:"數學學習障礙學生若同時有數學語詞理解與運算概念困難，下列哪種教學最符合多重表徵原則？",options:["反覆抄寫計算步驟","只進行心算競賽","結合圖像、實物操作與情境文本","完全取消文字題"],answer:2,explanation:"多重表徵透過圖像、操作與情境語意連結抽象數學概念，能同時支持語詞理解與運算概念。",source:"阿摩114臺南教育專業第90題考點改寫"},
{year:"114",level:"高中音樂",exam:"國立臺灣師大附中正式教師甄選",topic:"世界音樂",difficulty:"中",question:"下列哪一組『藝術形式／樂器－主要文化地區』的配對正確？",options:["Pansori－日本","Komun'go－韓國","Didgeridoo－印度","Rumba－巴西"],answer:1,explanation:"Komun'go（玄琴）為韓國傳統絃樂器；Pansori 亦屬韓國，Didgeridoo 主要與澳洲原住民族相關，Rumba 主要源於古巴。",source:"阿摩114師大附中音樂科選擇題考點改寫"},
{year:"114",level:"高中音樂",exam:"國立臺灣師大附中正式教師甄選",topic:"世界音樂",difficulty:"中",question:"Didgeridoo 最主要與哪一地區的原住民族音樂文化相關？",options:["澳洲","韓國","古巴","芬蘭"],answer:0,explanation:"Didgeridoo 是澳洲原住民族傳統管樂器。",source:"阿摩114師大附中音樂科選擇題考點改寫"},
{year:"114",level:"高中音樂",exam:"國立臺灣師大附中正式教師甄選",topic:"音樂教育／課綱",difficulty:"中高",question:"藝術才能資賦優異專長領域課程綱要，強調學生在專長領域的學習應同時涵蓋下列何者？",options:["只重視技術展演","創作展演、知識思考、美感文化與專題應用等面向","只依一般班藝術課綱","僅以升學考科為核心"],answer:1,explanation:"藝術才能資優專長領域課程重視多面向專長發展，不僅是技術訓練，也包括知識、美感、文化與專題應用。",source:"阿摩114師大附中音樂科第3題考點改寫"},
{year:"114",level:"高中音樂",exam:"國立臺灣師大附中正式教師甄選",topic:"二十世紀音樂",difficulty:"高",question:"十二音技法中，P0 通常表示什麼？",options:["原始音列，移調基準為0","逆行音列","倒影音列","逆行倒影音列"],answer:0,explanation:"P 代表 Prime（原形），0 表示以原始音高層級為基準的音列形式。",source:"阿摩114師大附中申論題十二音列考點改寫"},
{year:"114",level:"高中音樂",exam:"國立臺灣師大附中正式教師甄選",topic:"臺灣音樂",difficulty:"中",question:"《1947序曲》與下列哪位臺灣作曲家最相關？",options:["郭芝苑","蕭泰然","馬水龍","江文也"],answer:1,explanation:"《1947序曲》為蕭泰然的重要作品之一。",source:"阿摩114師大附中申論題考點改寫"},
{year:"114",level:"高中音樂",exam:"國立臺灣師大附中正式教師甄選",topic:"原住民族音樂",difficulty:"中",question:"Pasibutbut（祈禱小米豐收歌）主要與哪一臺灣原住民族群相關？",options:["布農族","阿美族","排灣族","卑南族"],answer:0,explanation:"Pasibutbut 是布農族著名的複音歌唱傳統。",source:"阿摩114師大附中申論題考點改寫"}
);