window.EXTRA_QUESTIONS = window.EXTRA_QUESTIONS || [];
window.EXTRA_QUESTIONS.push(
{id:"115-HCHS-01",year:"115",school:"國立新竹高中",level:"高中音樂",rarity:"👹高鑑別",question:"下列哪一組術語最能描述印象樂派常見的音響與作曲語彙？",options:["Basso continuo、Sequence、Terraced dynamics","Atonality、Twelve-tone row、Sprechstimme","Parallel chords、Whole-tone scale、Timbre-driven texture","Periodic phrasing、Alberti bass、Functional harmony"],answer:2,explanation:"印象派常以平行和弦、全音音階、五聲音階、非功能性和聲及音色導向織度塑造色彩。十二音列與Sprechstimme較屬第二維也納樂派脈絡。"},
{id:"115-HCHS-02",year:"115",school:"國立新竹高中",level:"高中音樂",rarity:"👹跨域",question:"以UbD設計Khoomei／泛音唱法單元時，下列哪一個探究問題最不適切？",options:["口型改變如何強化不同泛音？","雙音現象如何挑戰單音音樂分類？","模仿自然聲響如何連結游牧文化與環境觀？","呼麥歌手是否具有與一般人本質不同的遺傳聲帶結構？"],answer:3,explanation:"UbD的核心問題應引導可探究、可理解與可遷移的概念。把呼麥能力歸因於本質性的遺傳差異既缺乏適切證據，也容易形成文化與生理刻板印象。"},
{id:"115-HCHS-04",year:"115",school:"國立新竹高中",level:"高中音樂",rarity:"👹曲式辨析",question:"下列哪一種與其說是一個固定曲式，更適合視為一種作曲技法？",options:["輪旋奏鳴曲","主題變奏曲","賦格","輪旋二段體"],answer:2,explanation:"Fugue（賦格）核心是以主題、答題、模仿與對位方式組織音樂，因此更常被理解為對位作曲技法，而非只有單一固定外型的曲式模板。"},
{id:"115-HCHS-05",year:"115",school:"國立新竹高中",level:"高中音樂",rarity:"臺灣音樂",question:"灣聲樂團《臺灣的聲音 新年音樂會》的音樂總監為何人？",options:["馬世芳","李哲藝","呂岱衛","胡乃元"],answer:1,explanation:"灣聲樂團由李哲藝擔任音樂總監，以臺灣作品及臺灣題材作品為重要策展核心。這類題目反映教甄也會考當代臺灣音樂實務與文化推廣。"},
{id:"115-HCHS-06",year:"115",school:"國立新竹高中",level:"高中音樂",rarity:"👹臺灣戲曲",question:"曾創辦薪傳歌仔戲劇團，並以歌仔戲傳承與精緻化著稱的國寶級藝師為何人？",options:["楊麗花","廖瓊枝","陳亞蘭","孫翠鳳"],answer:1,explanation:"廖瓊枝長期投入歌仔戲表演、傳承與教育，創辦薪傳歌仔戲劇團，被譽為『東方最美的詠嘆調』。需與電視歌仔戲明星楊麗花、陳亞蘭等辨析。"},
{id:"115-HCHS-07",year:"115",school:"國立新竹高中",level:"高中音樂",rarity:"👹臺灣傳統音樂",question:"臺灣傳統音樂中，常被稱為『音樂活化石』的是哪一類？",options:["京劇","南管","北管","崑曲"],answer:1,explanation:"南管保存古老曲牌、樂器、演奏與唱腔傳統，常被形容為音樂活化石。教甄常進一步連考上四管、指骨、郎君樂、南音／弦管等別稱。"},
{id:"115-HCHS-08",year:"115",school:"國立新竹高中",level:"高中音樂",rarity:"👹和聲陷阱",question:"關於半終止（Half Cadence），下列何者最能掌握其判斷核心？",options:["任何包含IV的進行都是半終止","樂句或片段在屬功能V上形成停頓或結束感","只要出現V–VI就是半終止","任何未回到I的兩和弦進行都叫半終止"],answer:1,explanation:"半終止的核心不是背固定兩和弦公式，而是樂句在V（屬功能）上形成終止／停頓。V–VI通常是阻礙終止；不能只看兩個羅馬數字而忽略句法位置。"},
{id:"115-HCHS-09",year:"115",school:"國立新竹高中",level:"高中音樂",rarity:"👹第二維也納樂派",question:"下列何者較能正確區辨第二維也納樂派三位作曲家的風格？",options:["把微型結構、點描織度與音色旋律主要歸給Berg","Berg常保留較強的浪漫抒情性與調性痕跡","把高度精簡點描織度主要歸給Schoenberg而非Webern","只背三人的生卒年即可充分區辨風格"],answer:1,explanation:"Berg常在無調性／十二音技法中保留浪漫抒情與調性暗示；Webern則以高度濃縮、點描、對稱與音色組織著稱；Schoenberg是無調性與十二音技法的重要開創者。"},
{id:"115-HCHS-10",year:"115",school:"國立新竹高中",level:"高中音樂",rarity:"臺灣作曲家",question:"關於馬水龍《梆笛協奏曲》，下列何者正確？",options:["完全採西方十二音列技法","融合五聲音階思維與西方管弦樂編制","全曲只有單一樂章","完全排除西洋打擊樂器"],answer:1,explanation:"《梆笛協奏曲》是臺灣現代音樂中融合傳統民族器樂語彙與西方管弦樂的重要作品，展現傳統與現代、本土與西方的整合。"}
);