// 114 高雄市國中教師聯甄音樂科｜高鑑別題第一批
window.QUESTIONS = window.QUESTIONS || [];
window.QUESTIONS.push(
{year:"114",school:"高雄市國中教師聯甄",level:"國中",type:"choice",difficulty:"中",topic:"音樂教育",question:"Orff Schulwerk 最具代表性的教學特色為何？",options:["以固定曲目與傳統記譜為核心","結合語言、律動、歌唱、器樂與即興","以音樂史年代背誦為核心","以十二音技法訓練兒童作曲"],answer:1,explanation:"Orff 強調元素性音樂（elemental music），常從語言節奏、身體律動、歌唱、打擊樂器與即興創作出發，並融合舞蹈與戲劇。"},
{year:"114",school:"高雄市國中教師聯甄",level:"國中",type:"choice",difficulty:"中",topic:"音樂教育",question:"Kodály 教學中使用 Curwen hand signs，最直接的目的為何？",options:["辨識樂器音色","連結音高、唱名與視唱","記憶作曲家年代","訓練指揮拍型"],answer:1,explanation:"柯達伊體系重視歌唱、首調唱名、手號與節奏音節；手號將音高關係視覺化與身體化，協助內在聽覺與視唱。"},
{year:"114",school:"高雄市國中教師聯甄",level:"國中",type:"choice",difficulty:"👹",topic:"音樂教育哲學",question:"下列何者最能區分 Bennett Reimer 與 David Elliott 的音樂教育哲學？",options:["Reimer重審美經驗；Elliott重音樂實踐與musicing","Reimer主張只教流行音樂；Elliott只教古典音樂","兩人皆以器樂技巧標準化為唯一目標","兩人皆反對學生實際參與音樂活動"],answer:0,explanation:"Reimer常與審美音樂教育哲學連結；Elliott則以praxial music education著稱，強調music making／musicing、musicianship與情境中的音樂實踐。"},
{year:"114",school:"高雄市國中教師聯甄",level:"國中",type:"choice",difficulty:"👹",topic:"音樂教育",question:"下列何者最不屬於 Dalcroze Eurhythmics 的核心概念？",options:["以身體動作感受節奏與音樂元素","重視kinesthesia肌肉運動知覺","即興與聽覺反應可融入學習","以Gordon的Audiation與音樂性向測驗作為核心理論"],answer:3,explanation:"Dalcroze核心為Eurhythmics、solfège與improvisation，重視身體律動與動覺；Audiation與音樂性向測驗則主要屬Edwin Gordon的音樂學習理論。"},
{year:"114",school:"高雄市國中教師聯甄",level:"國中",type:"choice",difficulty:"中",topic:"西洋音樂史",question:"巴洛克時期 Oratorio（神劇）與歌劇相比，最典型的差異為何？",options:["神劇通常以器樂獨奏為主且無人聲","神劇通常不以完整舞台佈景與戲劇動作演出，常採宗教題材","神劇一定使用拉丁文，歌劇一定使用義大利文","神劇沒有合唱"],answer:1,explanation:"Oratorio常包含獨唱、重唱、合唱與管弦樂，但通常採音樂會式演出而非完整舞台戲劇；Handel《Messiah》是最常見代表。"},
{year:"114",school:"高雄市國中教師聯甄",level:"國中",type:"choice",difficulty:"中",topic:"臺灣音樂",question:"1930年代創作〈望春風〉、〈雨夜花〉等作品，常被稱為臺灣歌謠重要代表人物的是？",options:["鄧雨賢","陳達","胡德夫","楊三郎"],answer:0,explanation:"鄧雨賢是日治時期臺灣重要作曲家，代表作常見〈望春風〉、〈雨夜花〉、〈月夜愁〉、〈四季紅〉。教甄常以作品與人物互換命題。"},
{year:"114",school:"高雄市國中教師聯甄",level:"國中",type:"choice",difficulty:"👹",topic:"中國音樂史",question:"下列中國音樂史敘述何者最值得判為錯誤？",options:["周代大司樂兼具禮樂教育功能","漢代相和歌與鼓吹樂皆為重要音樂類型","把秦代樂府制度與高漸離直接視為成熟漢代樂府體制的同一概念","隋唐宮廷音樂呈現多民族與外來文化交流"],answer:2,explanation:"『樂府』制度的歷史脈絡需區分秦漢，漢武帝時期的擴充尤其重要；不能把秦代、高漸離與後來成熟的漢代樂府制度簡單畫上等號。教甄常用朝代錯置製造陷阱。"},
{year:"114",school:"高雄市國中教師聯甄",level:"國中",type:"choice",difficulty:"👹",topic:"Mozart",question:"關於 Mozart，下列何者正確？",options:["第40號交響曲為D小調","《魔笛》是其早期義大利正歌劇代表","第21號鋼琴協奏曲第二樂章常因電影而有Elvira Madigan之稱","《安魂曲》由Mozart生前完整親筆完成"],answer:2,explanation:"第40號交響曲為G小調；《魔笛》是晚期德語Singspiel；《安魂曲》在Mozart逝世時未完成，後由Süssmayr等續成。K.467第二樂章因電影《Elvira Madigan》而廣為人知。"}
);