window.LOCAL_QUESTIONS = (window.LOCAL_QUESTIONS || []).concat([
{id:'RARE8-001',subject:'高中音樂',topic:'臺灣北管',level:'冷門魔王',year:'111',exam:'中壢高中',source_type:'歷屆考點改寫',source_title:'111 中壢高中音樂科',question:'下列何者不屬於傳統北管常見樂曲？',option_a:'風入松',option_b:'一江風',option_c:'四時景',option_d:'百家春',answer:'C',explanation:'111 中壢高中曾以此類北管曲目辨識命題；四時景並非該題所列的傳統北管曲目。'},
{id:'RARE8-002',subject:'高中音樂',topic:'世界音樂',level:'冷門魔王',year:'111',exam:'中壢高中',source_type:'歷屆考點改寫',source_title:'111 中壢高中音樂科',question:'下列國家與傳統樂器配對何者錯誤？',option_a:'日本—太鼓',option_b:'印尼—Tabla',option_c:'韓國—Gayageum',option_d:'印度—Mridangam',answer:'B',explanation:'Tabla 主要與印度音樂傳統相關；印尼常見代表性合奏則包括 Gamelan。'},
{id:'RARE8-003',subject:'高中音樂',topic:'宗教音樂',level:'高鑑別度',year:'111',exam:'中壢高中',source_type:'歷屆考點改寫',source_title:'111 中壢高中音樂科',question:'下列何者不屬於天主教彌撒常規（Mass Ordinary）經文？',option_a:'Agnus Dei',option_b:'Alleluia',option_c:'Credo',option_d:'Sanctus',answer:'B',explanation:'Alleluia 屬彌撒特定（Proper）內容；Kyrie、Gloria、Credo、Sanctus、Agnus Dei 為常規主要部分。'},
{id:'RARE8-004',subject:'高中音樂',topic:'原住民族音樂',level:'冷門魔王',year:'111',exam:'中壢高中',source_type:'歷屆考點改寫',source_title:'111 中壢高中音樂科',question:'賽夏族矮靈祭（巴斯達隘）最具代表性的聲響物件之一為何？',option_a:'臀鈴',option_b:'腰鈴／背響類鈴具',option_c:'雙管鼻笛',option_d:'木琴',answer:'B',explanation:'巴斯達隘的舞蹈與鈴具聲響密切相關；此類族群祭典與樂器配對是教甄常見細節題。'},
{id:'RARE8-005',subject:'高中音樂',topic:'中國器樂',level:'冷門魔王',year:'111',exam:'中壢高中',source_type:'歷屆考點改寫',source_title:'111 中壢高中音樂科',question:'下列哪一首傳統名曲主要以嗩吶獨奏聞名？',option_a:'百鳥朝鳳',option_b:'空山鳥語',option_c:'十面埋伏',option_d:'燭影搖紅',answer:'A',explanation:'《百鳥朝鳳》為著名嗩吶曲；《空山鳥語》常與二胡、《十面埋伏》與琵琶相關。'},
{id:'RARE8-006',subject:'高中音樂',topic:'和聲',level:'高鑑別度',year:'111',exam:'嘉義高中',source_type:'歷屆考點改寫',source_title:'111 嘉義高中音樂科',question:'在 D 大調中，拿坡里六和弦（Neapolitan Sixth）通常建立在哪個變化音級上？',option_a:'升高第二級',option_b:'降低第二級',option_c:'降低第六級',option_d:'升高第四級',answer:'B',explanation:'Neapolitan chord 建立在降二級上，古典和聲中常以第一轉位 N6 出現。'},
{id:'RARE8-007',subject:'高中音樂',topic:'和聲',level:'冷門魔王',year:'111',exam:'嘉義高中',source_type:'歷屆考點改寫',source_title:'111 嘉義高中音樂科',question:'Phrygian Half Cadence 最典型的低音進行為何？',option_a:'1→5',option_b:'4→5',option_c:'♭6→5',option_d:'2→1',answer:'C',explanation:'小調語境中的 Phrygian half cadence 常見低音 ♭6–5，並形成具有半音下行特色的終止效果。'},
{id:'RARE8-008',subject:'高中音樂',topic:'臺灣與世界音樂',level:'冷門魔王',year:'111',exam:'高雄高中聯招',source_type:'歷屆考點改寫',source_title:'111 高雄高中聯招音樂科',question:'Didgeridoo（迪吉里杜管）最常與哪一文化傳統連結？',option_a:'澳洲原住民族',option_b:'蒙古游牧民族',option_c:'日本雅樂',option_d:'西非曼丁文化',answer:'A',explanation:'Didgeridoo 是澳洲原住民族、尤其澳洲北部部分族群的重要吹奏樂器。'},
{id:'RARE8-009',subject:'高中音樂',topic:'世界音樂',level:'冷門魔王',year:'111',exam:'高雄高中聯招',source_type:'歷屆考點改寫',source_title:'111 高雄高中聯招音樂科',question:'Piphat（皮帕特）主要是哪一地區的傳統合奏？',option_a:'泰國',option_b:'印度北部',option_c:'韓國',option_d:'葡萄牙',answer:'A',explanation:'Piphat 是泰國古典音樂的重要合奏類型，以打擊與吹管樂器為核心。'},
{id:'RARE8-010',subject:'高中音樂',topic:'爵士與流行',level:'冷門魔王',year:'111',exam:'高雄高中聯招',source_type:'歷屆考點改寫',source_title:'111 高雄高中聯招音樂科',question:'Milonga 與下列哪一音樂／舞蹈傳統關係最密切？',option_a:'Tango',option_b:'Gagaku',option_c:'Flamenco',option_d:'Kecak',answer:'A',explanation:'Milonga 與拉普拉塔河流域音樂文化密切相關，也是探討 Tango 發展時的重要概念。'}
]);