window.LOCAL_QUESTIONS = window.LOCAL_QUESTIONS || [];
window.LOCAL_QUESTIONS.push(
{id:'RARE4-001',subject:'高中音樂',topic:'臺灣傳統音樂',level:'魔王',year:'112',exam:'臺中一中教師甄選考點',source_type:'歷屆考點改寫',source_title:'112 臺中一中音樂科',question:'下列何者不是北管常見的音樂類型／曲類？',option_a:'整弦',option_b:'細曲',option_c:'牌子',option_d:'弦譜',answer:'A',explanation:'北管常見分類包含戲曲、牌子、弦譜、細曲等；「整弦」不是此處的北管曲類。'},
{id:'RARE4-002',subject:'高中音樂',topic:'臺灣傳統音樂',level:'魔王',year:'112',exam:'臺中一中教師甄選考點',source_type:'歷屆考點改寫',source_title:'112 臺中一中音樂科',question:'下列何者不是南管「上四管」的核心樂器？',option_a:'琵琶',option_b:'洞簫',option_c:'二弦',option_d:'雙音',answer:'D',explanation:'南管上四管通常為琵琶、三弦、洞簫、二弦。'},
{id:'RARE4-003',subject:'高中音樂',topic:'世界音樂與樂器',level:'高鑑別',year:'114',exam:'和美實驗學校教師甄選考點',source_type:'歷屆考點改寫',source_title:'114 和美實驗學校音樂科',question:'下列國家／地區與傳統樂器的配對，何者正確？',option_a:'韓國—Ryuteki',option_b:'日本—Haegeum',option_c:'印度—Saron',option_d:'印尼—Angklung',answer:'D',explanation:'Angklung（安格隆）是印尼竹製搖奏樂器；Ryuteki 為日本雅樂樂器，Haegeum 為韓國樂器，Saron 常見於印尼甘美朗。'},
{id:'RARE4-004',subject:'高中音樂',topic:'音樂科技',level:'高鑑別',year:'114',exam:'和美實驗學校教師甄選考點',source_type:'歷屆考點改寫',source_title:'114 和美實驗學校音樂科',question:'下列何者是知名的開源音訊編輯軟體？',option_a:'Audacity',option_b:'Cubase',option_c:'GarageBand',option_d:'Logic Pro',answer:'A',explanation:'Audacity 為免費、開源的音訊錄製與編輯軟體。'},
{id:'RARE4-005',subject:'高中音樂',topic:'原住民族音樂',level:'魔王',year:'112',exam:'六家高中教師甄選考點',source_type:'歷屆考點改寫',source_title:'112 六家高中音樂科',question:'臺灣原住民族傳統音樂中，哪一族以「平行音」唱法相關特色受到教甄命題注意？',option_a:'太魯閣族',option_b:'鄒族',option_c:'卑南族',option_d:'撒奇萊雅族',answer:'B',explanation:'歷屆題目以鄒族作為平行音唱法辨識考點；原住民族複音、和聲與祭儀歌唱是常見冷門題區。'},
{id:'RARE4-006',subject:'高中音樂',topic:'錄音媒體與科技',level:'魔王',year:'112',exam:'教育部高中聯招考點',source_type:'歷屆考點改寫',source_title:'112 教育部高中聯招音樂科',question:'下列何者不是黑膠唱片常見的標準轉速？',option_a:'33 1/3 rpm',option_b:'45 rpm',option_c:'68 rpm',option_d:'78 rpm',answer:'C',explanation:'33 1/3、45、78 rpm 都是常見唱片轉速；68 rpm 並非常見標準規格。'},
{id:'RARE4-007',subject:'高中音樂',topic:'臺灣音樂史',level:'魔王',year:'112',exam:'教育部高中聯招考點',source_type:'歷屆考點改寫',source_title:'112 教育部高中聯招音樂科',question:'下列何者最能說明北管俗諺「吃肉吃三層，看戲看亂彈」中的「亂彈」？',option_a:'北管戲曲傳統',option_b:'南管指套',option_c:'歌仔戲內台戲',option_d:'客家採茶戲',answer:'A',explanation:'「亂彈」與北管戲曲傳統密切相關，是辨識臺灣傳統戲曲的重要關鍵詞。'},
{id:'RARE4-008',subject:'高中音樂',topic:'20世紀音樂',level:'魔王',year:'109',exam:'教育部高中聯招名詞考點',source_type:'歷屆考點延伸',source_title:'109 教育部高中聯招音樂科',question:'Microtonal Music（微分音音樂）的核心概念為何？',option_a:'只使用五聲音階',option_b:'使用小於傳統半音的音程分割或微小音程',option_c:'完全取消節奏',option_d:'只能使用電子樂器',answer:'B',explanation:'微分音音樂運用小於十二平均律半音的音程或其他微細音高分割，並不限於電子樂器。'},
{id:'RARE4-009',subject:'高中音樂',topic:'世界音樂',level:'高鑑別',year:'109',exam:'教育部高中聯招名詞考點',source_type:'歷屆考點延伸',source_title:'109 教育部高中聯招音樂科',question:'Gamelan 最主要與哪一地區的傳統合奏文化相關？',option_a:'印尼爪哇與峇里',option_b:'蒙古草原',option_c:'葡萄牙里斯本',option_d:'西非曼丁文化圈',answer:'A',explanation:'Gamelan（甘美朗）主要與印尼爪哇、峇里等地相關，以鑼、金屬鍵盤類打擊樂器等構成重要合奏文化。'},
{id:'RARE4-010',subject:'高中音樂',topic:'爵士樂',level:'魔王',year:'109',exam:'教育部高中聯招名詞考點',source_type:'歷屆考點延伸',source_title:'109 教育部高中聯招音樂科',question:'下列何者最符合 Free Jazz 的典型特徵？',option_a:'嚴格依循十二小節藍調和聲',option_b:'強調固定華爾滋節奏',option_c:'弱化既定和聲、曲式或拍節限制並擴大自由即興',option_d:'完全禁止即興',answer:'C',explanation:'Free Jazz 常突破固定和聲進行、曲式與拍節框架，強調更自由的集體或個人即興。'}
);