// 115 新北市公立高中聯甄｜教育專業 × 音樂整合（第27–35題）
window.EXTRA_QUESTIONS = window.EXTRA_QUESTIONS || [];
window.EXTRA_QUESTIONS.push(
{year:"115",school:"新北市公立高中聯甄",type:"education",question:"依修訂版Bloom教育目標分類，學生規劃並執行『班際合唱比賽方案』時，最直接涉及哪一知識向度？",options:["事實知識 factual knowledge","程序知識 procedural knowledge","概念知識 conceptual knowledge","後設認知知識 metacognitive knowledge"],answer:1,explanation:"方案規劃與執行涉及『如何做』的方法、流程、技術與程序，核心屬程序知識。考題若強調策略選擇、自我監控與反思自己的認知，才更接近後設認知。"},
{year:"115",school:"新北市公立高中聯甄",type:"curriculum",question:"依108藝術領域課綱，強調運用數位軟硬體、解構傳統創作思維並完成跨學科藝術創作的加深加廣選修科目為何？",options:["新媒體藝術","音樂產製","藝術與生活","多媒體音樂"],answer:0,explanation:"原題答案指向『新媒體藝術』。辨識關鍵是數位媒材、跨學科與解構傳統藝術創作思維；若題幹更集中錄音、編曲、製作流程，才較像音樂產製。"},
{year:"115",school:"新北市公立高中聯甄",type:"curriculum",question:"Fogarty課程統整模式中的Immersed（浸潤式）最符合哪一描述？",options:["由單一學科教師主導，其他學科只補充資料","各科圍繞同一主題平行授課，但仍保持各自學科視角","多位教師共同打破學科界線設計同一專案","學習者從自身高度投入的興趣或專長出發，自行把不同學科知識整合進同一視角"],answer:3,explanation:"Immersed的核心在『學習者』以自身興趣／專長作為濾鏡，自主浸潤並整合不同學科。若是多位教師共同打破學科界線設計專案，較接近Integrated等模式。"},
{year:"115",school:"新北市公立高中聯甄",type:"assessment",question:"關於Performance Level Descriptor（表現等級描述），下列何者錯誤？",options:["屬標準參照取向","可用文字描述各等級表現特徵","以等級與規準描述學習表現","音樂性向測驗本身就是Performance Level Descriptor"],answer:3,explanation:"PLD是描述不同表現等級『學生能做到什麼』的規準文字，不等於音樂性向測驗。性向測驗是一種測量工具；PLD則是對表現標準／等級的描述。"},
{year:"115",school:"新北市公立高中聯甄",type:"assessment",question:"教師用VR模擬音樂廳演出，學生依自己的演奏與反思紀錄持續修正學習；若反思本身也是評量與學習歷程的一部分，最符合哪一理念？",options:["Assessment as Learning 評量即學習","Assessment for Learning 促進學習的評量","Assessment of Learning 學習結果的評量","Diagnostic Assessment 診斷性評量"],answer:0,explanation:"Assessment as Learning強調學生後設認知、自我評量、自我監控與反思，學生本身成為評量歷程的主動參與者。for Learning偏教師利用形成性證據調整教學；of Learning偏總結成果。"},
{year:"115",school:"新北市公立高中聯甄",type:"copyright",question:"一首作品採CC BY-SA授權。教師合法改編成管弦樂版並分享時，何者最符合授權要求？",options:["只寫改編者姓名即可","改編後改標『版權所有』禁止他人利用","只要非商業使用即可任選任何CC授權","標示原作者／來源，並以相同或相容的BY-SA方式分享改編作品"],answer:3,explanation:"BY要求姓名標示；SA（ShareAlike）要求改作以相同或相容授權條款釋出。它並不等同NC，因此『只要非商業即可任選授權』是錯誤理解。"},
{year:"115",school:"新北市公立高中聯甄",type:"technology",question:"下列數位科技音樂創作教學設計，哪一項可行性最低？",options:["用Scratch製作數位鋼琴鍵盤並即興","用Chrome Music Lab Song Maker在格狀介面創作","用BandLab匯入音訊進行改編與混音","用GarageBand智慧樂器與Loops探索伴奏與創作"],answer:1,explanation:"陷阱在介面描述：Song Maker主要採格狀／piano-roll式視覺介面，不是『在五線譜上拖曳音符』。其他三項皆屬可行的數位音樂創作活動。"},
{year:"115",school:"新北市公立高中聯甄",type:"bilingual",question:"以雙語介紹音樂織度時，哪一敘述最正確？",options:["Bach fugue is homophonic because it has melody and chordal accompaniment.","Bach fugue can feature multiple independent melodic lines, creating polyphonic texture.","Haydn piano sonata is monophonic because only one pianist performs it.","Melody with accompaniment in Haydn is heterophonic texture."],answer:1,explanation:"Fugue以多條相對獨立旋律線的模仿與交織為典型polyphonic texture。演奏者只有一人不代表monophony；旋律加伴奏通常屬homophonic，而非heterophonic。"},
{year:"115",school:"新北市公立高中聯甄",type:"terminology",question:"若要提示演唱音量『逐漸減弱直至消失』，哪一組術語最適當？",options:["Morendo＋Smorzando","Sotto voce＋Mezzo forte","Stringendo＋Affrettando","Allargando＋Maestoso"],answer:0,explanation:"Morendo有『逐漸消逝、如死去般』之意；Smorzando亦指聲音逐漸減弱、熄滅。Stringendo／Affrettando偏加快與催促；Allargando偏漸寬廣；Maestoso為莊嚴。"}
);