// 115年國高中音樂教甄｜高鑑別考點改寫 batch29
// 來源依據：阿摩正式試卷（115中區國中、115高雄高中、115新北高中等）
// 原題不逐字重製，改寫為可複習、可追蹤的考點題。
window.EXTRA_QUESTIONS = window.EXTRA_QUESTIONS || [];
window.EXTRA_QUESTIONS.push(
 {id:'115-b29-01',year:115,level:'國中',source:'115中區縣市政府教師甄選策略聯盟－國中音樂科',topic:'臺灣音樂',difficulty:'中',question:'民間歌者陳達演唱恆春民謠時，最具代表性的自彈自唱伴奏樂器為何？',options:['月琴','琵琶','三弦','阮咸'],answer:0,explanation:'陳達是臺灣恆春民謠重要民間歌者，以月琴自彈自唱最具代表性。準備時應連結「人物－地域－曲種－樂器」，而非只背單一人名。',tags:['陳達','月琴','恆春民謠','臺灣音樂','跨年高頻']},
 {id:'115-b29-02',year:115,level:'國中',source:'115中區縣市政府教師甄選策略聯盟－國中音樂科',topic:'中國音樂',difficulty:'中',question:'下列何者最符合二胡名曲《賽馬》的原始樂器編制？',options:['二胡獨奏','古琴獨奏','琵琶獨奏','笛子獨奏'],answer:0,explanation:'《賽馬》為黃海懷創作的二胡獨奏曲。教甄常把作品、作曲者、樂器與音樂形象交叉配對。',tags:['二胡','賽馬','黃海懷','中國音樂']},
 {id:'115-b29-03',year:115,level:'國中',source:'115中區縣市政府教師甄選策略聯盟－國中音樂科',topic:'譜表',difficulty:'高',question:'若某五線譜「第三間」所代表的音名為 F，最可能使用哪一種 C 譜表？',options:['女高音譜表','女中音譜表','中音譜表','次中音譜表'],answer:1,explanation:'C譜表所在的線就是中央C。女中音譜表（mezzo-soprano clef）將C譜號置於第二線，因此第三間為F。這類題要靠譜表位置推導，不宜死背。',tags:['C譜表','Mezzo-Soprano clef','讀譜','高鑑別']},
 {id:'115-b29-04',year:115,level:'國中',source:'115中區縣市政府教師甄選策略聯盟－國中音樂科',topic:'巴洛克',difficulty:'高',question:'巴赫管風琴作品 BWV 596 所改編的協奏曲素材，原作與哪位義大利作曲家關係最密切？',options:['Corelli','Vivaldi','Albinoni','Tartini'],answer:1,explanation:'BWV 596 是巴赫依據 Vivaldi 協奏曲素材所作的管風琴改編。此題反映教甄常考「跨作曲家改編／引用關係」。',tags:['Bach','Vivaldi','BWV596','巴洛克','冷門高鑑別']},
 {id:'115-b29-05',year:115,level:'高中',source:'115高雄市立高雄高中正式教師甄選',topic:'管弦樂法',difficulty:'中',question:'一般管弦樂總譜由上而下的主要樂器家族排列，何者最合理？',options:['木管→銅管→打擊→豎琴／鍵盤→弦樂','弦樂→木管→銅管→打擊→鍵盤','銅管→木管→弦樂→打擊→豎琴','打擊→銅管→木管→弦樂→鍵盤'],answer:0,explanation:'現代管弦樂總譜通常由木管、銅管、打擊，再到豎琴／鍵盤等特殊或補充樂器，最後為弦樂。實際總譜會依編制略有差異。',tags:['總譜順序','管弦樂法','配器']},
 {id:'115-b29-06',year:115,level:'高中',source:'115高雄市立高雄高中正式教師甄選',topic:'音樂與科技文化',difficulty:'高',question:'關於 Voyager Golden Record（航海家金唱片），下列哪項理解最正確？',options:['只收錄歐美古典音樂','內容包含世界不同文化的聲音與音樂，用以呈現地球文化多樣性','是專為音樂教育課綱製作的教材','僅收錄20世紀流行音樂'],answer:1,explanation:'航海家金唱片收錄自然聲響、語言問候與多文化音樂，目的之一是向可能的地外接收者呈現地球生命與文化。這類題把音樂史、科技史與全球文化素養結合。',tags:['Voyager Golden Record','世界音樂','科技','跨領域','近年升溫']},
 {id:'115-b29-07',year:115,level:'高中',source:'115新北市公立高中教師聯合甄選',topic:'音樂教育',difficulty:'中',question:'Dalcroze Eurhythmics 的核心精神最接近下列何者？',options:['以身體律動經驗節奏與音樂，再連結聽覺、即興與音樂理解','以固定手勢取代所有歌唱活動','以十二音列作為兒童創作起點','以電腦軟體進行純視覺化樂理訓練'],answer:0,explanation:'達克羅士教學以 Eurhythmics（律動）、solfège 與 improvisation 為重要支柱，強調透過身體動作內化節奏與音樂感。',tags:['Dalcroze','Eurhythmics','音樂教育','跨年高頻']},
 {id:'115-b29-08',year:115,level:'高中',source:'115新北市公立高中教師聯合甄選',topic:'SEL與音樂教育',difficulty:'高',question:'若要把社會情緒學習（SEL）真正融入高中音樂課，哪一種設計最符合其精神？',options:['只要求學生背誦SEL五大能力名稱','以作品聆聽辨識情緒線索，連結自我覺察、觀點取替與小組音樂創作後反思','將SEL獨立成與音樂無關的班會講述','只以紙筆測驗評量情緒詞彙'],answer:1,explanation:'SEL重點不是額外講授名詞，而是讓學生在真實互動與任務中發展自我覺察、自我管理、社會覺察、人際技巧與負責任決策。音樂聆聽、合奏與創作都可成為媒介。',tags:['SEL','社會情緒學習','素養導向','教學轉化','115新趨勢']},
 {id:'115-b29-09',year:115,level:'高中',source:'115中山女高正式教師甄試',topic:'世界音樂',difficulty:'高',question:'西非 Kora 最適合被描述為何種樂器？',options:['以葫蘆共鳴箱為基礎、具有多弦的橋式豎琴／魯特類樂器','日本三味線類三弦撥弦樂器','印度雙面鼓','安地斯排簫'],answer:0,explanation:'Kora 是西非曼德文化重要弦樂器，常與 griot／jeli 傳統相關。構造具有大型葫蘆共鳴體、皮面與多弦，分類上常描述為 bridge-harp 或 harp-lute。',tags:['Kora','西非','世界音樂','griot','冷門高鑑別']},
 {id:'115-b29-10',year:115,level:'高中',source:'115中山女高正式教師甄試',topic:'音樂劇',difficulty:'中',question:'音樂劇表演訓練中常說的「Triple Threat」通常指表演者同時具備哪三項能力？',options:['作曲、指揮、編曲','唱歌、舞蹈、戲劇表演','鋼琴、聲樂、視唱','錄音、混音、燈光'],answer:1,explanation:'Musical theatre 的 triple threat 指 singing、dancing、acting 三項皆具專業能力的表演者。近年高中教甄明顯增加音樂劇、表演藝術與跨域實務題。',tags:['Triple Threat','音樂劇','表演藝術','近年升溫']}
);
