window.EXTRA_QUESTIONS = (window.EXTRA_QUESTIONS || []).concat([
{id:"115-MOE-NC13-01",year:115,subject:"高中音樂",topic:"歌劇與音樂劇",level:"👹 魔王",question:"18世紀德語地區以口語對白穿插歌曲、重唱與合唱的喜歌劇類型，最適合以哪一術語稱呼？",options:["Singspiel","Opéra comique","Opera seria","Zarzuela"],answer:0,explanation:"Singspiel 是德語歌唱劇，以口語對白與歌曲交替為重要特徵；莫札特《後宮誘逃》、《魔笛》常作為代表。",source:"115 教育部高中音樂教師甄選非選題考點改寫｜阿摩 #139594"},
{id:"115-MOE-NC13-02",year:115,subject:"高中音樂",topic:"英國音樂史",level:"👹 魔王",question:"18世紀英國以流行曲調重新填詞、搭配口語對白，並常帶有社會諷刺色彩的舞臺類型為何？",options:["Ballad opera","Masque","Grand opera","Intermezzo"],answer:0,explanation:"Ballad opera（民謠歌劇）是18世紀英國重要的喜歌劇形式，《乞丐歌劇》為經典代表。",source:"115 教育部高中音樂教師甄選非選題考點改寫｜阿摩 #139594"},
{id:"115-MOE-NC13-03",year:115,subject:"高中音樂",topic:"文藝復興音樂",level:"👹 魔王",question:"若樂譜安排兩組以上合唱團或器樂團分置於教堂不同空間，彼此應答並形成空間化音響，最直接對應哪一概念？",options:["Cori spezzati","Cantus firmus","Fauxbourdon","Hocket"],answer:0,explanation:"Cori spezzati 即分置合唱，與威尼斯聖馬可大教堂及 Gabrieli 等人的複合唱團傳統密切相關。",source:"115 教育部高中音樂教師甄選名詞解釋考點改寫｜阿摩 #139594"},
{id:"115-MOE-NC13-04",year:115,subject:"高中音樂",topic:"中世紀音樂",level:"👹 魔王",question:"Guido of Arezzo 教學體系中的 hexachord，基本上由幾個相鄰音構成？",options:["5","6","7","8"],answer:1,explanation:"Hexachord 為六音系統，中世紀與文藝復興時期常以 ut–re–mi–fa–sol–la 六音唱名進行視唱與音高組織。",source:"115 教育部高中音樂教師甄選名詞解釋考點改寫｜阿摩 #139594"},
{id:"115-MOE-NC13-05",year:115,subject:"高中音樂",topic:"宗教音樂",level:"困難",question:"下列何者最能區分 Passion（受難曲）與一般神劇？",options:["Passion 通常以耶穌受難福音敘事為核心","Passion 必須以拉丁文演唱","Passion 一律不用合唱","Passion 只存在於天主教彌撒中"],answer:0,explanation:"Passion 的核心是基督受難敘事，常有 Evangelist、耶穌角色、合唱與詠嘆調等；巴赫《馬太受難曲》、《約翰受難曲》是代表。",source:"115 教育部高中音樂教師甄選名詞解釋考點改寫｜阿摩 #139594"},
{id:"115-MOE-NC13-06",year:115,subject:"高中音樂",topic:"二十世紀音樂",level:"👹 魔王",question:"Scriabin 晚期作品中常見、由增四度等音程堆疊而形成並與其神祕思想相關的六音和弦，通常稱為？",options:["Mystic chord","Tristan chord","Neapolitan chord","Petrushka chord"],answer:0,explanation:"Mystic Chord（神祕和弦）與 Scriabin 晚期和聲語彙密切相關；教甄常將它與其他具專名的特殊和弦混淆命題。",source:"115 教育部高中音樂教師甄選名詞解釋考點改寫｜阿摩 #139594"},
{id:"115-MOE-NC13-07",year:115,subject:"高中音樂",topic:"世界音樂",level:"👹 魔王",question:"一名歌者以敘事歌唱配合一名鼓手，在長篇故事中交替使用歌唱、說白與戲劇性動作。此韓國傳統表演最可能是？",options:["Pansori","Gagaku","Noh","Kulintang"],answer:0,explanation:"Pansori（盤索里）是韓國傳統敘事歌唱，由歌者與鼓手共同演出，具有長篇敘事、說唱與戲劇性表達。",source:"115 教育部高中音樂教師甄選名詞解釋考點改寫｜阿摩 #139594"},
{id:"115-MOE-NC13-08",year:115,subject:"高中音樂",topic:"世界音樂",level:"👹 魔王",question:"葡萄牙都市歌唱傳統中，常以 saudade 所象徵的懷念、失落與命運感為重要情緒特質者為何？",options:["Fado","Flamenco","Rebetiko","Chanson"],answer:0,explanation:"Fado（法朵）是葡萄牙代表性都市歌唱傳統，常與 saudade 的懷念、惆悵與失落感相連。",source:"115 教育部高中音樂教師甄選名詞解釋考點改寫｜阿摩 #139594"}
]);