window.LOCAL_QUESTIONS = (window.LOCAL_QUESTIONS || []).concat([
{id:'RARE7-001',subject:'高中音樂',topic:'臺灣音樂',level:'冷門魔王',year:'112',exam:'教育部高中聯招',question:'音樂劇《釧兒》的故事主要取材自哪一齣臺灣傳統戲曲？',option_a:'陳三五娘',option_b:'薛平貴與王寶釧',option_c:'什細記',option_d:'山伯英台',answer:'B',explanation:'《釧兒》取材自歌仔戲經典《薛平貴與王寶釧》的相關故事脈絡。',source_type:'歷屆考點改寫',source_title:'112 教育部高中音樂教師甄選'},
{id:'RARE7-002',subject:'高中音樂',topic:'管弦樂作品',level:'冷門魔王',year:'112',exam:'教育部高中聯招',question:'下列哪一組「作品—主要獨奏樂器」配對正確？',option_a:'柴可夫斯基《洛可可主題變奏曲》—大提琴',option_b:'布魯赫《晚禱》—長笛',option_c:'白遼士《哈羅德在義大利》—小提琴',option_d:'羅德利哥《阿蘭輝茲協奏曲》—鋼琴',answer:'A',explanation:'《洛可可主題變奏曲》為大提琴與樂團作品；《哈羅德在義大利》突出中提琴，《阿蘭輝茲協奏曲》為吉他協奏曲。',source_type:'歷屆考點改寫',source_title:'112 教育部高中音樂教師甄選'},
{id:'RARE7-003',subject:'高中音樂',topic:'現代音樂',level:'冷門魔王',year:'110',exam:'教育部高中聯招',question:'梅湘的音樂語言中，除了節奏的對稱排列變換外，下列何者最具代表性？',option_a:'有限移位調式',option_b:'曼海姆火箭',option_c:'阿爾貝蒂低音',option_d:'固定低音詠嘆調',answer:'A',explanation:'Messiaen 以 modes of limited transposition（有限移位調式）及特殊節奏觀念著稱。',source_type:'歷屆考點改寫',source_title:'110 教育部高中音樂教師甄選'},
{id:'RARE7-004',subject:'高中音樂',topic:'臺灣音樂',level:'冷門魔王',year:'112',exam:'教育部高中聯招',question:'《網路交響曲第一號：英雄》（Internet Symphony No. 1 “Eroica”）與下列哪位作曲家關係最密切？',option_a:'Tan Dun 譚盾',option_b:'Bright Sheng 盛宗亮',option_c:'Chen Yi 陳怡',option_d:'Zhou Long 周龍',answer:'A',explanation:'Google/YouTube 的 YouTube Symphony Orchestra 計畫委託譚盾創作 Internet Symphony No. 1 “Eroica”。',source_type:'歷屆考點改寫',source_title:'112 教育部高中音樂教師甄選'},
{id:'RARE7-005',subject:'高中音樂',topic:'中國傳統音樂',level:'冷門魔王',year:'112',exam:'教育部高中聯招',question:'中國傳統名曲《百鳥朝鳳》最典型的獨奏樂器為何？',option_a:'笛',option_b:'嗩吶',option_c:'笙',option_d:'管子',answer:'B',explanation:'《百鳥朝鳳》是著名嗩吶獨奏曲，以模仿鳥鳴等音響效果聞名。',source_type:'歷屆考點改寫',source_title:'112 教育部高中音樂教師甄選'},
{id:'RARE7-006',subject:'高中音樂',topic:'臺灣音樂',level:'冷門魔王',year:'112',exam:'興大附中',question:'下列哪位音樂家創作／參與的作品與臺灣當代音樂文化連結最密切，並曾在教甄以「名詞解釋」方式出現？',option_a:'坂本龍一',option_b:'Jean Sibelius',option_c:'Anton Bruckner',option_d:'François Couperin',answer:'A',explanation:'112 興大附中直接將「坂本龍一」列為名詞解釋，反映教甄會考當代跨域音樂人物。',source_type:'歷屆考點改寫',source_title:'112 興大附中音樂科'},
{id:'RARE7-007',subject:'高中音樂',topic:'臺灣當代作品',level:'冷門魔王',year:'112',exam:'興大附中',question:'《菊花夜行軍》在近年高中音樂教甄中曾以何種形式出現？',option_a:'和聲寫作指定低音',option_b:'名詞解釋',option_c:'視唱旋律',option_d:'指揮拍型辨識',answer:'B',explanation:'112 興大附中將《菊花夜行軍》直接列入名詞解釋，顯示臺灣當代作品名稱也可能成為冷門考點。',source_type:'歷屆考點改寫',source_title:'112 興大附中音樂科'},
{id:'RARE7-008',subject:'高中音樂',topic:'臺灣當代作品',level:'冷門魔王',year:'112',exam:'興大附中',question:'《很久沒有敬我了你》較適合歸入下列哪一種教甄準備範圍？',option_a:'臺灣當代音樂／原住民族文化相關作品',option_b:'義大利正歌劇',option_c:'法國大歌劇',option_d:'德國藝術歌曲',answer:'A',explanation:'112 興大附中將《很久沒有敬我了你》列為名詞解釋，準備時應連結臺灣當代音樂與原住民族文化脈絡。',source_type:'歷屆考點改寫',source_title:'112 興大附中音樂科'},
{id:'RARE7-009',subject:'高中音樂',topic:'音樂史',level:'冷門魔王',year:'110',exam:'教育部高中聯招',question:'Neue Zeitschrift für Musik（《新音樂雜誌》）的創辦與下列哪位作曲家／評論家關係最密切？',option_a:'Robert Schumann',option_b:'Franz Liszt',option_c:'Hector Berlioz',option_d:'Richard Wagner',answer:'A',explanation:'舒曼於1834年共同創辦 Neue Zeitschrift für Musik，並以音樂評論推介新一代作曲家。',source_type:'歷屆考點改寫',source_title:'110 教育部高中音樂教師甄選'},
{id:'RARE7-010',subject:'高中音樂',topic:'臺灣傳統音樂',level:'冷門魔王',year:'112',exam:'臺中一中',question:'「客家八音」中的「八音」最適合理解為何？',option_a:'固定只有八位演奏者',option_b:'固定只有八件樂器',option_c:'傳統器樂合奏文化名稱，不宜簡化成固定八件樂器',option_d:'八個固定音高的音階',answer:'C',explanation:'客家八音是客家傳統器樂合奏的重要類型，「八音」並非單純等同固定八件樂器。',source_type:'歷屆考點改寫',source_title:'112 臺中一中音樂科'}
]);