// 114 高雄市國中教師聯甄音樂科｜高鑑別題第三批
window.QUESTIONS = window.QUESTIONS || [];
window.QUESTIONS.push(
{year:"114",school:"高雄市國中教師聯甄",level:"國中",type:"choice",difficulty:"👹",topic:"中國音樂史",question:"下列有關中國音樂史的敘述，何者最需要修正？",options:["周代已有大司樂等禮樂教育職掌","漢代相和歌與鼓吹樂均為重要音樂類型","秦代已有樂府相關官署發展，但漢武帝時期樂府制度更為著名","隋唐時期已普遍以今日工尺譜作為固定調唱法的官方標準"],answer:3,explanation:"工尺譜的歷史演變複雜，不能把後世成熟形態直接套回隋唐，更不能簡化成『固定調唱法的官方標準』。教甄中國音樂史常以朝代錯置、制度提前出現來設陷阱。"},
{year:"114",school:"高雄市國中教師聯甄",level:"國中",type:"choice",difficulty:"👹",topic:"古典時期",question:"關於 Mozart《安魂曲》K.626，下列何者正確？",options:["全曲皆由Mozart生前親筆完成","Mozart逝世時作品尚未完成，後由Süssmayr等人續成","作品是德語Singspiel","作品完成於其薩爾斯堡少年時期"],answer:1,explanation:"Mozart於1791年逝世時《安魂曲》尚未完成，後由Franz Xaver Süssmayr等人依既有材料續成。『全曲由Mozart親筆完成』是常見陷阱。"},
{year:"114",school:"高雄市國中教師聯甄",level:"國中",type:"choice",difficulty:"👹",topic:"古典時期",question:"Mozart《第40號交響曲》K.550的調性為何？",options:["D小調","G小調","C小調","E♭大調"],answer:1,explanation:"《第40號交響曲》K.550為G小調，是Mozart少數小調交響曲之一。教甄常將它與D小調《安魂曲》或其他作品調性互換。"},
{year:"114",school:"高雄市國中教師聯甄",level:"國中",type:"choice",difficulty:"中",topic:"古典時期",question:"Mozart《魔笛》最適合歸入哪一類型？",options:["義大利Opera Seria","德語Singspiel","法國Grand Opera","巴洛克Oratorio"],answer:1,explanation:"《魔笛》Die Zauberflöte（1791）是德語Singspiel的重要代表，具有歌唱段落與口語對白。不要因作品有華麗詠嘆調就誤判為Opera Seria。"},
{year:"114",school:"高雄市國中教師聯甄",level:"國中",type:"choice",difficulty:"👹",topic:"爵士樂史",question:"下列爵士樂人物與風格配對何者最適切？",options:["Charlie Parker—Bebop","Ornette Coleman—Swing","Louis Armstrong—Free Jazz","John Coltrane—Ragtime"],answer:0,explanation:"Charlie Parker是Bebop核心人物；Ornette Coleman與Free Jazz密切相關；Armstrong是早期爵士重要人物；Coltrane則與Hard Bop、Modal Jazz及後期前衛探索相關。"},
{year:"114",school:"高雄市國中教師聯甄",level:"國中",type:"choice",difficulty:"👹",topic:"音樂教育哲學",question:"David Elliott的Praxial Music Education最強調下列何者？",options:["音樂價值主要存在於作品形式的審美知覺","透過文化情境中的musing／musicing實踐發展musicianship","先完成所有樂理知識後才進行演奏","音樂教育應避免學生創作與即興"],answer:1,explanation:"Elliott的實踐音樂教育觀強調music as human activity，學生透過演奏、創作、即興等musicing，在具體文化情境中發展musicianship。可與Reimer早期較偏審美教育取向對照。"},
{year:"114",school:"高雄市國中教師聯甄",level:"國中",type:"choice",difficulty:"👹",topic:"終止式",question:"V–I雖形成正格終止，但終止I和弦最高聲部不是主音，通常應判為？",options:["PAC","IAC","Plagal Cadence","Deceptive Cadence"],answer:1,explanation:"完全正格終止PAC除V–I外，通常要求兩和弦根音位置且終止I最高聲部為主音；若正格終止成立但條件未全滿足，通常為IAC。"},
{year:"114",school:"高雄市國中教師聯甄",level:"國中",type:"choice",difficulty:"👹",topic:"跨文化音樂",question:"下列何者最能說明世界音樂教學中『不要以十二平均律套用所有文化』的原因？",options:["所有非西方音樂都沒有固定音高","不同文化可能具有不同調律、音階與音程組織，例如Gamelan的sléndro與pélog","十二平均律只適用於聲樂","世界音樂不能使用樂譜記錄"],answer:1,explanation:"不同文化有自身的音高組織與調律實踐。以Gamelan為例，sléndro、pélog不能簡單等同西洋十二平均律中的某組固定音級；比較時應先理解文化脈絡與實際聲響。"}
);