window.LOCAL_QUESTIONS = (window.LOCAL_QUESTIONS || []).concat([
{id:"RARE3-001",subject:"高中音樂",topic:"音樂史｜👹冷門魔王",level:"高鑑別度",year:"115",exam:"師大附中",source_type:"歷屆考點改寫",source_title:"115 師大附中音樂科",question:"下列音樂史概念依出現時間由早至晚，何者最合理？",option_a:"Sturm und Drang → castrato → idée fixe → verismo → aleatory",option_b:"castrato → Sturm und Drang → idée fixe → verismo → aleatory",option_c:"castrato → idée fixe → Sturm und Drang → aleatory → verismo",option_d:"Sturm und Drang → idée fixe → castrato → verismo → aleatory",answer:"B",explanation:"Castrato 盛行於巴洛克；Sturm und Drang 為18世紀；idée fixe 與白遼士19世紀浪漫主義相關；verismo 為19世紀末；aleatory 主要屬20世紀。"},
{id:"RARE3-002",subject:"高中音樂",topic:"中國音樂史｜👹冷門魔王",level:"高鑑別度",year:"110",exam:"中正高中",source_type:"歷屆非選考點改寫",source_title:"110 中正高中音樂科",question:"「新法密律」最直接與下列哪位人物相關？",option_a:"朱載堉",option_b:"京房",option_c:"蔡元定",option_d:"何承天",answer:"A",explanation:"明代朱載堉提出新法密律，以精密數學方法處理十二律等比關係，是中國律學史重要成果。"},
{id:"RARE3-003",subject:"高中音樂",topic:"臺灣客家音樂｜👹冷門魔王",level:"高鑑別度",year:"110",exam:"臺南女中",source_type:"歷屆非選考點改寫",source_title:"110 臺南女中音樂科",question:"下列哪一組最適合放在「臺灣客家山歌傳統曲調」的同一脈絡比較？",option_a:"老山歌、山歌仔、平板",option_b:"七字調、都馬調、哭調",option_c:"四空仔、五空仔、倍思",option_d:"江河水、二泉映月、寒春風曲",answer:"A",explanation:"老山歌、山歌仔、平板是客家山歌常見的重要曲調類型；其他選項分屬歌仔戲／南管或器樂等不同脈絡。"},
{id:"RARE3-004",subject:"高中音樂",topic:"臺灣原住民族｜👹冷門魔王",level:"高鑑別度",year:"110",exam:"臺南女中",source_type:"歷屆非選考點改寫",source_title:"110 臺南女中音樂科",question:"《kinakaian 母親的舌頭》最適合與下列哪位臺灣音樂人連結？",option_a:"阿爆 ABAO",option_b:"桑布伊",option_c:"舒米恩",option_d:"陳建年",answer:"A",explanation:"《kinakaian 母親的舌頭》與阿爆（ABAO）的排灣族語當代音樂創作脈絡密切相關，110臺南女中曾直接出題。"},
{id:"RARE3-005",subject:"高中音樂",topic:"20世紀音樂｜👹冷門魔王",level:"高鑑別度",year:"110",exam:"中正高中",source_type:"歷屆非選考點改寫",source_title:"110 中正高中音樂科",question:"關於 Serialism（序列主義），下列敘述何者最精確？",option_a:"只允許使用十二個半音且每音只能出現一次",option_b:"以預先組織的序列控制音樂材料，並可擴展至節奏、力度、音色等參數",option_c:"完全依演奏者即興決定所有音樂材料",option_d:"以自然泛音列作為唯一和聲來源",answer:"B",explanation:"序列主義源自音高序列的組織思維，後來可擴展到節奏、力度、音色等參數；不能簡化為十二音技法。"},
{id:"RARE3-006",subject:"高中音樂",topic:"音樂術語｜👹冷門魔王",level:"高鑑別度",year:"115",exam:"高雄高中聯招",source_type:"歷屆考點改寫",source_title:"115 高雄高中音樂科",question:"法文音樂術語 Berceuse 的意思最接近下列何者？",option_a:"船歌 Barcarolle",option_b:"輓歌 Elegy",option_c:"搖籃曲 Lullaby",option_d:"練聲曲 Vocalise",answer:"C",explanation:"Berceuse 是法文「搖籃曲」，教甄常以法、德、義文曲種與術語做細節辨識。"},
{id:"RARE3-007",subject:"高中音樂",topic:"節奏與拍號｜👹冷門魔王",level:"高鑑別度",year:"115",exam:"師大附中",source_type:"歷屆考點延伸",source_title:"115 師大附中音樂科",question:"下列哪一個節拍分組最能呈現 asymmetric meter（不對稱拍子）的概念？",option_a:"6/8＝3+3個八分音符",option_b:"9/8＝3+3+3個八分音符",option_c:"7/8＝2+2+3個八分音符",option_d:"12/8＝3+3+3+3個八分音符",answer:"C",explanation:"不對稱拍子的核心是不等長分組，例如7/8的2+2+3；115師大附中甚至以捷運進站音樂考此概念。"},
{id:"RARE3-008",subject:"高中音樂",topic:"浪漫時期｜👹冷門魔王",level:"高鑑別度",year:"115",exam:"師大附中",source_type:"歷屆考點延伸",source_title:"115 師大附中音樂科",question:"下列何者最適合說明 Berlioz 的 idée fixe？",option_a:"固定低音反覆形成的變奏基礎",option_b:"代表特定人物／觀念且在作品中反覆、變形出現的主題",option_c:"十二個半音依固定次序排列的音列",option_d:"巴洛克協奏曲中全體反覆段落",answer:"B",explanation:"idée fixe 最著名的例子是《幻想交響曲》中代表愛人的主題，會在各樂章依情境變形。"},
{id:"RARE3-009",subject:"高中音樂",topic:"臺灣音樂／當代｜👹冷門魔王",level:"高鑑別度",year:"115",exam:"新北高中聯招",source_type:"歷屆考點改寫",source_title:"115 新北高中音樂科",question:"若題目提到以卑南族古調為核心、融合現代民謠與世界音樂，並在2025年以《靠近 mudalrep》受到金曲獎關注，最可能指哪位音樂人？",option_a:"桑布伊",option_b:"阿爆",option_c:"舒米恩",option_d:"巴奈",answer:"A",explanation:"115新北高中把近期臺灣原住民族音樂與金曲獎資訊直接納入教甄，顯示命題也會碰當代文化資訊。"},
{id:"RARE3-010",subject:"高中音樂",topic:"歌劇與劇場｜👹冷門魔王",level:"高鑑別度",year:"115",exam:"教育部高中聯招",source_type:"歷屆填充考點改寫",source_title:"115 教育部高中聯招音樂科",question:"18世紀後歐洲各國喜歌劇發展中，德國與英國具「口說對白」特徵的代表類型依序為何？",option_a:"Singspiel、Ballad Opera",option_b:"Opera seria、Masque",option_c:"Zarzuela、Opéra comique",option_d:"Intermezzo、Vaudeville",answer:"A",explanation:"德國常稱 Singspiel，英國的重要類型為 Ballad Opera；115教育部高中聯招直接以填充題考此組合。"}
]);