// 114年中等教甄考點改寫：新北、臺南教育專業＋師大附中／臺南女中音樂
// 來源以阿摩保存之歷屆試卷為索引；題幹皆為考點改寫，避免逐字大量重製。
window.EXTRA_QUESTIONS = window.EXTRA_QUESTIONS || [];
window.EXTRA_QUESTIONS.push(
{year:"114",level:"教育專業",exam:"新北市國中教師聯合甄選",topic:"教育行政",difficulty:"中",question:"教育行政的混沌理論常用哪一概念說明：系統中微小的初始變化，可能經非線性互動後造成巨大結果？",options:["霍桑效應","蝴蝶效應","月暈效應","旁觀者效應"],answer:1,explanation:"混沌理論強調非線性、敏感依賴初始條件；『蝴蝶效應』是其代表性概念。",source:"阿摩｜114新北教育專業科（80題）"},
{year:"114",level:"教育專業",exam:"新北市國中教師聯合甄選",topic:"衝突管理",difficulty:"中",question:"Thomas 的衝突處理模式主要以哪兩個向度區分競爭、合作、妥協、逃避與順應等策略？",options:["權力與責任","果決與合作","正式與非正式","理性與情感"],answer:1,explanation:"Thomas 模式以 assertiveness（果決／堅持自身關切）與 cooperativeness（合作／關切他人）兩向度分類衝突處理方式。",source:"阿摩｜114新北教育專業科（80題）"},
{year:"114",level:"教育專業",exam:"臺南市國中正式教師聯合甄選",topic:"教育行政",difficulty:"易",question:"學校主管透過明確的績效交換與酬賞，引導教師完成既定目標，最符合哪一種領導？",options:["轉型領導","交易領導","分布式領導","道德領導"],answer:1,explanation:"交易領導強調領導者與成員之間以目標、績效與報酬進行交換。",source:"阿摩｜114臺南教育專業科（90題）"},
{year:"114",level:"教育專業",exam:"臺南市國中正式教師聯合甄選",topic:"教育行政",difficulty:"易",question:"霍桑效應對學校行政最典型的啟示是什麼？",options:["只有物理環境能決定績效","人知道自己受到關注時，表現可能改變","薪資是唯一工作動機","組織成員不受人際關係影響"],answer:1,explanation:"霍桑效應指出，被研究、被注意或感受到關注本身可能改變個體的行為與績效。",source:"阿摩｜114臺南教育專業科（90題）"},
{year:"114",level:"教育專業",exam:"臺南市國中正式教師聯合甄選",topic:"融合教育",difficulty:"中",question:"對聽覺障礙且具有資優潛能的學生，哪一種支持最符合『同時降低溝通障礙並發展優勢能力』的原則？",options:["只增加大量口語演說訓練","提供字幕、視覺化資訊與可展現優勢的創作任務","取消所有高層次學習任務","只安排紙筆測驗以維持公平"],answer:1,explanation:"雙重特殊需求學生應同時獲得障礙支持與優勢發展；視覺化、字幕、書面指令可提升可近性，創作任務則能發展其潛能。",source:"阿摩｜114臺南教育專業科（90題）"},
{year:"114",level:"教育專業",exam:"臺南市國中正式教師聯合甄選",topic:"特殊教育",difficulty:"中",question:"學生有數學學習障礙，對抽象數學語詞與運算概念都感到困難。下列何者較符合多重表徵與情境化教學？",options:["每日大量抄寫算式","圖像語詞卡、實物操作並結合情境故事","只增加限時口算競賽","要求背誦所有定義後再開始解題"],answer:1,explanation:"圖像、實物與情境文本能把抽象語詞連結到具體概念，有助於建立語意與運算概念間的連結。",source:"阿摩｜114臺南教育專業科（90題）"},
{year:"114",level:"高中音樂",exam:"師大附中正式教師甄選",topic:"世界音樂",difficulty:"中",question:"下列哪一組『音樂／樂器—主要文化地區』配對正確？",options:["Pansori—日本","Komun'go—韓國","Didgeridoo—印度","Rumba—阿根廷"],answer:1,explanation:"玄琴 Komun'go（geomungo）是韓國傳統絃樂器；Pansori 亦屬韓國，Didgeridoo 主要與澳洲原住民族文化相關，Rumba 則源自古巴。",source:"阿摩｜114師大附中音樂科（23題）"},
{year:"114",level:"高中音樂",exam:"師大附中正式教師甄選",topic:"世界音樂",difficulty:"中",question:"Didgeridoo 最主要與哪一地區的原住民族音樂文化相關？",options:["澳洲","韓國","古巴","西班牙"],answer:0,explanation:"Didgeridoo 是澳洲原住民族傳統吹奏樂器之一。",source:"阿摩｜114師大附中音樂科（23題）"},
{year:"114",level:"高中音樂",exam:"師大附中正式教師甄選",topic:"藝術才能課綱",difficulty:"難",question:"藝術才能資賦優異專長領域課程的設計，最不應被理解成下列哪一種做法？",options:["兼顧專長深化與高層次思考","依學生專長需求安排個別化學習","只以單一術科技巧反覆訓練取代整體課程目標","連結展演、知識脈絡、美感與創意應用"],answer:2,explanation:"藝術才能資優課程不只是術科技巧訓練，而應兼顧專業能力、思考、文化美感、創作與應用等面向。",source:"阿摩｜114師大附中音樂科（23題）"},
{year:"114",level:"高中音樂",exam:"臺南女中教師甄選",topic:"移調樂器",difficulty:"難",question:"A 調單簧管看到記譜 C 時，實際發出的音高為何？",options:["C","A","E♭","D"],answer:1,explanation:"A 調單簧管是移調樂器，記譜 C 實際發出 A，實音比記譜音低小三度。",source:"阿摩｜114臺南女中音樂科（31題非選）考點改寫"},
{year:"114",level:"高中音樂",exam:"臺南女中教師甄選",topic:"移調樂器",difficulty:"難",question:"若要讓 A 調單簧管發出實音 C，通常應記譜為哪一音？",options:["A","B♭","C","E♭"],answer:3,explanation:"A 調單簧管的實音比記譜低小三度，因此欲得到實音 C，記譜需寫高小三度的 E♭。",source:"阿摩｜114臺南女中音樂科（31題非選）考點改寫"},
{year:"114",level:"高中音樂",exam:"臺南女中教師甄選",topic:"速度計算",difficulty:"中",question:"若一段音樂共 48 拍，實際演奏 24 秒，則以四分音符為一拍時計算出的速度約為多少 BPM？",options:["60","90","120","144"],answer:2,explanation:"48 拍 ÷ 24 秒 = 每秒 2 拍；乘以 60 秒即 120 BPM。此題延伸自臺南女中要求依拍數與時間推算速度的考點。",source:"阿摩｜114臺南女中音樂科（31題非選）考點改寫"}
);