window.LOCAL_QUESTIONS = window.LOCAL_QUESTIONS || [];
window.LOCAL_QUESTIONS.push(
{id:'RARE6-001',subject:'高中音樂',topic:'臺灣音樂',level:'魔王',year:'113',exam:'教育部高中聯招',question:'歌仔戲中有「萬能唱腔」之稱、早期甚至可能一劇從頭唱到尾的核心曲調為何？',option_a:'七字調',option_b:'都馬調',option_c:'哭調',option_d:'江湖調',answer:'A',explanation:'七字調源自民間歌謠性傳統，是歌仔戲最重要且使用頻繁的基本曲調之一，113教育部聯招以非選題直接考此考點。',source_type:'歷屆非選考點改寫',source_title:'113教育部受託辦理公立高中教師甄選音樂科'},
{id:'RARE6-002',subject:'高中音樂',topic:'臺灣音樂',level:'魔王',year:'113',exam:'教育部高中聯招',question:'布農族《祈禱小米豐收歌》的族語名稱為何？',option_a:'Pasibutbut',option_b:'Pasiwali',option_c:'Malikoda',option_d:'Pakelabi',answer:'A',explanation:'Pasibutbut 是布農族重要祭儀歌唱，常以複音與泛音般的聲響效果受到討論；113教育部聯招要求直接寫出族語原名。',source_type:'歷屆非選考點改寫',source_title:'113教育部受託辦理公立高中教師甄選音樂科'},
{id:'RARE6-003',subject:'高中音樂',topic:'中國音樂',level:'魔王',year:'112',exam:'教育部高中聯招',question:'中國傳統樂曲《百鳥朝鳳》最具代表性的獨奏樂器為何？',option_a:'嗩吶',option_b:'笙',option_c:'二胡',option_d:'琵琶',answer:'A',explanation:'《百鳥朝鳳》為著名嗩吶獨奏曲，以模仿鳥鳴等技巧著稱。112教育部高中聯招直接以填充方式考樂器。',source_type:'歷屆非選考點改寫',source_title:'112教育部高中教師甄選音樂科'},
{id:'RARE6-004',subject:'高中音樂',topic:'20世紀音樂',level:'魔王',year:'112',exam:'教育部高中聯招',question:'《網路交響曲第一號：英雄》(Internet Symphony No. 1 “Eroica”) 是由哪位作曲家受 YouTube 委託創作？',option_a:'Tan Dun 譚盾',option_b:'Bright Sheng 盛宗亮',option_c:'Chen Yi 陳怡',option_d:'Unsuk Chin 陳銀淑',answer:'A',explanation:'譚盾為 YouTube Symphony Orchestra 創作 Internet Symphony No.1 “Eroica”。112教育部聯招直接考作曲家。',source_type:'歷屆非選考點改寫',source_title:'112教育部高中教師甄選音樂科'},
{id:'RARE6-005',subject:'高中音樂',topic:'民族音樂',level:'魔王',year:'111',exam:'中壢高中',question:'下列哪一組最符合烏克蘭／俄羅斯傳統樂器的範疇？',option_a:'Bandura、Balalaika、Domra、Gusli',option_b:'Kora、Mbira、Balafon、Djembe',option_c:'Shamisen、Koto、Shakuhachi、Biwa',option_d:'Sitar、Sarod、Tabla、Bansuri',answer:'A',explanation:'Bandura 與烏克蘭文化密切相關；Balalaika、Domra、Gusli 等則常見於俄羅斯及東歐傳統樂器脈絡。111中壢高中以多項選擇形式考此類冷門世界樂器。',source_type:'歷屆考點改寫',source_title:'111中壢高中教師甄選音樂科'},
{id:'RARE6-006',subject:'高中音樂',topic:'西洋音樂史',level:'魔王',year:'111',exam:'中壢高中',question:'《Neue Zeitschrift für Musik》（新音樂雜誌）與下列哪位作曲家／評論家關係最密切？',option_a:'Robert Schumann',option_b:'Hector Berlioz',option_c:'Franz Liszt',option_d:'Richard Wagner',answer:'A',explanation:'舒曼於1834年參與創辦 Neue Zeitschrift für Musik，並以評論推介同時代與新進作曲家。111中壢高中直接列為名詞解釋。',source_type:'名詞考點轉辨識題',source_title:'111中壢高中教師甄選音樂科'},
{id:'RARE6-007',subject:'高中音樂',topic:'原住民族音樂',level:'魔王',year:'111',exam:'中壢高中',question:'下列臺灣原住民族祭典／樂器配對何者正確？',option_a:'賽夏族—巴斯達隘—臀鈴',option_b:'布農族—豐年祭—臀鈴',option_c:'鄒族—戰祭—杵音',option_d:'達悟族—頭髮舞—口簧琴',answer:'A',explanation:'賽夏族矮靈祭（巴斯達隘）與臀鈴具有代表性連結。此類族群、祭儀、樂器三向配對是教甄常見高鑑別題型。',source_type:'歷屆考點改寫',source_title:'111中壢高中教師甄選音樂科'},
{id:'RARE6-008',subject:'高中音樂',topic:'音樂劇',level:'魔王',year:'111',exam:'彰化女中',question:'音樂劇唱法中，較接近古典美聲傳統、常運用頭腔共鳴且音色較清亮的唱法稱為？',option_a:'Legit',option_b:'Belt',option_c:'Growl',option_d:'Sprechstimme',answer:'A',explanation:'Legit 保留較多古典／美聲技術特徵；Belt 則偏胸聲主導、明亮強烈。111彰化女中曾細考音樂劇唱腔分類。',source_type:'歷屆考點改寫',source_title:'111彰化女中音樂科教師甄選'},
{id:'RARE6-009',subject:'高中音樂',topic:'西洋音樂史',level:'魔王',year:'112',exam:'臺中一中',question:'下列何者不是 Stravinsky《春之祭》最適當的音樂史描述？',option_a:'作品直接引用葛雷果聖歌《Dies irae》作為核心素材',option_b:'首演與20世紀現代舞及音樂史密切相關',option_c:'節奏與重音組織具有高度創新性',option_d:'與俄羅斯原始主義色彩密切相關',answer:'A',explanation:'《春之祭》並非以葛雷果聖歌《Dies irae》作為核心引用素材。112臺中一中以此類作品細節辨誤拉高鑑別度。',source_type:'歷屆考點改寫',source_title:'112臺中一中教師甄選音樂科'},
{id:'RARE6-010',subject:'高中音樂',topic:'音樂與媒體',level:'魔王',year:'111',exam:'中壢高中',question:'下列電影與古典音樂配對何者最可疑／不正確？',option_a:'《阿甘正傳》—Schubert〈Erlkönig〉',option_b:'《2001太空漫遊》—R. Strauss《Also sprach Zarathustra》',option_c:'《沉默的羔羊》—Bach《Goldberg Variations》',option_d:'《戰地琴人》—Chopin 夜曲',answer:'A',explanation:'111中壢高中以電影配樂與既有古典音樂的配對出題；這類題要求跨越音樂史與影視文化記憶。',source_type:'歷屆考點改寫',source_title:'111中壢高中教師甄選音樂科'}
);