window.LOCAL_QUESTIONS = [
  ...(Array.isArray(window.LOCAL_QUESTIONS) ? window.LOCAL_QUESTIONS : []),

  {id:"OFF111-HS-001",subject:"高中音樂",topic:"臺灣音樂",level:"理解",year:"111",exam:"師大附中高中音樂科",source_type:"官方原題考點改寫",question:"1960年代臺灣『民歌採集運動』中，與史惟亮共同推動、對保存臺灣傳統音樂有重要貢獻的音樂家是誰？",option_a:"郭芝苑",option_b:"呂泉生",option_c:"許常惠",option_d:"賴德和",answer:"C",explanation:"許常惠與史惟亮共同推動民歌採集運動，進行大量田野採集與傳統音樂保存工作。",source_title:"師大附中111學年度高中音樂科教師甄選試題與參考答案",source_url:"https://www.hs.ntnu.edu.tw/academic/content?a=T0RESU5ERTBORFUwT1RZPXdZak13VWpOeDRrVGludGVseQ%3D%3D&cat=T0RESU1qVXlNVGd3TWpVPXhrak55SWpOeElrVGludGVseQ%3D%3D",tags:"臺灣音樂;民歌採集;許常惠"},
  {id:"OFF111-HS-002",subject:"高中音樂",topic:"世界音樂",level:"基礎",year:"111",exam:"師大附中高中音樂科",source_type:"官方原題考點改寫",question:"韓國傳統說唱藝術 Pansori（盤索里）屬於哪一國家的代表性民俗音樂？",option_a:"日本",option_b:"中國",option_c:"韓國",option_d:"越南",answer:"C",explanation:"Pansori 是韓國重要的傳統敘事說唱藝術，典型編制為一位歌者與一位鼓手。",source_title:"師大附中111學年度高中音樂科教師甄選試題與參考答案",source_url:"https://www.hs.ntnu.edu.tw/academic/content?a=T0RESU5ERTBORFUwT1RZPXdZak13VWpOeDRrVGludGVseQ%3D%3D&cat=T0RESU1qVXlNVGd3TWpVPXhrak55SWpOeElrVGludGVseQ%3D%3D",tags:"世界音樂;Pansori;韓國"},
  {id:"OFF111-HS-003",subject:"高中音樂",topic:"世界音樂",level:"理解",year:"111",exam:"師大附中高中音樂科",source_type:"官方原題考點改寫",question:"呼麥（Khoomei）最常被視為哪一地區的代表性唱腔？",option_a:"蒙古",option_b:"葡萄牙",option_c:"印度",option_d:"墨西哥",answer:"A",explanation:"呼麥與蒙古及圖瓦等中亞、北亞草原文化關係密切，常以泛音唱法形成多聲部聽覺效果。",source_title:"師大附中111學年度高中音樂科教師甄選試題與參考答案",source_url:"https://www.hs.ntnu.edu.tw/academic/content?a=T0RESU5ERTBORFUwT1RZPXdZak13VWpOeDRrVGludGVseQ%3D%3D&cat=T0RESU1qVXlNVGd3TWpVPXhrak55SWpOeElrVGludGVseQ%3D%3D",tags:"世界音樂;呼麥;Khoomei"},
  {id:"OFF111-HS-004",subject:"高中音樂",topic:"樂器學",level:"進階",year:"111",exam:"師大附中高中音樂科",source_type:"官方原題考點改寫",question:"依 Hornbostel-Sachs 樂器分類法，口簧琴（Jew's harp）通常屬於哪一類？",option_a:"氣鳴樂器",option_b:"弦鳴樂器",option_c:"體鳴樂器",option_d:"膜鳴樂器",answer:"C",explanation:"口簧琴主要由樂器本體彈片振動發聲，因此歸於體鳴樂器。",source_title:"師大附中111學年度高中音樂科教師甄選試題與參考答案",source_url:"https://www.hs.ntnu.edu.tw/academic/content?a=T0RESU5ERTBORFUwT1RZPXdZak13VWpOeDRrVGludGVseQ%3D%3D&cat=T0RESU1qVXlNVGd3TWpVPXhrak55SWpOeElrVGludGVseQ%3D%3D",tags:"Hornbostel-Sachs;口簧琴;樂器分類"},
  {id:"OFF111-HS-005",subject:"高中音樂",topic:"巴洛克音樂",level:"理解",year:"111",exam:"師大附中高中音樂科",source_type:"官方原題考點改寫",question:"將 Allemande、Courante、Sarabande、Gigue 四種舞曲逐漸固定為巴洛克組曲核心順序的重要作曲家是誰？",option_a:"Froberger",option_b:"Monteverdi",option_c:"Corelli",option_d:"Scarlatti",answer:"A",explanation:"Johann Jakob Froberger 對鍵盤組曲舞曲順序的固定化具有重要影響。",source_title:"師大附中111學年度高中音樂科教師甄選試題與參考答案",source_url:"https://www.hs.ntnu.edu.tw/academic/content?a=T0RESU5ERTBORFUwT1RZPXdZak13VWpOeDRrVGludGVseQ%3D%3D&cat=T0RESU1qVXlNVGd3TWpVPXhrak55SWpOeElrVGludGVseQ%3D%3D",tags:"巴洛克;組曲;Froberger"},

  {id:"OFF113-HS-001",subject:"高中音樂",topic:"和聲",level:"進階",year:"113",exam:"師大附中高中音樂科",source_type:"官方原題考點改寫",question:"拿坡里六和弦（Neapolitan sixth）最典型的結構為何？",option_a:"升高導音三和弦原位",option_b:"降二級大三和弦第一轉位",option_c:"屬七和弦第三轉位",option_d:"增六和弦原位",answer:"B",explanation:"拿坡里六和弦通常是建立在降二級上的大三和弦，並以第一轉位最為典型。",source_title:"師大附中113學年度高中音樂科教師甄選試題與參考解答",source_url:"https://www.hs.ntnu.edu.tw/academic/content?a=T0RESU16Y3dOek15TURrPTJNVE94RXpOeDRrVGludGVseQ%3D%3D&c=T0RESU5ESTJORFF4TURBPTFnVE14TWpOeElrVGludGVseQ%3D%3D&cat=T0RESTEyNTIxODAyNTk2MjI2MVRDaW50ZWx5",tags:"和聲;拿坡里六和弦;Neapolitan"},
  {id:"OFF113-HS-002",subject:"高中音樂",topic:"曲式",level:"理解",year:"113",exam:"師大附中高中音樂科",source_type:"官方原題考點改寫",question:"莫札特《A大調鋼琴奏鳴曲》K.331 第一樂章採用的主要曲式是什麼？",option_a:"奏鳴曲式",option_b:"主題與變奏",option_c:"輪旋曲式",option_d:"賦格",answer:"B",explanation:"K.331 第一樂章為主題與變奏，第三樂章才是著名的〈土耳其進行曲〉。",source_title:"師大附中113學年度高中音樂科教師甄選試題與參考解答",source_url:"https://www.hs.ntnu.edu.tw/academic/content?a=T0RESU16Y3dOek15TURrPTJNVE94RXpOeDRrVGludGVseQ%3D%3D&c=T0RESU5ESTJORFF4TURBPTFnVE14TWpOeElrVGludGVseQ%3D%3D&cat=T0RESTEyNTIxODAyNTk2MjI2MVRDaW50ZWx5",tags:"莫札特;K331;主題與變奏"},
  {id:"OFF113-HS-003",subject:"高中音樂",topic:"電影配樂",level:"理解",year:"113",exam:"師大附中高中音樂科",source_type:"官方原題考點改寫",question:"電影《海上鋼琴師》（The Legend of 1900）的配樂作曲家是誰？",option_a:"Ennio Morricone",option_b:"John Williams",option_c:"Hans Zimmer",option_d:"Philip Glass",answer:"A",explanation:"《海上鋼琴師》的配樂由義大利作曲家 Ennio Morricone 創作。",source_title:"師大附中113學年度高中音樂科教師甄選試題與參考解答",source_url:"https://www.hs.ntnu.edu.tw/academic/content?a=T0RESU16Y3dOek15TURrPTJNVE94RXpOeDRrVGludGVseQ%3D%3D&c=T0RESU5ESTJORFF4TURBPTFnVE14TWpOeElrVGludGVseQ%3D%3D&cat=T0RESTEyNTIxODAyNTk2MjI2MVRDaW50ZWx5",tags:"電影配樂;Morricone;海上鋼琴師"},
  {id:"OFF113-HS-004",subject:"高中音樂",topic:"中國音樂史",level:"理解",year:"113",exam:"師大附中高中音樂科",source_type:"官方原題考點改寫",question:"明代朱載堉提出十二平均律理論的重要著作為何？",option_a:"《聲無哀樂論》",option_b:"《律呂精義》",option_c:"《白石道人歌曲》",option_d:"《溪山琴況》",answer:"B",explanation:"朱載堉在《律呂精義》等著作中系統闡述新法密率，對十二平均律理論發展影響深遠。",source_title:"師大附中113學年度高中音樂科教師甄選試題與參考解答",source_url:"https://www.hs.ntnu.edu.tw/academic/content?a=T0RESU16Y3dOek15TURrPTJNVE94RXpOeDRrVGludGVseQ%3D%3D&c=T0RESU5ESTJORFF4TURBPTFnVE14TWpOeElrVGludGVseQ%3D%3D&cat=T0RESTEyNTIxODAyNTk2MjI2MVRDaW50ZWx5",tags:"中國音樂史;朱載堉;律呂精義"},

  {id:"OFF114-JH-001",subject:"國中音樂",topic:"世界音樂",level:"基礎",year:"114",exam:"師大附中國中音樂科",source_type:"官方原題考點改寫",question:"玄琴（Komun'go）主要與哪一國家的傳統音樂文化相關？",option_a:"韓國",option_b:"日本",option_c:"印度",option_d:"印尼",answer:"A",explanation:"玄琴是韓國傳統絃樂器之一。",source_title:"師大附中114學年度國中音樂科教師甄選試題",source_url:"https://www.hs.ntnu.edu.tw/music/content?a=T0RESVRtcG5NVTFxUVhoT1ZGazk0bGthTnBYVTY1RWUwc0dWaW50ZWx5",tags:"世界音樂;韓國;玄琴"},
  {id:"OFF114-JH-002",subject:"國中音樂",topic:"歌劇",level:"理解",year:"114",exam:"師大附中國中音樂科",source_type:"官方原題考點改寫",question:"下列哪一部歌劇通常不歸類為德語 Singspiel？",option_a:"《魔笛》",option_b:"《後宮誘逃》",option_c:"《自由射手》",option_d:"《莎樂美》",answer:"D",explanation:"《莎樂美》為 Richard Strauss 的歌劇；《魔笛》、《後宮誘逃》與《自由射手》常與德語 Singspiel 傳統相連。",source_title:"師大附中114學年度國中音樂科教師甄選試題",source_url:"https://www.hs.ntnu.edu.tw/music/content?a=T0RESVRtcG5NVTFxUVhoT1ZGazk0bGthTnBYVTY1RWUwc0dWaW50ZWx5",tags:"歌劇;Singspiel;莎樂美"},
  {id:"OFF114-JH-003",subject:"國中音樂",topic:"二十世紀音樂",level:"理解",year:"114",exam:"師大附中國中音樂科",source_type:"官方原題考點改寫",question:"《Mode de valeurs et d'intensités》（時值與力度的模式）是哪位作曲家的作品？",option_a:"梅湘",option_b:"史托克豪森",option_c:"薛費爾",option_d:"薩悌",answer:"A",explanation:"《Mode de valeurs et d'intensités》為 Olivier Messiaen 的重要作品，常被討論為全面序列主義發展的前驅。",source_title:"師大附中114學年度國中音樂科教師甄選試題",source_url:"https://www.hs.ntnu.edu.tw/music/content?a=T0RESVRtcG5NVTFxUVhoT1ZGazk0bGthTnBYVTY1RWUwc0dWaW50ZWx5",tags:"梅湘;序列音樂;二十世紀"},
  {id:"OFF114-JH-004",subject:"國中音樂",topic:"演奏法與術語",level:"理解",year:"114",exam:"師大附中國中音樂科",source_type:"官方原題考點改寫",question:"下列何者主要屬於裝飾音，而不是 articulation（奏法／發音法）？",option_a:"Portato",option_b:"Marcato",option_c:"Appoggiatura",option_d:"Spiccato",answer:"C",explanation:"Appoggiatura 是倚音，屬裝飾音；Portato、Marcato、Spiccato 則屬常見奏法或發音表現。",source_title:"師大附中114學年度國中音樂科教師甄選試題",source_url:"https://www.hs.ntnu.edu.tw/music/content?a=T0RESVRtcG5NVTFxUVhoT1ZGazk0bGthTnBYVTY1RWUwc0dWaW50ZWx5",tags:"articulation;Appoggiatura;演奏術語"},

  {id:"OFF115-JH-001",subject:"國中音樂",topic:"音樂教學法",level:"基礎",year:"115",exam:"師大附中國中音樂科",source_type:"官方原題考點改寫",question:"以歌唱、傳統民謠、首調唱名與手勢建立音高概念的教學法，最符合哪一位音樂教育家的理念？",option_a:"Dalcroze",option_b:"Orff",option_c:"Kodály",option_d:"Suzuki",answer:"C",explanation:"Kodály 教學法重視歌唱、優質民謠、首調唱名與手勢，並由內在聽覺建立音樂讀寫能力。",source_title:"師大附中115學年度國中音樂科教師甄選官方試題",source_url:"https://www.hs.ntnu.edu.tw/academic/content?a=T0RESU16TTJOell4T0RjPTRZak4wY3pOeDRrVGludGVseQ%3D%3D&c=T0RESU5ESTJORFF4TURBPTFnVE14TWpOeElrVGludGVseQ%3D%3D&cat=T0RESTEyNTIxODAyNTk2MjI2MVRDaW50ZWx5",tags:"Kodaly;音樂教學法;手勢"},
  {id:"OFF115-JH-002",subject:"國中音樂",topic:"世界音樂",level:"基礎",year:"115",exam:"師大附中國中音樂科",source_type:"官方原題考點改寫",question:"Reggae（雷鬼）音樂的主要發源地是哪一個國家？",option_a:"古巴",option_b:"牙買加",option_c:"巴西",option_d:"葡萄牙",answer:"B",explanation:"Reggae 起源並發展於牙買加，後來成為全球重要流行音樂類型。",source_title:"師大附中115學年度國中音樂科教師甄選官方試題",source_url:"https://www.hs.ntnu.edu.tw/academic/content?a=T0RESU16TTJOell4T0RjPTRZak4wY3pOeDRrVGludGVseQ%3D%3D&c=T0RESU5ESTJORFF4TURBPTFnVE14TWpOeElrVGludGVseQ%3D%3D&cat=T0RESTEyNTIxODAyNTk2MjI2MVRDaW50ZWx5",tags:"Reggae;牙買加;世界音樂"},
  {id:"OFF115-JH-003",subject:"教育專業",topic:"社會情緒學習",level:"理解",year:"115",exam:"師大附中國中音樂科",source_type:"官方原題考點改寫",question:"下列何者不是 CASEL 所提出的社會情緒學習（SEL）五大核心能力？",option_a:"自主行動",option_b:"社會覺察",option_c:"人際技巧",option_d:"負責任的決定",answer:"A",explanation:"CASEL 五大核心包括自我覺察、自我管理、社會覺察、人際技巧、負責任的決定。",source_title:"師大附中115學年度國中音樂科教師甄選官方試題",source_url:"https://www.hs.ntnu.edu.tw/academic/content?a=T0RESU16TTJOell4T0RjPTRZak4wY3pOeDRrVGludGVseQ%3D%3D&c=T0RESU5ESTJORFF4TURBPTFnVE14TWpOeElrVGludGVseQ%3D%3D&cat=T0RESTEyNTIxODAyNTk2MjI2MVRDaW50ZWx5",tags:"SEL;CASEL;教育專業"},
  {id:"OFF115-JH-004",subject:"國中音樂",topic:"臺灣原住民族音樂",level:"理解",year:"115",exam:"師大附中國中音樂科",source_type:"官方原題考點改寫",question:"臺灣原住民族樂器『臀鈴』最具代表性地與哪一族群文化相關？",option_a:"邵族",option_b:"賽夏族",option_c:"布農族",option_d:"阿美族",answer:"B",explanation:"臀鈴是賽夏族祭儀中具有代表性的響器之一。",source_title:"師大附中115學年度國中音樂科教師甄選官方試題",source_url:"https://www.hs.ntnu.edu.tw/academic/content?a=T0RESU16TTJOell4T0RjPTRZak4wY3pOeDRrVGludGVseQ%3D%3D&c=T0RESU5ESTJORFF4TURBPTFnVE14TWpOeElrVGludGVseQ%3D%3D&cat=T0RESTEyNTIxODAyNTk2MjI2MVRDaW50ZWx5",tags:"原住民族音樂;賽夏族;臀鈴"},
  {id:"OFF115-JH-005",subject:"國中音樂",topic:"世界音樂",level:"理解",year:"115",exam:"師大附中國中音樂科",source_type:"官方原題考點改寫",question:"《冰雪奇緣2》〈Into the Unknown〉中反覆出現的高音呼喊，常被指出運用了哪一種北歐傳統唱腔技巧？",option_a:"Kulning",option_b:"Bel canto",option_c:"Khoomei",option_d:"Yodeling",answer:"A",explanation:"Kulning 是斯堪地那維亞地區傳統的高亢呼喊式唱法，常用於遠距離傳聲。",source_title:"師大附中115學年度國中音樂科教師甄選官方試題",source_url:"https://www.hs.ntnu.edu.tw/academic/content?a=T0RESU16TTJOell4T0RjPTRZak4wY3pOeDRrVGludGVseQ%3D%3D&c=T0RESU5ESTJORFF4TURBPTFnVE14TWpOeElrVGludGVseQ%3D%3D&cat=T0RESTEyNTIxODAyNTk2MjI2MVRDaW50ZWx5",tags:"Kulning;世界音樂;北歐"},
  {id:"OFF115-JH-006",subject:"國中音樂",topic:"世界音樂",level:"理解",year:"115",exam:"師大附中國中音樂科",source_type:"官方原題考點改寫",question:"關於 Pansori（盤索里）的典型表演形式，下列何者最正確？",option_a:"一位說唱者搭配一位鼓手",option_b:"大型混聲合唱團搭配管弦樂",option_c:"四位舞者搭配三味線",option_d:"兩位歌者搭配甘美朗",answer:"A",explanation:"盤索里是韓國傳統敘事說唱藝術，典型形式為一位歌者與一位鼓手共同演出。",source_title:"師大附中115學年度國中音樂科教師甄選官方試題",source_url:"https://www.hs.ntnu.edu.tw/academic/content?a=T0RESU16TTJOell4T0RjPTRZak4wY3pOeDRrVGludGVseQ%3D%3D&c=T0RESU5ESTJORFF4TURBPTFnVE14TWpOeElrVGludGVseQ%3D%3D&cat=T0RESTEyNTIxODAyNTk2MjI2MVRDaW50ZWx5",tags:"Pansori;韓國;世界音樂"}
];