// 114 桃園市國中教師聯甄音樂科｜高鑑別題第一批
window.QUESTIONS = window.QUESTIONS || [];
window.QUESTIONS.push(
{year:"114",school:"桃園市國中教師聯甄",level:"國中",type:"choice",difficulty:"👹",topic:"音樂教育",question:"學生在沒有樂譜時，仍能在心中聽見、理解並組織音高與節奏，此能力最接近 Gordon 音樂學習理論中的哪一概念？",options:["Eurhythmics","Audiation","Elemental Music","Fixed-do"],answer:1,explanation:"Gordon 的 Audiation 常譯為音樂語感、音樂聽想或內在聽覺思考，重點不是外在聲音仍在播放，而是能在心中理解、預期與組織音樂。教甄常把它和 Dalcroze 律動、Kodály 視唱、Orff 即興混在一起考。"},
{year:"114",school:"桃園市國中教師聯甄",level:"國中",type:"choice",difficulty:"👹",topic:"音樂科技",question:"下列何者主要不是以 AI 音樂生成／作曲為核心定位的工具？",options:["Suno","AIVA","Mureka","Grok"],answer:3,explanation:"Suno、AIVA、Mureka皆可用於AI音樂生成或創作；Grok主要是通用型生成式AI助理。考試重點不是背品牌，而是辨識工具的核心功能。"},
{year:"114",school:"桃園市國中教師聯甄",level:"國中",type:"choice",difficulty:"👹",topic:"中國音樂",question:"關於工尺譜，下列何者最不恰當？",options:["屬傳統漢字譜系統","可配合板眼標示節奏","常見於戲曲、器樂等傳統音樂","本質上固定等同西洋十二平均律的絕對音高記譜"],answer:3,explanation:"工尺譜以工、尺、上等譜字記錄音高關係，實際音高與宮調、樂種、傳承脈絡有關，不能簡化為固定等同十二平均律的絕對音高系統。板眼則是傳統節拍／節奏組織的重要概念。"},
{year:"114",school:"桃園市國中教師聯甄",level:"國中",type:"choice",difficulty:"👹",topic:"歌劇",question:"關於 Puccini《Turandot》，下列何者最可能是錯誤敘述？",options:["作曲家逝世時作品尚未完全完成","作品引用中國民謠〈茉莉花〉素材","作品中可見反覆出現的主題性材料","全劇主要依巴洛克式封閉編號歌劇原則構成"],answer:3,explanation:"《Turandot》是20世紀初歌劇，Puccini逝世時未完成，後由Alfano等補成；作品亦使用〈茉莉花〉素材。把它說成以巴洛克／古典時期典型的封閉式 Number Opera 為主要結構原則，過度簡化。"},
{year:"114",school:"桃園市國中教師聯甄",level:"國中",type:"choice",difficulty:"👹",topic:"臺灣音樂劇",question:"下列臺灣原創音樂劇與文化議題的配對，何者最值得警覺可能被命題者設為錯誤陷阱？",options:["《勸世三姊妹》—牽亡歌陣／喪葬文化","《木蘭少女》—性別角色再詮釋","《釧兒》—以客語為主要語言並聚焦礦業文化","臺灣音樂劇可融合地方語言、歷史與當代議題"],answer:2,explanation:"《釧兒》與臺灣礦業、地方生命記憶相關，但不能因此直接推成『以客語為主要演唱語言』。教甄很愛把作品的地域題材、語言與文化背景交叉偷換。"},
{year:"114",school:"桃園市國中教師聯甄",level:"國中",type:"choice",difficulty:"👹",topic:"世界音樂",question:"關於印度 Sitar，下列何者錯誤？",options:["與北印度 Hindustani 音樂關係密切","具有共鳴弦等構造特色","Ravi Shankar 是重要演奏家","是南印度 Carnatic 音樂最具代表性的主要彈撥樂器"],answer:3,explanation:"Sitar主要與北印度Hindustani傳統相關。Ravi Shankar使其在全球廣為人知，George Harrison亦曾向其學習。把Sitar說成南印度Carnatic傳統的代表樂器，是常見陷阱。"},
{year:"114",school:"桃園市國中教師聯甄",level:"國中",type:"choice",difficulty:"中",topic:"西洋音樂史",question:"下列音樂體裁依歷史發展由早至晚排列，何者最合理？",options:["Motet→Concerto Grosso→String Quartet→Symphonic Poem","Concerto Grosso→Motet→Symphonic Poem→String Quartet","String Quartet→Motet→Concerto Grosso→Symphonic Poem","Motet→String Quartet→Concerto Grosso→Symphonic Poem"],answer:0,explanation:"Motet可追溯至中世紀；Concerto Grosso盛於巴洛克；String Quartet在古典時期成熟；Symphonic Poem則是19世紀浪漫時期的重要管弦樂體裁。"},
{year:"114",school:"桃園市國中教師聯甄",level:"國中",type:"choice",difficulty:"👹",topic:"臺灣流行音樂",question:"1970年代末，以商業唱片與比賽機制推動臺灣校園民歌創作的重要獎項是？",options:["金音獎","金曲獎","金韻獎","金鐘獎"],answer:2,explanation:"新格唱片推動的金韻獎是校園民歌發展的重要制度與平台之一。不要和今日鼓勵創作型音樂的金音創作獎，或金曲獎混淆。"},
{year:"114",school:"桃園市國中教師聯甄",level:"國中",type:"choice",difficulty:"中",topic:"藝術歌曲",question:"下列詩人與歌曲配對何者正確？",options:["Schubert〈Erlkönig〉—Goethe","Mendelssohn〈Auf Flügeln des Gesanges〉—Schiller","Schubert〈Die Forelle〉—Heine","Schubert《Winterreise》—Schubart"],answer:0,explanation:"〈魔王〉文本為Goethe；〈乘著歌聲的翅膀〉詩為Heine；〈鱒魚〉詩為Schubart；《冬之旅》詩為Wilhelm Müller。這組人名是教甄常見配對陷阱。"},
{year:"114",school:"桃園市國中教師聯甄",level:"國中",type:"choice",difficulty:"👹",topic:"流行音樂",question:"下列何者不是 The Beatles 的作品？",options:["Let It Be","Yellow Submarine","We Will Rock You","Hey Jude"],answer:2,explanation:"〈We Will Rock You〉是Queen作品。教甄常以極知名曲目混入另一支英國搖滾樂團，測試基本流行音樂文化辨識。"}
);