window.QUESTION_BANK = window.QUESTION_BANK || [];
window.QUESTION_BANK.push(
{subject:'高中音樂',year:'113',topic:'聲樂與歌劇',level:'中等',question:'下列哪一首詠嘆調最符合 Lyric Soprano（抒情女高音）的典型聲部？',options:['《Der Hölle Rache kocht in meinem Herzen》','《In questa reggia》','《Sì, mi chiamano Mimì》','《La donna è mobile》'],answer:2,explanation:'Mimì 的詠嘆調《Sì, mi chiamano Mimì》是典型抒情女高音曲目；夜后偏花腔女高音，Turandot 偏戲劇女高音，《La donna è mobile》則是男高音詠嘆調。',source:'113 中興附中音樂科'},
{subject:'高中音樂',year:'113',topic:'曲式',level:'基礎',question:'一種以呈示部、發展部、再現部為主要架構，並系統運用主題與調性對比的曲式為何？',options:['Fugue','Rondo','Theme and Variations','Sonata Form'],answer:3,explanation:'奏鳴曲式典型核心為呈示部、發展部、再現部，並以主題及調性關係建立張力與回歸。',source:'113 中興附中音樂科'},
{subject:'高中音樂',year:'113',topic:'音樂史',level:'中等',question:'2024 年逢重要整數紀念週年的作曲家組合，下列何者最合理？',options:['Beethoven 與 Fauré','Puccini 與 Bruckner','Debussy 與 Smetana','Verdi 與 Brahms'],answer:1,explanation:'Puccini 1924年逝世，2024為逝世100週年；Bruckner 1824年出生，2024為誕辰200週年。',source:'113 中興附中音樂科'},
{subject:'高中音樂',year:'113',topic:'臺灣音樂',level:'👹 冷門',question:'下列哪一首不是鄧雨賢的作品？',options:['《滿面春風》','《芎林小唄》','《青春嶺》','《跳舞時代》'],answer:1,explanation:'《芎林小唄》並非鄧雨賢作品；教甄常以較冷門曲名混入《四季紅》《望春風》《雨夜花》《月夜愁》等熟悉作品測辨識。',source:'113 中興附中音樂科'},
{subject:'高中音樂',year:'113',topic:'20世紀音樂史',level:'中等',question:'「努力捍衛自己的名聲、接受官方要求並描寫勝利行進」的政治語境，最可能與哪位作曲家的《第五號交響曲》相關？',options:['Mahler','Tchaikovsky','Shostakovich','Beethoven'],answer:2,explanation:'Shostakovich《第五號交響曲》創作於蘇聯政治壓力下，常與1936年遭官方批判後的處境及「對正當批評的回應」語境並論。',source:'113 中興附中音樂科'},
{subject:'高中音樂',year:'113',topic:'巴洛克',level:'高頻',question:'關於巴洛克時期常見的「階梯式力度」（terraced dynamics），下列何者正確？',options:['主要以長時間連續漸強漸弱為特徵','常呈現不同力度層級間較明確的轉換','只存在於聲樂作品','等同浪漫時期 rubato'],answer:1,explanation:'階梯式力度強調力度層級較明確的轉換；將其描述成以持續漸強、漸弱為主要特徵並不恰當。',source:'113 中興附中音樂科'},
{subject:'高中音樂',year:'113',topic:'臺灣音樂',level:'👹 冷門',question:'下列哪一項最能說明「流行文化作為橋梁」的音樂教學策略？',options:['先禁止學生聽流行音樂，再教授古典音樂','只比較作曲家出生年代','從流行歌曲的 ostinato、配器或敘事手法連結古典與傳統作品','只要求背誦音樂史名詞'],answer:2,explanation:'有效的轉化教學應從學生既有聆聽經驗出發，以共同音樂元素建立跨風格連結，而非建立流行與古典的價值高低。',source:'113 中興附中非選題轉化'},
{subject:'高中音樂',year:'113',topic:'20世紀音樂',level:'👹 冷門',question:'下列哪位作曲家最常與 Chance Music（機遇音樂）連結？',options:['John Cage','Giacomo Puccini','Anton Bruckner','Vincenzo Bellini'],answer:0,explanation:'John Cage 是機遇音樂的重要代表，曾以偶然程序與《易經》等方法介入創作決策。',source:'113 中興附中非選題轉化'},
{subject:'高中音樂',year:'113',topic:'歌劇',level:'高頻',question:'Leitmotiv（主導動機）在戲劇音樂中的主要功能為何？',options:['固定每一首詠嘆調都使用同一調性','以特定音樂動機聯結人物、物件、情感或觀念，並隨劇情變形','專指歌劇序曲最後一個和弦','限制樂團只能使用弦樂器'],answer:1,explanation:'主導動機藉可辨識的音樂材料建立戲劇語意，並可隨劇情透過調性、配器、節奏等方式轉化，Wagner 樂劇尤其具代表性。',source:'113 中興附中非選題轉化'},
{subject:'高中音樂',year:'113',topic:'世界音樂',level:'👹 冷門',question:'Khoomei 最具代表性的聲響特徵為何？',options:['以假聲快速輪唱','以持續基音配合共鳴調整凸顯泛音，形成多層聲響','只使用無固定音高的耳語','以十二音列決定旋律'],answer:1,explanation:'Khoomei 屬泛音／喉音歌唱傳統，透過口腔與共鳴腔調整強化泛音，使基音上方浮現高音旋律感。',source:'113 中興附中非選題轉化'}
);