window.QUESTIONS = window.QUESTIONS || [];
window.QUESTIONS.push(
{year:"115",level:"國中音樂",exam:"新北市立國民中學教師聯合甄選",topic:"課程綱要",difficulty:"中",question:"十二年國教藝術領域進入國中階段後，哪一項學習內容較明顯開始連結音樂職涯與產業認識？",options:["簡易即興","輪唱與合唱","音樂相關工作的特性與種類","音樂會基本禮儀"],answer:2,explanation:"國中藝術領域的音樂學習不只延伸表現與鑑賞，也開始納入音樂相關工作特性與種類等較具生涯探索意義的內容。",source:"阿摩115新北國中音樂第5題考點改寫"},
{year:"115",level:"國中音樂",exam:"新北市立國民中學教師聯合甄選",topic:"二十世紀音樂",difficulty:"中",question:"《月光小丑》（Pierrot lunaire）是哪位第二維也納樂派作曲家的代表作品？",options:["Schoenberg","Scriabin","Stravinsky","Berg"],answer:0,explanation:"《Pierrot lunaire》為 Arnold Schoenberg 1912年的重要作品，以Sprechstimme等技法著名。",source:"阿摩115新北國中音樂第7題考點改寫"},
{year:"115",level:"國中音樂",exam:"新北市立國民中學教師聯合甄選",topic:"西洋音樂史",difficulty:"中",question:"下列哪部管弦樂作品在終樂章中加入獨唱與合唱，突破傳統交響曲純器樂慣例？",options:["Debussy《牧神午後前奏曲》","Beethoven《第九號交響曲》","R. Strauss《查拉圖斯特拉如是說》","Stravinsky《火鳥》"],answer:1,explanation:"Beethoven《第九號交響曲》第四樂章加入獨唱與合唱，使用Schiller《歡樂頌》文本。",source:"阿摩115新北國中音樂第8題考點改寫"},
{year:"115",level:"高中音樂",exam:"教育部受託辦理115學年度公立高級中等學校教師甄選",topic:"流行音樂",difficulty:"中",question:"1960年代末起源於牙買加，1970年代走向全球，並常被視為受壓迫者聲音的流行音樂風格為何？",options:["Blues","Reggae","Hip-hop","R&B"],answer:1,explanation:"Reggae於1960年代末在牙買加形成，後來透過Bob Marley等音樂人走向國際。",source:"阿摩115教育部高中音樂第4題考點改寫"},
{year:"115",level:"高中音樂",exam:"教育部受託辦理115學年度公立高級中等學校教師甄選",topic:"二十世紀音樂",difficulty:"中高",question:"Messiaen《世界末日四重奏》原始編制不包含下列哪一件樂器？",options:["長笛","單簧管","小提琴","鋼琴"],answer:0,explanation:"此作編制為單簧管、小提琴、大提琴與鋼琴，沒有長笛。",source:"阿摩115教育部高中音樂第7題考點改寫"},
{year:"115",level:"高中音樂",exam:"教育部受託辦理115學年度公立高級中等學校教師甄選",topic:"歌劇史",difficulty:"中高",question:"哪一座劇院以Wagner理念設計，將樂池下沉並遮蔽，以形成所謂「神祕洞穴」（mystic gulf）的聲響與視覺效果？",options:["Bayreuth Festspielhaus","Musikverein","Berliner Philharmonie","Carnegie Hall"],answer:0,explanation:"Bayreuth Festspielhaus依Wagner劇場理念設計，隱蔽式樂池是其重要特色。",source:"阿摩115教育部高中音樂第9題考點改寫"},
{year:"115",level:"高中音樂",exam:"新北市公立高級中等學校教師聯合甄選",topic:"日本傳統音樂",difficulty:"中高",question:"關於日本歌舞伎（Kabuki），下列何者最正確？",options:["現代主要由男女演員共同演出所有角色","屬UNESCO非物質文化遺產，並常以隈取臉譜強化角色性格","主要伴奏樂器為尺八，源自宮廷雅樂","最初專供貴族階級觀賞"],answer:1,explanation:"Kabuki已列入UNESCO非物質文化遺產，隈取（kumadori）是其具代表性的舞台化妝傳統之一。",source:"阿摩115新北高中音樂第12題考點改寫"},
{year:"115",level:"高中音樂",exam:"新北市公立高級中等學校教師聯合甄選",topic:"電影配樂／極簡音樂",difficulty:"中",question:"若課堂要示範極簡音樂以反覆分解和弦與琶音營造時間推進感，下列哪組電影／作曲家最適合作為案例？",options:["《Dune》／Hans Zimmer","《Crouching Tiger, Hidden Dragon》／Tan Dun","《The Hours》／Philip Glass","《The Last Emperor》／Ryuichi Sakamoto"],answer:2,explanation:"Philip Glass是極簡音樂代表作曲家，《The Hours》配樂大量運用其典型反覆型態與和聲語彙。",source:"阿摩115新北高中音樂第14題考點改寫"},
{year:"115",level:"高中音樂",exam:"新北市公立高級中等學校教師聯合甄選",topic:"嘻哈音樂",difficulty:"中高",question:"關於Hip-hop歷史，下列哪項敘述最需要修正？",options:["1970年代起源於紐約哈林區","DJ Kool Herc對breakbeat發展具關鍵影響","Public Enemy以政治與社會批判聞名","El Général的作品與阿拉伯之春脈絡相關"],answer:0,explanation:"Hip-hop通常追溯至1970年代紐約Bronx（布朗克斯），而非Harlem；DJ Kool Herc被視為奠基人物之一。",source:"阿摩115新北高中音樂第15題考點改寫"},
{year:"115",level:"高中音樂",exam:"新北市公立高級中等學校教師聯合甄選",topic:"音樂教育法",difficulty:"中",question:"Eurhythmics（律動教學）最主要與哪位音樂教育家相關？",options:["Émile Jaques-Dalcroze","Zoltán Kodály","Carl Orff","Edwin Gordon"],answer:0,explanation:"Dalcroze Eurhythmics以身體律動連結節奏、聽覺與音樂感知，是二十世紀重要音樂教育方法。",source:"阿摩115新北高中音樂申論題Eurhythmics考點改寫"}
);