window.EXTRA_QUESTIONS = window.EXTRA_QUESTIONS || [];
window.EXTRA_QUESTIONS.push(
{id:'114moe21-1',year:'114',subject:'高中音樂',topic:'臺灣傳統戲曲',level:'👹 冷門',question:'榮興客家採茶劇團主要傳承與推廣下列何種表演藝術？',options:['歌仔戲','客家採茶戲','布袋戲','北管亂彈戲'],answer:1,explanation:'榮興客家採茶劇團以客家採茶戲（三腳採茶戲及客家大戲相關傳承）為核心。教甄常以劇團名稱反推劇種。',source:'114 教育部受託辦理公立高級中等學校教師甄選音樂科'},
{id:'114moe21-2',year:'114',subject:'高中音樂',topic:'臺灣原住民族音樂文化',level:'👹 冷門',question:'「五年祭」及其中著名的刺球儀式，主要與臺灣哪一原住民族相關？',options:['阿美族','排灣族','布農族','賽夏族'],answer:1,explanation:'排灣族五年祭（Maleveq）是重要祭儀，刺球是高度辨識性的儀式活動。賽夏族則以矮靈祭著名。',source:'114 教育部受託辦理公立高級中等學校教師甄選音樂科'},
{id:'114moe21-3',year:'114',subject:'高中音樂',topic:'西洋歌劇與音樂節',level:'👹 冷門',question:'德國拜魯特音樂節（Bayreuth Festival）與哪位作曲家的歌劇／樂劇作品關係最密切？',options:['Mozart','Wagner','Verdi','Richard Strauss'],answer:1,explanation:'拜魯特音樂節由 Richard Wagner 創設，核心為演出其樂劇與歌劇作品；Festspielhaus 亦依其戲劇理念建造。',source:'114 教育部受託辦理公立高級中等學校教師甄選音樂科'},
{id:'114moe21-4',year:'114',subject:'高中音樂',topic:'20世紀音樂',level:'👹 冷門',question:'Stravinsky《士兵的故事》（L’Histoire du soldat）原作最具代表性的特色之一為何？',options:['為大型浪漫管弦樂團而作','採七人器樂編制並結合敘事與舞臺元素','全曲僅使用弦樂四重奏','為無伴奏合唱宗教劇'],answer:1,explanation:'《士兵的故事》為第一次世界大戰末期的小型巡演作品，採小型七人器樂編制，並結合朗誦、戲劇與舞蹈。',source:'114 教育部受託辦理公立高級中等學校教師甄選音樂科'},
{id:'114moe21-5',year:'114',subject:'高中音樂',topic:'藝術歌曲',level:'中高難度',question:'關於 Schubert 藝術歌曲《魔王》（Erlkönig），下列何者正確？',options:['由四位歌者分別扮演四個角色','鋼琴連續快速音型有助營造奔馳與緊張感','作品採純器樂形式沒有歌詞','歌詞作者為 Goethe 以外的 Wagner'],answer:1,explanation:'《魔王》通常由一位歌者以不同音域、音色與表情塑造敘述者、父親、兒子與魔王；鋼琴快速三連音型營造馬匹奔馳與緊迫感，詩作出自 Goethe。',source:'114 教育部受託辦理公立高級中等學校教師甄選音樂科'},
{id:'114moe21-6',year:'114',subject:'高中音樂',topic:'音樂節與文化',level:'中高難度',question:'若題目要求辨認「以特定作曲家作品為核心、並在其專屬劇院演出」的音樂節，下列何者最符合？',options:['Salzburg Festival—Mahler','Bayreuth Festival—Wagner','Glastonbury—Bach','Tomorrowland—Debussy'],answer:1,explanation:'Bayreuth Festival 與 Wagner 及 Bayreuth Festspielhaus 的關係最具代表性，是常見音樂文化辨識考點。',source:'114 教育部受託辦理公立高級中等學校教師甄選音樂科'},
{id:'114moe21-7',year:'114',subject:'高中音樂',topic:'臺灣音樂文化',level:'👹 冷門',question:'面對教甄中的臺灣地方戲曲題，若看到「客家、採茶、丑角互動、山歌小調」等線索，最優先聯想到何者？',options:['南管戲','三腳採茶戲','梨園戲','京劇'],answer:1,explanation:'三腳採茶戲是客家傳統戲曲的重要形式，典型以二旦一丑等角色互動，並與採茶歌、山歌小調文化密切相關。',source:'114 教育部受託辦理公立高級中等學校教師甄選音樂科'},
{id:'114moe21-8',year:'114',subject:'高中音樂',topic:'作品與編制',level:'中高難度',question:'《士兵的故事》使用小型混合器樂編制，最能反映下列哪一20世紀創作傾向？',options:['追求華格納式超大型樂團','在有限資源下探索鮮明音色與節奏組合','完全排除打擊樂器','回到文藝復興無伴奏聲樂'],answer:1,explanation:'作品以少量但音色差異鮮明的樂器形成高度透明的聲響，節奏與音色組合極具特色，也是理解 Stravinsky 20世紀語法的好例子。',source:'114 教育部受託辦理公立高級中等學校教師甄選音樂科'}
);