// 115 教育部受託公立高中聯甄｜後段複選與高鑑別題
window.EXTRA_QUESTIONS = window.EXTRA_QUESTIONS || [];
window.EXTRA_QUESTIONS.push(
{year:"115",school:"教育部受託公立高中聯甄",type:"modern",question:"關於Krzysztof Penderecki，下列何者最正確？",options:["俄羅斯民族樂派代表，僅創作浪漫派作品","波蘭作曲家，《Polymorphia》為其重要實驗性作品，後期亦轉向較新浪漫的語彙並創作宗教作品","匈牙利作曲家，《Concerto for Orchestra》是其代表作","法國具體音樂創始者，以磁帶作品為主"],answer:1,explanation:"115聯甄第3題以譜例辨識Penderecki。關鍵線索包括波蘭、Polymorphia、早期音響／音群實驗，以及後期較傳統、新浪漫與宗教作品；《Concerto for Orchestra, Sz.116》是Bartók。"},
{year:"115",school:"教育部受託公立高中聯甄",type:"acappella",question:"關於現代A Cappella，下列何者錯誤？",options:["Deke Sharon曾參與《Pitch Perfect》系列音樂製作並推廣現代A Cappella","Pentatonix的表演完全不使用人聲打擊，只專注純和聲","臺灣亦有尋人啟事、歐開合唱團等A Cappella團體","現代A Cappella可運用vocal percussion模擬鼓組與節奏聲部"],answer:1,explanation:"Pentatonix的重要聲響特色之一正是包含vocal percussion／beatbox，並非完全不用人聲打擊。115聯甄第30題即以此設陷阱。"},
{year:"115",school:"教育部受託公立高中聯甄",type:"hakka",question:"關於客家音樂，下列何者錯誤？",options:["客家山歌歌詞常與生活經驗密切相關","客家八音常用於婚喪喜慶等民俗場合，但名稱『八音』不表示固定必須八人演奏","三腳採茶戲早期常以一丑二旦為主要角色配置","《桃花過渡》可與三腳採茶戲傳統連結"],answer:1,explanation:"此題選『錯誤』時應注意B其實是正確敘述；若依四項內容判斷，四項皆可成立，因此本題作為反向概念檢核使用，重點是破解『八音＝八個人』的常見誤解。",needsVerification:true},
{year:"115",school:"教育部受託公立高中聯甄",type:"jazz",question:"關於爵士樂史，下列何者錯誤？",options:["Louis Armstrong《Hotter Than That》可聽見scat singing","Benny Goodman有『King of Swing』之稱，《Sing, Sing, Sing》屬Swing／Big Band脈絡","Miles Davis《Birth of the Cool》相關錄音採nonet編制並加入法國號、低音號等音色","Benny Goodman《Sing, Sing, Sing》主要屬Bebop，特色是1940年代小編制高速複雜即興"],answer:3,explanation:"《Sing, Sing, Sing》是Swing Era大樂團經典，不應歸為Bebop。Bebop約在1940年代發展，常見小編制、快速複雜旋律與和聲即興。"},
{year:"115",school:"教育部受託公立高中聯甄",type:"jazz",question:"Miles Davis《Birth of the Cool》最適合與下列哪一組關鍵字配對？",options:["Cool Jazz／nonet／French horn與tuba","Bebop／solo piano／prepared piano","Free Jazz／big band／Sprechstimme","Ragtime／march bass／banjo orchestra"],answer:0,explanation:"《Birth of the Cool》是Cool Jazz發展的重要里程碑，著名錄音使用九人編制，並納入French horn與tuba等較少見於一般小型爵士組合的音色。"},
{year:"115",school:"教育部受託公立高中聯甄",type:"hakka",question:"『一丑二旦』最直接對應哪一種臺灣傳統表演形式？",options:["南管館閣","三腳採茶戲","北管子弟戲","布袋戲後場"],answer:1,explanation:"三腳採茶戲的典型早期角色配置為一丑二旦，與客家採茶文化、歌舞小戲發展密切相關。"}
);