// 114 高雄市國中教師聯甄音樂科｜高鑑別題第二批
window.QUESTIONS = window.QUESTIONS || [];
window.QUESTIONS.push(
{year:"114",school:"高雄市國中教師聯甄",level:"國中",type:"choice",difficulty:"👹",topic:"臺灣音樂史",question:"著有《臺灣音樂史初稿》，並長期投入民族音樂採集與音樂教育的臺灣音樂家是？",options:["江文也","許常惠","馬水龍","李泰祥"],answer:1,explanation:"許常惠兼具作曲家、音樂教育者與民族音樂研究者身分，曾投入臺灣民間音樂採集與保存，著有《臺灣音樂史初稿》。教甄常把許常惠、史惟亮、江文也、馬水龍的角色與作品交叉配對。"},
{year:"114",school:"高雄市國中教師聯甄",level:"國中",type:"choice",difficulty:"👹",topic:"世界音樂",question:"關於印尼爪哇 Gamelan，下列何者最正確？",options:["主要由竹笛構成，幾乎不使用金屬樂器","常使用 sléndro、pélog 等音階系統，並大量運用鑼與金屬鍵盤樂器","以西洋功能和聲與十二平均律為主要基礎","主要是無固定節拍的獨奏音樂"],answer:1,explanation:"爪哇與峇里甘美朗以鑼、金屬鍵盤類樂器等合奏為重要特色，常見 sléndro 與 pélog 調律／音階系統。不可直接以西洋十二平均律理解其音高組織。"},
{year:"114",school:"高雄市國中教師聯甄",level:"國中",type:"choice",difficulty:"👹",topic:"西洋音樂史",question:"下列哪位作曲家不屬於文藝復興時期？",options:["Josquin des Prez","Palestrina","Orlando di Lasso","Guillaume de Machaut"],answer:3,explanation:"Machaut是14世紀 Ars Nova 的代表人物，屬中世紀晚期；Josquin、Palestrina、Lasso則是文藝復興重要作曲家。『Machaut名字很古老所以猜文藝復興』是常見年代陷阱。"},
{year:"114",school:"高雄市國中教師聯甄",level:"國中",type:"choice",difficulty:"👹",topic:"臺灣作曲家",question:"關於江文也，下列何者最能概括其創作特色？",options:["完全排斥西洋作曲技法，只採傳統民間旋律","常在現代西洋作曲語彙中融入東亞與臺灣文化素材","主要以臺語校園民歌創作聞名","主要研究南管，沒有重要器樂作品"],answer:1,explanation:"江文也是20世紀重要臺灣作曲家，其生命與創作跨越臺灣、日本與中國，作品常呈現現代西洋作曲技法與東亞文化想像的交會。人物題要避免把『臺灣作曲家』簡化成單一民謠素材。"},
{year:"114",school:"高雄市國中教師聯甄",level:"國中",type:"choice",difficulty:"中",topic:"歌劇",question:"下列哪一部歌劇最常被視為20世紀現代主義歌劇的重要代表？",options:["Mozart《魔笛》","Puccini《波希米亞人》","Berg《Wozzeck》","Verdi《弄臣》"],answer:2,explanation:"Alban Berg《Wozzeck》是20世紀現代主義歌劇的重要代表，與無調性／高度半音化語彙、表現主義戲劇等密切相關。其餘分別屬古典、浪漫／寫實歌劇傳統。"},
{year:"114",school:"高雄市國中教師聯甄",level:"國中",type:"choice",difficulty:"👹",topic:"爵士樂史",question:"若題目問『早期爵士樂最具代表性的音樂家之一』，下列何者最適合？",options:["Louis Armstrong","Charlie Parker","John Coltrane","Ornette Coleman"],answer:0,explanation:"Armstrong是早期爵士、New Orleans／Chicago jazz與獨奏即興發展的關鍵人物；Parker屬Bebop，Coltrane主要活躍於Hard Bop、Modal Jazz等，Coleman則與Free Jazz密切相關。"},
{year:"114",school:"高雄市國中教師聯甄",level:"國中",type:"choice",difficulty:"👹",topic:"和聲",question:"完全正格終止 Perfect Authentic Cadence（PAC）最核心的判斷條件為何？",options:["任何V–I即可，不論轉位與最高聲部","V–I，兩和弦皆根音位置，且I和弦最高聲部為主音","IV–I且最高聲部為主音","ii–V–I只要最後到I即可"],answer:1,explanation:"PAC通常要求V（或V7）到I、兩和弦根音位置，終止I的最高聲部落在主音。若V–I成立但最高聲部或轉位條件不符，通常歸為IAC。這是教甄很愛考的PAC／IAC界線。"},
{year:"114",school:"高雄市國中教師聯甄",level:"國中",type:"choice",difficulty:"👹",topic:"中國音樂史",question:"依中國古代『八音』分類，下列何者配對錯誤？",options:["編鐘—金","琵琶—絲","篳篥—竹","鼓—木"],answer:3,explanation:"八音依主要發聲／製作材料分金、石、土、革、絲、木、匏、竹；鼓以鼓皮為關鍵，通常歸『革』，不能因鼓架是木製就判為木。"},
{year:"114",school:"高雄市國中教師聯甄",level:"國中",type:"choice",difficulty:"👹",topic:"爵士樂史",question:"下列爵士風格與年代／特色配對，何者最需要修正？",options:["Bebop—1940年代，快速且和聲複雜","Cool Jazz—較抒情克制，Miles Davis等","Swing—主要成熟於1930年代的大樂團時代","Free Jazz—1960年代強調更自由的結構與即興"],answer:2,explanation:"若把Swing說成『1920年代的主要風格』會過度提前；Swing Era通常以1930年代至1940年代中期的大樂團文化為核心。教甄常用年代差十年製造陷阱。"}
);