window.LOCAL_QUESTIONS = (window.LOCAL_QUESTIONS || []).concat([
{id:"RARE5-001",subject:"高中音樂",topic:"世界音樂／韓國",level:"冷門魔王",year:"112",exam:"臺中一中教師甄選考點改寫",source_type:"歷屆非選考點改寫",source_title:"112 臺中一中音樂科",question:"下列何者最符合 Gayageum（伽倻琴）的描述？",option_a:"日本以弓拉奏的三弦樂器",option_b:"韓國傳統撥弦樂器，可藉按弦產生裝飾音",option_c:"印尼以竹管搖奏的體鳴樂器",option_d:"西非以拇指撥動金屬簧片的樂器",answer:"B",explanation:"Gayageum 是韓國代表性的傳統撥弦樂器。D 描述較接近 Kalimba/Mbira。"},
{id:"RARE5-002",subject:"高中音樂",topic:"民族音樂學／樂器分類",level:"冷門魔王",year:"112",exam:"臺中一中教師甄選考點改寫",source_type:"歷屆非選考點改寫",source_title:"112 臺中一中音樂科",question:"Kalimba（卡林巴）依發聲原理最適合歸入下列哪一類？",option_a:"Lamellophone 體鳴樂器",option_b:"膜鳴樂器",option_c:"氣鳴樂器",option_d:"弦鳴樂器",answer:"A",explanation:"Kalimba 以手指撥動金屬簧片發聲，是 lamellophone，屬體鳴樂器。"},
{id:"RARE5-003",subject:"高中音樂",topic:"浪漫時期／歌劇",level:"高鑑別度",year:"112",exam:"臺中一中教師甄選考點改寫",source_type:"歷屆非選考點改寫",source_title:"112 臺中一中音樂科",question:"《Der Freischütz》（《魔彈射手》）與下列哪位作曲家關係最密切？",option_a:"Weber",option_b:"Rossini",option_c:"Verdi",option_d:"Bizet",answer:"A",explanation:"Weber 的《魔彈射手》是德國浪漫歌劇的重要代表。"},
{id:"RARE5-004",subject:"高中音樂",topic:"浪漫時期／歌劇",level:"冷門魔王",year:"112",exam:"臺中一中教師甄選考點改寫",source_type:"歷屆非選考點改寫",source_title:"112 臺中一中音樂科",question:"歌劇《La forza del destino》（《命運之力》）是誰的作品？",option_a:"Puccini",option_b:"Verdi",option_c:"Wagner",option_d:"Mascagni",answer:"B",explanation:"《命運之力》為 Giuseppe Verdi 的歌劇。教甄常直接以原文作品名考作曲家辨識。"},
{id:"RARE5-005",subject:"高中音樂",topic:"臺灣原住民族",level:"高頻冷門",year:"112",exam:"高雄高中聯招考點改寫",source_type:"歷屆非選考點改寫",source_title:"112 高雄市高中聯合教甄",question:"教甄題目中的「臀鈴」最應與哪一族及祭儀連結？",option_a:"布農族－射耳祭",option_b:"賽夏族－矮靈祭",option_c:"達悟族－飛魚祭",option_d:"阿美族－豐年祭",answer:"B",explanation:"臀鈴是賽夏族矮靈祭極具代表性的聲響與舞蹈器物，歷屆教甄反覆出現。"},
{id:"RARE5-006",subject:"高中音樂",topic:"世界音樂／日本劇場",level:"冷門魔王",year:"112",exam:"高雄高中聯招考點改寫",source_type:"歷屆非選考點改寫",source_title:"112 高雄市高中聯合教甄",question:"關於 Kabuki（歌舞伎），下列何者最適當？",option_a:"韓國由歌者與鼓手敘事的聲樂形式",option_b:"日本結合戲劇、舞蹈與音樂的傳統劇場形式",option_c:"印度以即興拉格為核心的器樂形式",option_d:"印尼以鑼群與金屬鍵盤樂器為核心的合奏",answer:"B",explanation:"Kabuki 是日本傳統劇場，常與女形、三味線等概念一起考。"},
{id:"RARE5-007",subject:"高中音樂",topic:"文藝復興音樂",level:"冷門魔王",year:"115",exam:"高雄高中教師甄選考點改寫",source_type:"歷屆非選考點改寫",source_title:"115 高雄高中音樂科",question:"Imitation Mass（亦常稱 parody mass）的主要特色為何？",option_a:"全曲只使用葛利果聖歌單一固定旋律",option_b:"借用既有複音作品多個聲部或素材重新組織成彌撒",option_c:"完全禁止使用世俗音樂素材",option_d:"只為器樂編制而作，不含聲樂",answer:"B",explanation:"Imitation/Parody Mass 會借用既有複音作品較完整的聲部、主題或結構素材。"},
{id:"RARE5-008",subject:"高中音樂",topic:"20世紀／電子音樂",level:"冷門魔王",year:"115",exam:"高雄高中教師甄選考點改寫",source_type:"歷屆非選考點改寫",source_title:"115 高雄高中音樂科",question:"1958 年 Philips Pavilion 的《Poème électronique》是哪位作曲家的作品？",option_a:"Pierre Schaeffer",option_b:"Karlheinz Stockhausen",option_c:"Edgard Varèse",option_d:"Iannis Xenakis",answer:"C",explanation:"Varèse 的《Poème électronique》是電子音樂與空間／多媒體史的重要作品。Xenakis 與該館建築設計密切相關，是很有迷惑性的干擾項。"},
{id:"RARE5-009",subject:"高中音樂",topic:"浪漫晚期／交響曲",level:"高鑑別度",year:"115",exam:"高雄高中教師甄選考點改寫",source_type:"歷屆非選考點改寫",source_title:"115 高雄高中音樂科",question:"被稱為「Resurrection Symphony（復活交響曲）」的是下列哪一部作品？",option_a:"Mahler Symphony No. 2",option_b:"Mahler Symphony No. 8",option_c:"Bruckner Symphony No. 7",option_d:"Berlioz Symphonie fantastique",answer:"A",explanation:"馬勒第二號交響曲《復活》後段加入獨唱與合唱。"},
{id:"RARE5-010",subject:"高中音樂",topic:"臺灣原住民族／永續",level:"冷門魔王",year:"112",exam:"高雄高中聯招考點改寫",source_type:"歷屆非選考點改寫",source_title:"112 高雄市高中聯合教甄",question:"「PawPaw／寶抱」在臺灣音樂文化題目中最可能指什麼？",option_a:"利用廢棄漁業浮筒等材料製成的部落環保鼓",option_b:"排灣族雙管鼻笛的另一名稱",option_c:"賽夏族臀鈴的阿美語名稱",option_d:"南管下四管中的打擊樂器",answer:"A",explanation:"PAW-PAW 鼓運用廢棄浮筒等材料製作，兼具部落文化與環境永續意涵，是非常典型的冷門跨域教甄考點。"}
]);