(()=>{
 if(window.__QUESTION_MASTERY_OVERVIEW_V1__)return;window.__QUESTION_MASTERY_OVERVIEW_V1__=true;
 const STATS='musicTeacherExamStatsV1',SRS='musicTeacherExamSpacedReviewV1';
 const load=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}},qs=()=>window.MusicTeacherExam?.questions||[];
 const subjects=['國中音樂','高中音樂','教育專業'];
 function risk(q,s,r){if(window.MusicTeacherSRS?.effectiveRisk)return window.MusicTeacherSRS.effectiveRisk(q,r,s);const x=r[q.id]||{},streak=x.correctStreak||0,id=String(q.id),wrong=new Set((s.wrong||[]).map(String)),unknown=new Set((s.unknown||[]).map(String));if(x.lastResult==='unknown'||x.lastResult==='wrong')return x.lastResult;if(streak>=2)return null;if(unknown.has(id))return'unknown';if(wrong.has(id))return'wrong';return null}
 function one(pool,s,r){let attemptTotal=0,attemptCorrect=0,tried=0,mastered=0,learning=0;pool.forEach(q=>{const a=s.attempts?.[q.id];if(a?.total){tried++;attemptTotal+=a.total||0;attemptCorrect+=a.correct||0;const x=r[q.id]||{},streak=x.correctStreak??a.streak??0;if(streak>=3&&!risk(q,s,r))mastered++;else learning++}});return{totalQuestions:pool.length,attemptTotal,attemptCorrect,attemptAcc:attemptTotal?Math.round(attemptCorrect/attemptTotal*100):null,tried,coverage:pool.length?Math.round(tried/pool.length*100):0,mastered,learning,masteryOfTried:tried?Math.round(mastered/tried*100):0,masteryOfAll:pool.length?Math.round(mastered/pool.length*100):0}}
 function metrics(){const s=load(STATS,{attempts:{},wrong:[],unknown:[]}),r=load(SRS,{}),all=qs(),bySubject={};subjects.forEach(sub=>bySubject[sub]=one(all.filter(q=>q.subject===sub),s,r));return{overall:one(all,s,r),bySubject}}
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function render(){const home=document.getElementById('homeView');if(!home)return;let box=document.getElementById('questionMasteryOverview');if(!box){box=document.createElement('section');box.id='questionMasteryOverview';box.className='card section-card';const progress=document.getElementById('learningProgressPanel'),srs=document.getElementById('mtSrs');(progress||srs||home.querySelector('.stats-grid'))?.insertAdjacentElement('afterend',box)||home.appendChild(box)}const m=metrics(),o=m.overall;box.innerHTML=`<div class="section-title"><div><span class="eyebrow">不要讓重複刷熟悉題灌高百分比</span><h3>📐 題次正確率 vs 題目掌握率</h3></div></div><p class="muted">「題次正確率」看每一次作答；「題目掌握率」看有多少不同題已連續答對 3 次且目前沒有高風險。兩個數字分開，才能看出是刷得多，還是真的會得多。</p><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(145px,1fr));gap:9px;margin:12px 0"><div style="padding:13px;border:1px solid var(--line);border-radius:12px"><small class="muted">累積題次正確率</small><div style="font-size:28px;font-weight:900">${o.attemptAcc??'--'}<small style="font-size:12px">%</small></div><small class="muted">${o.attemptCorrect}/${o.attemptTotal} 題次</small></div><div style="padding:13px;border:1px solid var(--line);border-radius:12px"><small class="muted">已看過不同題</small><div style="font-size:28px;font-weight:900">${o.coverage}<small style="font-size:12px">%</small></div><small class="muted">${o.tried}/${o.totalQuestions} 題</small></div><div style="padding:13px;border:1px solid var(--line);border-radius:12px"><small class="muted">已掌握不同題</small><div style="font-size:28px;font-weight:900">${o.masteryOfTried}<small style="font-size:12px">%</small></div><small class="muted">${o.mastered}/${o.tried||0} 已練題</small></div><div style="padding:13px;border:1px solid var(--line);border-radius:12px"><small class="muted">全題庫掌握覆蓋</small><div style="font-size:28px;font-weight:900">${o.masteryOfAll}<small style="font-size:12px">%</small></div><small class="muted">${o.mastered}/${o.totalQuestions} 題</small></div></div><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:8px">${subjects.map(sub=>{const x=m.bySubject[sub];return`<div style="padding:11px;border:1px solid var(--line);border-radius:12px"><b>${esc(sub)}</b><div style="font-size:13px;line-height:1.8;margin-top:5px">題次正確率：<b>${x.attemptAcc??'--'}%</b><br>題目掌握率：<b>${x.masteryOfTried}%</b>（${x.mastered}/${x.tried}）<br>題庫覆蓋：<b>${x.coverage}%</b>（${x.tried}/${x.totalQuestions}）</div></div>`}).join('')}</div>`;window.HomeCategoryOrganizer?.apply?.()}
 function bind(){render();window.addEventListener('musicExamLearningSynced',render);window.addEventListener('musicExamAttemptLogged',()=>setTimeout(render,60));window.addEventListener('storage',e=>{if([STATS,SRS].includes(e.key))render()});const fb=document.getElementById('feedback');if(fb&&!fb.dataset.questionMasteryObserved){fb.dataset.questionMasteryObserved='1';new MutationObserver(()=>{if(!fb.classList.contains('hidden'))setTimeout(render,100)}).observe(fb,{attributes:true,attributeFilter:['class']})}}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(bind,1200),{once:true});else setTimeout(bind,180);window.QuestionMasteryOverview={metrics,render};
})();