// 115 教育部受託公立高中聯甄｜前段選擇與時事高鑑別題
window.EXTRA_QUESTIONS = window.EXTRA_QUESTIONS || [];
window.EXTRA_QUESTIONS.push(
{year:"115",school:"教育部受託公立高中聯甄",type:"modern",question:"Krzysztof Penderecki最適合與下列哪組配對？",options:["Poland／Polymorphia／tone cluster","Hungary／Concerto for Orchestra／night music","France／musique concrète／tape","Russia／The Rite of Spring／ballet"],answer:0,explanation:"Penderecki是波蘭作曲家，《Polymorphia》《Threnody to the Victims of Hiroshima》均與其早期音響實驗、音群與特殊弦樂奏法密切相關。"},
{year:"115",school:"教育部受託公立高中聯甄",type:"world",question:"1960年代末在牙買加形成，1970年代成為國際風格，並常被視為被壓迫者聲音的流行音樂類型是？",options:["Blues","Reggae","Hip-hop","R&B"],answer:1,explanation:"Reggae於1960年代末在Jamaica形成，之後透過Bob Marley等人物成為全球性流行音樂風格。"},
{year:"115",school:"教育部受託公立高中聯甄",type:"history",question:"下列作品依創作／完成年代由早至晚，何者正確？",options:["《Symphony of Psalms》→《Pierrot lunaire》→《Má vlast》→《Turangalîla-symphonie》","《Má vlast》→《Symphony of Psalms》→《Pierrot lunaire》→《Turangalîla-symphonie》","《Má vlast》→《Pierrot lunaire》→《Symphony of Psalms》→《Turangalîla-symphonie》","《Turangalîla-symphonie》→《Symphony of Psalms》→《Má vlast》→《Pierrot lunaire》"],answer:2,explanation:"Smetana《Má vlast》1870年代；Schoenberg《Pierrot lunaire》1912；Stravinsky《Symphony of Psalms》1930；Messiaen《Turangalîla-symphonie》1940年代。"},
{year:"115",school:"教育部受託公立高中聯甄",type:"jazz",question:"Blues、Swing、R&B、Funk若依大致歷史發展先後排列，何者最合理？",options:["Funk→R&B→Blues→Swing","Swing→Blues→R&B→Funk","Blues→Swing→R&B→Funk","Blues→R&B→Funk→Swing"],answer:2,explanation:"以教甄常見概略年代判斷，可記成Blues較早，Swing盛於1930年代，R&B於1940年代後形成，Funk於1960年代後發展。"},
{year:"115",school:"教育部受託公立高中聯甄",type:"modern",question:"Messiaen《Quatuor pour la Fin du Temps（世界末日四重奏）》的原始四重奏編制不包含哪件樂器？",options:["長笛","單簧管","小提琴","鋼琴"],answer:0,explanation:"作品編制為clarinet、violin、cello、piano，不包含flute。此編制與Messiaen戰俘營創作背景密切相關。"},
{year:"115",school:"教育部受託公立高中聯甄",type:"opera",question:"哪一座劇院以Wagner設計理念著稱，將樂池下沉並遮蔽，使觀眾看不到樂團與指揮，形成所謂『mystic gulf』？",options:["Bayreuth Festspielhaus","Musikverein Golden Hall","Berliner Philharmonie","Carnegie Hall"],answer:0,explanation:"Bayreuth Festspielhaus的隱蔽式樂池是Wagner劇場理念的重要特色，讓觀眾視線集中舞臺並改變管弦樂聲響投射。"},
{year:"115",school:"教育部受託公立高中聯甄",type:"modern",question:"以機率、集合論、數學結構與隨機程序著稱的20世紀作曲家是？",options:["Iannis Xenakis","Pierre Schaeffer","Edgard Varèse","György Ligeti"],answer:0,explanation:"Xenakis具有工程與數學背景，常把stochastic processes、機率與數學模型融入作曲思考。"},
{year:"115",school:"教育部受託公立高中聯甄",type:"current",question:"2025年第19屆蕭邦國際鋼琴大賽首獎得主是？",options:["Bruce Liu","Eric Lu","Kevin Chen","Seong-Jin Cho"],answer:1,explanation:"第19屆蕭邦國際鋼琴大賽於2025年舉行，首獎由美國鋼琴家Eric Lu獲得；Kevin Chen獲第二名。"},
{year:"115",school:"教育部受託公立高中聯甄",type:"taiwan",question:"1975年於臺北中山堂舉辦《現代民謠創作演唱會》，並以余光中詩作譜曲，被視為臺灣校園民歌運動重要開端的人物是？",options:["李雙澤","李泰祥","胡德夫","楊弦"],answer:3,explanation:"楊弦1975年的《現代民謠創作演唱會》常被視為臺灣現代民歌／校園民歌運動的重要起點之一。"},
{year:"115",school:"教育部受託公立高中聯甄",type:"hiphop",question:"Hip-hop語彙中，何者解釋錯誤？",options:["Punchline＝整首歌曲中最洗腦、重複最多次的旋律句","Flow＝饒舌時的節奏編排、韻律與斷句方式","Freestyle＝未事先寫好完整歌詞而配合節奏即興","Vibe＝歌曲營造出的整體氛圍、情緒與律動感"],answer:0,explanation:"Punchline較接近具有衝擊力、機智、反轉或記憶點的關鍵句，不等同流行歌曲中反覆最多次的hook。"}
);