window.EXTRA_QUESTIONS = (window.EXTRA_QUESTIONS || []).concat([
{id:"115-NH-15-01",year:115,subject:"高中音樂",topic:"音樂時事",level:"進階",question:"2025年第36屆金曲獎『年度歌曲獎』得獎作品為何？",options:["〈星期五晚上〉","〈又到天黑〉","〈最好的時光〉","〈愛情你比我想的閣較偉大〉"],answer:1,explanation:"2025年第36屆金曲獎年度歌曲獎為〈又到天黑〉。此類近年音樂時事已實際進入教師甄試。",source:"115 臺北市立內湖高工正式教師甄選音樂科（阿摩題庫）"},
{id:"115-NH-15-02",year:115,subject:"高中音樂",topic:"客家音樂",level:"進階",question:"關於客家傳統〈老山歌〉，下列何者最符合其旋律與歌詞關係？",options:["節奏與每句長度均固定不變","唱詞可依語言韻律使旋律長短產生彈性","必定採七聲音階且不能加入裝飾音","是由〈山歌子〉在20世紀改編而成"],answer:1,explanation:"老山歌具有較自由、悠長的歌唱特質，旋律長短可隨唱詞語言韻律而有彈性。教甄常把客家三大調與歌唱特質交叉命題。",source:"115 臺北市立內湖高工正式教師甄選音樂科（阿摩題庫）"},
{id:"115-NH-15-03",year:115,subject:"高中音樂",topic:"中國音樂史",level:"👹 魔王",question:"關於漢代『相和歌』，下列何者最不適切？",options:["常以絲竹樂器伴奏","漢代相和歌具有重要地位","名稱與人聲及絲竹相和的表演方式有關","本質上主要屬宮廷雅樂系統"],answer:3,explanation:"相和歌源於漢代民間俗樂歌唱傳統，後亦進入宮廷，但不宜直接等同宮廷雅樂。『絲竹更相和，執節者歌』是常見理解線索。",source:"115 臺北市立內湖高工正式教師甄選音樂科（阿摩題庫）"},
{id:"115-NH-15-04",year:115,subject:"高中音樂",topic:"中國音樂史",level:"👹 魔王",question:"下列中國音樂史配對何者錯誤？",options:["鼓詞、彈詞—清代說唱音樂","清商樂—魏晉南北朝重要樂種","瓦舍—宋代城市娛樂表演場所","三分損益法—始創於漢代"],answer:3,explanation:"三分損益的律學思想遠早於漢代，可見於先秦文獻脈絡；因此把它說成『始於漢朝』不正確。",source:"115 臺北市立內湖高工正式教師甄選音樂科（阿摩題庫）"},
{id:"115-NH-15-05",year:115,subject:"高中音樂",topic:"音樂織度",level:"基礎",question:"關於 Homophony（主音音樂／主調織度），下列何者錯誤？",options:["古典時期大量使用","常呈現主要旋律與伴奏層次","巴赫是此織度最具代表性的唯一核心作曲家","各聲部功能常具有主從之分"],answer:2,explanation:"巴赫最具代表性的歷史形象之一是複音／對位寫作。主調織度在古典時期尤其普遍，但不同時期作品也可能交替使用多種織度。",source:"115 臺北市立內湖高工正式教師甄選音樂科（阿摩題庫）"},
{id:"115-NH-15-06",year:115,subject:"高中音樂",topic:"音樂史",level:"基礎",question:"古典時期歌劇改革最常與下列哪位作曲家連結？",options:["Gluck","Haydn","Beethoven","Palestrina"],answer:0,explanation:"Christoph Willibald Gluck主張戲劇與音樂整體統一、減少炫技性與僵化慣例，是18世紀歌劇改革的重要人物。",source:"115 臺北市立內湖高工正式教師甄選音樂科（阿摩題庫）"},
{id:"115-NH-15-07",year:115,subject:"高中音樂",topic:"巴洛克音樂",level:"進階",question:"關於 Handel，下列敘述何者錯誤？",options:["是巴洛克時期重要作曲家","創作《Water Music》","出生於英國，之後才前往德國發展","晚年逝世後葬於西敏寺"],answer:2,explanation:"Handel出生於德國哈雷，後長期在英國發展並入籍英國；《Water Music》為其代表作品之一，死後葬於Westminster Abbey。",source:"115 臺北市立內湖高工正式教師甄選音樂科（阿摩題庫）"},
{id:"115-NH-15-08",year:115,subject:"高中音樂",topic:"二十世紀音樂",level:"進階",question:"關於20世紀 Expressionism（表現主義），下列敘述何者最不適切？",options:["Schoenberg是重要代表人物","與無調性及後續十二音技法發展密切相關","屬20世紀重要藝術思潮之一","在西方音樂史上明確早於印象主義興起"],answer:3,explanation:"印象主義的形成與代表作品早於20世紀表現主義成熟；Schoenberg及第二維也納樂派則是表現主義與無調性／十二音技法的重要脈絡。",source:"115 臺北市立內湖高工正式教師甄選音樂科（阿摩題庫）"},
{id:"115-NH-15-09",year:115,subject:"高中音樂",topic:"音樂術語",level:"基礎",question:"下列速度術語通常表示最快速度的是？",options:["Vivace","Vivo","Presto","Prestissimo"],answer:3,explanation:"Prestissimo通常表示極快，速度程度高於Presto；實際演奏速度仍需結合作品時代、風格與上下文判斷。",source:"115 臺北市立內湖高工正式教師甄選音樂科（阿摩題庫）"},
{id:"115-NH-15-10",year:115,subject:"高中音樂",topic:"舞曲",level:"👹 魔王",question:"下列舞曲與典型拍子配對何者有誤？",options:["Sarabande—三拍子","Gavotte—三拍子","Chaconne—常見三拍子","Pavane—二拍子系統"],answer:1,explanation:"Gavotte通常為中速二拍子（常見2/2或相關二拍系統），並常具有半小節弱起；Sarabande與Chaconne常見三拍子。",source:"115 臺北市立內湖高工正式教師甄選音樂科（阿摩題庫）"},
{id:"115-NH-15-11",year:115,subject:"高中音樂",topic:"浪漫時期",level:"進階",question:"『新曲種蓬勃、沙龍音樂興盛、作曲家個人風格與主觀表達突出』最符合哪一音樂史時期？",options:["巴洛克","古典","浪漫","戰後前衛"],answer:2,explanation:"浪漫時期重視個人情感與作曲家獨特性，並出現大量性格小品、藝術歌曲等新興或高度發展的曲種，沙龍文化亦相當重要。",source:"115 臺北市立內湖高工正式教師甄選音樂科（阿摩題庫）"},
{id:"115-NH-15-12",year:115,subject:"高中音樂",topic:"原住民族音樂",level:"👹 魔王",question:"Enigma〈Return to Innocence〉取樣而引發著作權爭議的臺灣原住民族歌聲，主要與哪一族相關？",options:["阿美族","布農族","排灣族","賽夏族"],answer:0,explanation:"該曲取樣阿美族歌者郭英男（Difang Duana）等人的歌聲，後引發著作權與文化挪用相關爭議，是臺灣原住民族音樂與全球流行文化的重要案例。",source:"115 臺北市立內湖高工正式教師甄選音樂科（阿摩題庫）"}
]);