window.LOCAL_QUESTIONS = [
  {id:"JH-001",subject:"國中音樂",topic:"音樂教學法",level:"基礎",question:"重視歌唱、民謠素材、首調唱名與手勢系統的音樂教學法，最符合下列何者？",option_a:"達克羅茲",option_b:"奧福",option_c:"柯大宜",option_d:"鈴木",answer:"C",explanation:"柯大宜教學法強調歌唱、民謠、首調唱名與手勢，重視內在聽覺的建立。",source_title:"教甄核心知識練習（非正式原題）",source_url:"",tags:"教學法;柯大宜"},
  {id:"JH-002",subject:"國中音樂",topic:"二十世紀音樂",level:"理解",question:"「有限移位調式」與「不可逆行節奏」最具代表性的作曲家是誰？",option_a:"梅湘",option_b:"巴爾托克",option_c:"魏本",option_d:"柯普蘭",answer:"A",explanation:"梅湘常運用有限移位調式、不可逆行節奏、鳥鳴等素材。",source_title:"教甄核心知識練習（非正式原題）",source_url:"",tags:"梅湘;二十世紀"},
  {id:"JH-003",subject:"國中音樂",topic:"世界音樂",level:"基礎",question:"Reggae（雷鬼）音樂最具代表性的發源地為何？",option_a:"古巴",option_b:"牙買加",option_c:"巴西",option_d:"葡萄牙",answer:"B",explanation:"Reggae 發展於牙買加，並在20世紀後半成為具有全球影響力的音樂類型。",source_title:"教甄核心知識練習（非正式原題）",source_url:"",tags:"世界音樂;Reggae"},
  {id:"JH-004",subject:"國中音樂",topic:"世界音樂",level:"理解",question:"韓國 Pansori（盤索里）最典型的表演編制為何？",option_a:"一位說唱者搭配一位鼓手",option_b:"四人弦樂四重奏",option_c:"多人合唱搭配伽倻琴",option_d:"舞者搭配大型管弦樂團",answer:"A",explanation:"盤索里通常由一位歌者／說唱者與一位鼓手合作完成長篇敘事。",source_title:"教甄核心知識練習（非正式原題）",source_url:"",tags:"世界音樂;韓國;Pansori"},
  {id:"JH-005",subject:"國中音樂",topic:"世界音樂",level:"理解",question:"關於 Gamelan（甘美朗），下列何者最合理？",option_a:"主要以鋼琴與弦樂為核心",option_b:"主要流行於印尼，常使用鑼與金屬打擊樂器",option_c:"源自愛爾蘭民間舞曲",option_d:"必須使用西方指揮棒指揮",answer:"B",explanation:"甘美朗主要分布於印尼爪哇、峇里等地，合奏大量使用鑼與金屬打擊樂器。",source_title:"教甄核心知識練習（非正式原題）",source_url:"",tags:"世界音樂;甘美朗"},
  {id:"JH-006",subject:"國中音樂",topic:"曲式",level:"基礎",question:"若一首作品的主要段落結構為 A–B–A，最基本的曲式判斷為何？",option_a:"二段體",option_b:"三段體",option_c:"輪旋曲",option_d:"變奏曲",answer:"B",explanation:"A–B–A 是典型三段體的基本結構。",source_title:"教甄核心知識練習（非正式原題）",source_url:"",tags:"曲式;三段體"},

  {id:"HS-001",subject:"高中音樂",topic:"西洋音樂史",level:"理解",question:"「Infinite melody（無限旋律）」最常與哪位作曲家的音樂戲劇觀念連結？",option_a:"華格納",option_b:"威爾第",option_c:"德布西",option_d:"史特拉溫斯基",answer:"A",explanation:"華格納的音樂戲劇追求連續發展，避免傳統封閉式段落，形成無限旋律的概念。",source_title:"高中音樂教甄常見名詞練習（非正式原題）",source_url:"",tags:"華格納;歌劇"},
  {id:"HS-002",subject:"高中音樂",topic:"西洋音樂史",level:"進階",question:"18世紀 Sturm und Drang（狂飆風格）的音樂特徵，何者最符合？",option_a:"小調、強烈動態對比與突發性轉折",option_b:"全曲固定五聲音階",option_c:"完全避免轉調",option_d:"只使用單一力度",answer:"A",explanation:"狂飆風格強調情感張力，常見小調、強弱對比、突發休止與戲劇性轉折。",source_title:"高中音樂教甄常見名詞練習（非正式原題）",source_url:"",tags:"狂飆風格;古典前期"},
  {id:"HS-003",subject:"高中音樂",topic:"二十世紀音樂",level:"理解",question:"《Ludus Tonalis》是哪位20世紀作曲家的鋼琴作品？",option_a:"巴爾托克",option_b:"亨德密特",option_c:"荀貝格",option_d:"普羅柯菲夫",answer:"B",explanation:"《Ludus Tonalis》為 Paul Hindemith 的重要鋼琴作品。",source_title:"高中音樂教甄常見名詞練習（非正式原題）",source_url:"",tags:"Hindemith;Ludus Tonalis"},
  {id:"HS-004",subject:"高中音樂",topic:"臺灣音樂",level:"理解",question:"臺灣客家「老山歌」常見的旋律核心三音為何？",option_a:"Do–Re–Mi",option_b:"La–Do–Mi",option_c:"Sol–La–Do",option_d:"Re–Fa–La",answer:"B",explanation:"老山歌常以 La、Do、Mi 為旋律核心，並具有節奏自由、一字多音與拖腔等特色。",source_title:"高中音樂教甄核心知識練習（非正式原題）",source_url:"",tags:"臺灣音樂;客家;老山歌"},
  {id:"HS-005",subject:"高中音樂",topic:"巴洛克音樂",level:"進階",question:"sonata da chiesa 與 sonata da camera 最主要的差異，何者最合理？",option_a:"前者偏教會用途與較嚴謹對位，後者常帶舞曲性格",option_b:"前者只給鋼琴，後者只給管弦樂",option_c:"前者一定五樂章，後者一定三樂章",option_d:"兩者只差調性",answer:"A",explanation:"教會奏鳴曲較偏嚴謹與對位；室內奏鳴曲較自由，常與舞曲組曲性格相連。",source_title:"高中音樂教甄核心知識練習（非正式原題）",source_url:"",tags:"巴洛克;奏鳴曲"},
  {id:"HS-006",subject:"高中音樂",topic:"二十世紀音樂",level:"理解",question:"作品常以極度精煉的短音、音色對比與大量留白呈現點描式聲響，最容易聯想到第二維也納樂派哪位作曲家？",option_a:"荀貝格",option_b:"貝爾格",option_c:"魏本",option_d:"馬勒",answer:"C",explanation:"魏本作品常極度精煉，重視單音、音色、休止與聲響配置。",source_title:"高中音樂教甄核心知識練習（非正式原題）",source_url:"",tags:"魏本;第二維也納樂派"},

  {id:"EDU-001",subject:"教育專業",topic:"社會情緒學習",level:"理解",question:"下列何者不是 CASEL 社會情緒學習（SEL）五大核心能力之一？",option_a:"自我覺察",option_b:"社會覺察",option_c:"人際技巧",option_d:"自主行動",answer:"D",explanation:"CASEL五大核心能力包括自我覺察、自我管理、社會覺察、人際技巧與負責任的決定。",source_title:"教育專業核心知識練習（非正式原題）",source_url:"",tags:"SEL;CASEL"},
  {id:"EDU-002",subject:"教育專業",topic:"形成性評量",level:"理解",question:"教師在課程進行中透過提問、短任務與即時回饋掌握學生理解，再調整後續教學，最符合何種評量？",option_a:"形成性評量",option_b:"總結性評量",option_c:"常模參照評量",option_d:"安置性評量",answer:"A",explanation:"形成性評量發生於學習歷程中，目的是取得證據並調整教與學。",source_title:"教育專業核心知識練習（非正式原題）",source_url:"",tags:"形成性評量;課程與教學"},
  {id:"EDU-003",subject:"教育專業",topic:"班級經營",level:"理解",question:"學生在課堂中突然情緒失控並有攻擊風險時，教師第一優先原則為何？",option_a:"立即追究責任",option_b:"先確保學生本人與現場其他人的安全",option_c:"要求全班寫反省單",option_d:"立刻公開討論事件原因",answer:"B",explanation:"危機情境先處理安全與降溫，再進行後續支持、溝通與教育處遇。",source_title:"教育專業情境練習（非正式原題）",source_url:"",tags:"班級經營;危機處理"},
  {id:"EDU-004",subject:"教育專業",topic:"特殊教育",level:"進階",question:"面對同時具有音樂資優與身心障礙需求的學生，下列何者最符合適性教育原則？",option_a:"只強化音樂優勢，忽略障礙需求",option_b:"只依障礙降低所有學習期待",option_c:"同時發展優勢並提供合理支持與課程調整",option_d:"盡量避免團體活動",answer:"C",explanation:"雙重特殊需求學生應兼顧優勢潛能與障礙支持，透過個別化調整與跨專業合作促進學習。",source_title:"教育專業情境練習（非正式原題）",source_url:"",tags:"雙重特殊需求;特殊教育"},
  {id:"EDU-005",subject:"教育專業",topic:"十二年國教",level:"基礎",question:"下列何者屬於十二年國教課程中常見的議題融入範疇？",option_a:"性別平等教育",option_b:"多元文化教育",option_c:"原住民族教育",option_d:"以上皆是",answer:"D",explanation:"議題融入可涵蓋性別平等、多元文化、原住民族、閱讀素養等多項議題。",source_title:"教育專業核心知識練習（非正式原題）",source_url:"",tags:"十二年國教;議題融入"},
  {id:"EDU-006",subject:"教育專業",topic:"課程設計",level:"理解",question:"素養導向教學設計最不適合只停留在哪一層次？",option_a:"連結真實情境",option_b:"讓學生應用知識解決問題",option_c:"只要求記憶單一知識點而沒有應用",option_d:"整合知識、技能與態度",answer:"C",explanation:"素養強調能在情境中整合知識、技能與態度並實際運用，不只是記憶知識。",source_title:"教育專業核心知識練習（非正式原題）",source_url:"",tags:"素養導向;課程設計"}
];
