// 111 年中等音樂教甄考點擴充：新北、臺北雙語、高雄高中
// 依阿摩歷屆試卷考點整理改寫，避免逐字重製原卷；保留來源供核對。
(function(){
  const batch = [
    {year:"111",level:"國中音樂",exam:"111新北市立國民中學教師聯合甄選",topic:"西洋音樂史",difficulty:"中",q:"下列哪一位作曲家屬於德奧晚期浪漫樂派，並以大型交響曲與歌曲創作聞名？",options:["Gustav Mahler","François Couperin","John Cage","Claude Debussy"],answer:0,explanation:"Mahler 是德奧晚期浪漫主義的重要作曲家與指揮家，交響曲與歌曲套曲為其核心創作。",source:"阿摩111新北國中音樂科#108396"},
    {year:"111",level:"國中音樂",exam:"111新北市立國民中學教師聯合甄選",topic:"英國音樂",difficulty:"中",q:"《Enigma Variations（謎語變奏曲）》的作曲家是誰？",options:["Edward Elgar","Edvard Grieg","Jean Sibelius","Bedřich Smetana"],answer:0,explanation:"Elgar 是英國浪漫時期代表作曲家，《謎語變奏曲》與《威風凜凜進行曲》均為代表作。",source:"阿摩111新北國中音樂科#108396"},
    {year:"111",level:"國中音樂",exam:"111新北市立國民中學教師聯合甄選",topic:"國民樂派",difficulty:"中",q:"《Peer Gynt（皮爾金組曲）》與 a 小調鋼琴協奏曲最常與哪位挪威作曲家連結？",options:["Grieg","Sibelius","Dvořák","Balakirev"],answer:0,explanation:"Edvard Grieg 是挪威國民樂派的重要人物，代表作包含《皮爾金》配樂與 a 小調鋼琴協奏曲。",source:"阿摩111新北國中音樂科#108396"},
    {year:"111",level:"國中音樂",exam:"111新北市立國民中學教師聯合甄選",topic:"音樂劇",difficulty:"易",q:"音樂劇《Cats（貓）》的作曲者是誰？",options:["Andrew Lloyd Webber","Leonard Bernstein","Stephen Sondheim","Richard Rodgers"],answer:0,explanation:"《Cats》由 Andrew Lloyd Webber 作曲，改編自 T. S. Eliot 的詩集。",source:"阿摩111新北國中音樂科#108396"},
    {year:"111",level:"國中音樂",exam:"111新北市立國民中學教師聯合甄選",topic:"國民樂派",difficulty:"中",q:"交響詩《Finlandia（芬蘭頌）》是哪位作曲家的代表作？",options:["Jean Sibelius","Edvard Grieg","Antonín Dvořák","Carl Nielsen"],answer:0,explanation:"《芬蘭頌》是芬蘭作曲家 Sibelius 最具代表性的民族精神作品之一。",source:"阿摩111新北國中音樂科#108396"},
    {year:"111",level:"國中音樂",exam:"111新北市立國民中學教師聯合甄選",topic:"俄國音樂",difficulty:"中",q:"技巧艱深的鋼琴幻想曲《Islamey》出自哪位俄國作曲家？",options:["Mily Balakirev","Modest Mussorgsky","Nikolai Rimsky-Korsakov","Alexander Borodin"],answer:0,explanation:"《Islamey》是俄國五人組領導人物 Balakirev 的著名鋼琴作品。",source:"阿摩111新北國中音樂科#108396"},
    {year:"111",level:"國中音樂",exam:"111臺北市國中教師聯合甄選音樂雙語科",topic:"雙語樂理",difficulty:"易",q:"In music, pitch, interval, and contour are most directly associated with which element?",options:["Melody","Timbre","Texture","Form"],answer:0,explanation:"Pitch、interval 與 contour 都是描述旋律線的重要概念，因此答案為 melody。",source:"阿摩111臺北國中音樂雙語科#108152"},
    {year:"111",level:"國中音樂",exam:"111臺北市國中教師聯合甄選音樂雙語科",topic:"雙語樂理",difficulty:"易",q:"Which musical element refers to the simultaneous vertical combination of pitches?",options:["Harmony","Articulation","Dynamics","Timbre"],answer:0,explanation:"Harmony 指多個音高在垂直方向同時結合所形成的和聲關係。",source:"阿摩111臺北國中音樂雙語科#108152"},
    {year:"111",level:"國中音樂",exam:"111臺北市國中教師聯合甄選音樂雙語科",topic:"作品編號",difficulty:"中",q:"The catalogue abbreviation “Hob.” is associated with the works of which composer?",options:["Joseph Haydn","J. S. Bach","Franz Schubert","Frédéric Chopin"],answer:0,explanation:"Hob. 為 Anthony van Hoboken 編纂的海頓作品目錄編號。",source:"阿摩111臺北國中音樂雙語科#108152"},
    {year:"111",level:"國中音樂",exam:"111臺北市國中教師聯合甄選音樂雙語科",topic:"音樂教育",difficulty:"中",q:"Which music educator uses “inference learning” as an important level in music learning theory?",options:["Edwin Gordon","Bennett Reimer","David Elliott","Peter Webster"],answer:0,explanation:"Edwin Gordon 的 Music Learning Theory 區分 discrimination learning 與 inference learning。",source:"阿摩111臺北國中音樂雙語科#108152"},
    {year:"111",level:"國中音樂",exam:"111臺北市國中教師聯合甄選音樂雙語科",topic:"古典樂派",difficulty:"易",q:"Alberti bass is most strongly associated with which period?",options:["Classical","Renaissance","Baroque","20th century"],answer:0,explanation:"阿爾貝蒂低音是古典時期常見的伴奏音型，常見於鋼琴奏鳴曲。",source:"阿摩111臺北國中音樂雙語科#108152"},
    {year:"111",level:"國中音樂",exam:"111臺北市國中教師聯合甄選音樂雙語科",topic:"節奏",difficulty:"中",q:"Two groups of three pulses perceived as three groups of two pulses is called what?",options:["Hemiola","Syncopation","Polyrhythm","Ostinato"],answer:0,explanation:"Hemiola 常形成 3:2 的節拍重新分組感，在巴洛克舞曲與後世作品中都常見。",source:"阿摩111臺北國中音樂雙語科#108152"},
    {year:"111",level:"高中音樂",exam:"111高雄市立高級中等學校聯合教師甄選",topic:"音樂科技",difficulty:"易",q:"下列何者主要是樂譜製作軟體，而非以錄音波形編輯為主要功能？",options:["Sibelius","Audacity","Sound Forge","GoldWave"],answer:0,explanation:"Sibelius 主要用於樂譜輸入、排版與播放；其餘選項皆以聲音錄製或波形編輯功能著稱。",source:"阿摩111高雄高中聯招音樂科#108161"},
    {year:"111",level:"高中音樂",exam:"111高雄市立高級中等學校聯合教師甄選",topic:"世界音樂",difficulty:"中",q:"蒙古與圖瓦等中亞文化中，一位歌者可同時呈現基音與泛音旋律的歌唱技巧稱為什麼？",options:["呼麥（Khoomei）","Pansori","Qawwali","Yodel"],answer:0,explanation:"呼麥是一種泛音歌唱技法，演唱者藉由共鳴腔控制，使泛音形成可辨識的第二旋律。",source:"阿摩111高雄高中聯招音樂科#108161申論考點"},
    {year:"111",level:"高中音樂",exam:"111高雄市立高級中等學校聯合教師甄選",topic:"世界音樂",difficulty:"中",q:"印度古典音樂中，用以組織旋律音高、具有特定音程與旋律行進規範的概念為何？",options:["Raga","Tala","Gamelan","Milonga"],answer:0,explanation:"Raga（拉加）是印度古典音樂的旋律框架；Tala 則主要指節奏循環。",source:"阿摩111高雄高中聯招音樂科#108161申論考點"},
    {year:"111",level:"高中音樂",exam:"111高雄市立高級中等學校聯合教師甄選",topic:"現代音樂",difficulty:"中",q:"以重複短小動機、漸進式變化與穩定脈動為常見特徵的二十世紀音樂風格是？",options:["Minimalism","Expressionism","Spectralism","Musique concrète"],answer:0,explanation:"Minimalism 常以反覆音型、相位變化與逐步變化建立音樂過程，Reich、Glass 等為代表人物。",source:"阿摩111高雄高中聯招音樂科#108161申論考點"}
  ];
  window.QUESTION_BANK = window.QUESTION_BANK || [];
  window.QUESTION_BANK.push(...batch);
})();
