// 115 中區縣市政府教師甄選策略聯盟｜國中音樂科｜高鑑別第一批
window.QUESTIONS = window.QUESTIONS || [];
window.QUESTIONS.push(
{year:"115",school:"中區縣市政府教師甄選策略聯盟",level:"國中",type:"choice",difficulty:"👹",topic:"臺灣傳統音樂",question:"民間藝人陳達演唱臺灣說唱歌謠時，最具代表性的伴奏樂器為何？",options:["三弦","月琴","阮咸","琵琶"],answer:1,explanation:"陳達是臺灣民間歌謠與說唱傳統的重要藝人，常以月琴自彈自唱。教甄常把月琴、三弦、琵琶、阮互換。"},
{year:"115",school:"中區縣市政府教師甄選策略聯盟",level:"國中",type:"choice",difficulty:"中",topic:"中國器樂",question:"下列哪一首作品原初為二胡獨奏曲？",options:["《月兒高》","《賽馬》","《廣陵散》","《離騷》"],answer:1,explanation:"《賽馬》是黃海懷著名二胡作品；《廣陵散》《離騷》與古琴傳統相關，《月兒高》常見於琵琶等器樂版本。"},
{year:"115",school:"中區縣市政府教師甄選策略聯盟",level:"國中",type:"choice",difficulty:"👹",topic:"譜表",question:"若某五線譜的第三間所記音名為 F，最可能使用哪一種 C 譜表？",options:["Soprano clef","Mezzo-soprano clef","Alto clef","Tenor clef"],answer:2,explanation:"Alto clef 的 C 譜號中心落在第三線，因此第三間為 F。辨識 C 譜表時，先找『中央C落在哪一線』，比死背每個間線音名可靠。"},
{year:"115",school:"中區縣市政府教師甄選策略聯盟",level:"國中",type:"choice",difficulty:"👹",topic:"巴洛克",question:"J. S. Bach 的管風琴作品 BWV 596 改編／引用自哪位作曲家的協奏曲？",options:["Handel","Purcell","Rameau","Vivaldi"],answer:3,explanation:"BWV 596 是 Bach 對 Vivaldi 協奏曲素材的管風琴改編，反映 Bach 對義大利協奏曲風格的吸收。"},
{year:"115",school:"中區縣市政府教師甄選策略聯盟",level:"國中",type:"choice",difficulty:"👹",topic:"巴洛克",question:"Pachelbel 著名《Canon and Gigue》最常見的調性為何？",options:["D大調","G大調","D小調","B小調"],answer:0,explanation:"著名的 Pachelbel Canon 為 D major。命題常把關係大小調、屬調、下屬調包裝成推理題。"},
{year:"115",school:"中區縣市政府教師甄選策略聯盟",level:"國中",type:"choice",difficulty:"👹",topic:"歌劇",question:"1821年首演、取材民間傳說，並被視為德國浪漫主義歌劇重要里程碑的作品是？",options:["《魔彈射手》","《費加洛的婚禮》","《茶花女》","《魔笛》"],answer:0,explanation:"Weber《Der Freischütz》（魔彈射手）1821年柏林首演，是德國浪漫歌劇代表作；森林、狩獵、超自然題材與德語傳統都是辨識線索。"},
{year:"115",school:"中區縣市政府教師甄選策略聯盟",level:"國中",type:"choice",difficulty:"中",topic:"歌劇",question:"下列哪一部不是 Giuseppe Verdi 的歌劇？",options:["《Rigoletto》","《La traviata》","《La bohème》","《Aida》"],answer:2,explanation:"《La bohème》為 Puccini 代表作；其餘三部皆為 Verdi。人物—作品錯配是教甄高頻陷阱。"},
{year:"115",school:"中區縣市政府教師甄選策略聯盟",level:"國中",type:"choice",difficulty:"👹",topic:"藝術領綱",question:"下列何者不是十二年國教藝術領域三大學習構面？",options:["表現 Expression","鑑賞 Appreciation","實踐 Practice","探索 Exploration"],answer:3,explanation:"藝術領域三大學習構面為表現、鑑賞、實踐。『探索』會出現在學習表現敘述中，但不是三大構面之一。"}
);