// 112 臺中一中音樂科｜歷屆考點改寫
window.EXTRA_QUESTIONS = window.EXTRA_QUESTIONS || [];
window.EXTRA_QUESTIONS.push(
  {id:'112-tcfsh-01',year:112,subject:'高中音樂',topic:'臺灣傳統音樂',level:'進階',question:'下列何者「不是」北管常見的音樂型態／曲類名稱？',options:['整弦','細曲','牌子','弦譜'],answer:3,explanation:'北管常見曲類可見牌子、細曲、譜等不同分類脈絡；「弦譜」則是南管的重要曲類名稱之一，因此是本題辨識關鍵。',source:'112 臺中一中音樂科'},
  {id:'112-tcfsh-02',year:112,subject:'高中音樂',topic:'音樂術語',level:'基礎',question:'下列音樂術語與中文意義的配對，何者正確？',options:['Cantabile－如歌的','Delicato－莊嚴的','Tranquillo－急促的','Con brio－悲傷地'],answer:0,explanation:'Cantabile 意為「如歌的」。Delicato 偏向細緻、優雅；Tranquillo 為平靜地；Con brio 為有精神、有活力地。',source:'112 臺中一中音樂科'},
  {id:'112-tcfsh-03',year:112,subject:'高中音樂',topic:'西洋音樂史',level:'魔王',question:'關於歌劇史，下列何者錯誤？',options:['18世紀喜歌劇發展與中產階級文化興起有關','華格納強調音樂戲劇整體性與連續發展','Monteverdi 的代表作包含 Verdi 的《Il trovatore（吟遊詩人）》','Rossini 的歌劇配器充分運用木管色彩'],answer:2,explanation:'《Il trovatore》是 Giuseppe Verdi 的歌劇，不是 Monteverdi。此題故意利用兩位義大利作曲家姓名相似製造干擾。',source:'112 臺中一中音樂科'},
  {id:'112-tcfsh-04',year:112,subject:'高中音樂',topic:'20世紀音樂',level:'進階',question:'《Pierrot lunaire（月光小丑）》的作曲家是誰？',options:['Arnold Schoenberg','Claude Debussy','Anton Webern','Gustav Mahler'],answer:0,explanation:'《Pierrot lunaire》Op.21（1912）為 Schoenberg 代表作之一，使用 Sprechstimme（說唱式聲樂）並展現表現主義語彙。',source:'112 臺中一中音樂科'},
  {id:'112-tcfsh-05',year:112,subject:'高中音樂',topic:'中國音樂',level:'進階',question:'下列中國器樂作品中，哪一首以嗩吶模擬鳥鳴、人聲般音色效果而著名？',options:['《漁舟唱晚》','《百鳥朝鳳》','《廣陵散》','《二泉映月》'],answer:1,explanation:'《百鳥朝鳳》是著名嗩吶曲，運用循環換氣、吐音與模擬鳥鳴等技巧，是「器樂模擬自然／人聲效果」的高頻考點。',source:'112 臺中一中音樂科考點延伸'},
  {id:'112-tcfsh-06',year:112,subject:'高中音樂',topic:'原住民族音樂',level:'進階',question:'下列族群與代表祭儀／歌樂的配對，何者有誤？',options:['賽夏族－矮靈祭','達悟族－頭髮舞','布農族－祈禱小米豐收歌','鄒族－戰祭'],answer:0,explanation:'矮靈祭是賽夏族重要祭儀，不是阿美族。教甄常用「族群－祭儀－歌樂」交叉配對出題。',source:'112 臺中一中音樂科考點改寫'},
  {id:'112-tcfsh-07',year:112,subject:'高中音樂',topic:'樂器學',level:'基礎',question:'下列哪一項屬於有固定音高的打擊樂器？',options:['Cymbal','Tubular Bells／Chimes','Triangle','Castanets'],answer:1,explanation:'Tubular bells（管鐘，亦常稱 orchestral chimes）具有明確音高；鈸、三角鐵、響板通常歸為無固定音高打擊樂器。',source:'112 臺中一中音樂科'},
  {id:'112-tcfsh-08',year:112,subject:'高中音樂',topic:'南管',level:'魔王',question:'下列何者不是南管「上四管」的核心樂器？',options:['二弦','洞簫','琵琶','嗩吶'],answer:3,explanation:'南管上四管核心為琵琶、三弦、二弦、洞簫；嗩吶並非上四管。這類編制細節是教甄常見冷門題。',source:'112 臺中一中音樂科'},
  {id:'112-tcfsh-09',year:112,subject:'高中音樂',topic:'西洋音樂史',level:'魔王',question:'下列作品與素材來源的敘述，何者錯誤？',options:['Britten《青少年管弦樂入門》以 Purcell 主題為基礎','Schubert《冬之旅》採用 Wilhelm Müller 詩作','Brahms《D大調小提琴協奏曲》與 Joseph Joachim 關係密切','Stravinsky《春之祭》引用 Gregorian chant〈Dies irae〉作為主要素材'],answer:3,explanation:'《春之祭》的重要素材與俄羅斯／立陶宛民間旋律研究相關，不能把它和〈Dies irae〉的引用混為一談。',source:'112 臺中一中音樂科'},
  {id:'112-tcfsh-10',year:112,subject:'高中音樂',topic:'臺灣音樂家',level:'進階',question:'1960年代與史惟亮推動臺灣大規模民歌採集運動，並創作《葬花吟》等作品的音樂家是誰？',options:['許常惠','呂泉生','郭芝苑','蕭泰然'],answer:0,explanation:'許常惠是臺灣現代音樂創作、民族音樂研究與民歌採集的重要人物，1967年與史惟亮推動民歌採集運動。',source:'112 臺中一中音樂科非選題'},
  {id:'112-tcfsh-11',year:112,subject:'高中音樂',topic:'臺灣音樂家',level:'進階',question:'《杯底不可飼金魚》、《搖嬰仔歌》、《阮若打開心內的門窗》與下列哪位音樂家關係最密切？',options:['呂泉生','許常惠','江文也','馬水龍'],answer:0,explanation:'呂泉生長期投入臺灣歌曲、合唱教育與兒童合唱推廣，《阮若打開心內的門窗》等為重要代表。',source:'112 臺中一中音樂科非選題'},
  {id:'112-tcfsh-12',year:112,subject:'高中音樂',topic:'臺灣音樂家',level:'魔王',question:'下列哪位臺灣音樂家以《客家隨想曲》、《客家協奏曲》及鋼琴變奏曲《老山歌》等作品著稱？',options:['蘇凡凌','陳建年','郭芝苑','鄭榮興'],answer:0,explanation:'蘇凡凌長期投入客家音樂創作與研究，相關作品是臺灣音樂家人物辨識中的冷門考點。',source:'112 臺中一中音樂科非選題考點'}
);