window.QUESTIONS = window.QUESTIONS || [];
window.QUESTIONS.push(
{year:"111",level:"教育專業",exam:"111金門縣國中教師聯合甄選",topic:"評量",difficulty:"中",question:"教師依學習目標，讓學生系統性彙整作品、紀錄與相關資料，以呈現一段時間的學習歷程與成果，最符合哪一種評量？",options:["紙筆評量","檔案評量","常模評量","診斷評量"],answer:1,explanation:"檔案評量（portfolio assessment）重視一段時間內學習證據的系統性蒐集、整理與反思。",source:"阿摩111金門縣國中教育專業第12題考點改寫"},
{year:"111",level:"教育專業",exam:"111金門縣國中教師聯合甄選",topic:"班級經營",difficulty:"中",question:"教師說：『我聽到你持續敲桌子的聲音，這會干擾我上課，也影響同學學習，我感到困擾，希望你停止。』這最符合哪一種溝通方式？",options:["你訊息","我訊息","權威命令","消弱訊息"],answer:1,explanation:"我訊息通常描述具體行為、對自己的影響與感受，再表達期待，避免直接貼標籤或責備學生。",source:"阿摩111金門縣國中教育專業第15題考點改寫"},
{year:"111",level:"教育專業",exam:"111金門縣國中教師聯合甄選",topic:"教育哲學",difficulty:"中",question:"R. S. Peters 對『教育』提出的三項重要規準，不包含下列何者？",options:["合價值性","合認知性","合自願性","合團體性"],answer:3,explanation:"Peters 常見的教育規準為合價值性、合認知性與合自願性；『合團體性』不在其中。",source:"阿摩111金門縣國中教育專業第16題考點改寫"},
{year:"111",level:"教育專業",exam:"111金門縣國中教師聯合甄選",topic:"十二年國教",difficulty:"易",question:"十二年國教核心素養中的『系統思考與解決問題』及『身心素質與自我精進』，都屬於哪一個面向？",options:["自主行動","溝通互動","社會參與","多元文化"],answer:0,explanation:"核心素養三大面向為自主行動、溝通互動、社會參與；身心素質與自我精進、系統思考與解決問題皆屬自主行動。",source:"阿摩111金門縣國中教育專業第17題考點改寫"},
{year:"111",level:"教育專業",exam:"111金門縣國中教師聯合甄選",topic:"課程與教學",difficulty:"中",question:"學校自行規劃全校性、全年級或班群學習活動，以落實學校本位與特色課程，最符合十二年國教中的哪一類課程？",options:["領域學習課程","彈性學習課程","部定必修課程","空白課程"],answer:1,explanation:"國中小的彈性學習課程由學校依願景、特色與學生需求規劃，可包含統整性主題、社團、技藝、特殊需求等。",source:"阿摩111金門縣國中教育專業第19題考點改寫"},
{year:"111",level:"教育專業",exam:"111金門縣國中教師聯合甄選",topic:"教育行政",difficulty:"中",question:"在競值架構（Competing Values Framework）中，同時強調『外部焦點』與『彈性』的組織模式為何？",options:["理性目標模式","內部過程模式","人群關係模式","開放系統模式"],answer:3,explanation:"競值架構中，外部＋彈性對應開放系統模式；外部＋控制為理性目標，內部＋彈性為人群關係，內部＋控制為內部過程。",source:"阿摩111金門縣國中教育專業第43題考點改寫"},
{year:"111",level:"教育專業",exam:"111金門縣國中教師聯合甄選",topic:"教育行政",difficulty:"中",question:"情境領導理論中，若部屬對工作既缺乏能力又缺乏意願，領導者最適合採取哪一種方式？",options:["告知式","推銷式","參與式","授權式"],answer:0,explanation:"低成熟度／低準備度部屬需要高度工作指導與較低關係支持，對應告知式（telling/directing）。",source:"阿摩111金門縣國中教育專業第45題考點改寫"},
{year:"111",level:"教育專業",exam:"111金門縣國中教師聯合甄選",topic:"課程與教學",difficulty:"中",question:"Bruner 的螺旋式課程讓重要概念在不同年級反覆出現，並逐漸提高複雜度，主要體現哪兩項課程組織規準？",options:["繼續性與順序性","繼續性與統整性","順序性與統整性","統整性與銜接性"],answer:0,explanation:"概念反覆出現體現繼續性，內容逐步加深加廣則體現順序性。",source:"阿摩111金門縣國中教育專業第49題考點改寫"},
{year:"111",level:"教育專業",exam:"111金門縣國中教師聯合甄選",topic:"認知心理",difficulty:"中",question:"把『5616616』轉換成一句有意義、容易記住的語句，最直接運用了訊息處理歷程中的哪一項策略？",options:["注意","編碼","感覺記憶","提取失敗"],answer:1,explanation:"將原始材料轉換成有意義的形式屬於編碼策略，可增加訊息進入長期記憶的機會。",source:"阿摩111金門縣國中教育專業第55題考點改寫"},
{year:"111",level:"教育專業",exam:"111金門縣國中教師聯合甄選",topic:"教育哲學",difficulty:"中",question:"108課綱強調跨領域『探索與實作』，若從教育哲學來看，最接近哪一學派強調做中學、經驗與問題解決的精神？",options:["永恆主義","實驗主義","存在主義","精粹主義"],answer:1,explanation:"實驗主義／進步主義受 Dewey 影響，重視經驗、做中學與真實問題解決。",source:"阿摩111金門縣國中教育專業第65題考點改寫"},
{year:"111",level:"高中音樂",exam:"111國立嘉義高中教師甄選",topic:"和聲",difficulty:"難",question:"在 D 大調中，拿坡里六和弦（Neapolitan Sixth）通常可理解為哪一個和弦的第一轉位？",options:["降二級大三和弦","二級小三和弦","降六級大三和弦","屬七和弦"],answer:0,explanation:"Neapolitan chord 通常是建立在降二級上的大三和弦（♭II），實務上常以第一轉位 N6 出現。",source:"阿摩111嘉義高中音樂科第3題考點延伸改寫；原卷標示無官方正解"},
{year:"111",level:"高中音樂",exam:"111國立嘉義高中教師甄選",topic:"和聲",difficulty:"難",question:"下列哪一項最能區分 French augmented-sixth chord 與 German augmented-sixth chord？",options:["French sixth 含升四級，German sixth 不含","German sixth 通常具有四個不同音，而 French sixth 只有三音","French sixth 的內聲部通常形成二級音，German sixth 則常包含降三級音","German sixth 不具有增六度音程"],answer:2,explanation:"兩者皆以降六級與升四級形成增六度；French +6 常含二級音，German +6 常含降三級音，因而產生不同的和聲色彩與解決問題。",source:"依阿摩111嘉義高中音樂科增六和弦題群改寫；原卷標示無官方正解"}
);