window.QUESTIONS = window.QUESTIONS || [];
window.QUESTIONS.push(
{year:"115",level:"國中音樂",exam:"桃園市國民中學新進教師聯合甄選",topic:"音樂術語",difficulty:"中",question:"音樂術語 calando 最接近下列哪一種速度與力度變化？",options:["漸慢且漸弱","漸快且漸強","漸慢且漸強","漸快且漸弱"],answer:0,explanation:"calando 通常表示聲音逐漸消退，常呈現漸慢並漸弱的效果。",source:"阿摩115桃園國中音樂第52題考點改寫"},
{year:"115",level:"國中音樂",exam:"桃園市國民中學新進教師聯合甄選",topic:"二十世紀音樂",difficulty:"中高",question:"Aleatory Music（機遇音樂）的核心概念最接近下列何者？",options:["固定使用十二音列控制所有音高","將部分結構或演奏決定權交給機遇或演奏者","只採集現實聲音重新剪接","以持續不規則重音為主要特徵"],answer:1,explanation:"機遇音樂強調把部分音樂結果交由偶然、機率或演奏者選擇決定。",source:"阿摩115桃園國中音樂第54題考點改寫"},
{year:"115",level:"國中音樂",exam:"桃園市國民中學新進教師聯合甄選",topic:"舞劇與作曲家",difficulty:"中",question:"下列芭蕾舞劇與作曲家的配對，何者錯誤？",options:["《天鵝湖》－柴科夫斯基","《唐吉訶德》－德利伯","《胡桃鉗》－柴科夫斯基","《吉賽兒》－阿道夫・亞當"],answer:1,explanation:"《唐吉訶德》著名芭蕾音樂由 Ludwig Minkus 作曲；Delibes 的代表芭蕾包括《Coppélia》與《Sylvia》。",source:"阿摩115桃園國中音樂第55題考點改寫"},
{year:"115",level:"國中音樂",exam:"桃園市國民中學新進教師聯合甄選",topic:"二十世紀音樂",difficulty:"中",question:"各聲部以短小音型持續交錯、反覆堆疊，最可能屬於哪一種20世紀後半葉創作手法？",options:["Aleatory Music","Serialism","Musique concrète","Minimal Music"],answer:3,explanation:"Minimal Music 常以短小動機、規律反覆、漸進變化與層次堆疊形成音樂進程。",source:"阿摩115桃園國中音樂第56題考點改寫"},
{year:"115",level:"國中音樂",exam:"桃園市國民中學新進教師聯合甄選",topic:"音樂史",difficulty:"中",question:"交響詩（Symphonic Poem）最典型的特徵為何？",options:["多樂章且使用固定古典形式","單樂章的標題性管弦樂作品","只用於教會禮儀的合唱作品","歌劇前奏曲的固定名稱"],answer:1,explanation:"交響詩為浪漫時期重要的標題音樂體裁，通常採單樂章管弦樂形式。",source:"阿摩115桃園國中音樂第59題考點改寫"},
{year:"115",level:"國中音樂",exam:"桃園市國民中學新進教師聯合甄選",topic:"古典時期",difficulty:"中",question:"海頓第45號《告別》交響曲末樂章安排樂手陸續離席，主要用意為何？",options:["哀悼國王逝世","抗議樂團裁員","暗示雇主讓團員返鄉休假","進行前衛劇場實驗"],answer:2,explanation:"海頓藉樂手逐一離席，委婉向 Esterházy 親王表達團員希望結束長期駐留、返家探親。",source:"阿摩115桃園國中音樂第61題考點改寫"},
{year:"115",level:"國中音樂",exam:"桃園市國民中學新進教師聯合甄選",topic:"宗教音樂",difficulty:"中高",question:"傳統羅馬天主教安魂彌撒（Requiem Mass）相較常規彌撒，通常省略哪兩段較具歡欣讚頌性質的經文？",options:["Kyrie與Agnus Dei","Gloria與Credo","Sanctus與Introitus","Dies irae與Offertorium"],answer:1,explanation:"傳統安魂彌撒通常省略 Gloria 與 Credo，並加入如 Introitus、Dies irae 等專屬文本。",source:"阿摩115桃園國中音樂第62題考點改寫"},
{year:"115",level:"國中音樂",exam:"桃園市國民中學新進教師聯合甄選",topic:"臺灣傳統音樂",difficulty:"中",question:"臺灣傳統音樂中，以典雅細緻風格著稱，且與唐宋大曲歷史脈絡關係密切者為何？",options:["北管","南管","雜劇","傳奇"],answer:1,explanation:"南管保存深厚古樂傳統，風格細緻典雅，是臺灣重要傳統音樂類型。",source:"阿摩115桃園國中音樂第64題考點改寫"},
{year:"115",level:"教育專業",exam:"中區縣市政府教師甄選策略聯盟",topic:"學生輔導法規",difficulty:"中",question:"依高級中等以下學校學生輔導相關規定，學校每學年為一般教職員辦理輔導知能在職進修，至少應達多少時數？",options:["36小時","12小時","18小時","3小時"],answer:3,explanation:"一般教職員每學年應接受至少3小時學生輔導知能相關在職進修。",source:"阿摩115中區教育專業第1題考點改寫"},
{year:"115",level:"教育專業",exam:"中區縣市政府教師甄選策略聯盟",topic:"教育哲學",difficulty:"中",question:"重建主義（Reconstructionism）的教育主張最強調下列何者？",options:["社會議題、社會參與與公民責任","學生個人興趣與完全自由","回歸學科基本知識","追求永恆不變的真理"],answer:0,explanation:"重建主義將教育視為改造社會的重要力量，重視公共議題、民主參與及社會改革。",source:"阿摩115中區教育專業第3題考點改寫"},
{year:"115",level:"教育專業",exam:"中區縣市政府教師甄選策略聯盟",topic:"課程理論",difficulty:"中",question:"Goodlad 課程層次中，最直接描述學生實際經歷與感受到的課程為何？",options:["理念課程","正式課程","知覺課程","經驗課程"],answer:3,explanation:"Goodlad 的 experienced curriculum 指學生真正經驗到的課程；它關注學習者實際的學習歷程與感受。",source:"阿摩115中區教育專業第4題考點改寫"},
{year:"115",level:"國中音樂",exam:"桃園市國民中學新進教師聯合甄選",topic:"音樂科技與倫理",difficulty:"中高",question:"學生使用AI工具生成畢業歌曲後，教師最應優先引導討論哪一議題？",options:["如何提高生成速度","如何全面取代真人創作","著作權歸屬與倫理使用","如何縮短抄譜時間"],answer:2,explanation:"AI音樂創作涉及資料來源、著作權、署名與合理使用等倫理與法律議題，應優先建立學生的負責任使用觀念。",source:"阿摩115桃園國中音樂第87題考點改寫"}
);