window.QUESTIONS = (window.QUESTIONS || []).concat([
{id:"MOE115-NC-01",year:115,subject:"高中音樂",topic:"歌劇與音樂劇",level:"👹魔王",question:"18世紀中葉後，各國喜歌劇發展出不同名稱。德國具有口說對白的喜歌劇傳統通常稱為何者？",options:["Opéra comique","Singspiel","Opera buffa","Ballad opera"],answer:1,explanation:"Singspiel 是德語地區結合歌唱與口說對白的重要戲劇類型。教甄常把各國喜歌劇名稱交叉配對考：義大利 opera buffa、法國 opéra comique、德國 Singspiel、英國 ballad opera。",source:"115教育部高中教師甄選音樂科非選題考點改寫"},
{id:"MOE115-NC-02",year:115,subject:"高中音樂",topic:"歌劇與音樂劇",level:"👹魔王",question:"若題目要求寫出18世紀英國具有口說對白、通俗歌曲改編特色的喜歌劇類型，最適合的答案為何？",options:["Ballad opera","Singspiel","Opera seria","Zarzuela"],answer:0,explanation:"Ballad opera（民謠歌劇）是18世紀英國的重要喜劇性音樂戲劇類型，常以既有通俗曲調配新詞並穿插口說對白，《乞丐歌劇》是代表例。",source:"115教育部高中教師甄選音樂科非選題考點改寫"},
{id:"MOE115-NC-03",year:115,subject:"高中音樂",topic:"臺灣音樂",level:"困難",question:"馬水龍《臺灣組曲》最適合從哪一個角度理解其創作特色？",options:["完全模仿十二音列技法","以五聲音階與現代鋼琴語彙描繪臺灣民俗、宗教與生活意象","以爵士大樂團寫成四首舞曲","全部直接引用西方聖詠旋律"],answer:1,explanation:"《臺灣組曲》以現代鋼琴語彙結合五聲性素材與臺灣文化意象。教甄若考作品，不只要背曲名，更要能連結作曲家、媒介、文化素材與創作語法。",source:"115教育部高中教師甄選音樂科非選題考點改寫"},
{id:"MOE115-NC-04",year:115,subject:"高中音樂",topic:"音樂史",level:"困難",question:"Cori spezzati 最直接與下列哪一個音樂史脈絡相關？",options:["威尼斯聖馬可大教堂的分置合唱傳統","巴黎聖母院的奧爾加農","曼海姆樂派的漸強","第二維也納樂派的十二音技法"],answer:0,explanation:"Cori spezzati 指將合唱／器樂群分置於不同空間位置，形成對答與空間音響效果，與16世紀威尼斯樂派及聖馬可大教堂聲學環境密切相關。",source:"115教育部高中教師甄選音樂科名詞解釋考點改寫"},
{id:"MOE115-NC-05",year:115,subject:"高中音樂",topic:"二十世紀音樂",level:"困難",question:"下列何者最能說明 Prepared Piano（預置鋼琴）的概念？",options:["將鋼琴調成純律","在琴弦之間或琴弦上放置物件以改變音色與共鳴","以兩架鋼琴相差四分之一音演奏","只使用鋼琴內部直接撥弦而禁止鍵盤"],answer:1,explanation:"Prepared Piano 常與 John Cage 聯繫，透過螺絲、橡膠等物件改變琴弦振動，使鋼琴產生近似打擊樂器的多樣音色。",source:"115教育部高中教師甄選音樂科名詞解釋考點改寫"},
{id:"MOE115-NC-06",year:115,subject:"高中音樂",topic:"世界音樂",level:"👹魔王",question:"Pansori（盤索里）屬於哪一文化傳統？",options:["日本能樂的器樂間奏","韓國由歌者與鼓手共同呈現的長篇敘事歌唱","印度北部的拉格器樂獨奏","印尼爪哇宮廷甘美朗"],answer:1,explanation:"Pansori 是韓國重要敘事聲樂傳統，核心演出常由一名歌者與一名鼓手構成，融合歌唱、說白、動作與戲劇敘事。",source:"115教育部高中教師甄選音樂科名詞解釋考點改寫"},
{id:"MOE115-NC-07",year:115,subject:"高中音樂",topic:"世界音樂",level:"👹魔王",question:"Fado 最常與下列哪一國家的都市歌唱文化相連？",options:["葡萄牙","匈牙利","墨西哥","芬蘭"],answer:0,explanation:"Fado 是葡萄牙代表性的都市歌唱傳統，常與里斯本等地文化及 saudade（帶有思念、惆悵意味的情感）相聯。",source:"115教育部高中教師甄選音樂科名詞解釋考點改寫"},
{id:"MOE115-NC-08",year:115,subject:"高中音樂",topic:"二十世紀音樂",level:"👹魔王",question:"Mystic Chord（神祕和弦）最常與哪位作曲家的晚期音樂語彙聯繫？",options:["Scriabin","Satie","Bartók","Britten"],answer:0,explanation:"Mystic Chord 常與俄國作曲家 Alexander Scriabin 晚期作品相關，是理解其和聲色彩、神祕主義思想與調性鬆動的重要考點。",source:"115教育部高中教師甄選音樂科名詞解釋考點改寫"}
]);