window.EXTRA_QUESTIONS = window.EXTRA_QUESTIONS || [];
window.EXTRA_QUESTIONS.push(
{year:113,subject:'高中音樂',topic:'臺灣傳統音樂',level:'👹 冷門',question:'關於客家傳統「三腳採茶戲」，何者最符合其傳統表演編制？',options:['一生二旦','一丑二旦','二丑一旦','一丑一生一旦'],answer:1,explanation:'三腳採茶戲傳統核心角色為一丑二旦，表演具有歌舞與即興性。',source:'113 新北市高中教師聯合甄選音樂科'},
{year:113,subject:'高中音樂',topic:'20世紀音樂',level:'困難',question:'下列何者最具代表性地屬於史特拉溫斯基的新古典主義作品？',options:['《火鳥》','《春之祭》','《浪子的歷程》','《彼得洛希卡》'],answer:2,explanation:'《浪子的歷程》是史特拉溫斯基新古典主義時期的重要歌劇；前三部芭蕾常與其俄羅斯時期連結。',source:'113 新北市高中教師聯合甄選音樂科'},
{year:113,subject:'高中音樂',topic:'聲音與環境',level:'困難',question:'「世界聲景計畫」World Soundscape Project 與下列何人關係最密切？',options:['John Cage','R. Murray Schafer','Pierre Schaeffer','Karlheinz Stockhausen'],answer:1,explanation:'R. Murray Schafer 推動 World Soundscape Project，關注聲音環境、聆聽意識與聲學生態。',source:'113 新北市高中教師聯合甄選音樂科'},
{year:113,subject:'高中音樂',topic:'音樂科技',level:'一般',question:'下列哪一項工具具有 AI 自動生成音樂的功能？',options:['Soundraw','GoldWave','OpenShot','MuseScore'],answer:0,explanation:'Soundraw 為 AI 音樂生成工具；GoldWave 偏音訊編輯、OpenShot 為影片編輯、MuseScore 主要為樂譜製作。',source:'113 新北市高中教師聯合甄選音樂科'},
{year:113,subject:'教育專業',topic:'教學法',level:'一般',question:'學生課前先觀看爵士樂介紹影片，課堂中再進行提問、討論與音樂實作，最符合哪一種教學模式？',options:['STEAM','Flipped Classroom','CLIL','TPACK'],answer:1,explanation:'翻轉教室將部分知識輸入移至課前，課堂時間用於互動、問題解決與實作。',source:'113 新北市高中教師聯合甄選音樂科'},
{year:113,subject:'高中音樂',topic:'音樂美學',level:'困難',question:'音樂欣賞同時重視節奏、旋律、和聲等形式特質，以及標題、歌詞與創作背景所指涉的內容，最接近哪一音樂美學觀？',options:['形式主義','絕對表現主義','指涉主義','純粹主義'],answer:2,explanation:'指涉主義重視音樂與音樂之外的概念、情境、意象或意義之關聯；題幹特別加入標題、歌詞與背景。',source:'113 新北市高中教師聯合甄選音樂科'},
{year:113,subject:'高中音樂',topic:'世界音樂',level:'一般',question:'下列哪一音樂節位於比利時，並以電子舞曲音樂聞名？',options:['Salzburg Festival','Bayreuth Festival','Tomorrowland','Coachella'],answer:2,explanation:'Tomorrowland 是比利時著名大型電子音樂節。',source:'113 新北市高中教師聯合甄選音樂科'},
{year:113,subject:'高中音樂',topic:'流行與表演',level:'一般',question:'A Cappella 最核心的表演特徵為何？',options:['以弦樂團伴奏','以人聲為主要聲響來源而不依賴器樂伴奏','固定使用電子合成器','必須由四人演唱'],answer:1,explanation:'A cappella 指無器樂伴奏或以人聲本身構成主要聲響與伴奏層次的演唱方式。',source:'113 新北市高中教師聯合甄選音樂科'},
{year:113,subject:'教育專業',topic:'鷹架教學',level:'困難',question:'教師把複雜音樂創作任務拆解成數個操作步驟，引導學生依序完成，最符合哪一類鷹架？',options:['Conceptual scaffolding','Procedural scaffolding','Metacognitive scaffolding','Affective scaffolding'],answer:1,explanation:'Procedural scaffolding 著重「如何做」的程序與操作支持，例如將複雜任務拆成步驟。',source:'113 新北市高中教師聯合甄選音樂科'},
{year:113,subject:'高中音樂',topic:'當代音樂文化',level:'👹 冷門',question:'葛萊美獎於 2023 年新增、Stephanie Economou 成為首位得主的獎項為何？',options:['Best AI Music Album','Best Score Soundtrack for Video Games and Other Interactive Media','Best Electronic Opera','Best Immersive Classical Composition'],answer:1,explanation:'2023 年首度頒發 Best Score Soundtrack for Video Games and Other Interactive Media，首位得主為 Stephanie Economou。',source:'113 新北市高中教師聯合甄選音樂科'}
);