(()=>{
 if(window.__REVIEW_OPTION_DETAILS_V2__)return;window.__REVIEW_OPTION_DETAILS_V2__=true;
 const OK='musicTeacherExamOptionNotesV1',QK='musicTeacherExamQuestionNotesV1';
 const read=k=>{try{return JSON.parse(localStorage.getItem(k))||{}}catch{return{}}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
 const clean=s=>String(s??'').replace(/\s+/g,' ').trim(),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const qs=()=>Array.isArray(window.LOCAL_QUESTIONS)?window.LOCAL_QUESTIONS:[];
 function currentQuestion(){const id=document.getElementById('reviewSource')?.textContent?.match(/題號：([^\s]+)/)?.[1];if(id){const q=qs().find(x=>String(x.id)===String(id));if(q)return q}const stem=clean(document.getElementById('reviewQuestion')?.textContent||''),opts=[...document.querySelectorAll('#reviewOptions .option-btn')].map(b=>({k:b.dataset.choice,t:clean(b.textContent.replace(/^\s*[A-D][.．]\s*/,''))}));return qs().find(q=>clean(q.question)===stem&&opts.every(x=>clean(q[`option_${x.k.toLowerCase()}`])===x.t))||null}
 function setOpt(id,k,v){const x=read(OK);x[id]=x[id]||{};if(clean(v))x[id][k]=v.trim();else delete x[id][k];if(!Object.keys(x[id]).length)delete x[id];write(OK,x)}
 function setQ(id,v){const x=read(QK);if(clean(v))x[id]=v.trim();else delete x[id];write(QK,x)}
 function rowsFor(q){if(window.getMusicOptionExplanations)return window.getMusicOptionExplanations(q);return ['A','B','C','D'].map(k=>({key:k,text:q[`option_${k.toLowerCase()}`]||'',correct:k===q.answer,explanation:k===q.answer?(q.explanation||'此選項為本題正解。'):'此選項不是本題答案；獨立錯因詳解尚待核對。'}))}
 function render(){const fb=document.getElementById('reviewFeedback');if(!fb||fb.classList.contains('hidden'))return;const q=currentQuestion();if(!q)return;let box=document.getElementById('reviewOptionDetails');if(!box){box=document.createElement('div');box.id='reviewOptionDetails';document.getElementById('reviewExplanation')?.insertAdjacentElement('afterend',box)}const rows=rowsFor(q),on=read(OK)[q.id]||{},qn=read(QK)[q.id]||'';box.innerHTML=`<div class="feedback-title" style="margin-top:16px">🔎 四個選項逐項複習</div><div class="muted" style="font-size:12px;margin:5px 0 9px">每個選項分開理解；尚未核對的錯因會明確標示，不用硬背猜測內容。</div><div style="display:grid;gap:9px">${rows.map(x=>`<div style="padding:11px 12px;border:1px solid var(--line);border-radius:12px;line-height:1.6"><b>${x.correct?'✅':'▫️'} ${x.key}. ${esc(x.text)}</b><div style="margin-top:4px">${esc(x.explanation)}</div><details style="margin-top:7px"><summary style="cursor:pointer;font-weight:800">📝 我的 ${x.key} 選項筆記${on[x.key]?' ✓':''}</summary><textarea class="review-opt-note" data-k="${x.key}" rows="3" style="width:100%;margin-top:7px;padding:9px;border:1px solid var(--line);border-radius:10px;background:var(--card);color:var(--text);resize:vertical" placeholder="補充考點、錯因、容易混淆處…">${esc(on[x.key]||'')}</textarea><div style="text-align:right;margin-top:6px"><button class="primary small review-opt-save" data-k="${x.key}" type="button">💾 儲存</button></div></details></div>`).join('')}</div>${q.review_focus?`<div class="source-box" style="margin-top:10px"><b>🧠 本題複習核心：</b>${esc(q.review_focus)}</div>`:''}<details style="margin-top:11px;padding:10px 12px;border:1px dashed var(--border);border-radius:12px"><summary style="cursor:pointer;font-weight:900">📒 本題總筆記${qn?' ✓':''}</summary><textarea id="reviewQuestionNote" rows="4" style="width:100%;margin-top:7px;padding:9px;border:1px solid var(--line);border-radius:10px;background:var(--card);color:var(--text);resize:vertical" placeholder="口訣、延伸概念、比較表、查證提醒…">${esc(qn)}</textarea><div style="text-align:right;margin-top:6px"><button id="reviewQuestionNoteSave" class="primary small" type="button">💾 儲存本題筆記</button></div></details>`;box.querySelectorAll('.review-opt-save').forEach(b=>b.onclick=()=>{const i=box.querySelector(`.review-opt-note[data-k="${b.dataset.k}"]`);setOpt(q.id,b.dataset.k,i?.value||'');b.textContent='✅ 已儲存';setTimeout(render,350)});box.querySelector('#reviewQuestionNoteSave')?.addEventListener('click',()=>{setQ(q.id,box.querySelector('#reviewQuestionNote')?.value||'');render()})}
 function mount(){const fb=document.getElementById('reviewFeedback');if(!fb||fb.dataset.optionDetailObserved)return;fb.dataset.optionDetailObserved='1';new MutationObserver(()=>setTimeout(render,0)).observe(fb,{attributes:true,attributeFilter:['class']});document.getElementById('reviewNextBtn')?.addEventListener('click',()=>{document.getElementById('reviewOptionDetails')?.remove()})}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();
})();