(() => {
  const QUESTIONS=Array.isArray(window.LOCAL_QUESTIONS)?window.LOCAL_QUESTIONS:[];
  const REVIEW_KEY='musicTeacherExamSpacedReviewV1';
  const STATS_KEY='musicTeacherExamStatsV1';
  const $=id=>document.getElementById(id);
  const load=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}};
  const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
  const addHours=(d,h)=>new Date(d.getTime()+h*3600000),addDays=(d,x)=>addHours(d,x*24);
  const fmt=d=>`${d.getMonth()+1}/${d.getDate()}`;
  const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const intervalFor=n=>n<=1?3:n===2?7:n===3?14:n===4?30:n===5?60:90;
  let quiz=[],idx=0,correct=0,answered=false;

  function normalizedStats(){const s=load(STATS_KEY,{});return{...s,attempts:s.attempts||{},wrong:Array.isArray(s.wrong)?s.wrong:[],unknown:Array.isArray(s.unknown)?s.unknown:[],daily:s.daily||{},topics:s.topics||{}}}
  function bootstrap(){const r=load(REVIEW_KEY,{}),s=normalizedStats(),unknown=new Set(s.unknown);let changed=false;QUESTIONS.forEach(q=>{const a=s.attempts?.[q.id];if(!a?.total)return;if(!r[q.id]){const acc=(a.correct||0)/a.total,isUnknown=unknown.has(q.id)||(a.unknown||0)>0;r[q.id]={due:new Date().toISOString(),correctStreak:isUnknown?0:(acc===1?1:0),lastResult:isUnknown?'unknown':(acc===1?'correct':'wrong'),hadWrong:isUnknown||acc<1,lastReviewed:null,intervalDays:0};changed=true}else if(unknown.has(q.id)&&r[q.id].lastResult!=='unknown'){r[q.id]={...r[q.id],due:new Date().toISOString(),correctStreak:0,lastResult:'unknown',intervalDays:0};changed=true}});if(changed)save(REVIEW_KEY,r);return r;}
  function state(q,r,s){const a=s.attempts?.[q.id];if(!a?.total)return'new';const x=r[q.id],acc=(a.correct||0)/a.total,unknown=new Set(s.unknown||[]),wrong=new Set(s.wrong||[]);if(unknown.has(q.id)||wrong.has(q.id)||!x||x.lastResult==='wrong'||x.lastResult==='unknown'||acc<.6)return'red';if((x.correctStreak||0)>=3&&new Date(x.due)>new Date())return'green';return'yellow'}
  function dueQuestions(){const r=bootstrap(),s=normalizedStats(),now=new Date(),arr=[];QUESTIONS.forEach(q=>{const x=r[q.id];if(x?.due&&new Date(x.due)<=now)arr.push({q,state:state(q,r,s),due:new Date(x.due),review:x})});arr.sort((a,b)=>({red:0,yellow:1,green:2}[a.state]-({red:0,yellow:1,green:2}[b.state])||a.due-b.due);return arr.slice(0,20)}
  function update(q,isCorrect){const r=bootstrap(),prev=r[q.id]||{correctStreak:0,hadWrong:false,lastResult:null},now=new Date();let due;if(!isCorrect){const repeated=prev.lastResult==='wrong'||prev.lastResult==='unknown';due=repeated?addDays(now,1):addHours(now,4);r[q.id]={...prev,due:due.toISOString(),correctStreak:0,hadWrong:true,lastResult:'wrong',lastReviewed:now.toISOString(),intervalDays:repeated?1:0};}else{const n=(prev.correctStreak||0)+1,days=intervalFor(n);due=addDays(now,days);r[q.id]={...prev,due:due.toISOString(),correctStreak:n,lastResult:'correct',lastReviewed:now.toISOString(),intervalDays:days};}save(REVIEW_KEY,r);return{due,streak:r[q.id].correctStreak,intervalDays:r[q.id].intervalDays}}
  function recordAttempt(q,isCorrect){const s=normalizedStats();s.attempts[q.id]=s.attempts[q.id]||{total:0,correct:0,unknown:0,streak:0,bestStreak:0};const a=s.attempts[q.id];a.total++;if(isCorrect){a.correct++;a.streak=(a.streak||0)+1;a.bestStreak=Math.max(a.bestStreak||0,a.streak||0)}else a.streak=0;s.topics[q.topic]=s.topics[q.topic]||{total:0,correct:0};s.topics[q.topic].total++;if(isCorrect)s.topics[q.topic].correct++;const d=new Date(),key=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;s.daily[key]=(s.daily[key]||0)+1;const w=new Set(s.wrong||[]),u=new Set(s.unknown||[]);if(isCorrect){w.delete(q.id);u.delete(q.id)}else{w.add(q.id);u.delete(q.id)}s.wrong=[...w];s.unknown=[...u];save(STATS_KEY,s)}
  function show(id){['reviewIntro','reviewQuiz','reviewResult'].forEach(x=>$(x)?.classList.toggle('active',x===id))}
  function render(){answered=false;const item=quiz[idx];if(!item){finish();return}const q=item.q;$('reviewProgress').textContent=`${idx+1} / ${quiz.length}`;$('reviewScore').textContent=`答對 ${correct}`;$('reviewBar').style.width=`${idx/quiz.length*100}%`;$('reviewSubject').textContent=q.subject;$('reviewTopic').textContent=q.topic;$('reviewState').textContent=item.state==='red'?'🔴 優先回收':'🟡 到期複習';$('reviewQuestion').textContent=q.question;$('reviewFeedback').classList.add('hidden');$('reviewNextBtn').classList.add('hidden');$('reviewOptions').innerHTML=[['A',q.option_a],['B',q.option_b],['C',q.option_c],['D',q.option_d]].map(([k,t])=>`<button class="option-btn" data-choice="${k}"><b>${k}.</b> ${esc(t)}</button>`).join('');document.querySelectorAll('.option-btn').forEach(b=>b.addEventListener('click',()=>answer(b.dataset.choice)))}
  function answer(choice){if(answered)return;answered=true;const q=quiz[idx].q,isCorrect=choice===q.answer;if(isCorrect)correct++;document.querySelectorAll('.option-btn').forEach(b=>{b.disabled=true;if(b.dataset.choice===q.answer)b.classList.add('correct');if(b.dataset.choice===choice&&!isCorrect)b.classList.add('wrong')});recordAttempt(q,isCorrect);const result=update(q,isCorrect);$('reviewFeedbackTitle').textContent=isCorrect?'✅ 答對了':'❌ 正確答案是 '+q.answer;$('reviewExplanation').textContent=q.explanation||'';$('reviewNext').textContent=isCorrect?`🧠 連續提取 ${result.streak} 次｜下一次 ${fmt(result.due)}（${result.intervalDays} 天後）`:`🧠 這題會在 ${fmt(result.due)} 優先再出現。`;$('reviewSource').innerHTML=`來源標示：${esc(q.source_title||'練習題')}<br>題號：${esc(q.id)}`;$('reviewFeedback').classList.remove('hidden');$('reviewNextBtn').textContent=idx===quiz.length-1?'查看結果 →':'下一題 →';$('reviewNextBtn').classList.remove('hidden');$('reviewScore').textContent=`答對 ${correct}`}
  function next(){if(!answered)return;idx++;idx>=quiz.length?finish():render()}
  function finish(){const score=quiz.length?Math.round(correct/quiz.length*100):0;$('reviewResultScore').textContent=score;$('reviewResultText').textContent=`今天複習 ${quiz.length} 題，答對 ${correct} 題。答對後會依 3→7→14→30→60→90 天逐步延長；答錯則縮短到 4 小時或 1 天。`;show('reviewResult')}
  document.addEventListener('DOMContentLoaded',()=>{quiz=dueQuestions();if(!quiz.length){$('reviewStatus').textContent='今天沒有到期題目，可以回首頁做新題或申論／試教練習。';return}$('reviewStatus').textContent=`今天有 ${quiz.length} 題到期，會先回收「不知道／答錯」的高風險題，再做一般到期題。`;show('reviewQuiz');render();$('reviewNextBtn').addEventListener('click',next)});
})();