(()=>{
 if(window.__REVIEW_OPTION_DETAILS__)return;window.__REVIEW_OPTION_DETAILS__=true;
 const OK='musicTeacherExamOptionNotesV1',QK='musicTeacherExamQuestionNotesV1';
 const read=k=>{try{return JSON.parse(localStorage.getItem(k))||{}}catch{return{}}};const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
 const clean=s=>String(s??'').replace(/\s+/g,' ').trim();const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const qs=()=>Array.isArray(window.LOCAL_QUESTIONS)?window.LOCAL_QUESTIONS:[];
 function currentQuestion(){const id=document.getElementById('reviewSource')?.textContent?.match(/題號：([^\s]+)/)?.[1];if(id){const q=qs().find(x=>String(x.id)===String(id));if(q)return q}const stem=clean(document.getElementById('reviewQuestion')?.textContent||'');const opts=[...document.querySelectorAll('#reviewOptions .option-btn')].map(b=>({k:b.dataset.choice,t:clean(b.textContent.replace(/^\s*[A-D][.．]\s*/,''))}));return qs().find(q=>clean(q.question)===stem&&opts.every(x=>clean(q[`option_${x.k.toLowerCase()}`])===x.t))||null}
 function setOpt(id,k,v){const x=read(OK);x[id]=x[id]||{};if(clean(v))x[id][k]=v.trim();else delete x[id][k];if(!Object.keys(x[id]).length)delete x[id];write(OK,x)}
 function setQ(id,v){const x=read(QK);if(clean(v))x[id]=v.trim();else delete x[id];write(QK,x)}
 function render(){const fb=document.getElementById('reviewFeedback');if(!fb||fb.classList.contains('hidden'))return;const q=currentQuestion();if(!q)return;let box=document.getElementById('reviewOptionDetails');if(!box){box=document.createElement('div');box.id='reviewOptionDetails';document.getElementById('reviewExplanation')?.insertAdjacentElement('afterend',box)}const rows=window.getMusicOptionExplanations?window.getMusicOptionExplanations(q):[];const on=read(OK)[q.id]||{},qn=read(QK)[q.id]||'';box.innerHTML=`<div class="feedback-title" style="margin-top:16px">🔎 四個選項逐項複習</div><div style="display:grid;gap:9px;margin-top:9px">${rows.map(x=>`<div style="padding:11px 12px;border:1px solid var(--line);border-radius:12px;line-height:1.6"><b>${x.correct?'✅':'▫️'} ${x.key}. ${esc(x.text)}</b><div style="margin-top:4px">${esc(x.explanation)}</div><details style="margin-top:7px"><summary style="cursor:pointer;font-weight:800">📝 我的 ${x.key} 選項筆記${on[x.key]?' ✓':''}</summary><textarea class="review-opt-note" data-k="${x.key}" rows="3" style="width:100%;margin-top:7px;padding:9px;border:1px solid var(--line);border-radius:10px;background:var(--card);color:var(--text)">${esc(on[x.key]||'')}</textarea><button class="primary small review-opt-save" data-k="${x.key}" type="button" style="margin-top:6px">💾 儲存</button></details></div>`).join('')}</div><details style="margin-top:11px;padding:10px 12px;border:1px dashed var(--border);border-radius:12px"><summary style="cursor:pointer;font-weight:900">📒 本題總筆記${qn?' ✓':''}</summary><textarea id="reviewQuestionNote" rows="4" style="width:100%;margin-top:7px;padding:9px;border:1px solid var(--line);border-radius:10px;background:var(--card);color:var(--text)">${esc(qn)}</textarea><button id="reviewQuestionNoteSave" class="primary small" type="button" style="margin-top:6px">💾 儲存本題筆記</button></details>`;box.querySelectorAll('.review-opt-save').forEach(b=>b.onclick=()=>{const i=box.querySelector(`.review-opt-note[data-k="${b.dataset.k}"]`);setOpt(q.id,b.dataset.k,i?.value||'');b.textContent='✅ 已儲存';setTimeout(render,350)});box.querySelector('#reviewQuestionNoteSave')?.addEventListener('click',()=>{setQ(q.id,box.querySelector('#reviewQuestionNote')?.value||'');render()})}
 document.addEventListener('click',e=>{if(e.target.closest('#reviewOptions .option-btn'))setTimeout(render,80)});new MutationObserver(()=>setTimeout(render,0)).observe(document.body,{childList:true,subtree:true});
})();