(()=>{
 if(window.__RISK_TOPIC_DRILL_PROGRESS_V1__)return;window.__RISK_TOPIC_DRILL_PROGRESS_V1__=true;
 const SESSION='musicTeacherExamRiskTopicDrillV1',BACKLOG='musicTeacherExamRiskBacklogV1',STATS='musicTeacherExamStatsV1',SRS='musicTeacherExamSpacedReviewV1';
 const load=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}},save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
 const qs=()=>window.MusicTeacherExam?.questions||[],esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function isRisk(q){const s=load(STATS,{wrong:[],unknown:[]}),r=load(SRS,{}),id=q.id;return(s.unknown||[]).includes(id)||(s.wrong||[]).includes(id)||(r[id]?.due&&new Date(r[id].due)<=new Date())}
 function topicRisk(topic){return qs().filter(q=>(q.topic||q.subject||'綜合')===topic&&isRisk(q))}
 function begin(topic,ids){const before=topicRisk(topic).length;save(SESSION,{topic,ids:(ids||[]).map(String),before,startedAt:Date.now(),results:{},active:true})}
 function capture(){const x=load(SESSION,null);if(!x?.active)return;const id=document.getElementById('sourceBox')?.textContent?.match(/題號：([^\s]+)/)?.[1];if(!id||!x.ids.includes(String(id)))return;const title=document.getElementById('feedbackTitle')?.textContent||'',status=title.includes('我不知道')?'unknown':title.includes('答對')?'correct':'wrong';x.results=x.results||{};x.results[String(id)]={status,at:Date.now()};save(SESSION,x)}
 function maybeReport(){const x=load(SESSION,null);if(!x?.active)return;const answered=Object.keys(x.results||{}).length;if(answered<x.ids.length)return;setTimeout(()=>{const y=load(SESSION,null);if(!y?.active)return;const after=topicRisk(y.topic).length,improved=Math.max(0,y.before-after),correct=Object.values(y.results||{}).filter(r=>r.status==='correct').length,total=Object.keys(y.results||{}).length;y.active=false;y.completedAt=Date.now();y.after=after;y.improved=improved;save(SESSION,y);renderReport(y,correct,total)},80)}
 function renderReport(x,correct,total){const home=document.getElementById('homeView');if(!home)return;let box=document.getElementById('riskTopicDrillReport');if(!box){box=document.createElement('section');box.id='riskTopicDrillReport';box.className='card section-card';const mission=document.getElementById('dailyMission');mission?.insertAdjacentElement('afterend',box)||home.prepend(box)}const pct=total?Math.round(correct/total*100):0;box.innerHTML=`<div class="section-title"><div><span class="eyebrow">FOCUSED RECOVERY</span><h3>🎯 ${esc(x.topic)}｜剛剛補弱點成果</h3></div><span class="pill">${pct}%</span></div><p>這輪共練 ${total} 題，答對 ${correct} 題。</p><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:10px 0"><div style="padding:10px;border:1px solid var(--line);border-radius:11px"><small>練習前高風險</small><b style="display:block;font-size:24px">${x.before}</b></div><div style="padding:10px;border:1px solid var(--line);border-radius:11px"><small>目前高風險</small><b style="display:block;font-size:24px">${x.after}</b></div><div style="padding:10px;border:1px solid var(--line);border-radius:11px"><small>本輪收斂</small><b style="display:block;font-size:24px">${x.improved}</b></div></div><p class="muted">${x.improved?`很好，這個主題的高風險題從 ${x.before} 題降到 ${x.after} 題；剩下的會繼續留在錯題／不知道／間隔複習中。`:`這輪還沒有讓高風險數量下降；先看四選項錯因與自己的筆記，下一次再用主動提取確認。`}</p><button class="ghost small" id="dismissRiskTopicReport" type="button">知道了</button>`;box.querySelector('#dismissRiskTopicReport').onclick=()=>box.remove()}
 function restore(){const x=load(SESSION,null);if(x&&!x.active&&x.completedAt&&Date.now()-x.completedAt<12*3600000){const correct=Object.values(x.results||{}).filter(r=>r.status==='correct').length;renderReport(x,correct,Object.keys(x.results||{}).length)}}
 function bind(){const fb=document.getElementById('feedback');if(fb&&!fb.dataset.riskDrillObserved){fb.dataset.riskDrillObserved='1';new MutationObserver(()=>{if(!fb.classList.contains('hidden')){setTimeout(()=>{capture();maybeReport()},25)}}).observe(fb,{attributes:true,attributeFilter:['class']})}restore()}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(bind,300),{once:true});else setTimeout(bind,300);
 window.RiskTopicDrillProgress={begin,topicRisk,renderReport};
})();