// 115 九宮格｜互動任務第三批：思考＋關係圖＋學習作品集
(function(){
 if(window.__SELFSTUDY115_INTERACTIVE3__)return;window.__SELFSTUDY115_INTERACTIVE3__=true;
 var KEY='musicTeacherExamSelfStudy115Interactive3V1';
 function load(){try{return JSON.parse(localStorage.getItem(KEY))||{}}catch(e){return{}}}function save(s){localStorage.setItem(KEY,JSON.stringify(s||{}))}
 function esc(s){return String(s||'').replace(/[&<>\"]/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]})}
 function parts(pair){return String(pair||'').split(' ↔ ').map(function(x){return x.trim()}).filter(Boolean)}function currentPair(){var h=document.querySelector('#selfStudy115 h3');return h?String(h.textContent).replace(/^🧩\s*/,'').trim():''}
 function store(pair,id,data){var s=load();s[pair]=s[pair]||{};s[pair][id]={data:data,updatedAt:Date.now()};save(s)}function existing(pair,id){var s=load();return s[pair]&&s[pair][id]?s[pair][id].data:null}
 function markDone(pair,id){var api=window.SelfStudy115;if(!api||!api.state)return;var st=api.state(pair);if(!(st.done||[]).includes(id)){var b=document.querySelector('#selfStudy115 [data-mission="'+id+'"]');if(b){var e=new Event('click',{bubbles:true,cancelable:true});e.__ss115=true;b.dispatchEvent(e)}}}
 function modal(title,body){document.getElementById('ss115Modal3')?.remove();var w=document.createElement('div');w.id='ss115Modal3';w.style.cssText='position:fixed;inset:0;background:rgba(0,0,0,.55);z-index:9999;display:grid;place-items:center;padding:18px';w.innerHTML='<div class="card" style="width:min(760px,100%);max-height:88vh;overflow:auto;padding:18px"><div style="display:flex;justify-content:space-between;gap:12px"><div><span class="eyebrow">九宮格實作</span><h3>'+esc(title)+'</h3></div><button id="ss3Close" class="ghost small">✕</button></div>'+body+'</div>';document.body.appendChild(w);w.querySelector('#ss3Close').onclick=function(){w.remove()};w.onclick=function(e){if(e.target===w)w.remove()};return w}
 function openThink(pair){var p=parts(pair),o=existing(pair,'think')||{},body='<p class="muted">不要只寫「不一樣」。請找出真正造成混淆的分析層級。</p><label>兩者最核心的比較維度<select id="ss3Dim" style="width:100%;margin-top:6px"><option>人物／角色</option><option>時代／地點</option><option>族群／文化</option><option>音樂構造／分析層級</option><option>功能／用途</option><option>教學／評量目的</option><option>其他</option></select></label><label style="display:block;margin-top:12px">為什麼 '+esc(p[0]||'A')+' 不是 '+esc(p[1]||'B')+'？<textarea id="ss3Why" rows="4" style="width:100%;margin-top:6px">'+esc(o.why||'')+'</textarea></label><label style="display:block;margin-top:12px">最容易被命題者怎麼偷換？<textarea id="ss3Trap" rows="3" style="width:100%;margin-top:6px">'+esc(o.trap||'')+'</textarea></label><div id="ss3Msg" class="hf115-note" style="margin:10px 0"></div><button id="ss3SaveThink" class="primary wide">✅ 儲存思考並完成</button>';var m=modal('🧠 為什麼不同｜'+pair,body);if(o.dim)m.querySelector('#ss3Dim').value=o.dim;m.querySelector('#ss3SaveThink').onclick=function(){var why=m.querySelector('#ss3Why').value.trim(),trap=m.querySelector('#ss3Trap').value.trim(),msg=m.querySelector('#ss3Msg');if(why.length<15||trap.length<8){msg.textContent='請至少寫出一個完整差異，以及一個可能的考題陷阱。';return}store(pair,'think',{dim:m.querySelector('#ss3Dim').value,why:why,trap:trap});markDone(pair,'think');msg.textContent='已儲存 ✓';setTimeout(function(){m.remove()},600)}}
 function openDraw(pair){var p=parts(pair),o=existing(pair,'draw')||{},body='<p class="muted">用「文字關係圖」也可以完成。把共同點放中間、差異放兩側；之後若想手繪，也可以照這份骨架畫。</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px"><label>'+esc(p[0]||'A')+' 專屬特徵<textarea id="ss3A" rows="4" style="width:100%;margin-top:6px">'+esc(o.a||'')+'</textarea></label><label>'+esc(p[1]||'B')+' 專屬特徵<textarea id="ss3B" rows="4" style="width:100%;margin-top:6px">'+esc(o.b||'')+'</textarea></label></div><label style="display:block;margin-top:12px">兩者共同點／為什麼容易混淆？<textarea id="ss3Same" rows="3" style="width:100%;margin-top:6px">'+esc(o.same||'')+'</textarea></label><label style="display:block;margin-top:12px">我的圖像／箭頭記憶法<textarea id="ss3Visual" rows="3" style="width:100%;margin-top:6px" placeholder="例：多調性 → 看『中心』；多和弦 → 看『堆疊』">'+esc(o.visual||'')+'</textarea></label><div id="ss3DrawMsg" class="hf115-note" style="margin:10px 0"></div><button id="ss3SaveDraw" class="primary wide">🎨 儲存關係圖並完成</button>';var m=modal('🎨 畫關係圖｜'+pair,body);m.querySelector('#ss3SaveDraw').onclick=function(){var d={a:m.querySelector('#ss3A').value.trim(),b:m.querySelector('#ss3B').value.trim(),same:m.querySelector('#ss3Same').value.trim(),visual:m.querySelector('#ss3Visual').value.trim()},msg=m.querySelector('#ss3DrawMsg');if(d.a.length<8||d.b.length<8||d.same.length<8){msg.textContent='左右差異與中間共同點都填完整，再算完成。';return}store(pair,'draw',d);markDone(pair,'draw');msg.textContent='關係圖骨架已保存 ✓';setTimeout(function(){m.remove()},600)}}
 function collectPortfolio(){var out=[];function add(source,label,data){Object.keys(data||{}).forEach(function(pair){Object.keys(data[pair]||{}).forEach(function(id){var x=data[pair][id];if(x&&x.data)out.push({pair:pair,id:id,label:label[id]||id,data:x.data,time:x.updatedAt||0,source:source})})})}if(window.SelfStudyInteractive115)add('第一批',{write:'✍️ 一句定義',create:'🛠️ 自己出題'},window.SelfStudyInteractive115.load());if(window.SelfStudyInteractive2_115)add('第二批',{play:'🎮 反向挑戰',teach:'🧑‍🏫 教別人'},window.SelfStudyInteractive2_115.load());add('第三批',{think:'🧠 為什麼不同',draw:'🎨 關係圖'},load());return out.sort(function(a,b){return b.time-a.time})}
 function summary(x){var d=x.data;if(x.id==='write')return (d.a||'')+'｜'+(d.b||'');if(x.id==='create')return (d.q||'')+'（答案 '+(d.ans||'')+'）';if(x.id==='play')return '修正：'+(d.fix||'');if(x.id==='teach')return d.text||'';if(x.id==='think')return (d.dim||'')+'｜'+(d.why||'');if(x.id==='draw')return (d.a||'')+' ↔ '+(d.b||'');return JSON.stringify(d)}
 function openPortfolio(){var arr=collectPortfolio(),body='<p class="muted">這裡收集你在九宮格留下的學習證據。它不是另一份筆記，而是「我曾經怎麼理解、修正、出題與教別人」的作品集。</p>'+(arr.length?'<div style="display:grid;gap:10px">'+arr.map(function(x){return'<article class="hf115-topic"><div class="hf115-rank">'+new Date(x.time).toLocaleDateString('zh-TW')+'</div><h4>'+esc(x.label)+'｜'+esc(x.pair)+'</h4><p>'+esc(summary(x)).slice(0,320)+'</p></article>'}).join('')+'</div>':'<p class="hf115-cue">目前還沒有作品。先完成「一句定義、反向挑戰、自己出題、教別人」其中一格吧。</p>');modal('📂 我的學習作品',body)}
 function enhance(){var box=document.getElementById('selfStudy115');if(box){var t=box.querySelector('[data-mission="think"]'),d=box.querySelector('[data-mission="draw"]');if(t&&!t.dataset.i3){t.dataset.i3='1';t.addEventListener('click',function(e){if(e.__ss115)return;e.preventDefault();e.stopImmediatePropagation();openThink(currentPair())},true)}if(d&&!d.dataset.i3){d.dataset.i3='1';d.addEventListener('click',function(e){if(e.__ss115)return;e.preventDefault();e.stopImmediatePropagation();openDraw(currentPair())},true)}}var sec=document.getElementById('hf115Section');if(sec&&!document.getElementById('ss115PortfolioBtn')){var actions=sec.querySelector('.hf115-actions');if(actions){var b=document.createElement('button');b.id='ss115PortfolioBtn';b.className='hf115-btn';b.innerHTML='<b>📂 我的學習作品</b><small>回看自己寫過的定義、陷阱、題目、關係圖與教學說法</small>';b.onclick=openPortfolio;actions.appendChild(b)}}return !!box}
 var obs=new MutationObserver(enhance);obs.observe(document.documentElement,{childList:true,subtree:true});enhance();window.SelfStudyInteractive3_115={load:load,openThink:openThink,openDraw:openDraw,portfolio:collectPortfolio,openPortfolio:openPortfolio};
})();