// 115 九宮格｜互動任務第二批：反向挑戰＋教別人
(function(){
 if(window.__SELFSTUDY115_INTERACTIVE2__)return;window.__SELFSTUDY115_INTERACTIVE2__=true;
 var KEY='musicTeacherExamSelfStudy115Interactive2V1';
 function load(){try{return JSON.parse(localStorage.getItem(KEY))||{}}catch(e){return{}}}
 function save(s){localStorage.setItem(KEY,JSON.stringify(s||{}))}
 function esc(s){return String(s||'').replace(/[&<>\"]/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]})}
 function pairParts(pair){return String(pair||'').split(' ↔ ').map(function(x){return x.trim()}).filter(Boolean)}
 function store(pair,id,payload){var s=load();s[pair]=s[pair]||{};s[pair][id]={data:payload,updatedAt:Date.now()};save(s)}
 function existing(pair,id){var s=load();return s[pair]&&s[pair][id]?s[pair][id].data:null}
 function markDone(pair,id){var api=window.SelfStudy115;if(!api||!api.state)return;var st=api.state(pair);if(!(st.done||[]).includes(id)){var btn=document.querySelector('#selfStudy115 [data-mission="'+id+'"]');if(btn){var ev=new Event('click',{bubbles:true,cancelable:true});ev.__ss115=true;btn.dispatchEvent(ev)}}}
 function modalShell(title,body){var old=document.getElementById('ss115Modal2');if(old)old.remove();var wrap=document.createElement('div');wrap.id='ss115Modal2';wrap.style.cssText='position:fixed;inset:0;background:rgba(0,0,0,.55);z-index:9999;display:grid;place-items:center;padding:18px';wrap.innerHTML='<div class="card" style="width:min(720px,100%);max-height:88vh;overflow:auto;padding:18px"><div style="display:flex;justify-content:space-between;gap:12px;align-items:center"><div><span class="eyebrow">九宮格實作</span><h3 style="margin:4px 0">'+esc(title)+'</h3></div><button id="ss115Close2" class="ghost small">✕</button></div>'+body+'</div>';document.body.appendChild(wrap);wrap.querySelector('#ss115Close2').onclick=function(){wrap.remove()};wrap.addEventListener('click',function(e){if(e.target===wrap)wrap.remove()});return wrap}
 function currentPair(){var h=document.querySelector('#selfStudy115 h3');return h?String(h.textContent).replace(/^🧩\s*/,'').trim():''}
 function reversePrompt(pair){var p=pairParts(pair),a=p[0]||'概念A',b=p[1]||'概念B';return '「'+a+' 和 '+b+' 其實完全相同，只是不同語言的說法。」'}
 function openPlay(pair){var old=existing(pair,'play')||{},body='<p class="muted">系統先給一個看似合理但其實有問題的敘述。請指出錯在哪，並改寫成正確版本。</p><div class="hf115-cue"><b>👹 錯誤敘述：</b><br>'+esc(reversePrompt(pair))+'</div><label style="display:block;margin-top:12px">錯在哪？<textarea id="ss115Why" rows="3" style="width:100%;margin-top:6px">'+esc(old.why||'')+'</textarea></label><label style="display:block;margin-top:12px">請改寫成正確說法<textarea id="ss115Fix" rows="4" style="width:100%;margin-top:6px">'+esc(old.fix||'')+'</textarea></label><div id="ss115PlayMsg" class="hf115-note" style="margin:10px 0"></div><button id="ss115SavePlay" class="primary wide">✅ 儲存修正並完成這一格</button>';var m=modalShell('🎮 反向挑戰｜'+pair,body);m.querySelector('#ss115SavePlay').onclick=function(){var why=m.querySelector('#ss115Why').value.trim(),fix=m.querySelector('#ss115Fix').value.trim(),msg=m.querySelector('#ss115PlayMsg');if(why.length<8||fix.length<12){msg.textContent='至少寫出一個完整錯誤理由，並用一句完整話修正。';return}store(pair,'play',{wrong:reversePrompt(pair),why:why,fix:fix});markDone(pair,'play');msg.textContent='已儲存 ✓';setTimeout(function(){m.remove()},650)}}
 var teachTimer=null,teachLeft=60;
 function stopTeach(){if(teachTimer){clearInterval(teachTimer);teachTimer=null}}
 function openTeach(pair){stopTeach();var old=existing(pair,'teach')||{},body='<p class="muted">想像學生問：「老師，這兩個到底差在哪？」請用不超過60秒、生活化而且不失準確的方式解釋。</p><div class="hf115-cue"><b>🧑‍🏫 教學提示：</b>先說「最核心的差異」，再給一個例子，最後用一句記憶口訣收尾。</div><div style="display:flex;align-items:end;justify-content:space-between;margin:14px 0"><div><span class="eyebrow">Teach-back</span><div style="font-size:2rem;font-weight:800"><span id="ss115TeachTimer">60</span> 秒</div></div><button id="ss115TeachStart" class="ghost">▶ 開始計時</button></div><label>把你剛剛的教法留下來<textarea id="ss115TeachText" rows="5" style="width:100%;margin-top:6px">'+esc(old.text||'')+'</textarea></label><div id="ss115TeachMsg" class="hf115-note" style="margin:10px 0"></div><button id="ss115SaveTeach" class="primary wide">✅ 儲存教學說法並完成這一格</button>';var m=modalShell('🧑‍🏫 教別人｜'+pair,body),timer=m.querySelector('#ss115TeachTimer');m.querySelector('#ss115TeachStart').onclick=function(){stopTeach();teachLeft=60;timer.textContent=teachLeft;teachTimer=setInterval(function(){teachLeft--;timer.textContent=Math.max(0,teachLeft);if(teachLeft<=0)stopTeach()},1000)};m.querySelector('#ss115SaveTeach').onclick=function(){var text=m.querySelector('#ss115TeachText').value.trim(),msg=m.querySelector('#ss115TeachMsg');if(text.length<20){msg.textContent='至少留下兩到三句完整教學說法，才算完成。';return}store(pair,'teach',{text:text});markDone(pair,'teach');msg.textContent='已儲存 ✓';stopTeach();setTimeout(function(){m.remove()},650)}}
 function enhance(){var box=document.getElementById('selfStudy115');if(!box)return false;var p=box.querySelector('[data-mission="play"]'),t=box.querySelector('[data-mission="teach"]');if(p&&!p.dataset.interactive2){p.dataset.interactive2='1';p.addEventListener('click',function(e){if(e.__ss115)return;e.preventDefault();e.stopImmediatePropagation();openPlay(currentPair())},true)}if(t&&!t.dataset.interactive2){t.dataset.interactive2='1';t.addEventListener('click',function(e){if(e.__ss115)return;e.preventDefault();e.stopImmediatePropagation();openTeach(currentPair())},true)}return !!(p&&t)}
 var obs=new MutationObserver(function(){enhance()});obs.observe(document.documentElement,{childList:true,subtree:true});enhance();
 if(!document.querySelector('script[data-selfstudy115-i3]')){var s=document.createElement('script');s.src='selfstudy_interactive3_115.js?v=20260819';s.dataset.selfstudy115I3='1';document.head.appendChild(s)}
 window.SelfStudyInteractive2_115={load:load,openPlay:openPlay,openTeach:openTeach};
})();