// 115 九宮格｜互動任務第四批：視覺＋聽覺＋閱讀
(function(){
 if(window.__SELFSTUDY115_INTERACTIVE4__)return;window.__SELFSTUDY115_INTERACTIVE4__=true;
 var KEY='musicTeacherExamSelfStudy115Interactive4V1';
 function load(){try{return JSON.parse(localStorage.getItem(KEY))||{}}catch(e){return{}}}function save(s){localStorage.setItem(KEY,JSON.stringify(s||{}))}
 function esc(s){return String(s||'').replace(/[&<>\"]/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]})}function pair(){var h=document.querySelector('#selfStudy115 h3');return h?String(h.textContent).replace(/^🧩\s*/,'').trim():''}function parts(p){return String(p||'').split(' ↔ ').map(function(x){return x.trim()}).filter(Boolean)}
 function store(p,id,data){var s=load();s[p]=s[p]||{};s[p][id]={data:data,updatedAt:Date.now()};save(s)}function old(p,id){var s=load();return s[p]&&s[p][id]?s[p][id].data:null}
 function done(p,id){var api=window.SelfStudy115;if(!api||!api.state)return;var st=api.state(p);if(!(st.done||[]).includes(id)){var b=document.querySelector('#selfStudy115 [data-mission="'+id+'"]');if(b){var e=new Event('click',{bubbles:true,cancelable:true});e.__ss115=true;b.dispatchEvent(e)}}}
 function modal(title,body){document.getElementById('ss115Modal4')?.remove();var w=document.createElement('div');w.id='ss115Modal4';w.style.cssText='position:fixed;inset:0;background:rgba(0,0,0,.55);z-index:9999;display:grid;place-items:center;padding:18px';w.innerHTML='<div class="card" style="width:min(720px,100%);max-height:88vh;overflow:auto;padding:18px"><div style="display:flex;justify-content:space-between"><div><span class="eyebrow">九宮格實作</span><h3>'+esc(title)+'</h3></div><button id="ss4Close" class="ghost small">✕</button></div>'+body+'</div>';document.body.appendChild(w);w.querySelector('#ss4Close').onclick=function(){w.remove()};w.onclick=function(e){if(e.target===w)w.remove()};return w}
 function openSee(p){var ps=parts(p),o=old(p,'see')||{},body='<p class="muted">視覺任務不是再讀一次答案，而是把兩個概念壓縮成「一眼就能辨認」的關鍵字。</p><div class="hf115-vs"><div class="hf115-fighter">'+esc(ps[0])+'</div><div class="hf115-vsmark">VS</div><div class="hf115-fighter">'+esc(ps[1])+'</div></div><label>'+esc(ps[0])+' 的3個視覺關鍵字<input id="ss4A" style="width:100%;margin-top:6px" placeholder="用、分隔" value="'+esc(o.a||'')+'"></label><label style="display:block;margin-top:12px">'+esc(ps[1])+' 的3個視覺關鍵字<input id="ss4B" style="width:100%;margin-top:6px" placeholder="用、分隔" value="'+esc(o.b||'')+'"></label><label style="display:block;margin-top:12px">如果考卷只能圈一個字，我要圈什麼？<input id="ss4One" style="width:100%;margin-top:6px" value="'+esc(o.one||'')+'"></label><div id="ss4Msg" class="hf115-note" style="margin:10px 0"></div><button id="ss4Save" class="primary wide">👀 儲存關鍵字並完成</button>';var m=modal('👀 看辨析｜'+p,body);m.querySelector('#ss4Save').onclick=function(){var a=m.querySelector('#ss4A').value.trim(),b=m.querySelector('#ss4B').value.trim(),one=m.querySelector('#ss4One').value.trim(),msg=m.querySelector('#ss4Msg');if(a.split(/[、,，]/).filter(Boolean).length<2||b.split(/[、,，]/).filter(Boolean).length<2||one.length<1){msg.textContent='兩邊至少各抓2～3個關鍵字，再選出最重要的一個辨識字。';return}store(p,'see',{a:a,b:b,one:one});done(p,'see');msg.textContent='視覺辨識卡已保存 ✓';setTimeout(function(){m.remove()},600)}}
 var timer=null,left=30;function openHear(p){if(timer)clearInterval(timer);var o=old(p,'hear')||{},body='<p class="muted">先不要看筆記。按下計時後，用自己的聲音說出兩者差異；30秒後再寫下你剛剛記得的內容。</p><div style="display:flex;align-items:end;justify-content:space-between;margin:14px 0"><div><span class="eyebrow">Retrieval aloud</span><div style="font-size:2rem;font-weight:800"><span id="ss4Timer">30</span> 秒</div></div><button id="ss4Start" class="ghost">▶ 開始口述</button></div><label>不看答案，我剛剛能說出的3個重點<textarea id="ss4Recall" rows="4" style="width:100%;margin-top:6px">'+esc(o.recall||'')+'</textarea></label><label style="display:block;margin-top:12px">哪一點我卡住／說不出來？<textarea id="ss4Stuck" rows="2" style="width:100%;margin-top:6px">'+esc(o.stuck||'')+'</textarea></label><div id="ss4HearMsg" class="hf115-note" style="margin:10px 0"></div><button id="ss4SaveHear" class="primary wide">👂 儲存回想並完成</button>';var m=modal('👂 聽自己說｜'+p,body),tm=m.querySelector('#ss4Timer');m.querySelector('#ss4Start').onclick=function(){if(timer)clearInterval(timer);left=30;tm.textContent=left;timer=setInterval(function(){left--;tm.textContent=Math.max(0,left);if(left<=0){clearInterval(timer);timer=null}},1000)};m.querySelector('#ss4SaveHear').onclick=function(){var r=m.querySelector('#ss4Recall').value.trim(),s=m.querySelector('#ss4Stuck').value.trim(),msg=m.querySelector('#ss4HearMsg');if(r.length<15){msg.textContent='先留下至少3個自己回想出的重點，才算完成。';return}store(p,'hear',{recall:r,stuck:s});done(p,'hear');msg.textContent='口述回想已保存 ✓';if(timer)clearInterval(timer);setTimeout(function(){m.remove()},600)}}
 function highFreqText(p){var ps=parts(p),all=window.EXAM_HIGH_FREQUENCY||[],hit=all.filter(function(x){var t=[x.topic].concat(x.mustKnow||[]).join(' ').toLowerCase();return ps.some(function(k){return t.includes(k.toLowerCase())})});return hit.slice(0,2).map(function(x){return '<div class="hf115-cue"><b>'+esc(x.topic)+'</b><br>'+esc((x.mustKnow||[]).join(' → '))+'<br><span class="hf115-note">'+esc(x.answerFrame||'')+'</span></div>'}).join('')||'<div class="hf115-cue">先回到高頻卡或自己的筆記，讀一小段與這組概念相關的內容。</div>'}
 function openRead(p){var o=old(p,'read')||{},body='<p class="muted">閱讀後不要抄整段。只留下「三個真正值得帶進考場的資訊」。</p>'+highFreqText(p)+'<label style="display:block;margin-top:12px">關鍵資訊1<input id="ss4R1" style="width:100%;margin-top:6px" value="'+esc(o.r1||'')+'"></label><label style="display:block;margin-top:10px">關鍵資訊2<input id="ss4R2" style="width:100%;margin-top:6px" value="'+esc(o.r2||'')+'"></label><label style="display:block;margin-top:10px">關鍵資訊3<input id="ss4R3" style="width:100%;margin-top:6px" value="'+esc(o.r3||'')+'"></label><label style="display:block;margin-top:10px">其中哪一點最可能變成考題？為什麼？<textarea id="ss4RQ" rows="3" style="width:100%;margin-top:6px">'+esc(o.q||'')+'</textarea></label><div id="ss4ReadMsg" class="hf115-note" style="margin:10px 0"></div><button id="ss4SaveRead" class="primary wide">📖 儲存閱讀提取並完成</button>';var m=modal('📖 讀高頻卡｜'+p,body);m.querySelector('#ss4SaveRead').onclick=function(){var d={r1:m.querySelector('#ss4R1').value.trim(),r2:m.querySelector('#ss4R2').value.trim(),r3:m.querySelector('#ss4R3').value.trim(),q:m.querySelector('#ss4RQ').value.trim()},msg=m.querySelector('#ss4ReadMsg');if(!d.r1||!d.r2||!d.r3||d.q.length<8){msg.textContent='請提取3個關鍵資訊，並說明至少一個可能的命題點。';return}store(p,'read',d);done(p,'read');msg.textContent='閱讀提取已保存 ✓';setTimeout(function(){m.remove()},600)}}
 function enhance(){var box=document.getElementById('selfStudy115');if(!box)return false;[['see',openSee],['hear',openHear],['read',openRead]].forEach(function(x){var b=box.querySelector('[data-mission="'+x[0]+'"]');if(b&&!b.dataset.i4){b.dataset.i4='1';b.addEventListener('click',function(e){if(e.__ss115)return;e.preventDefault();e.stopImmediatePropagation();x[1](pair())},true)}});return true}
 var obs=new MutationObserver(enhance);obs.observe(document.documentElement,{childList:true,subtree:true});enhance();window.SelfStudyInteractive4_115={load:load,openSee:openSee,openHear:openHear,openRead:openRead};
})();