// 115 九宮格｜可操作任務：一句定義＋自己出題
(function(){
 if(window.__SELFSTUDY115_INTERACTIVE__)return;window.__SELFSTUDY115_INTERACTIVE__=true;
 var KEY='musicTeacherExamSelfStudy115InteractiveV1';
 function load(){try{return JSON.parse(localStorage.getItem(KEY))||{}}catch(e){return{}}}
 function save(s){localStorage.setItem(KEY,JSON.stringify(s||{}))}
 function esc(s){return String(s||'').replace(/[&<>\"]/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]})}
 function pairParts(pair){return String(pair||'').split(' ↔ ').map(function(x){return x.trim()}).filter(Boolean)}
 function store(pair,id,payload){var s=load();s[pair]=s[pair]||{};s[pair][id]={data:payload,updatedAt:Date.now()};save(s)}
 function existing(pair,id){var s=load();return s[pair]&&s[pair][id]?s[pair][id].data:null}
 function markDone(pair,id){var api=window.SelfStudy115;if(!api||!api.state)return;var st=api.state(pair);if(!(st.done||[]).includes(id)){var btn=document.querySelector('#selfStudy115 [data-mission="'+id+'"]');if(btn)btn.click()}}
 function modalShell(title,body){var old=document.getElementById('ss115Modal');if(old)old.remove();var wrap=document.createElement('div');wrap.id='ss115Modal';wrap.style.cssText='position:fixed;inset:0;background:rgba(0,0,0,.55);z-index:9999;display:grid;place-items:center;padding:18px';wrap.innerHTML='<div class="card" style="width:min(680px,100%);max-height:88vh;overflow:auto;padding:18px"><div style="display:flex;justify-content:space-between;gap:12px;align-items:center"><div><span class="eyebrow">九宮格實作</span><h3 style="margin:4px 0">'+esc(title)+'</h3></div><button id="ss115Close" class="ghost small">✕</button></div>'+body+'</div>';document.body.appendChild(wrap);wrap.querySelector('#ss115Close').onclick=function(){wrap.remove()};wrap.addEventListener('click',function(e){if(e.target===wrap)wrap.remove()});return wrap}
 function openWrite(pair){var p=pairParts(pair),old=existing(pair,'write')||{},body='<p class="muted">各用一句話定義，建議每個概念約20～40字。重點是「核心差異」，不是把百科全書抄進來。</p><label>'+esc(p[0]||'概念A')+'<textarea id="ss115DefA" rows="3" style="width:100%;margin-top:6px">'+esc(old.a||'')+'</textarea></label><label style="display:block;margin-top:12px">'+esc(p[1]||'概念B')+'<textarea id="ss115DefB" rows="3" style="width:100%;margin-top:6px">'+esc(old.b||'')+'</textarea></label><div id="ss115WriteMsg" class="hf115-note" style="margin:10px 0"></div><button id="ss115SaveWrite" class="primary wide">✅ 儲存並完成這一格</button>';var m=modalShell('✍️ 一句定義｜'+pair,body);m.querySelector('#ss115SaveWrite').onclick=function(){var a=m.querySelector('#ss115DefA').value.trim(),b=m.querySelector('#ss115DefB').value.trim(),msg=m.querySelector('#ss115WriteMsg');if(a.length<8||b.length<8){msg.textContent='兩個概念都至少寫一個完整句子，再算完成喔。';return}store(pair,'write',{a:a,b:b});markDone(pair,'write');msg.textContent='已儲存 ✓ 之後可再回來修改。';setTimeout(function(){m.remove()},650)}}
 function openCreate(pair){var p=pairParts(pair),old=existing(pair,'create')||{},body='<p class="muted">自己出一題四選一。至少要有題幹、四個選項與正確答案；其中一個錯誤選項要「很像真的」。</p><label>題幹<textarea id="ss115Q" rows="3" style="width:100%;margin-top:6px">'+esc(old.q||'')+'</textarea></label><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:10px">'+['A','B','C','D'].map(function(k){return'<label>'+k+'<input id="ss115'+k+'" value="'+esc((old.opts||{})[k]||'')+'" style="width:100%;margin-top:6px"></label>'}).join('')+'</div><label style="display:block;margin-top:12px">正確答案<select id="ss115Ans" style="width:100%;margin-top:6px">'+['A','B','C','D'].map(function(k){return'<option '+(old.ans===k?'selected':'')+'>'+k+'</option>'}).join('')+'</select></label><div id="ss115CreateMsg" class="hf115-note" style="margin:10px 0"></div><button id="ss115SaveCreate" class="primary wide">✅ 儲存題目並完成這一格</button>';var m=modalShell('🛠️ 自己出題｜'+pair,body);m.querySelector('#ss115SaveCreate').onclick=function(){var q=m.querySelector('#ss115Q').value.trim(),opts={};['A','B','C','D'].forEach(function(k){opts[k]=m.querySelector('#ss115'+k).value.trim()});var msg=m.querySelector('#ss115CreateMsg');if(q.length<8||Object.values(opts).some(function(v){return v.length<2})){msg.textContent='題幹與四個選項都要填完整，才算完成。';return}var ans=m.querySelector('#ss115Ans').value;store(pair,'create',{q:q,opts:opts,ans:ans});markDone(pair,'create');msg.textContent='題目已保存 ✓';setTimeout(function(){m.remove()},650)}}
 function currentPair(){var h=document.querySelector('#selfStudy115 h3');return h?String(h.textContent).replace(/^🧩\s*/,'').trim():''}
 function enhance(){var box=document.getElementById('selfStudy115');if(!box)return false;var w=box.querySelector('[data-mission="write"]'),c=box.querySelector('[data-mission="create"]');if(w&&!w.dataset.interactive){w.dataset.interactive='1';w.addEventListener('click',function(e){if(e.__ss115)return;e.preventDefault();e.stopImmediatePropagation();openWrite(currentPair())},true)}if(c&&!c.dataset.interactive){c.dataset.interactive='1';c.addEventListener('click',function(e){if(e.__ss115)return;e.preventDefault();e.stopImmediatePropagation();openCreate(currentPair())},true)}return !!(w&&c)}
 var obs=new MutationObserver(function(){enhance()});obs.observe(document.documentElement,{childList:true,subtree:true});enhance();
 window.SelfStudyInteractive115={load:load,openWrite:openWrite,openCreate:openCreate};
})();