(()=>{
 if(window.__STUDY_NOTES_LIBRARY_V3__)return;window.__STUDY_NOTES_LIBRARY_V3__=true;
 const OK='musicTeacherExamOptionNotesV1',QK='musicTeacherExamQuestionNotesV1',FK='musicTeacherExamNoteFocusV1';
 const read=k=>{try{return JSON.parse(localStorage.getItem(k))||{}}catch{return{}}};const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const qs=()=>window.MusicTeacherExam?.questions||window.LOCAL_QUESTIONS||[];
 function entries(){const o=read(OK),n=read(QK),f=read(FK),ids=new Set([...Object.keys(o),...Object.keys(n)]);return [...ids].map(id=>{const q=qs().find(x=>String(x.id)===String(id));return{id,q,note:n[id]||'',options:o[id]||{},focus:!!f[id]}}).filter(x=>x.q)}
 function toggleFocus(id){const f=read(FK),q=qs().find(x=>String(x.id)===String(id)),was=!!f[id];if(was)delete f[id];else f[id]={added_at:new Date().toISOString()};write(FK,f);if(q){if(was)window.MusicTeacherSRS?.unscheduleFocus?.(q);else window.MusicTeacherSRS?.scheduleFocus?.(q)}render()}
 function render(){const box=document.getElementById('studyNotesLibrary');if(!box)return;const input=box.querySelector('#studyNotesSearch'),term=(input?.value||'').trim().toLowerCase(),all=entries(),list=all.filter(x=>!term||[x.q.question,x.q.topic,x.q.subject,x.note,...Object.values(x.options)].join(' ').toLowerCase().includes(term));const out=box.querySelector('#studyNotesResults'),count=box.querySelector('#studyNotesCount'),focusCount=all.filter(x=>x.focus).length;if(count)count.textContent=`${all.length} 題有筆記｜⭐ ${focusCount} 題重點`;if(!out)return;if(!list.length){out.innerHTML=`<p class="muted">${all.length?'找不到符合關鍵字的筆記。':'你還沒有建立筆記。做選擇題後，可在四個選項或「本題總筆記」直接新增。'}</p>`;return}out.innerHTML=list.slice(0,100).map(x=>`<details class="note-library-item" style="border:1px solid var(--line);border-radius:12px;padding:10px 12px"><summary style="cursor:pointer"><b>${esc(x.q.topic||x.q.subject||'選擇題')}</b>｜${esc(x.q.question)}</summary>${x.note?`<div style="margin-top:9px"><b>📒 本題總筆記</b><div style="white-space:pre-wrap;margin-top:4px">${esc(x.note)}</div></div>`:''}${Object.entries(x.options).filter(([,v])=>String(v).trim()).map(([k,v])=>`<div style="margin-top:8px"><b>📝 ${k} 選項</b><div style="white-space:pre-wrap;margin-top:3px">${esc(v)}</div></div>`).join('')}<div style="display:flex;justify-content:space-between;gap:8px;align-items:center;flex-wrap:wrap;margin-top:10px"><div class="muted" style="font-size:12px">題號：${esc(x.id)}${x.q.source_title?`｜${esc(x.q.source_title)}`:''}</div><button class="ghost small note-focus-btn" data-id="${esc(x.id)}" type="button">${x.focus?'⭐ 已加入重點｜點一下取消':'☆ 加入重點複習'}</button></div></details>`).join('');out.querySelectorAll('.note-focus-btn').forEach(b=>b.onclick=()=>toggleFocus(b.dataset.id))}
 function mount(){const home=document.getElementById('homeView');if(!home||document.getElementById('studyNotesLibrary'))return;const s=document.createElement('section');s.id='studyNotesLibrary';s.className='card section-card';s.innerHTML='<div class="section-head"><div><span class="eyebrow">MY NOTES</span><h2>📚 我的筆記</h2><p>搜尋自己的補充；⭐ 是額外優先標記。取消星號只會移除人工標記，不會刪除原本的錯題／不知道／到期複習。</p></div><span id="studyNotesCount" class="pill">0 題有筆記</span></div><input id="studyNotesSearch" type="search" placeholder="搜尋：德布西、奏鳴曲式、十二音列……" style="width:100%;padding:11px 12px;border:1px solid var(--line);border-radius:12px;background:var(--card);color:var(--text);margin-bottom:10px"><div id="studyNotesResults" style="display:grid;gap:8px"></div>';home.appendChild(s);s.querySelector('#studyNotesSearch').addEventListener('input',render);render();window.HomeCategoryOrganizer?.apply?.()}
 const ready=()=>document.readyState==='loading'?document.addEventListener('DOMContentLoaded',()=>setTimeout(mount,20),{once:true}):setTimeout(mount,20);ready();window.addEventListener('storage',e=>{if([OK,QK,FK].includes(e.key))render()});document.addEventListener('click',e=>{if(e.target.closest('.option-note-save,#saveQuestionNote,.option-note-clear,#clearQuestionNote'))setTimeout(render,600)});window.StudyNotesLibrary={render,entries,toggleFocus};
})();