(()=>{
 if(window.__STUDY_NOTES_LIBRARY__)return;window.__STUDY_NOTES_LIBRARY__=true;
 const OK='musicTeacherExamOptionNotesV1',QK='musicTeacherExamQuestionNotesV1';
 const read=k=>{try{return JSON.parse(localStorage.getItem(k))||{}}catch{return{}}};
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const qs=()=>window.MusicTeacherExam?.questions||window.LOCAL_QUESTIONS||[];
 function entries(){const o=read(OK),n=read(QK),ids=new Set([...Object.keys(o),...Object.keys(n)]);return [...ids].map(id=>{const q=qs().find(x=>String(x.id)===String(id));return{id,q,note:n[id]||'',options:o[id]||{}}}).filter(x=>x.q)}
 function render(){const box=document.getElementById('studyNotesLibrary');if(!box)return;const input=box.querySelector('#studyNotesSearch'),term=(input?.value||'').trim().toLowerCase(),all=entries(),list=all.filter(x=>!term||[x.q.question,x.q.topic,x.q.subject,x.note,...Object.values(x.options)].join(' ').toLowerCase().includes(term));const out=box.querySelector('#studyNotesResults'),count=box.querySelector('#studyNotesCount');if(count)count.textContent=`${all.length} 題有筆記`;if(!out)return;if(!list.length){out.innerHTML=`<p class="muted">${all.length?'找不到符合關鍵字的筆記。':'你還沒有建立筆記。做選擇題後，可在四個選項或「本題總筆記」直接新增。'}</p>`;return}out.innerHTML=list.slice(0,100).map(x=>`<details class="note-library-item" style="border:1px solid var(--line);border-radius:12px;padding:10px 12px"><summary style="cursor:pointer"><b>${esc(x.q.topic||x.q.subject||'選擇題')}</b>｜${esc(x.q.question)}</summary>${x.note?`<div style="margin-top:9px"><b>📒 本題總筆記</b><div style="white-space:pre-wrap;margin-top:4px">${esc(x.note)}</div></div>`:''}${Object.entries(x.options).filter(([,v])=>String(v).trim()).map(([k,v])=>`<div style="margin-top:8px"><b>📝 ${k} 選項</b><div style="white-space:pre-wrap;margin-top:3px">${esc(v)}</div></div>`).join('')}<div class="muted" style="font-size:12px;margin-top:8px">題號：${esc(x.id)}${x.q.source_title?`｜${esc(x.q.source_title)}`:''}</div></details>`).join('')}
 function mount(){const home=document.getElementById('homeView');if(!home||document.getElementById('studyNotesLibrary'))return;const s=document.createElement('section');s.id='studyNotesLibrary';s.className='card section-card';s.innerHTML='<div class="section-head"><div><span class="eyebrow">MY NOTES</span><h2>📚 我的筆記</h2><p>把做題時留下的補充集中在這裡，直接搜尋名詞、人物、作品或考點。</p></div><span id="studyNotesCount" class="pill">0 題有筆記</span></div><input id="studyNotesSearch" type="search" placeholder="搜尋：德布西、奏鳴曲式、十二音列……" style="width:100%;padding:11px 12px;border:1px solid var(--line);border-radius:12px;background:var(--card);color:var(--text);margin-bottom:10px"><div id="studyNotesResults" style="display:grid;gap:8px"></div>';home.appendChild(s);s.querySelector('#studyNotesSearch').addEventListener('input',render);render();window.HomeCategoryOrganizer?.apply?.()}
 const ready=()=>document.readyState==='loading'?document.addEventListener('DOMContentLoaded',()=>setTimeout(mount,20),{once:true}):setTimeout(mount,20);ready();window.addEventListener('storage',e=>{if(e.key===OK||e.key===QK)render()});document.addEventListener('click',e=>{if(e.target.closest('.option-note-save,#saveQuestionNote,.option-note-clear,#clearQuestionNote'))setTimeout(render,600)});window.StudyNotesLibrary={render,entries};
})();