// 115 新北市公立高中聯甄｜教育專業 × 音樂教學詳細擬答
window.EXTRA_TERMS = window.EXTRA_TERMS || [];
window.EXTRA_TERMS.push(
{term:"Assessment as Learning（評量即學習）",year:"115",school:"新北市公立高中聯甄",rarity:"🔥教育專業／評量",definition:"把評量本身視為學習歷程，強調學生透過自我評量、同儕回饋、目標設定與反思監控自己的學習，核心是後設認知與學習者主體性。",keywords:["self-assessment","metacognition","reflection","self-monitoring","learner agency"],confusion:"as Learning＝學生藉評量學會監控自己；for Learning＝教師蒐集形成性證據來促進下一步學習；of Learning＝總結性判斷學習成果。",teaching:"『演奏偵錯迴圈』：學生錄30秒演奏→依rubric自評→圈出一個最需要改善處→重錄→比較兩版→寫一句『我用了什麼策略，證據是什麼？』。評量不是最後打分，而是下一次練習的導航。",answer:"【定義】Assessment as Learning譯為『評量即學習』，強調學生不是被動接受教師評分，而是在評量歷程中主動監控、理解與調整自己的學習。\n\n【核心】其核心包含自我評量、同儕回饋、目標設定、反思與後設認知。學生必須知道學習目標與成功規準，並能依證據判斷自己目前的位置與下一步策略。\n\n【與其他評量辨析】Assessment for Learning偏重教師利用形成性評量證據調整教學；Assessment of Learning偏向單元或課程結束後的總結性成果判斷；Assessment as Learning則把學生的自我監控本身視為學習。\n\n【音樂課應用】例如學生錄製演奏，依音準、節奏、樂句、音色rubric自評，設定下一輪練習目標，再錄製新版比較。教師評分不是終點，而是讓學生逐步形成自主練習能力。"},
{term:"Performance Level Descriptor（PLD，表現等級描述）",year:"115",school:"新北市公立高中聯甄",rarity:"👹教育評量",definition:"以具體文字描述學習者在不同表現等級所能展現的知識、技能或能力特徵，用來連結評量規準、標準與回饋。",keywords:["criterion-referenced","performance standard","level","descriptor","rubric"],confusion:"PLD不是測驗工具本身，也不是常模排名。它回答的是『達到這個等級的學生能做到什麼？』。",teaching:"把『演奏很好／普通／不好』改寫成三級PLD，例如Level 3：能維持穩定拍感並用力度與樂句呈現結構；Level 2：拍感大致穩定但表情控制不一致；Level 1：節奏中斷且尚需提示。學生再用PLD互評。",answer:"【定義】Performance Level Descriptor是『表現等級描述』，以文字具體說明不同成就或能力等級的典型表現。\n\n【特性】PLD通常屬標準參照取向，重點不是學生排第幾名，而是學生目前達到何種表現標準，以及下一等級需要增加哪些能力。\n\n【用途】可用於rubric、標準本位評量、大型測驗成就等級或課堂表現評量，提供比單一分數更具診斷性的回饋。\n\n【音樂課例】演奏評量可分成不同等級，分別描述節奏穩定度、音準、音色、樂句與詮釋等可觀察行為。\n\n【辨析】音樂性向測驗是一種測驗；PLD則是對表現等級的描述，兩者不能畫上等號。"},
{term:"Fogarty Immersed Model（浸潤式課程統整）",year:"115",school:"新北市公立高中聯甄",rarity:"👹課程統整",definition:"Fogarty課程統整模式之一，由學習者以自身高度投入的興趣、專長或觀點作為濾鏡，自主把不同學科知識浸潤並整合進同一探究脈絡。",keywords:["Fogarty","Immersed","learner-centered","integration","personal lens"],confusion:"Immersed不是『三科教師一起做專案』的同義詞；它特別強調學習者本身以個人興趣／專長主動統整多領域知識。",teaching:"『我的樂器研究所』：學生自行選一件最想研究的樂器，依興趣決定整合路徑：音樂聲響＋物理共振＋數學比例＋歷史文化＋科技製作。教師只提供資源地圖與檢核點，學生自己決定跨域連結。",answer:"【定義】Fogarty提出多種課程統整模式，其中Immersed Model通常譯為『浸潤式』。其特色是學習者從自身興趣、專長或研究焦點出發，把不同學科知識透過個人的認知濾鏡整合起來。\n\n【核心精神】統整的主體不是教師團隊，而是學習者。學生對某主題高度投入後，會主動從不同學科尋找能解決問題的知識。\n\n【辨析】若多科教師共同設計跨科單元，通常較接近其他跨學科／整合模式；Immersed則強調個人化、自主性與深度浸潤。\n\n【音樂課例】學生研究『為什麼小提琴能發出這種聲音』，自行整合弦振動物理、頻率比例數學、製琴工藝、音樂史與演奏技巧，即可呈現浸潤式統整。"},
{term:"CC BY-SA（姓名標示－相同方式分享）",year:"115",school:"新北市公立高中聯甄",rarity:"🔥數位素養／著作權",definition:"Creative Commons授權條款之一；BY要求使用者適當標示原作者／來源，SA要求改作以相同或相容的授權條款分享。",keywords:["Creative Commons","Attribution","ShareAlike","remix","adaptation"],confusion:"BY-SA沒有NC條件，所以不能誤解成『只能非商業使用』；也不能把改作改成完全封閉的All Rights Reserved。",teaching:"『授權卡牌Boss』：每組抽到BY、BY-SA、BY-NC或BY-ND作品卡，再抽『改編、剪輯、商用、上傳』任務卡，判斷能不能做以及成品要怎麼標示；答對才能發布作品。",answer:"【定義】CC BY-SA是Creative Commons『姓名標示－相同方式分享』授權。BY要求使用作品時適當標示原作者、來源與授權資訊；SA要求衍生或改作作品以相同或相容授權方式釋出。\n\n【改作】若教師使用BY-SA樂曲改編成管弦樂版，原則上應標示原作者與來源，指出曾做修改，並讓改編版本繼續採BY-SA或相容授權。\n\n【辨析】BY-SA不包含NC，因此並非單純『非商業才能使用』；也不同於ND，BY-SA允許改作，但必須遵守ShareAlike。\n\n【音樂教育】學生進行remix、編曲、Podcast或數位作品發表時，可透過CC授權理解『可以使用』不代表『不必標示』，並建立數位公民與創作者倫理。"}
);
(function(){var s=document.createElement('script');s.src='questions_115_newtaipei_hs_batch57.js';document.head.appendChild(s);})();
(function(){var s=document.createElement('script');s.src='terms_115_newtaipei_hs_batch67.js';document.head.appendChild(s);})();