window.TERM_PROMPTS = [...(window.TERM_PROMPTS||[]),
{id:"TERM-109-001",term:"Free Jazz",zh:"自由爵士",topic:"爵士與流行音樂",level:"高中音樂",definition:"1950年代末至1960年代興起的爵士取向，弱化或突破固定和聲進行、調性、拍號與傳統曲式限制，強調集體即興、音色探索與演奏者自由互動。",exam:"109 教育部高中聯招名詞解釋。答題可寫：年代、突破傳統和聲／曲式、自由即興，並舉 Ornette Coleman。",related:"Ornette Coleman；collective improvisation；avant-garde jazz"},
{id:"TERM-109-002",term:"Microtonal Music",zh:"微分音音樂",topic:"20世紀音樂",level:"高中音樂",definition:"使用小於西方十二平均律半音的音程單位所構成或包含的音樂；可運用四分音、六分音或其他微分音系統。",exam:"109 教育部高中聯招名詞解釋。不要只寫『音很小』；核心是小於半音的音高分割。",related:"quarter tone；Alois Hába；microtone"},
{id:"TERM-109-003",term:"Musique concrète",zh:"具象音樂／具體音樂",topic:"音樂科技與20世紀音樂",level:"高中音樂",definition:"20世紀中葉在法國發展的電聲音樂創作方式，以錄製的環境聲、物件聲或其他實際聲音為素材，透過剪接、變速、倒放等技術重新組織。",exam:"109 教育部高中聯招名詞解釋。關鍵：Pierre Schaeffer、法國、錄音聲響素材，而非只以電子振盪器合成聲音。",related:"Pierre Schaeffer；electroacoustic music；tape music"},
{id:"TERM-109-004",term:"Lied",zh:"德國藝術歌曲",topic:"浪漫時期音樂",level:"高中音樂",definition:"德語藝術歌曲，尤其指18世紀末至19世紀發展成熟、將詩與音樂緊密結合的聲樂體裁，通常為獨唱與鋼琴；鋼琴常參與描寫情境與心理。",exam:"109 教育部高中聯招名詞解釋。可舉 Schubert、Schumann；注意 Lied 單數、Lieder 複數。",related:"Schubert；Schumann；art song；poetry"},
{id:"TERM-109-005",term:"Gregorian Chant",zh:"葛利果聖歌／額我略聖歌",topic:"中世紀音樂",level:"高中音樂",definition:"西方中世紀羅馬天主教禮儀的重要單音聖歌傳統，主要使用拉丁文、無固定拍節，常以教會調式組織旋律，傳統上為無伴奏單音織體。",exam:"109 教育部高中聯招名詞解釋。答題關鍵：中世紀、拉丁文、單音、無伴奏、教會調式、禮儀。",related:"plainchant；church modes；Roman liturgy"},
{id:"TERM-109-006",term:"Gamelan",zh:"甘美朗",topic:"世界音樂",level:"高中音樂",definition:"印尼爪哇、峇里等地的重要合奏傳統，以鑼、金屬鍵琴等打擊樂器為核心，常使用 sléndro、pélog 等音階／調律系統，並具有層次化節奏與循環結構。",exam:"109 教育部高中聯招名詞解釋。國家＋核心樂器＋sléndro/pélog 是高分關鍵。",related:"Indonesia；Java；Bali；sléndro；pélog"},
{id:"TERM-109-007",term:"八音",zh:"八音分類法",topic:"中國音樂與樂器學",level:"高中音樂",definition:"中國古代依樂器主要製作材料分類的系統，分為金、石、土、革、絲、木、匏、竹八類。",exam:"109 教育部高中聯招名詞解釋。考場至少完整寫出金石土革絲木匏竹，並指出是依製作材料分類。",related:"中國樂器分類；金石土革絲木匏竹"},
{id:"TERM-109-008",term:"Expressionism",zh:"表現主義",topic:"20世紀音樂",level:"高中音樂",definition:"20世紀初與德奧文化圈密切相關的藝術思潮，重視強烈主觀情緒、心理張力與扭曲感；音樂上常與無調性、尖銳不協和及第二維也納樂派相關。",exam:"109 教育部高中聯招名詞解釋。可連結 Schoenberg、Berg、Webern；不要把『表現』泛化成所有有情緒的音樂。",related:"Second Viennese School；atonality；Schoenberg；Berg"},
{id:"TERM-109-009",term:"Plain Song",zh:"素歌／平歌",topic:"中世紀音樂",level:"高中音樂",definition:"基督宗教禮儀中的單音聖歌泛稱，典型特徵包括單音織體、無器樂伴奏、自由節奏與禮儀功能；Gregorian chant 是西方 plainchant 的重要傳統。",exam:"109 高雄市高中聯招名詞解釋。作答時要說明它是較廣義的禮儀單音聖歌概念，不宜直接把 plain song 與 Gregorian chant 完全畫上等號。",related:"plainchant；Gregorian chant；monophony；liturgy"},
{id:"TERM-109-010",term:"Krzysztof Penderecki",zh:"潘德列茨基／潘德列茲基",topic:"20世紀音樂",level:"高中音樂",definition:"波蘭作曲家 Krzysztof Penderecki（1933–2020），早期作品以音群、特殊演奏法、聲響質地與音色探索著稱，代表作包括《廣島受難者輓歌》（Threnody to the Victims of Hiroshima）。",exam:"109 高雄市高中聯招名詞解釋原題姓名拼寫近似 K. Penderecki。答題可寫：波蘭、20世紀／當代、音群與聲響探索、代表作。",related:"Poland；Threnody to the Victims of Hiroshima；tone cluster；sonorism"}
];