// 115 高雄市高中聯甄｜人物、曲種與20世紀音樂延伸詳細擬答
window.EXTRA_TERMS = window.EXTRA_TERMS || [];
window.EXTRA_TERMS.push(
{term:"Ruth Slenczynska",year:"115",school:"高雄市高中聯甄",rarity:"🔥人物／鋼琴演奏史",definition:"美國鋼琴家與音樂教育者，幼年即以神童身分登台，曾向Sergei Rachmaninoff學習；115高雄聯甄以其與Rachmaninoff的師承關係作人物辨識。",keywords:["Ruth Slenczynska","Rachmaninoff","pianist","child prodigy","20th century"],confusion:"考題重點是『Rachmaninoff的學生／女性鋼琴家』，不要與Maria Yudina、Cécile Chaminade或臺灣鋼琴家高慈美混淆。人物題若涉及『最後一名弟子』等新聞式敘述，應以官方題目所給線索辨識，避免自行延伸未核實的生平稱號。",teaching:"做『師承偵探』：學生從作曲家、演奏家、教師三種身分卡建立20世紀鋼琴師承網，再思考演奏傳統如何透過口傳、示範與錄音跨世代傳遞。",answer:"【人物】Ruth Slenczynska是美國鋼琴家與音樂教育者，幼年即展現高度鋼琴才能並登台演奏。\n\n【師承】她曾向俄國作曲家兼鋼琴家Sergei Rachmaninoff學習，因此在鋼琴演奏史與師承脈絡中具有特殊辨識度。\n\n【意義】她的生涯跨越極長年代，可用來觀察20世紀鋼琴演奏傳統如何由師承、舞台演出、錄音與教學延續。\n\n【教甄辨識】115高雄市高中聯甄即以Rachmaninoff師承關係作為人物題線索。\n\n【關鍵字】Ruth Slenczynska、pianist、Rachmaninoff、師承、20世紀鋼琴演奏。"},
{term:"Berceuse（搖籃曲）",year:"115",school:"高雄市高中聯甄",rarity:"⭐音樂術語／曲種",definition:"法文Berceuse意為搖籃曲（lullaby），通常具有柔和、安撫性的性格與規律搖曳感；19世紀後亦成為器樂性格小品的常見標題。",keywords:["Berceuse","Lullaby","搖籃曲","character piece","Chopin"],confusion:"不要與Barcarolle船歌、Elegy輓歌或Solfège視唱練耳混淆。Berceuse的字義核心就是lullaby。",teaching:"播放不標題的Berceuse與Barcarolle片段，讓學生只用拍感、伴奏型、力度與旋律線條推測『搖籃』或『船的搖曳』，再揭曉曲名，訓練從聲音證據理解術語。",answer:"【定義】Berceuse為法文，意指搖籃曲，英文相當於Lullaby。\n\n【音樂性格】通常速度平穩、力度柔和，伴奏常具有規律而搖曳的型態，以營造安撫、催眠或親密的氣氛。\n\n【歷史】浪漫時期以後，Berceuse除了實際的搖籃歌，也成為器樂性格小品的標題；Chopin《Berceuse, Op.57》是著名例子。\n\n【辨析】Barcarolle是船歌，Elegy偏向哀悼／輓歌，Solfège則是視唱與音感訓練。\n\n【關鍵字】French、Lullaby、搖籃曲、柔和、搖曳、character piece。"},
{term:"Clapping Music",year:"115",school:"高雄市高中聯甄",rarity:"🔥20世紀／極簡主義",definition:"Steve Reich於1972年創作的打擊／拍手作品，以同一短節奏型在兩位演奏者之間逐步位移，僅用拍手便產生不斷改變的複合節奏，是極簡主義與process music的重要例子。",keywords:["Steve Reich","1972","Minimalism","process music","rhythmic shifting","clapping"],confusion:"《Clapping Music》不是具體音樂，也不是印象主義；它雖與Reich早期phase technique有親緣，但此曲的程序是其中一聲部保持節奏型，另一聲部按固定程序逐次位移。",teaching:"兩組學生用12拍節奏卡進行『節奏位移Boss』：A組固定，B組每輪向前移一拍，記錄每次形成的新重音與複合節奏；最後用圖像表示『規則不變，結果為何一直改變』。",answer:"【作品】《Clapping Music》是美國作曲家Steve Reich於1972年創作的極簡主義作品。\n\n【編制】作品只需要兩位演奏者拍手，不依賴傳統旋律樂器。\n\n【技法】兩人使用相同的短節奏型，其中一人維持原型，另一人依固定程序逐步移動節奏起點，使兩個相同素材產生不同的複合節奏，最後重新重合。\n\n【風格】它呈現Minimalism常見的重複、穩定脈動、有限素材與可聽見的程序性變化，也是process music的代表例。\n\n【關鍵字】Steve Reich、1972、Minimalism、repetition、rhythmic shifting、process。"}
);
(function(){var s=document.createElement('script');s.src='questions_115_kaohsiung_joint_batch61.js';document.head.appendChild(s);})();
(function(){var s=document.createElement('script');s.src='terms_115_kaohsiung_hs_batch74.js';document.head.appendChild(s);})();
(function(){var s=document.createElement('script');s.src='questions_115_kaohsiung_hs_batch62.js';document.head.appendChild(s);})();