// 115 教育部高中聯甄｜前段選擇延伸名詞詳細擬答
window.EXTRA_TERMS = window.EXTRA_TERMS || [];
window.EXTRA_TERMS.push(
{term:"Iannis Xenakis（澤納基斯／森那基斯）",year:"115",school:"教育部受託公立高中聯甄",rarity:"👹20世紀／數學音樂",definition:"希臘裔法國作曲家、建築與工程背景人物，將機率、集合、統計與數學模型運用於音樂結構，是20世紀stochastic music的重要代表。",keywords:["Xenakis","stochastic music","probability","mathematics","architecture","Metastaseis"],confusion:"不要與Pierre Schaeffer的musique concrète、Varèse的音色／聲響組織或Ligeti的micropolyphony混淆。",teaching:"『機率作曲實驗室』：學生用骰子決定音高區、節奏密度與力度，再比較『隨機』與『受機率規則控制』的差異，最後反思數學規則是否會限制創意。",answer:"【人事時地物】Iannis Xenakis（1922–2001）是20世紀重要作曲家，具工程、數學與建築背景，曾與Le Corbusier合作。\n\n【作曲特色】他將機率論、統計、集合與數學模型引入作曲，以stochastic music建立大量聲部、密度與音響群聚的結構。\n\n【代表】《Metastaseis》等作品常被用來說明數學、建築思維與大型聲響運動的結合。\n\n【辨析】Xenakis的重點不是單純『亂數』，而是用數學規則組織聲音事件的機率與密度。"},
{term:"Bayreuth Festspielhaus & Mystic Gulf（拜魯特慶典劇院與神祕洞穴）",year:"115",school:"教育部受託公立高中聯甄",rarity:"👹Wagner／劇場史",definition:"Richard Wagner為演出其樂劇而規劃的拜魯特慶典劇院，以隱蔽式下沉樂池著稱；樂團與指揮不直接暴露於觀眾視線，Wagner稱其舞臺與觀眾之間形成『mystic gulf』。",keywords:["Wagner","Bayreuth","Festspielhaus","hidden orchestra pit","mystic gulf","music drama"],confusion:"不是維也納金色大廳或柏林愛樂廳；此概念與Wagner的樂劇、觀演關係與整體藝術理念密切相關。",teaching:"用教室模擬兩種演出：一次讓『樂團』坐在觀眾前方可見，一次藏在簾後／側後方，只保留舞臺演員，讓學生比較視覺注意力與聲音來源感受。",answer:"【定義】Bayreuth Festspielhaus是Richard Wagner為實現其樂劇理想而建立的重要劇院。其最具辨識度的設計之一，是將樂池下沉並遮蔽，使觀眾看不到樂團與指揮。\n\n【Mystic Gulf】Wagner將舞臺與觀眾之間的這種特殊距離與聲響遮蔽稱為『mystic gulf』，希望觀眾將注意力集中於舞臺戲劇，同時讓管弦樂聲先在空間中混合再傳至觀眾席。\n\n【意義】此設計與Wagner的music drama及Gesamtkunstwerk理念相互呼應，反映19世紀劇場對視覺、聲音與沉浸式觀演關係的重新設計。"},
{term:"Reggae（雷鬼音樂）",year:"115",school:"教育部受託公立高中聯甄",rarity:"🔥世界流行音樂",definition:"1960年代末形成於牙買加的重要流行音樂類型，以反拍吉他／鍵盤節奏、強調低音與鼓組律動著稱，並常與Rastafari文化、社會批判與Bob Marley連結。",keywords:["Jamaica","offbeat","bass","Rastafari","Bob Marley","1960s"],confusion:"不要與Ska或Rocksteady直接畫等號；三者有歷史關聯，但速度、節奏重心與年代脈絡不同。",teaching:"『反拍任務』：學生先拍四拍正拍，再把和弦聲部移到第2、4拍或反拍位置，搭配低音線，實際感受Reggae的重心如何和一般流行四拍不同。",answer:"【定義】Reggae是1960年代末在Jamaica形成的重要流行音樂風格，承接Ska與Rocksteady等牙買加音樂發展。\n\n【聲響】常見反拍吉他或鍵盤、厚實bass line、具有辨識度的鼓組律動與較放鬆的速度感。\n\n【文化】Reggae與Rastafari思想、反殖民、社會正義與被壓迫者聲音等議題密切相關；Bob Marley是其國際化最具代表性的人物之一。\n\n【辨析】Reggae不是單純『加勒比海音樂』的泛稱，教甄需寫出Jamaica、offbeat、bass、Bob Marley等關鍵字。"},
{term:"Quatuor pour la Fin du Temps（《世界末日四重奏》）",year:"115",school:"教育部受託公立高中聯甄",rarity:"🔥Messiaen／二戰",definition:"Olivier Messiaen於第二次世界大戰戰俘營期間創作的重要室內樂作品，原始編制為單簧管、小提琴、大提琴與鋼琴，1941年首演。",keywords:["Olivier Messiaen","1941","POW camp","clarinet","violin","cello","piano"],confusion:"編制不含flute。作品題名雖談『時間終結』，並非單純戰爭敘事，而與《啟示錄》宗教意象及Messiaen對時間、節奏與永恆的思考密切相關。",teaching:"『缺什麼樂器？』先給戰俘營情境與可用樂器卡，讓學生猜為何會形成如此不尋常的四重奏，再聆聽片段，討論限制如何反而成為創作條件。",answer:"【人事時地物】《Quatuor pour la Fin du Temps》由法國作曲家Olivier Messiaen於第二次世界大戰被俘期間創作，1941年在德國戰俘營首演。\n\n【編制】作品為clarinet、violin、cello、piano四重奏，這個特殊編制與當時可取得的演奏者與樂器條件有關。\n\n【思想】作品靈感與《啟示錄》中的『時間終結』意象相關，Messiaen藉不規則節奏、非逆行節奏與特殊調式等方法思考時間與永恆。\n\n【辨析】教甄常直接問編制；記成『單、小、大、鋼』即可快速排除長笛。"},
{term:"楊弦與臺灣現代民歌運動",year:"115",school:"教育部受託公立高中聯甄",rarity:"🔥臺灣流行音樂史",definition:"楊弦於1975年在臺北中山堂舉辦《現代民謠創作演唱會》，以余光中等現代詩入歌，被視為臺灣1970年代現代民歌／校園民歌運動的重要開端之一。",keywords:["楊弦","1975","臺北中山堂","余光中","現代民謠","校園民歌"],confusion:"不要與李雙澤1976年的淡江『唱自己的歌』事件混淆；兩者都是民歌運動的重要節點，但時間與象徵意義不同。",teaching:"建立『1975→1976→之後』聲音時間軸：學生分組查楊弦、李雙澤、胡德夫等人物，並用一首歌、一張照片、一則時代事件回答『青年為什麼開始想唱自己的歌？』。",answer:"【人物與事件】楊弦是臺灣1970年代現代民歌發展的重要人物。1975年他於臺北中山堂舉辦《現代民謠創作演唱會》，將余光中等現代詩作譜成歌曲公開演出。\n\n【歷史意義】此事件常被視為臺灣現代民歌／校園民歌運動的重要起點之一，象徵青年創作者開始以自己的語言、生活與文學素材創作歌曲。\n\n【辨析】1976年李雙澤的淡江事件與『唱自己的歌』同樣重要，但不是同一事件。考場應分清楊弦＝1975中山堂、李雙澤＝1976淡江。"}
);
(function(){var s=document.createElement('script');s.src='questions_115_moe_hs_batch52.js';document.head.appendChild(s);})();