// 115 國立彰化高中｜名詞解釋詳細擬答
window.EXTRA_TERMS = window.EXTRA_TERMS || [];
window.EXTRA_TERMS.push(
{term:"Hemiola（赫米奧拉／三二節奏錯置）",year:"115",school:"國立彰化高中",rarity:"🔥節奏術語",definition:"在原有拍節感中，透過重音或音符分組使二與三的節奏組織暫時互換；常見於三拍子中形成兩個大拍的聽覺效果。",keywords:["3:2","meter","accent","Baroque","cadence"],confusion:"不是單純切分音，也不是換拍號；關鍵是二與三之間的節拍／分組重新感知。",teaching:"讓學生先拍兩小節3/4，再保持總時值不變改拍成三組二分感，身體直接體驗『看起來三拍、聽起來兩大拍』。",answer:"【定義】Hemiola是一種節奏與節拍知覺的重新分組現象，常表現為三拍系統中的音符或重音暫時形成二拍的大分組，造成3:2或2:3的聽覺張力。\n\n【歷史與應用】文藝復興與巴洛克音樂常見此手法，尤其舞曲與終止前，可利用重音錯置增加推進感；後世作曲家亦持續使用。\n\n【辨析】Hemiola不等於一般syncopation。切分音主要是弱拍延續或重音移位；hemiola的核心則是二與三的節拍分組關係改變。\n\n【關鍵字】3:2、重音重新分組、三拍轉兩大拍、巴洛克、終止。"},
{term:"Heterophony（異音複音／支聲複音）",year:"115",school:"國立彰化高中",rarity:"🔥織度",definition:"兩個以上聲部同時演奏或演唱同一基本旋律，但各聲部以不同裝飾、節奏或細節變形呈現，形成多版本旋律並行的織度。",keywords:["texture","same melody","simultaneous variation","ornamentation","heterophonic"],confusion:"不是homophony的主旋律加和聲，也不是polyphony中彼此獨立的不同旋律線。",teaching:"全班共用一條四小節旋律，各組只能改裝飾音、節奏密度或尾音，最後同時演奏，聽見『同一首旋律的多個版本』。",answer:"【定義】Heterophony是音樂織度的一種，指兩個以上聲部同時以同一基本旋律為核心，但各聲部在節奏、裝飾音、音高細節或演奏方式上略有變化。\n\n【特色】因此聽者既能辨認共同旋律，又能聽見不同版本同時存在。此種織度常見於許多亞洲、中東及傳統音樂的合奏實踐。\n\n【辨析】Homophony通常是主旋律與和聲伴奏；polyphony強調相對獨立的旋律線；heterophony則是『同一旋律的同步變體』。\n\n【關鍵字】同一基本旋律、同步變奏、裝飾差異、織度。"},
{term:"Gebrauchsmusik（實用音樂）",year:"115",school:"國立彰化高中",rarity:"👹20世紀",definition:"20世紀德國音樂思潮之一，強調為實際演奏者、教育、社群或特定功能而創作的音樂；Paul Hindemith為重要代表人物。",keywords:["Germany","1920s","Paul Hindemith","use music","education","community"],confusion:"不是『背景音樂』的泛稱，也不代表作品沒有藝術價值；重點是音樂與實際使用、參與及社會功能的連結。",teaching:"學生為校園真實需求創作30秒功能音樂，例如下課提醒、閱讀空間或社團開場，最後說明『使用者、情境、功能』如何影響創作決策。",answer:"【定義】Gebrauchsmusik常譯為『實用音樂』，主要與20世紀1920年代德國音樂文化相關，強調音樂可為教育、業餘演奏、社群活動或特定實際用途而創作，而不只服務專業音樂廳。\n\n【人物】Paul Hindemith是此概念最常被提及的重要作曲家之一，其部分作品兼顧演奏功能、教育性與現代音樂語言。\n\n【背景】第一次世界大戰後，藝術家重新思考音樂與社會的關係，Gebrauchsmusik反映音樂走向公共參與、教育與功能性的傾向。\n\n【辨析】它不是廉價或純背景音樂的同義詞，而是對『音樂為誰而作、如何被使用』的現代觀念。"},
{term:"Hexachord（六聲音列／六音音階系統）",year:"115",school:"國立彰化高中",rarity:"👹中世紀樂理",definition:"中世紀至文藝復興早期重要的六音教學與唱名系統，與Guido of Arezzo傳統密切相關，以ut–re–mi–fa–sol–la六個唱名組成，分natural、hard、soft等hexachord。",keywords:["Guido of Arezzo","ut re mi fa sol la","natural","hard","soft","mutation"],confusion:"不是現代任意六音集合的唯一意思；歷史樂理題通常指Guidonian hexachord系統，也不可與十二音技法混淆。",teaching:"用三張六音階梯卡C–A、G–E、F–D，讓學生用ut–re–mi–fa–sol–la唱跨越範圍的旋律，遇到需要換系統時體驗mutation。",answer:"【定義】Hexachord在中世紀樂理脈絡中，指由六個音構成的唱名與音高組織單位，以ut、re、mi、fa、sol、la為六個唱名，與Guido of Arezzo及其後形成的教學傳統密切相關。\n\n【種類】常分為natural hexachord（以C為ut）、hard hexachord（以G為ut，使用B natural）與soft hexachord（以F為ut，使用B-flat）。\n\n【Mutation】旋律超出單一六音範圍時，歌者可在不同hexachord之間轉換唱名，此過程稱mutation。\n\n【意義】此系統是理解中世紀視唱、唱名法與musica recta／ficta等概念的重要基礎。"},
{term:"Wozzeck（《伍采克》）",year:"115",school:"國立彰化高中",rarity:"👹20世紀歌劇",definition:"Alban Berg根據Georg Büchner戲劇創作的三幕歌劇，1925年首演，是第二維也納樂派與表現主義歌劇的重要代表，融合無調性語言、嚴密傳統形式與強烈社會心理戲劇。",keywords:["Alban Berg","Büchner","1925","Expressionism","atonality","Second Viennese School"],confusion:"《Wozzeck》不是Schoenberg作品，也不是十二音歌劇的典型起點；Berg在此主要使用自由無調性並結合passacaglia、invention等傳統形式。",teaching:"『聲音心理劇』：學生為Wozzeck的壓迫、焦慮、嫉妒三種心理狀態各設計10秒音色／節奏動機，再討論為何傳統悅耳調性未必適合這個故事。",answer:"【人事時地物】《Wozzeck》是奧地利作曲家Alban Berg依Georg Büchner未完成戲劇《Woyzeck》創作的三幕歌劇，1925年於柏林首演。\n\n【風格】作品是20世紀表現主義歌劇的重要代表，以自由無調性、尖銳音色、Sprechstimme式語言感與高度戲劇化管弦樂描寫人物心理與社會壓迫。\n\n【結構】Berg並未拋棄傳統形式，而將passacaglia、invention、suite等結構嵌入各場，使強烈現代語言與嚴密形式並存。\n\n【意義】作品聚焦底層士兵Wozzeck遭受制度、醫生、上司與情感關係壓迫的悲劇，反映第一次世界大戰前後歐洲的疏離、焦慮與人性危機。\n\n【辨析】作曲家是Berg，不是Schoenberg；作品主要屬自由無調性時期，不能簡化成十二音作品。"}
);
(function(){var s=document.createElement('script');s.src='essay_115_changhua_hs_batch.js';document.head.appendChild(s);})();
(function(){var s=document.createElement('script');s.src='terms_115_changhua_hs_batch53.js';document.head.appendChild(s);})();