// 115 教育部受託公立高中教師甄選｜8大名詞詳細擬答
window.EXTRA_TERMS = window.EXTRA_TERMS || [];
window.EXTRA_TERMS.push(
{term:"Cori Spezzati（分置合唱／分場合唱）",year:"115",school:"教育部受託公立高中聯甄",rarity:"👹文藝復興／威尼斯樂派",definition:"文藝復興晚期威尼斯常見的空間性複合唱團技法，將兩組或以上合唱團／器樂群分置於教堂不同位置，以交替、應答與合奏形成空間對比。",keywords:["Venice","St. Mark's Basilica","San Marco","Andrea Gabrieli","Giovanni Gabrieli","polychoral"],confusion:"不是單純把合唱分聲部；核心是多個ensemble的空間分置與對話。常與Venetian School、San Marco特殊建築聲學連結。",teaching:"把教室四角變成San Marco：兩組學生用同一節奏／和弦做call-and-response，再移到同一位置重唱，比較『空間本身如何成為作曲材料』。",answer:"【定義】Cori spezzati意為『分開的合唱團』，是16世紀威尼斯樂派重要的複合唱團技法。作曲家將兩組或以上歌者、甚至器樂群分置在教堂不同位置，使聲音產生交替、應答、對比與共同合奏效果。\n\n【人事時地物】此技法與威尼斯聖馬可大教堂（San Marco）的建築空間密切相關，Andrea Gabrieli、Giovanni Gabrieli為重要代表。\n\n【意義】它使『空間』成為音樂結構的一部分，也促進文藝復興晚期至早期巴洛克的協奏性對比與大型聲響發展。"},
{term:"Prepared Piano（預置鋼琴）",year:"115",school:"教育部受託公立高中聯甄",rarity:"🔥20世紀實驗音樂",definition:"在鋼琴弦間或弦上放置螺絲、橡皮、螺帽等物件，改變原有音高、音色、延音與共鳴，使鋼琴轉化為具有打擊樂色彩的聲響裝置；John Cage為核心人物。",keywords:["John Cage","prepared piano","Sonatas and Interludes","timbre","percussion","objects"],confusion:"不是在琴上加電子效果，也不是任意破壞鋼琴；Cage作品通常精確指定材料、位置與準備方式。",teaching:"不直接把物件塞入學校鋼琴。可用弦線盒、橡皮筋與安全物件製作『預置聲音模型』，學生先預測聲音，再測試並記錄音色變化。",answer:"【定義】Prepared Piano是將特定物件依指定位置放置於鋼琴弦之間或弦上，以改變鋼琴原有音色與共鳴的20世紀演奏／創作技法。\n\n【人物作品】John Cage是此技法最重要的發展者之一，《Sonatas and Interludes》為代表作品。\n\n【美學】一架鋼琴可因此產生近似鑼、鼓、金屬或複合打擊樂器的聲響，反映20世紀對音色、噪音與樂器身分的重新思考。"},
{term:"Passion（受難曲）",year:"115",school:"教育部受託公立高中聯甄",rarity:"🔥宗教音樂",definition:"以耶穌基督受難與死亡敘事為核心的大型宗教聲樂體裁，文本主要依福音書受難敘事發展；巴洛克時期J. S. Bach的《馬太受難曲》《約翰受難曲》為代表。",keywords:["Passion","Gospel","Holy Week","J.S. Bach","St Matthew Passion","Evangelist"],confusion:"Passion不是一般Oratorio的同義詞；題材特指基督受難敘事。也不要與Mass彌撒曲固定經文混淆。",teaching:"以角色卡分Evangelist、Jesus、群眾、反思性詠唱，學生聽片段判斷『誰在敘事？誰在行動？誰代表信徒反思？』，從戲劇功能理解大型宗教作品。",answer:"【定義】Passion（受難曲）是以新約福音書中耶穌受難、死亡故事為核心的宗教聲樂體裁，與聖週禮儀傳統密切相關。\n\n【巴洛克代表】J. S. Bach《St Matthew Passion》與《St John Passion》最具代表性，常以Evangelist敘事、人物對話、群眾合唱、詠唱與聖詠共同構成。\n\n【辨析】它與Oratorio同樣可具大型聲樂器樂編制，但Passion的題材範圍更明確；亦不同於Mass以固定彌撒經文為核心。"},
{term:"Hexachord（六聲唱名系統）",year:"115",school:"教育部受託公立高中聯甄",rarity:"👹中世紀樂理",definition:"中世紀視唱與音高組織的重要六音系統，以ut–re–mi–fa–sol–la為唱名，後世與Guidonian tradition密切相關，常分natural、hard、soft hexachord。",keywords:["ut re mi fa sol la","Guido","natural","hard","soft","mutation"],confusion:"歷史樂理的hexachord不是泛指任何六音音階，也不是十二音技法中的六音集合概念。",teaching:"用C–A、G–E、F–D三條六音階梯卡唱旋律，超出一張卡時必須『換地圖』，由學生自己發現mutation的必要。",answer:"【定義】Hexachord在中世紀與文藝復興早期樂理中，是由ut、re、mi、fa、sol、la六個唱名構成的視唱與音高組織單位。\n\n【三類】Natural hexachord以C為ut；hard hexachord以G為ut並使用B natural；soft hexachord以F為ut並使用B-flat。\n\n【Mutation】旋律跨越單一hexachord時，可在不同六音系統間轉換唱名，稱mutation。此概念是理解中世紀視唱法的重要基礎。"},
{term:"Pansori（盤索里）",year:"115",school:"教育部受託公立高中聯甄",rarity:"👹韓國傳統音樂",definition:"韓國傳統敘事聲樂藝術，通常由一位歌者sorikkun與一位鼓手gosu共同演出；歌者結合歌唱、說白、動作與長篇故事敘事。",keywords:["Korea","sorikkun","gosu","buk","narrative singing","UNESCO"],confusion:"不是多人合唱，也不是韓國宮廷雅樂；其核心是單一敘事歌者與鼓手之間的互動。",teaching:"『一人一鼓一故事』：學生兩人一組，一人用唱、說、動作敘述60秒校園事件，一人只用鼓點與口頭應聲支援，體驗歌者與鼓手如何共同塑造敘事張力。",answer:"【定義】Pansori（盤索里）是韓國重要的傳統敘事聲樂藝術，由歌者sorikkun與鼓手gosu合作完成。歌者以歌唱、說白與身體動作演繹長篇故事，鼓手以buk伴奏並以口頭應聲鼓舞歌者。\n\n【特色】表演高度依賴聲音表情、節奏型、即興與觀眾互動，常由一位歌者扮演多種人物。\n\n【文化意義】Pansori兼具音樂、文學、戲劇與口傳文化價值，是理解韓國傳統表演藝術的重要入口。"},
{term:"Fado（法朵）",year:"115",school:"教育部受託公立高中聯甄",rarity:"👹葡萄牙傳統都市歌曲",definition:"19世紀葡萄牙里斯本等都市環境發展的重要歌唱傳統，以強烈情感、命運與saudade意象著稱，常由歌者搭配Portuguese guitar與古典吉他。",keywords:["Portugal","Lisbon","saudade","Portuguese guitar","Amália Rodrigues","urban song"],confusion:"Fado不是西班牙Flamenco；前者核心在葡萄牙都市歌曲與saudade，後者則與西班牙安達魯西亞歌舞傳統相關。",teaching:"播放Fado與Flamenco各一段，學生不能先猜國家，只能從人聲、樂器、節奏、身體動作提出證據，最後再揭曉文化背景，避免用『南歐音樂都一樣』的刻板印象。",answer:"【定義】Fado是葡萄牙重要的都市歌曲傳統，19世紀在里斯本等地逐漸發展。其表現常圍繞愛、離別、命運、城市生活與難以言喻的思念情緒，常以saudade概括。\n\n【聲響】典型演出由歌者搭配葡萄牙吉他（Portuguese guitar）及古典吉他等伴奏。Amália Rodrigues是20世紀國際推廣Fado的重要歌者。\n\n【辨析】Fado屬葡萄牙文化，不等於西班牙Flamenco。"},
{term:"Polytonality（多調性）",year:"115",school:"教育部受託公立高中聯甄",rarity:"🔥20世紀和聲",definition:"兩個或以上可辨識的調性中心同時存在的音樂現象；若主要是兩個調性並置，常稱bitonality。",keywords:["polytonality","bitonality","tonal centers","20th century","Milhaud","Stravinsky"],confusion:"Polytonality強調多個調性中心；Polychord強調多個和弦結構同時疊置。兩者可能同時發生，但不是同義詞。",teaching:"兩組學生各維持不同調的固定旋律／和弦，先分開再疊合，要求聽者回答『我還能同時感覺兩個家嗎？』，再與單純複合和弦比較。",answer:"【定義】Polytonality是兩個或以上調性中心同時存在的作曲現象，是20世紀擴張傳統調性的重要方法之一；兩個調性並存時亦常稱bitonality。\n\n【人物】Milhaud常被視為多調性技法的重要代表，Stravinsky等作曲家的部分作品也呈現相關現象。\n\n【辨析】Polychord描述和弦疊置；polytonality描述調性中心並存，答題時應分清分析層次。"},
{term:"Mystic Chord（神秘和弦）",year:"115",school:"教育部受託公立高中聯甄",rarity:"👹Scriabin／20世紀和聲",definition:"與Alexander Scriabin晚期音樂密切相關的六音和聲集合，常以四度疊置方式描述，例如C–F♯–B♭–E–A–D；又稱Prometheus chord。",keywords:["Scriabin","Prometheus chord","six-note chord","quartal","Prometheus: The Poem of Fire"],confusion:"不是Messiaen的有限移位調式，也不是Schoenberg十二音列；核心人物是Scriabin。",teaching:"把六個音分成六張角色卡，學生先按三度疊置失敗，再嘗試四度關係排列，聽比較傳統屬七與Mystic Chord的張力差異，討論『和弦一定要有傳統功能嗎？』。",answer:"【定義】Mystic Chord（神秘和弦）是與俄國作曲家Alexander Scriabin晚期創作密切相關的六音和聲集合，也常稱Prometheus chord。常見音高示例為C–F♯–B♭–E–A–D，可從四度結構理解其特殊音響。\n\n【作品】Scriabin《Prometheus: The Poem of Fire》是最常與此和弦連結的作品。\n\n【意義】它反映Scriabin晚期逐漸遠離傳統功能和聲，以特殊音集合、色彩與神秘哲學建立個人音樂語言。"}
);
(function(){var s=document.createElement('script');s.src='essay_115_moe_hs_batch.js';document.head.appendChild(s);})();