// 115 新北高中聯招｜第二批選擇題升級名詞詳細擬答
window.EXTRA_TERMS = window.EXTRA_TERMS || [];
window.EXTRA_TERMS.push(
{term:"French Overture（法式序曲）",year:"115",school:"新北高中聯招",rarity:"👹巴洛克",definition:"17世紀法國宮廷歌劇與芭蕾常見的序曲類型，與Jean-Baptiste Lully密切相關，典型由莊嚴、附點節奏的慢段與較快速、模仿對位的段落構成。",keywords:["Lully","Baroque","dotted rhythm","slow-fast","imitative counterpoint"],confusion:"不要與Italian Overture混淆：義大利序曲典型為快—慢—快，並與早期交響曲發展有關；French Overture的招牌是莊嚴附點節奏與後續快速模仿段。",teaching:"『序曲身分證』：給學生四段音樂，只能用速度、附點節奏、織度三項線索判斷French或Italian Overture；答對後再畫成節奏／織度圖像卡。",answer:"【定義】French Overture即法式序曲，是17世紀法國巴洛克宮廷音樂的重要序曲形式，尤其與Jean-Baptiste Lully及路易十四時期的歌劇、芭蕾文化密切相關。\n\n【特徵】典型結構以前段莊嚴緩慢、具有鮮明附點節奏為特色，後段轉為較快速並常採模仿對位或賦格性織度；部分作品亦可能再回到較慢材料。\n\n【辨析】法式序曲不可與Italian Overture混淆。義大利序曲常見快—慢—快三段配置，而法式序曲的高辨識關鍵是『莊嚴附點節奏＋快速模仿段』。\n\n【教學】可讓學生比較Lully、Handel或Bach作品中的法式序曲，先用身體踏步表現莊嚴附點節奏，再用分組模仿呈現快速對位段，使形式從聽覺轉為身體與視覺理解。"},
{term:"Symphony of Psalms（《詩篇交響曲》）",year:"115",school:"新北高中聯招",rarity:"👹20世紀作品",definition:"Igor Stravinsky於1930年創作的合唱與管弦樂作品，以拉丁文《詩篇》為文本，展現其新古典主義時期宗教性、客觀化與特殊配器音響。",keywords:["Stravinsky","1930","Latin Psalms","Neoclassicism","no violins/violas"],confusion:"最常考的配器陷阱是：作品並非沒有弦樂，而是刻意省略小提琴與中提琴，仍使用大提琴與低音提琴。",teaching:"『消失的樂器』：先播放一般浪漫交響曲與《詩篇交響曲》片段，學生以音色偵探表猜哪些聲部消失，再公布配器，討論作曲家如何用限制創造神聖、冷峻的音響。",answer:"【作品】《Symphony of Psalms》（《詩篇交響曲》）為Igor Stravinsky於1930年創作的重要合唱管弦樂作品，使用拉丁文《詩篇》文本，屬其新古典主義時期代表作之一。\n\n【音樂特徵】作品不以浪漫式個人情感為核心，而強調宗教性、形式秩序、節奏與音響結構。其特殊配器尤其著名：刻意省略小提琴與中提琴，卻保留大提琴與低音提琴，並運用木管、銅管及鋼琴等形成獨特而莊嚴的音色。\n\n【辨析】教甄若問『省略哪些樂器』，答案是violin與viola，而不是所有弦樂。\n\n【教學】可用『如果拿掉管弦樂團最高音域的弦樂，音色會發生什麼變化？』作為探究問題，讓學生比較聲響後再回推配器與作曲美學。"},
{term:"Assessment as Learning（評量即學習）",year:"115",school:"新北高中聯招",rarity:"🔥教育專業",definition:"把評量本身視為學生學習歷程的一部分，強調學生透過自評、同儕回饋、後設認知與反思監控自己的理解並調整策略。",keywords:["self-assessment","metacognition","reflection","student agency","feedback"],confusion:"Assessment of Learning偏總結結果；Assessment for Learning由教師運用評量資訊促進下一步學習；Assessment as Learning更凸顯學生自己監控、判斷與調整學習。",teaching:"錄下學生第一次演奏，讓學生依『節奏穩定、音準、句法、表情』rubric自評，只選一項作為下一輪改善目標；第二次錄音後寫證據說明是否改善。",answer:"【定義】Assessment as Learning可譯為『評量即學習』，其核心是讓學生在評量過程中發展後設認知與自我調整能力，使學生不只是被教師評分，而能主動蒐集自己學習的證據、判斷表現並修正策略。\n\n【方法】常見方式包括自我評量、同儕回饋、學習日誌、rubric、自我提問及反思紀錄。\n\n【辨析】Assessment of Learning主要判斷學習成果；Assessment for Learning強調教師利用形成性評量促進學習；Assessment as Learning則把學生置於評量核心，培養其自我監控與自主學習能力。\n\n【音樂教學】例如學生錄製演奏影片後依rubric自評，找出一項需要改善的音樂表現，重新練習、再錄製並比較兩版差異。此時評量不是課程最後才發生，而直接成為學習循環。"},
{term:"Morendo／Smorzando",year:"115",school:"新北高中聯招",rarity:"👹術語",definition:"兩者皆可表達聲音逐漸消逝的效果。Morendo意近『逐漸死去』，常涉及音量乃至速度、表情的消退；Smorzando意近『熄滅、消失』，表示聲響逐漸減弱至消失。",keywords:["dying away","fading","dynamics","tempo","expression"],confusion:"不要與diminuendo只理解為一般漸弱完全等同；也不要與Stringendo／Affrettando（加緊、加快）或Allargando（漸寬廣）混淆。",teaching:"『術語表情包』：學生抽到Morendo、Smorzando、Stringendo、Allargando四張卡，用同一句四小節旋律演奏出差異，同學只靠聲音猜術語並說出證據。",answer:"Morendo與Smorzando都是義大利音樂術語，常用於表示聲音逐漸減弱並趨向消失。Morendo字義近似『逐漸死去』，除音量外有時亦暗示速度與生命感逐步消退；Smorzando則有『熄滅』之意，著重聲響逐漸消散。教甄辨識時，可將兩者與Stringendo、Affrettando等催促加快術語，以及Allargando的漸寬廣效果區分。實際教學可讓學生用同一旋律演奏不同術語，再以聽覺證據描述力度、速度與表情如何改變。"}
);
// 載入下一站：115高雄國中聯甄
(function(){["questions_115_kaohsiung_jhs_batch43.js","terms_115_kaohsiung_jhs_batch48.js"].forEach(function(src){var s=document.createElement("script");s.src=src;s.defer=false;document.head.appendChild(s);});})();