// 115 新北市公立高中聯甄｜世界／流行音樂延伸名詞詳細擬答
window.EXTRA_TERMS = window.EXTRA_TERMS || [];
window.EXTRA_TERMS.push(
{term:"八音分類（Bayin）",year:"115",school:"新北市公立高中聯甄",rarity:"🔥中國音樂",definition:"中國古代依樂器主要製作材料分類的系統，分金、石、土、革、絲、木、匏、竹八類。",keywords:["金石土革絲木匏竹","instrument classification","Chinese music"],confusion:"分類依主要材料而非現代發音原理。篪為竹製吹管，屬竹；塤為陶土製，屬土。",teaching:"『八音材質偵探』：給學生樂器照片與材質卡，不先給名稱，先依觸感／材料分類，再與Hornbostel–Sachs依發音原理分類比較。",answer:"【定義】八音是中國古代依樂器主要製作材料建立的分類方式，共分金、石、土、革、絲、木、匏、竹八類。\n\n【例子】鐘屬金、磬屬石、塤屬土、鼓屬革、琴瑟屬絲、柷敔屬木、笙屬匏、簫笛篪屬竹。\n\n【意義】八音反映古代中國禮樂制度、材料文化與樂器觀念。\n\n【辨析】它與Hornbostel–Sachs不同：八音主要看材料；後者主要看聲音由何種物體振動產生。"},
{term:"Raga／Tala／Swaras",year:"115",school:"新北市公立高中聯甄",rarity:"🔥印度音樂",definition:"印度古典音樂三個常見核心概念：Raga是具有特定音級、行進、重要音與情感／時段聯想的旋律框架；Tala是循環性節奏組織；Swaras則指音級。",keywords:["India","Raga","Tala","Swaras","improvisation"],confusion:"Raga不是單純西方scale，Tala也不等於只有拍號；Slendro屬印尼甘美朗音階，不是印度核心概念。",teaching:"三層任務：第一組只拿音級限制、第二組拿節奏循環、第三組拿即興規則；合奏後辨認哪張卡對應Raga、Tala、Swaras。",answer:"【Raga】印度古典音樂的旋律組織框架，不只是音階，還包含上行／下行方式、重要音、典型樂句及特定情緒、時辰等文化聯想。\n\n【Tala】循環性的節奏時間架構，由固定拍數與重音／空拍關係組成，是演奏與即興的重要時間基礎。\n\n【Swaras】指印度音樂中的音級，常以Sa、Re、Ga、Ma、Pa、Dha、Ni表示。\n\n【辨析】三者可簡記為『旋律語法Raga＋節奏週期Tala＋音級Swaras』；不要把印尼Slendro混入。"},
{term:"Minimalism（極簡音樂）",year:"115",school:"新北市公立高中聯甄",rarity:"🔥20世紀／電影配樂",definition:"20世紀後半重要音樂思潮，以有限素材、反覆型、穩定脈動、漸進變化與長時間過程為常見特徵；Steve Reich、Philip Glass等為重要代表。",keywords:["repetition","process","pulse","Philip Glass","Steve Reich"],confusion:"不是『音符很少』就叫Minimalism；重點常在反覆與逐步變化的時間過程。Ravel《Boléro》有反覆與漸強，但不因此成為極簡主義作品。",teaching:"『只准改一件事』：四小節循環反覆六次，每次只能改一項參數（音高、密度、力度、配器），讓學生體驗微小變化如何累積成大尺度時間感。",answer:"【定義】Minimalism是20世紀1960年代後在美國特別重要的音樂思潮，常以簡化素材、規律脈動、短型反覆及漸進式過程組織音樂。\n\n【人物】La Monte Young、Terry Riley、Steve Reich、Philip Glass等常被列為代表人物。\n\n【特色】作品可能透過phase shifting、additive process、反覆琶音或和聲緩慢轉換，使聽者注意細微變化與時間流動。\n\n【應用】Philip Glass的電影配樂常利用反覆琶音與層次堆疊建立心理時間與壓迫感。\n\n【辨析】Minimalism不是單純『一直重複』，而是反覆素材與可感知的漸變過程。"},
{term:"Hip-hop Culture（嘻哈文化）",year:"115",school:"新北市公立高中聯甄",rarity:"🔥流行音樂／社會文化",definition:"1970年代於紐約Bronx非裔與拉丁裔社群形成的城市青年文化，常以DJing、MCing／rap、breaking與graffiti等元素描述，並與街區派對、取樣、breakbeat及社會議題表達密切相關。",keywords:["Bronx","DJ Kool Herc","MCing","breaking","graffiti","breakbeat"],confusion:"不要寫成『起源於Harlem，由一位歌手發明』；它是Bronx街區多種文化實踐共同形成。",teaching:"『四元素城市地圖』：學生把DJ、MC、breaking、graffiti分別連到聲音、語言、身體、視覺，再選一項校園議題製作30秒節奏口白；反思藝術如何成為公共表達。",answer:"【時地人】Hip-hop文化主要形成於1970年代紐約Bronx的非裔與拉丁裔青年社群，街區派對與DJ文化是重要背景。\n\n【元素】常以DJing、MCing／rap、breaking、graffiti四大元素概括，另可延伸beatboxing與knowledge等觀點。\n\n【人物】DJ Kool Herc常被稱為Hip-hop先驅／Hip-hop之父之一，其延長break段的DJ實踐對breaking與rap發展影響深遠。\n\n【社會意義】Hip-hop不只是音樂類型，也是青年以聲音、語言、舞蹈與視覺藝術回應城市生活、族群、階級與政治議題的文化。"}
);
(function(){var s=document.createElement('script');s.src='questions_115_newtaipei_hs_batch56.js';document.head.appendChild(s);})();
(function(){var s=document.createElement('script');s.src='terms_115_newtaipei_hs_batch66.js';document.head.appendChild(s);})();