// 115 教育部高中聯甄｜後段複選延伸名詞詳細擬答
window.EXTRA_TERMS = window.EXTRA_TERMS || [];
window.EXTRA_TERMS.push(
{term:"Krzysztof Penderecki（潘德列茨基）",year:"115",school:"教育部受託公立高中聯甄",rarity:"🔥20世紀／波蘭",definition:"波蘭20至21世紀重要作曲家，早期以音群、特殊奏法與音色組織形成前衛聲響語言，後期逐漸轉向較具調性與新浪漫色彩的寫作；亦創作大量宗教作品。",keywords:["Poland","sonorism","tone cluster","Polymorphia","Threnody","St Luke Passion"],confusion:"不要與Bartók混淆：《Concerto for Orchestra, Sz.116》是Bartók；Penderecki也不是一生只寫前衛實驗音樂。",teaching:"『聲音恐怖片配樂師』：學生先聽Polymorphia／Threnody片段，用音群、滑音、特殊奏法、密度四張偵探卡描述聲響，再比較後期作品，思考同一作曲家的風格為何會改變。",answer:"【人事時地物】Krzysztof Penderecki（1933–2020）是波蘭重要作曲家與指揮家。\n\n【早期風格】1950至60年代作品常以tone cluster、微分音、弦樂特殊奏法、音色與聲響密度作為結構材料，與波蘭音響主義／sonorism密切相關。《Threnody to the Victims of Hiroshima》《Polymorphia》為代表。\n\n【宗教與後期】他並未停留在單一前衛風格，《St Luke Passion》等顯示宗教題材的重要性；1970年代後逐步融入較傳統、調性與新浪漫語彙。\n\n【考場辨析】看到Polymorphia、Threnody、音群、特殊弦樂奏法可優先聯想到Penderecki；《Concerto for Orchestra, Sz.116》則是Bartók。"},
{term:"A Cappella（無伴奏人聲音樂／現代阿卡貝拉）",year:"115",school:"教育部受託公立高中聯甄",rarity:"🔥當代人聲",definition:"廣義指不依賴器樂伴奏的人聲音樂；現代A Cappella常以不同人聲聲部模擬旋律、和聲、低音與鼓組，並大量使用vocal percussion、beatbox與麥克風音色技術。",keywords:["voices only","vocal percussion","beatbox","Deke Sharon","Pentatonix","O-Kai"],confusion:"A Cappella不是『只能唱純和聲、不能打beatbox』；現代A Cappella的重要特色正是把人聲擴張成完整樂團功能。",teaching:"四人一組分Lead、Harmony、Bass、Vocal Percussion，先只用嘴完成8小節流行歌伴奏，再交換角色；最後反思『哪一個聲部拿掉後最像少了一件樂器？』。",answer:"【定義】A Cappella原指不依賴器樂伴奏的人聲演唱。當代A Cappella進一步利用人聲建立主唱、和聲、bass與vocal percussion等功能，使人聲形成近似完整樂團的聲響。\n\n【當代發展】Deke Sharon是現代A Cappella推廣的重要人物，亦參與《Pitch Perfect》相關音樂製作；Pentatonix則以流行編曲、多層人聲與vocal percussion聞名。臺灣亦有歐開合唱團、尋人啟事等團體。\n\n【辨析】Beatbox／vocal percussion並不違反A Cappella概念，因為聲音來源仍是人聲。"},
{term:"客家八音（Hakka Bayin）",year:"115",school:"教育部受託公立高中聯甄",rarity:"🔥臺灣傳統音樂",definition:"臺灣客家社會重要的器樂合奏傳統，常見於婚喪喜慶、祭典與生命禮俗等場合；『八音』源自傳統樂器材料分類概念，不代表固定由八位演奏者組成。",keywords:["Hakka","Bayin","ritual","suona","percussion","life-cycle ceremonies"],confusion:"最大陷阱是『八音＝八個人』。編制可因地區、場合與團體而異；也不能簡化成只有絲竹樂器。",teaching:"給學生婚禮、喪禮、廟會三張情境卡與樂器音色卡，要求設計最合適的客家八音聲景，並說明『音樂在儀式裡負責什麼工作』。",answer:"【定義】客家八音是臺灣客家文化中重要的傳統器樂合奏，與婚喪喜慶、祭祀及各類生命禮俗密切相關。\n\n【名稱】『八音』原與金、石、絲、竹、匏、土、革、木等傳統樂器材料分類觀念相關，不是規定必須八人演奏。\n\n【聲響】實際編制依地域與場合不同，可包含嗩吶、弦樂器、鑼鼓等，兼具儀式、娛樂與社群功能。\n\n【教甄陷阱】看到『主要只有絲竹』『固定八人』都應提高警覺。"},
{term:"Birth of the Cool",year:"115",school:"教育部受託公立高中聯甄",rarity:"🔥Jazz",definition:"Miles Davis領導的九人編制錄音計畫，主要錄於1949–1950年，後以《Birth of the Cool》專輯形式發行；其較柔和、精緻的編曲與特殊音色組合成為Cool Jazz發展的重要象徵。",keywords:["Miles Davis","Cool Jazz","nonet","Gil Evans","French horn","tuba"],confusion:"不是Bebop的典型小編制jam session，也不是大樂團Swing；其nonet介於小組與big band之間，並加入French horn、tuba等特殊音色。",teaching:"把同一旋律分別做成『Bebop高速小組版』與『Cool九重奏音色版』，學生用速度、音色、密度、編曲四項證據判斷風格，而不是只靠年代背答案。",answer:"【人事時地物】《Birth of the Cool》與Miles Davis於1949–1950年間領導的nonet錄音密切相關，後來集結發行成專輯。\n\n【編制】九人編制除小號、薩克斯風與節奏組外，還使用French horn與tuba等音色，使聲部配置較接近精緻編曲的小型管樂團。\n\n【風格意義】作品以較克制、透明、細緻的音色與編曲，和Bebop常見的高速複雜即興形成對比，是Cool Jazz的重要歷史節點。\n\n【關鍵字】Miles Davis、nonet、French horn、tuba、Cool Jazz。"}
);
(function(){var s=document.createElement('script');s.src='questions_115_moe_hs_batch51.js';document.head.appendChild(s);})();
(function(){var s=document.createElement('script');s.src='terms_115_moe_hs_batch61.js';document.head.appendChild(s);})();