window.TERM_QUESTIONS = window.TERM_QUESTIONS || [];
window.TERM_QUESTIONS.push(
{term:"Ennio Morricone（顏尼歐・莫里科內）",category:"電影配樂｜👹冷門高鑑別",source:"110 教育部高中聯招延伸",answer:"義大利作曲家、指揮家 Ennio Morricone（1928–2020），20世紀最具代表性的電影配樂家之一。早年受古典作曲訓練，作品橫跨實驗音樂、流行編曲與電影配樂；與導演 Sergio Leone 長期合作，以《荒野大鏢客》系列、《黃昏三鏢客》、《四海兄弟》等建立獨特的西部片聲響，另有《教會》與《八惡人》等重要作品。其配樂常使用口哨、人聲、電吉他、鐘聲與非傳統音色，並善用主題動機塑造人物與敘事。教甄辨析：John Williams 作《哈利波特：神秘的魔法石》，不是 Morricone。\n\n【5W2H】Who：Morricone；When：20–21世紀；Where：義大利／國際電影；What：電影配樂；How：主題動機＋特殊音色＋管弦／流行混合；Why：以音樂直接參與影像敘事。\n\n【老師怎麼教】先播放同一電影片段的靜音版與配樂版，讓學生標記情緒、人物與時間感的改變，再用教室樂器替一段無聲影片設計20秒主題。\n\n【考場擬答】Ennio Morricone為義大利作曲家與電影配樂大師，代表作包括《教會》、《黃昏三鏢客》、《四海兄弟》等。他善以鮮明主題動機及口哨、人聲、電吉他等特殊音色結合管弦樂，強化人物、場景與敘事，是20世紀電影音樂的重要代表。"},
{term:"Muqam／木卡姆",category:"世界音樂｜👹冷門高鑑別",source:"歷屆教甄名詞",answer:"Muqam（木卡姆）是中亞與伊斯蘭文化圈重要的音樂組織概念，名稱在不同地區具有不同實踐；在中國新疆維吾爾族音樂中，以「十二木卡姆」最具代表性，是包含歌、舞、器樂與敘事的龐大套曲傳統。它不是單純等同西洋的『調式音階』，而涉及旋律模式、曲目次序、節奏型、即興與文化實踐。新疆十二木卡姆於2005年列入 UNESCO 人類口述和非物質遺產代表作相關名錄體系。\n\n【易混淆】Muqam ≠ Major/minor key；不能只寫『新疆音階』。阿拉伯 maqam、波斯 dastgah、維吾爾 muqam 彼此相關但不可完全等同。\n\n【老師怎麼教】用『如果一個歌單不只規定音階，還規定曲目順序、節奏、即興與舞蹈，它還只是調式嗎？』引導比較西洋調性與木卡姆。\n\n【考場擬答】Muqam是中亞及伊斯蘭文化圈的重要音樂模式與套曲概念。維吾爾族十二木卡姆尤具代表性，融合歌唱、器樂、舞蹈、節奏與即興，具有固定傳承脈絡與大型套曲結構，因此不可僅視為西洋意義的音階或調式。"},
{term:"Dies Irae（震怒之日）",category:"中世紀／引用音樂｜👹冷門高鑑別",source:"歷屆教甄名詞",answer:"Dies Irae意為『震怒之日』，是中世紀拉丁文安魂彌撒傳統中的著名聖詠旋律，內容描寫末日審判。旋律開頭具有高度辨識度，後世作曲家常引用它象徵死亡、命運、恐懼或超自然意象，例如 Berlioz《幻想交響曲》第五樂章、Liszt《死之舞》、Rachmaninoff多部作品等。\n\n【易混淆】Mozart《Requiem》雖有名為 Dies irae 的段落，但考『引用古老 Dies Irae 聖詠旋律』時必須實際辨識旋律，不可只因作品有同名經文就判定。\n\n【老師怎麼教】做『死亡旋律偵探』：先讓學生聽原始聖詠，再從電影與古典作品中找相似四音／旋律輪廓，討論為何同一旋律能跨數百年成為文化符號。\n\n【考場擬答】Dies Irae為中世紀拉丁安魂彌撒傳統中的聖詠，意為『震怒之日』，描寫末日審判。其旋律後來成為死亡與命運的音樂象徵，Berlioz、Liszt、Rachmaninoff等作曲家皆曾引用。"},
{term:"Cori spezzati（分割合唱／複合唱隊）",category:"文藝復興／威尼斯樂派｜👹冷門高鑑別",source:"歷屆教甄名詞",answer:"Cori spezzati意為『分開的合唱隊』，是16世紀威尼斯樂派著名的空間性複合唱隊技法。作曲家將歌者或器樂者分成兩組以上，配置於教堂不同位置，以交替、呼應與合奏造成宏大的立體聲響；與威尼斯聖馬可大教堂的建築空間密切相關。代表人物包括 Adrian Willaert、Andrea Gabrieli、Giovanni Gabrieli。\n\n【易混淆】不是單純『複音音樂』，關鍵是多組 ансамбль 的空間分置與對答；並對巴洛克 concertato style 發展有重要影響。\n\n【老師怎麼教】把班級分成教室四角，先用同一句節奏做左右對答，再逐步疊加，讓學生直接用身體位置感受空間如何成為作曲參數。\n\n【考場擬答】Cori spezzati為16世紀威尼斯樂派的分割合唱技法，常將兩組以上合唱或器樂團分置於教堂不同位置，以交替、應答與合奏形成空間化聲響。聖馬可大教堂及 Gabrieli家族是重要脈絡，並影響巴洛克協奏風格。"},
{term:"Sonata da camera",category:"巴洛克體裁｜👹冷門高鑑別",source:"歷屆教甄名詞",answer:"Sonata da camera意為『室內奏鳴曲』，是巴洛克時期重要器樂體裁之一，主要用於世俗宮廷或室內場合，常由前奏曲加上一系列舞曲構成。與 sonata da chiesa（教會奏鳴曲）相對；後者通常採慢－快－慢－快等抽象樂章安排。Corelli是此類體裁的重要代表。\n\n【易混淆】Sonata da camera不是『三重奏鳴曲』的同義詞；camera/chiesa指功能與樂章性格，trio sonata則指聲部／編制概念，兩種分類可以交叉。\n\n【老師怎麼教】讓學生拿『場合卡：教堂／舞會』與『樂章卡：Allemande／Courante／慢快慢快』配對，快速建立功能與曲式差異。\n\n【考場擬答】Sonata da camera即巴洛克室內奏鳴曲，主要服務世俗宮廷與室內娛樂，常由前奏曲及多首舞曲組成；與較偏教會用途、常採慢快慢快配置的 sonata da chiesa相對。Corelli為重要代表。"},
{term:"Isorhythmic Motet（等節奏經文歌）",category:"中世紀 Ars Nova｜👹冷門高鑑別",source:"歷屆教甄名詞",answer:"Isorhythmic motet是14世紀 Ars Nova 常見的經文歌技法，尤其與 Philippe de Vitry、Guillaume de Machaut等脈絡相關。其核心是在較低聲部反覆使用固定的節奏模式 talea，而旋律音高序列稱 color；兩者長度可不同，因此重合位置會隨反覆而改變，形成大型結構。\n\n【易混淆】Isorhythm不是『每個聲部節奏都一樣』；也不同於文藝復興模仿複音。必背 talea＝節奏、color＝音高旋律。\n\n【老師怎麼教】用8格節奏循環配6音旋律循環，讓兩張卡同時重複，學生會直接看到『不同週期何時重新對齊』。\n\n【考場擬答】Isorhythmic motet為14世紀 Ars Nova的重要經文歌技法，常在 tenor等低聲部使用反覆的節奏模式 talea與旋律音高序列 color。兩者可具有不同長度，藉不同週期的重組形成大型結構，Vitry與Machaut作品中可見。"},
{term:"Gebrauchsmusik（實用音樂）",category:"20世紀音樂｜👹冷門高鑑別",source:"歷屆教甄名詞",answer:"Gebrauchsmusik是德文『實用音樂／功能音樂』，主要與1920年代德國音樂思潮相關，主張音樂不應只為音樂廳中的藝術自主性服務，也可為教育、業餘演奏、社群與特定場合而創作。Paul Hindemith常被視為代表人物之一，並與青年音樂、業餘合奏及音樂教育實踐相關。\n\n【易混淆】不是指『商業背景音樂』，也不是泛指所有有用途的音樂；考試要放回兩次世界大戰間德國的文化與教育脈絡。\n\n【老師怎麼教】請學生比較『為比賽寫的炫技曲』與『為全班都能演奏而寫的作品』，討論功能如何改變作曲選擇。\n\n【考場擬答】Gebrauchsmusik為20世紀1920年代德國興起的『實用音樂』理念，強調音樂可服務教育、業餘演奏與社會生活，而非只追求音樂廳中的藝術自主。Hindemith是重要代表人物。"},
{term:"Ritornello Form（利都奈羅曲式）",category:"巴洛克協奏曲｜👹冷門高鑑別",source:"歷屆教甄名詞",answer:"Ritornello意為『返回的小段落』。巴洛克協奏曲中，常由全體樂團 tutti 的 ritornello主題反覆回歸，中間穿插獨奏者的 episode；回歸段可能移調、縮短或只取部分素材。Vivaldi協奏曲尤其具代表性，並影響後來協奏曲第一樂章的形式思維。\n\n【易混淆】不是古典時期 rondo的完全同義詞；ritornello強調 tutti回歸與solo episode的對比，而且回歸內容可以不完整。\n\n【老師怎麼教】用『Boss關卡』比喻：全班固定主題＝Boss回歸，個人即興＝探索區；每次Boss可以少一段或換調。\n\n【考場擬答】Ritornello form是巴洛克協奏曲常見形式，由全體樂團反覆出現的ritornello段落與獨奏episode交替構成。回歸段可移調、縮短或節錄，Vivaldi協奏曲為典型代表。"},
{term:"Sprechstimme／Sprechgesang",category:"20世紀聲樂｜👹冷門高鑑別",source:"歷屆教甄名詞",answer:"Sprechstimme（說話聲調）是介於說話與歌唱之間的聲樂技巧，與 Schoenberg 的表現主義作品密切相關，最著名例子為1912年的《Pierrot lunaire（月迷彼埃羅）》。演唱者依記譜掌握節奏與大致音高，但音高通常迅速離開而呈現語音化效果。\n\n【易混淆】不是普通朗誦，也不是完全依固定音高持續歌唱；Sprechstimme與Sprechgesang用語在不同文獻有細微差異，教甄核心抓『說唱之間＋Schoenberg＋Pierrot lunaire』。\n\n【老師怎麼教】同一句文字分別用朗讀、歌唱、Sprechstimme三種方式演出，讓學生用耳朵界定聲音連續光譜。\n\n【考場擬答】Sprechstimme為介於說話與歌唱之間的聲樂技法，20世紀表現主義音樂中具代表性。Schoenberg《月迷彼埃羅》大量使用此法，演唱者依節奏與記譜音高起音後迅速離開固定音高，形成特殊語音化聲響。"},
{term:"Mystic Chord（神秘和弦）",category:"20世紀和聲｜👹冷門高鑑別",source:"歷屆教甄名詞",answer:"Mystic Chord（神秘和弦）與俄國作曲家 Alexander Scriabin 晚期作品密切相關，又常稱 Prometheus chord，著名於《Prometheus: The Poem of Fire》。常見拼法可表示為 C–F♯–B♭–E–A–D，其結構可視為以四度為主的六音集合。Scriabin藉此建立脫離傳統功能和聲的色彩與神秘哲學聲響世界。\n\n【易混淆】不是 Schoenberg的十二音列，也不是 Messiaen的有限移位調式；關鍵人物是 Scriabin。\n\n【老師怎麼教】先彈傳統V7–I，再彈Mystic Chord，讓學生用『期待解決／懸浮色彩』描述聽感，再反推和聲功能差異。\n\n【考場擬答】Mystic Chord為Scriabin晚期常用的六音和弦，又稱Prometheus chord，常以四度性結構理解，代表作品為《Prometheus: The Poem of Fire》。它弱化傳統功能和聲，形成Scriabin神秘主義與音色化和聲的重要語彙。"},
{term:"Cool Jazz（酷派爵士）",category:"爵士樂史｜👹冷門高鑑別",source:"歷屆教甄名詞",answer:"Cool Jazz主要興起於1940年代末至1950年代，常被視為對Bebop高速、強烈與複雜風格的一種不同取向。其聲響較克制、平滑，重視編曲、音色與較寬鬆的節奏感。Miles Davis《Birth of the Cool》是重要象徵，另可連結 Gerry Mulligan、Chet Baker、Dave Brubeck等。\n\n【易混淆】爵士時間軸可抓：Swing → Bebop → Cool／Hard Bop → Modal → Free → Fusion；Cool不是1920年代爵士。\n\n【老師怎麼教】同一節課盲聽Bebop與Cool Jazz，讓學生用速度、音色、密度、動態四個維度投票，最後才揭曉年代與人物。\n\n【考場擬答】Cool Jazz為1940年代末至1950年代重要爵士風格，相較Bebop常呈現較克制、平滑、重視編曲與音色的聲響。Miles Davis《Birth of the Cool》是代表性作品，並影響1950年代美國西岸爵士發展。"}
);