(()=>{const terms=[
{id:'TERM-H108-01',term:'Polyphony',zh:'複音音樂／複音織體',topic:'音樂織度',level:'高中音樂',definition:'兩個或以上具有相對獨立性的旋律聲部同時進行所形成的織體。各聲部具有旋律意義，而非單純由主旋律加和弦伴奏構成。',exam:'108 彰化女中名詞釋義。作答關鍵：多聲部、旋律獨立性、同時進行；可與 homophony 對照。',related:'counterpoint；homophony；Renaissance'},
{id:'TERM-H108-02',term:'Ars Nova',zh:'新藝術',topic:'中世紀音樂',level:'高中音樂',definition:'14世紀法國重要音樂風格與理論潮流，名稱與 Philippe de Vitry 的理論著作相關；其記譜與節奏系統更具彈性，世俗複音音樂亦高度發展。',exam:'108 彰化女中名詞釋義。建議寫：14世紀法國、Philippe de Vitry、節奏記譜革新、Machaut。',related:'Philippe de Vitry；Guillaume de Machaut；isorhythm'},
{id:'TERM-H108-03',term:'Requiem',zh:'安魂彌撒／安魂曲',topic:'宗教音樂',level:'高中音樂',definition:'羅馬天主教為亡者所舉行的彌撒及以其經文為基礎的音樂作品，名稱來自入祭唱 Requiem aeternam 的開頭。後世亦形成脫離禮儀使用的音樂會作品。',exam:'108 彰化女中名詞釋義。可舉 Mozart、Verdi、Fauré；注意不同作曲家選用的經文段落不盡相同。',related:'Mass；Dies irae；Mozart；Verdi；Fauré'},
{id:'TERM-H108-04',term:'Oratorio',zh:'神劇／清唱劇',topic:'巴洛克音樂',level:'高中音樂',definition:'大型聲樂體裁，常使用獨唱、合唱與管弦樂並具有敘事或戲劇性內容，但傳統上不以完整舞台佈景、服裝與戲劇動作演出。',exam:'108 彰化女中題目拼作 Oratoria，標準常用英文為 Oratorio。答題可與 opera 比較，並舉 Handel《Messiah》。',related:'Handel；Messiah；opera；chorus'},
{id:'TERM-H108-05',term:'Opera seria',zh:'正歌劇／嚴肅歌劇',topic:'歌劇史',level:'高中音樂',definition:'18世紀義大利歌劇的重要類型，多取材神話、歷史或英雄題材，重視獨唱者與 da capo aria，宣敘調與詠嘆調功能分明。',exam:'108 彰化女中名詞釋義。可寫與 opera buffa 相對；代表作曲家可連結 Handel、Hasse、Mozart 部分作品。',related:'opera buffa；da capo aria；recitative'},
{id:'TERM-H110-01',term:'Troubadour',zh:'特魯巴杜爾／南法遊唱詩人',topic:'中世紀音樂',level:'高中音樂',definition:'約11至13世紀活躍於法國南部奧克語地區的宮廷詩人音樂家，創作世俗單音歌曲，題材常涉及宮廷愛情。',exam:'110 教育部高中聯招名詞釋義。關鍵：南法、Occitan、世俗單音歌、courtly love；北法對應 trouvère。',related:'trouvère；courtly love；monophony'},
{id:'TERM-H110-02',term:'Aleatory Music',zh:'機遇音樂／偶然音樂',topic:'20世紀音樂',level:'高中音樂',definition:'作品的創作、結構排列或演奏實現中，部分因素由偶然程序或演奏者選擇決定，因此不同演出可能產生不同結果。',exam:'110 教育部高中聯招名詞釋義。可連結 John Cage；要說清楚「不確定性發生在哪一層」。',related:'John Cage；chance music；indeterminacy'},
{id:'TERM-H110-03',term:'Countertenor',zh:'假聲男高音／高男聲',topic:'聲樂與演唱',level:'高中音樂',definition:'成年男性以特殊聲區與技巧演唱接近女低音或女高音音域的高聲部，現代常使用頭聲或假聲機制，尤其常見於早期音樂演出。',exam:'110 教育部高中聯招名詞釋義。不要與 castrato 混淆：countertenor 是聲樂聲部／演唱方式，不等同閹伶。',related:'falsetto；alto；castrato；early music'},
{id:'TERM-H110-04',term:'Binary Form',zh:'二段體',topic:'曲式學',level:'高中音樂',definition:'由兩個主要段落構成的曲式，通常標示為 A–B；巴洛克舞曲中常見兩段各自反覆，調性設計常由主調走向近系調，再返回主調。',exam:'110 教育部高中聯招名詞釋義。進階需辨識 simple/rounded binary，以及 sectional/continuous binary。',related:'rounded binary；sectional；continuous；dance forms'},
{id:'TERM-H110-05',term:'Neue Zeitschrift für Musik',zh:'《新音樂雜誌》',topic:'浪漫時期音樂',level:'高中音樂',definition:'1834年創刊的德國重要音樂期刊，與 Robert Schumann 密切相關；舒曼藉評論倡議具有藝術理想的新音樂，並介紹與支持同時代及新進作曲家。',exam:'110 教育部高中聯招名詞釋義。答題至少寫：德國音樂期刊、1834、Schumann、音樂評論；可連結 Davidsbündler。',related:'Robert Schumann；music criticism；Davidsbündler'},
{id:'TERM-H110-06',term:'Christoph Willibald Gluck',zh:'葛路克',topic:'古典時期與歌劇',level:'高中音樂',definition:'18世紀作曲家，對歌劇改革具有關鍵地位，主張音樂服務戲劇、減少炫技與僵化慣例，使序曲、合唱、舞蹈與戲劇發展更具整體性。',exam:'110 教育部高中聯招以5分名詞釋義直接考人物。代表作品《Orfeo ed Euridice》；可連結 opera reform 與《Alceste》序言。',related:'opera reform；Orfeo ed Euridice；Alceste'},
{id:'TERM-H110-07',term:'VGL',zh:'視覺化圖形聆聽（Visual Graphic Listening）',topic:'音樂教育與科技',level:'高中音樂',definition:'以視覺圖像或圖形化資訊協助聆聽者追蹤音樂進程、結構與聲響事件的聆聽方式；實際術語用法應依命題來源與教材脈絡核對。',exam:'110 教育部高中聯招要求寫英文全名、中文字義與特色。此縮寫在不同脈絡可能有歧義，因此題庫標示為「需來源核對」的高鑑別名詞，不建議只死背縮寫。',related:'visual listening；graphic representation；music appreciation'}
];window.TERM_PROMPTS=Array.isArray(window.TERM_PROMPTS)?window.TERM_PROMPTS:[];const ids=new Set(window.TERM_PROMPTS.map(x=>x.id));terms.forEach(x=>{if(!ids.has(x.id))window.TERM_PROMPTS.push(x)});})();