// 115 高雄市立高雄高級中學｜正式教師甄選：名詞解釋第一批
window.EXTRA_TERMS = window.EXTRA_TERMS || [];
window.EXTRA_TERMS.push(
{term:"Imitation Mass（仿作彌撒／模仿彌撒）",year:"115",school:"高雄市立高雄高級中學",rarity:"👹文藝復興／彌撒曲",definition:"文藝復興時期常見的彌撒曲創作方式之一，作曲家以既有複音作品（如motet、chanson等）的多個聲部或整體素材作為彌撒各樂章的結構與音樂來源。",keywords:["Renaissance","Mass","model composition","motet","chanson","parody mass"],confusion:"不要與cantus firmus mass混淆。Cantus firmus mass通常以一條既有旋律作固定旋律；Imitation/Parody Mass則常吸收原作多個聲部、動機與段落結構。",teaching:"『音樂DNA重組』：先給學生一段四聲部motet，讓各組圈出2個節奏動機與2個旋律動機，再要求用同一批素材創作新的8小節段落，體驗文藝復興作曲家如何『借素材但不是照抄』。",answer:"【定義】Imitation Mass又稱Parody Mass，是文藝復興時期重要的彌撒曲創作方式。作曲家以既有複音作品，如motet、chanson或madrigal等為模型，將其多聲部動機、模仿結構、和聲進行或段落配置重新運用於Kyrie、Gloria、Credo、Sanctus、Agnus Dei等彌撒常用樂章。\n\n【特色】它不是單純引用一條旋律，而是吸收原作較完整的複音織度與結構，因此更像對既有作品的『再作曲』。\n\n【辨析】Cantus firmus Mass以一條固定旋律為核心；Imitation/Parody Mass則常取用原作多個聲部與動機。\n\n【歷史意義】此類型反映文藝復興作曲家對既有音樂素材進行再組織與創造的觀念，也是理解當時『原創』概念的重要窗口。"},
{term:"Poème électronique（《電子詩》）",year:"115",school:"高雄市立高雄高級中學",rarity:"🔥電子音樂／空間聲響",definition:"Edgard Varèse為1958年布魯塞爾世界博覽會Philips Pavilion創作的電子音樂作品，結合預錄聲音、電子聲響與建築空間中的多聲道播放，是20世紀聲音藝術與空間音樂的重要作品。",keywords:["Edgard Varèse","1958","Brussels World’s Fair","Philips Pavilion","Le Corbusier","Iannis Xenakis","electronic music"],confusion:"不要把它當一般管弦樂作品；其核心是電子聲響、建築空間與多聲道聲音移動。",teaching:"『聲音建築師』：學生先畫教室平面圖，標示四個喇叭位置，再設計30秒聲音從A→B→C移動的路徑，最後反思『音樂一定只能從舞台前方來嗎？』。",answer:"【人事時地物】《Poème électronique》是法裔美國作曲家Edgard Varèse於1958年為布魯塞爾世界博覽會Philips Pavilion創作的電子音樂作品。\n\n【場域】Philips Pavilion由Le Corbusier主持、Iannis Xenakis深度參與設計，作品並非只為音樂廳，而是為特定建築空間與多媒體展演而作。\n\n【音樂特色】作品以預錄聲音、電子聲響、噪音與多聲道播放構成，聲音可在空間中移動，讓建築本身成為作品的一部分。\n\n【歷史意義】它是20世紀電子音樂、聲音空間化與跨媒體藝術的重要里程碑，也預示今日聲音裝置與沉浸式展演。"},
{term:"Mahler Symphony No. 2 ‘Resurrection’（馬勒第二號交響曲《復活》）",year:"115",school:"高雄市立高雄高級中學",rarity:"🔥浪漫晚期／交響曲",definition:"Gustav Mahler於1888至1894年間完成的大型五樂章交響曲，末樂章加入女高音、女低音與合唱，主題由死亡、追問生命意義走向復活與超越。",keywords:["Mahler","Symphony No.2","Resurrection","five movements","chorus","Urlicht"],confusion:"不要與Mahler《Das Lied von der Erde》混淆；第二號交響曲是五樂章交響曲，末樂章合唱加入『復活』主題。",teaching:"把五樂章做成『生命旅程地圖』，學生用情緒曲線、音色與動機標記從衝突→回憶→荒誕→Urlicht→復活的轉折，再討論大型交響曲如何敘事。",answer:"【人事時地物】Mahler《Symphony No.2 in C minor, Resurrection》創作於1888–1894年間，是其早期大型交響曲代表。\n\n【結構與編制】全曲五樂章，使用龐大管弦樂團，第四樂章〈Urlicht〉加入女低音獨唱，末樂章再加入女高音、女低音與合唱。\n\n【思想】作品由死亡、人生困惑與荒誕感逐步走向希望、復活與精神超越。\n\n【音樂史意義】它延伸Beethoven之後『交響曲加入人聲』的傳統，同時展現晚期浪漫主義對龐大編制、哲學主題與長篇結構的追求。\n\n【關鍵字】Mahler、五樂章、Urlicht、chorus、Resurrection、晚期浪漫。"},
{term:"Sonata da chiesa（教會奏鳴曲）",year:"115",school:"高雄市立高雄高級中學",rarity:"🔥巴洛克／器樂體裁",definition:"巴洛克時期重要器樂奏鳴曲類型，常用於教會或莊重場合，典型四樂章配置為慢－快－慢－快，與以舞曲為核心的sonata da camera相對。",keywords:["Baroque","church sonata","slow-fast-slow-fast","Corelli","sonata da camera"],confusion:"不要把它和sonata da camera混淆。Da chiesa偏抽象、莊重且少用明確舞曲名稱；da camera則常由Allemande、Courante、Sarabande、Gigue等舞曲組成。",teaching:"『奏鳴曲身分證』：給學生兩組四樂章標題與速度，一組慢快慢快、一組Allemande–Courante–Sarabande–Gigue，判斷哪組是da chiesa、哪組是da camera，再說出證據。",answer:"【定義】Sonata da chiesa意為『教會奏鳴曲』，是巴洛克時期常見的器樂奏鳴曲類型。\n\n【結構】典型常見四樂章，速度安排為慢－快－慢－快；快速樂章可能運用模仿與賦格式對位。\n\n【人物】Arcangelo Corelli是此類型的重要代表作曲家。\n\n【辨析】Sonata da camera意為『室內奏鳴曲』，常以舞曲組曲形式呈現；da chiesa則較少直接使用舞曲名稱，風格更莊重。\n\n【關鍵字】Baroque、Corelli、slow-fast-slow-fast、church sonata、對位。"},
{term:"Pasibutbut（祈禱小米豐收歌）—高中教甄完整版",year:"115",school:"高雄市立高雄高級中學",rarity:"🔥臺灣原住民族音樂",definition:"布農族重要祭儀歌唱傳統，與小米農耕及祈求豐收相關，以男性多聲部合唱、音高逐步堆疊與集體聆聽合作著稱。",keywords:["Bunun","millet","ritual","polyphony","Kurosawa","Taiwan Indigenous music"],confusion:"不要只背『八部合音』；實際演唱並非每次固定八聲部，也不要與排灣族〈來甦〉混淆。",teaching:"『聲音疊塔』：全班從共同低音開始，依訊號逐層加入音高；完成後再聽原始Pasibutbut，反思『多聲部合作靠的是誰唱最大聲，還是彼此聽見？』。",answer:"【定義】Pasibutbut是臺灣布農族重要的祭儀性歌唱傳統，與小米農耕、祈求作物豐收的文化脈絡密切相關。\n\n【音樂特色】常由男性集體演唱，聲部由較低音開始，逐步加入與上移，形成密集而持續變化的多聲部和聲。\n\n【文化意義】其歌唱不只是音樂表演，也涉及祭儀、集體合作、農耕生活與族群認同。\n\n【研究史】20世紀黑澤隆朝等人的採錄，使布農族複音歌唱受到國際民族音樂學界注意。\n\n【辨析】『八部合音』是常見俗稱，不應誤解為固定八聲部。"}
);
(function(){var s=document.createElement('script');s.src='essay_115_kaohsiung_hs_batch2.js';document.head.appendChild(s);})();
(function(){var s=document.createElement('script');s.src='questions_115_kaohsiung_hs_batch63.js';document.head.appendChild(s);})();