window.TERM_PROMPTS = [...(window.TERM_PROMPTS || []),
{id:'term111-through',level:'高中音樂',topic:'西洋音樂史',term:'Through-composed song',zh:'貫穿全曲式歌曲',definition:'歌曲各段歌詞持續使用新的或明顯變化的音樂素材，不以同一段旋律反覆套用各詩節；常用於需要隨文本情緒、敘事與戲劇轉折改變音樂的藝術歌曲。',exam:'111國立基隆高中非選直接考名詞。答題可寫：相對於 strophic form；音樂隨文本發展；舒伯特《魔王》是常見辨識例。',related:'strophic form、varied strophic、Schubert、Erlkönig'},
{id:'term111-ragtime2',level:'高中音樂',topic:'爵士與流行音樂',term:'Ragtime',zh:'散拍音樂／拉格泰姆',definition:'19世紀末至20世紀初美國流行的鋼琴音樂類型，常見穩定低音與切分化高音旋律，與非裔美國音樂傳統及早期爵士發展密切相關。',exam:'111基隆高中直接考名詞；113基隆女中又要求名詞解釋後舉高中欣賞素材，屬跨年升級考點。可連結 Scott Joplin。',related:'Scott Joplin、syncopation、early jazz'},
{id:'term111-varese',level:'高中音樂',topic:'20世紀音樂',term:'Edgard Varèse',zh:'華列斯／瓦雷茲',definition:'20世紀重要現代音樂作曲家，重視音色、節奏、聲響空間與打擊樂，並對電子音樂與組織聲響的觀念具有先驅性影響。',exam:'111基隆高中直接考人物名詞。可寫代表作 Ionisation、Poème électronique，並強調 sound masses 與電子聲響。',related:'Ionisation、Poème électronique、electronic music、sound mass'},
{id:'term112-melismatic',level:'高中音樂',topic:'西洋音樂史',term:'Melismatic',zh:'花唱式／一字多音',definition:'同一個音節延伸演唱多個音高的旋律處理方式，與 syllabic（一字一音）形成對比；在聖歌、宗教聲樂與多種民族聲樂中皆可見。',exam:'112六家高中直接考名詞解釋。答題務必寫出「one syllable, many notes」並與 syllabic 對照。',related:'syllabic、neumatic、Gregorian chant'},
{id:'term112-ternary',level:'高中音樂',topic:'曲式與分析',term:'Ternary form',zh:'三段體',definition:'由三個主要段落構成，典型結構為 A-B-A；第三段回歸第一段素材，可為原樣或有所變化。',exam:'112六家高中直接考名詞。注意不要只寫「三段」，應指出 A-B-A 的對比與回歸關係。',related:'binary form、ABA、da capo'},
{id:'term112-analog',level:'高中音樂',topic:'音樂科技',term:'Analog recording',zh:'類比錄音',definition:'以連續變化的物理訊號記錄聲音波形，例如磁帶或唱片溝槽；與將聲音取樣、量化成數位資料的 digital recording 相對。',exam:'112六家高中直接考名詞，顯示音樂科技已進入高中教甄非選題。可比較 analog 與 digital 的訊號型態、媒介與轉換。',related:'digital recording、sampling、vinyl、magnetic tape'},
{id:'term112-offbroadway',level:'高中音樂',topic:'音樂劇與劇場',term:'Off-Broadway',zh:'外百老匯',definition:'紐約專業劇場類型之一，通常指座位規模小於 Broadway、但大於 Off-Off-Broadway 的劇場與製作體系；常提供較具實驗性或較低成本作品發展空間。',exam:'112教育部高中聯招名詞解釋。答題可從紐約劇場生態、規模與作品發展功能切入。',related:'Broadway、Off-Off-Broadway、musical theatre'},
{id:'term112-hemiola',level:'高中音樂',topic:'節奏與曲式',term:'Hemiola',zh:'赫米奧拉／三二節奏轉換',definition:'常指在原本三拍分組中形成二拍的大分組感，或二與三之間的節奏比例與重音重新組織；巴洛克舞曲終止附近常見。',exam:'112教育部高中聯招名詞解釋。不要只背「3:2」，應說明拍群或重音知覺的重新分組。',related:'3:2、metric grouping、Baroque dance'},
{id:'term112-carmina',level:'高中音樂',topic:'20世紀音樂',term:'Carmina Burana',zh:'《布蘭詩歌》',definition:'Carl Orff 於20世紀創作的世俗清唱劇／舞台康塔塔，文本取自中世紀拉丁文、德文等詩歌集；以強烈節奏、反覆音型與鮮明音響著稱。',exam:'112教育部高中聯招直接考名詞。可寫作曲家 Orff、文本來源、中世紀世俗詩歌、O Fortuna 與節奏特色。',related:'Carl Orff、O Fortuna、cantata、medieval poetry'},
{id:'term112-emi-clil',level:'高中音樂',topic:'雙語音樂教育',term:'EMI / CLIL / Immersion',zh:'全英授課／內容語言整合／沉浸式教育',definition:'EMI以英語作為學科教學媒介，學科內容通常是主要目標；CLIL同時設定學科內容與語言學習目標；Immersion則以目標語大量、持續地作為多科或整體學習環境。',exam:'112六家高中以10分申論要求比較三者。答題至少比較「內容目標、語言目標、使用比例／環境、教師鷹架」四面向。',related:'bilingual education、multimodality、language scaffolding'}
];