(()=>{
 if(window.__UNKNOWN_BOOK_VIEWS_V1__)return;window.__UNKNOWN_BOOK_VIEWS_V1__=true;
 const STATS='musicTeacherExamStatsV1',SRS='musicTeacherExamSpacedReviewV1';
 const load=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}},qs=()=>window.MusicTeacherExam?.questions||[];
 function historyPool(){const s=load(STATS,{attempts:{}});return qs().filter(q=>((s.attempts?.[q.id]?.unknown)||0)>0)}
 function currentPool(){const s=load(STATS,{attempts:{},unknown:[]}),r=load(SRS,{}),api=window.MusicTeacherSRS,legacy=new Set((s.unknown||[]).map(String));return qs().filter(q=>{if(api?.effectiveRisk)return api.effectiveRisk(q,r,s)==='unknown';const x=r[q.id]||{},id=String(q.id);if(x.lastResult==='unknown')return true;if((x.correctStreak||0)>=2)return false;return legacy.has(id)})}
 function start(pool,label){if(!pool.length){alert(label.includes('目前')?'目前沒有仍然「不知道」的題目 🎉':'目前還沒有曾按過「我不知道」的題目。');return}window.MusicTeacherExam?.startCustomQuiz(pool,label,pool.length)}
 function ensureButtons(){let btn=document.querySelector('[data-mode="unknown"]');if(!btn){const wrongHist=document.getElementById('wrongHistoryBtn'),wrong=document.querySelector('[data-mode="wrong"]'),grid=wrong?.parentElement||document.querySelector('.mode-grid');if(!grid)return null;btn=document.createElement('button');btn.className='mode-card';btn.type='button';btn.dataset.mode='unknown';btn.innerHTML='<span class="mode-icon">❓</span><b>目前仍不知道</b><small></small>';if(wrongHist)wrongHist.insertAdjacentElement('afterend',btn);else if(wrong)wrong.insertAdjacentElement('afterend',btn);else grid.appendChild(btn)}let hist=document.getElementById('unknownHistoryBtn');if(!hist){hist=document.createElement('button');hist.id='unknownHistoryBtn';hist.className='mode-card';hist.type='button';hist.innerHTML='<span class="mode-icon">🧾</span><b>歷史曾不知道</b><small></small>';btn.insertAdjacentElement('afterend',hist);hist.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();start(historyPool(),'🧾 歷史曾不知道')})}return{btn,hist}}
 function refresh(){const current=currentPool(),history=historyPool(),els=ensureButtons();const count=document.getElementById('unknownCount');if(count)count.textContent=current.length;const label=count?.closest('.stat')?.querySelector('.label');if(label)label.textContent='目前仍不知道';if(!els)return;const {btn,hist}=els;btn.querySelector('b')&&(btn.querySelector('b').textContent='目前仍不知道');btn.querySelector('small')&&(btn.querySelector('small').textContent=`現在仍需重新建立概念 ${current.length} 題`);hist.querySelector('small').textContent=`保留曾按過「我不知道」的 ${history.length} 題`}
 document.addEventListener('click',e=>{const b=e.target.closest('[data-mode="unknown"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();start(currentPool(),'❓ 目前仍不知道')},true);
 function watch(){refresh();window.addEventListener('storage',e=>{if([STATS,SRS].includes(e.key))refresh()});window.addEventListener('musicExamLearningSynced',refresh);const fb=document.getElementById('feedback');if(fb&&!fb.dataset.unknownViewsObserved){fb.dataset.unknownViewsObserved='1';new MutationObserver(()=>{if(!fb.classList.contains('hidden'))setTimeout(refresh,80)}).observe(fb,{attributes:true,attributeFilter:['class']})}}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(watch,280),{once:true});else setTimeout(watch,280);
 window.UnknownBookViews={currentPool,historyPool,refresh};
})();