(()=>{
 if(window.__WEAKNESS_TREND_V3__)return;window.__WEAKNESS_TREND_V3__=true;
 const STATS='musicTeacherExamStatsV1',LOG='musicTeacherExamAttemptLogV1',SESSION='musicTeacherExamWeaknessTrendDrillV1';
 const load=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}},save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
 const qs=()=>window.MusicTeacherExam?.questions||[],esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function normalizeLog(raw){const rows=Array.isArray(raw)?raw:[],seen=new Set(),out=[];for(const x of rows){if(!x?.id)continue;const attemptNo=Number(x.attemptNo||String(x.key||'').split(':')[1]||0),attemptAt=Number(x.attemptAt||x.at||0),signature=attemptNo?`${x.id}:${attemptNo}`:`${x.id}:${x.status||''}:${Math.floor(attemptAt/1500)}`;if(seen.has(signature))continue;seen.add(signature);out.push({...x,id:String(x.id),attemptNo,attemptAt:attemptAt||x.at||Date.now(),key:`${x.id}:${attemptNo||0}:${attemptAt||x.at||0}`})}return out.sort((a,b)=>(a.at||0)-(b.at||0)).slice(-1500)}
 function readLog(){const raw=load(LOG,[]),clean=normalizeLog(raw);if(clean.length!==raw.length||clean.some((x,i)=>x.key!==raw[i]?.key))save(LOG,clean);return clean}
 function metrics(){const s=load(STATS,{topics:{}}),log=readLog(),cut=Date.now()-14*86400000,recent=log.filter(x=>(x.at||x.attemptAt||0)>=cut),topics=new Map();Object.entries(s.topics||{}).forEach(([topic,v])=>{if(!v?.total)return;topics.set(topic,{topic,overallTotal:v.total,overallCorrect:v.correct||0,overallAcc:Math.round((v.correct||0)/v.total*100),recentTotal:0,recentCorrect:0,recentAcc:null})});recent.forEach(x=>{const k=x.topic||'綜合';if(!topics.has(k))topics.set(k,{topic:k,overallTotal:0,overallCorrect:0,overallAcc:null,recentTotal:0,recentCorrect:0,recentAcc:null});const t=topics.get(k);t.recentTotal++;if(x.correct)t.recentCorrect++});for(const t of topics.values()){if(t.recentTotal)t.recentAcc=Math.round(t.recentCorrect/t.recentTotal*100);const o=t.overallAcc,r=t.recentAcc;t.delta=o!=null&&r!=null?r-o:null;if(t.recentTotal>=3&&t.delta>=15)t.state='improving';else if(t.recentTotal>=3&&t.delta<=-15)t.state='declining';else if((r!=null&&t.recentTotal>=3?r:o)!=null&&(r!=null&&t.recentTotal>=3?r:o)<70)t.state='weak';else t.state='stable'}return[...topics.values()].sort((a,b)=>{const rank={weak:0,declining:1,improving:2,stable:3};return rank[a.state]-rank[b.state]||(a.recentAcc??a.overallAcc??100)-(b.recentAcc??b.overallAcc??100)||b.overallTotal-a.overallTotal})}
 const topicMetric=topic=>metrics().find(x=>x.topic===topic)||{topic,overallTotal:0,overallAcc:null,recentTotal:0,recentAcc:null,delta:null,state:'stable'};
 function badge(x){if(x.state==='improving')return'↗ 正在進步';if(x.state==='declining')return'↘ 最近下滑';if(x.state==='weak')return'🩹 目前弱點';return'→ 穩定'}
 function syncAll(){render();window.PersonalExamPriority?.render?.(document.getElementById('personalPriorityRadar')?.dataset.level||'');window.DailyExamMission?.render?.();window.dispatchEvent(new CustomEvent('musicExamWeaknessTrendUpdated'))}
 function capture(){const fb=document.getElementById('feedback');if(!fb||fb.classList.contains('hidden'))return;const id=document.getElementById('sourceBox')?.textContent?.match(/題號：([^\s]+)/)?.[1],q=qs().find(x=>String(x.id)===String(id));if(!q)return;const s=load(STATS,{attempts:{}}),a=s.attempts?.[q.id];if(!a?.total)return;const attemptNo=Number(a.total||0),attemptAt=Number(a.lastAt||Date.now()),signature=`${q.id}:${attemptNo}`,log=readLog();if(log.some(x=>`${x.id}:${x.attemptNo||0}`===signature))return;const title=document.getElementById('feedbackTitle')?.textContent||'',status=a.lastStatus|| (title.includes('我不知道')?'unknown':title.includes('答對')?'correct':'wrong'),row={key:`${q.id}:${attemptNo}:${attemptAt}`,id:String(q.id),attemptNo,attemptAt,topic:q.topic||q.subject||'綜合',subject:q.subject||'',status,correct:status==='correct',at:attemptAt};log.push(row);save(LOG,normalizeLog(log));window.dispatchEvent(new CustomEvent('musicExamAttemptLogged',{detail:{id:String(q.id),attemptNo,topic:row.topic,status}}));const session=load(SESSION,null);if(session?.active&&session.topic===row.topic){session.results=session.results||{};session.results[`${q.id}:${attemptNo}`]={status,correct:status==='correct',at:attemptAt};save(SESSION,session);if(Object.keys(session.results).length>=session.target){session.active=false;session.completedAt=Date.now();session.after=topicMetric(session.topic);save(SESSION,session);renderReport(session)}}syncAll()}
 function startTopic(topic){const pool=qs().filter(q=>(q.topic||q.subject||'綜合')===topic);if(!pool.length)return;const target=Math.min(10,pool.length),before=topicMetric(topic);save(SESSION,{topic,target,before,results:{},active:true,startedAt:Date.now()});window.MusicTeacherExam?.startCustomQuiz(pool,`🩹 弱點追蹤｜${topic}`,target)}
 function mount(){const home=document.getElementById('homeView');if(!home||document.getElementById('mtWeakTraining'))return;const sec=document.createElement('section');sec.id='mtWeakTraining';sec.className='card section-card';sec.style.display='none';home.appendChild(sec);render();restoreReport();window.HomeCategoryOrganizer?.apply?.()}
 function render(){const box=document.getElementById('mtWeakTraining');if(!box)return;const rows=metrics().filter(x=>x.overallTotal||x.recentTotal),hasRecent=readLog().length>0;box.innerHTML=`<div class="section-title"><div><span class="eyebrow">整體表現 × 近 14 天</span><h3>🩹 弱點趨勢</h3></div></div><p class="muted">近期趨勢只計一次真正作答；同一題同一次作答即使畫面重繪多次，也不會重複灌入統計。</p>${!hasRecent?'<div style="padding:11px;border:1px dashed var(--border);border-radius:11px;margin:10px 0" class="muted">近期趨勢會從新版開始累積；舊資料仍保留作為「整體表現」。再做幾題後，就會開始看得出變化。</div>':''}<div style="display:grid;gap:8px;margin-top:12px">${rows.slice(0,10).map(x=>`<div style="border:1px solid var(--line);border-radius:12px;padding:11px"><div style="display:flex;justify-content:space-between;gap:8px;align-items:center;flex-wrap:wrap"><b>${esc(x.topic)}</b><span class="pill">${badge(x)}</span></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:8px"><div><small class="muted">整體</small><div style="font-size:21px;font-weight:850">${x.overallAcc??'--'}%</div><small class="muted">${x.overallTotal} 題次</small></div><div><small class="muted">近 14 天</small><div style="font-size:21px;font-weight:850">${x.recentAcc??'--'}%</div><small class="muted">${x.recentTotal} 題次${x.delta!=null?`｜${x.delta>0?'+':''}${x.delta}%`:''}</small></div></div><button class="ghost small weak-topic-practice" data-topic="${esc(x.topic)}" style="margin-top:8px" type="button">🎯 練這個主題</button></div>`).join('')||'<p class="muted">作答後會開始分析。</p>'}</div>`;box.querySelectorAll('.weak-topic-practice').forEach(b=>b.onclick=()=>startTopic(b.dataset.topic))}
 function renderReport(x){const home=document.getElementById('homeView');if(!home||!x?.completedAt)return;let box=document.getElementById('weakTrendDrillReport');if(!box){box=document.createElement('section');box.id='weakTrendDrillReport';box.className='card section-card';const weak=document.getElementById('mtWeakTraining');weak?.insertAdjacentElement('afterend',box)||home.appendChild(box)}const before=x.before||{},after=x.after||topicMetric(x.topic),rs=Object.values(x.results||{}),correct=rs.filter(r=>r.correct).length,total=rs.length,pct=total?Math.round(correct/total*100):0,beforeRecent=before.recentAcc,afterRecent=after.recentAcc,change=beforeRecent!=null&&afterRecent!=null?afterRecent-beforeRecent:null;box.innerHTML=`<div class="section-title"><div><span class="eyebrow">WEAKNESS DRILL RESULT</span><h3>🎯 ${esc(x.topic)}｜弱點練習成果</h3></div><span class="pill">${pct}%</span></div><p>這輪完成 ${total} 題，答對 ${correct} 題。弱點趨勢已立即重新計算。</p><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:10px 0"><div style="padding:10px;border:1px solid var(--line);border-radius:11px"><small>練習前近14天</small><b style="display:block;font-size:24px">${beforeRecent??'--'}${beforeRecent==null?'':'%'}</b></div><div style="padding:10px;border:1px solid var(--line);border-radius:11px"><small>現在近14天</small><b style="display:block;font-size:24px">${afterRecent??'--'}${afterRecent==null?'':'%'}</b></div><div style="padding:10px;border:1px solid var(--line);border-radius:11px"><small>目前狀態</small><b style="display:block;font-size:16px">${badge(after)}</b></div></div><p class="muted">${change==null?'近期資料仍在累積；這輪作答已寫入趨勢紀錄。':change>0?`近14天正確率提升 ${change} 個百分點；如果持續穩定，這個主題會逐步從每日弱點補強中降權。`:change<0?`近14天正確率變化 ${change} 個百分點；系統會暫時提高這個主題的補強優先度。`:'近14天正確率目前持平，後續作答會繼續更新趨勢。'}</p><button class="ghost small" id="dismissWeakTrendReport" type="button">知道了</button>`;box.querySelector('#dismissWeakTrendReport').onclick=()=>box.remove();window.HomeCategoryOrganizer?.apply?.()}
 function restoreReport(){const x=load(SESSION,null);if(x&&!x.active&&x.completedAt&&Date.now()-x.completedAt<12*3600000)renderReport(x)}
 function bind(){normalizeLog(load(LOG,[]));mount();const fb=document.getElementById('feedback');if(fb&&!fb.dataset.weakTrendObserved){fb.dataset.weakTrendObserved='1';new MutationObserver(()=>{if(!fb.classList.contains('hidden'))setTimeout(capture,30)}).observe(fb,{attributes:true,attributeFilter:['class']})}window.addEventListener('storage',e=>{if([STATS,LOG].includes(e.key))syncAll()});window.addEventListener('musicExamLearningSynced',()=>{syncAll();restoreReport()});window.addEventListener('pageshow',restoreReport)}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(bind,1100),{once:true});else setTimeout(bind,150);window.WeaknessTrend={metrics,render,startTopic,topicMetric,renderReport,readLog,normalizeLog};
})();