(()=>{
 if(window.__WEAKNESS_TREND_V1__)return;window.__WEAKNESS_TREND_V1__=true;
 const STATS='musicTeacherExamStatsV1',LOG='musicTeacherExamAttemptLogV1';
 const load=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}},save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
 const qs=()=>window.MusicTeacherExam?.questions||[],esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function capture(){const fb=document.getElementById('feedback');if(!fb||fb.classList.contains('hidden'))return;const id=document.getElementById('sourceBox')?.textContent?.match(/題號：([^\s]+)/)?.[1],q=qs().find(x=>String(x.id)===String(id));if(!q)return;const s=load(STATS,{attempts:{}}),a=s.attempts?.[q.id],key=`${q.id}:${a?.total||0}`;const log=load(LOG,[]);if(log.some(x=>x.key===key))return;const title=document.getElementById('feedbackTitle')?.textContent||'',status=title.includes('我不知道')?'unknown':title.includes('答對')?'correct':'wrong';log.push({key,id:String(q.id),topic:q.topic||q.subject||'綜合',subject:q.subject||'',status,correct:status==='correct',at:Date.now()});save(LOG,log.slice(-1500));render()}
 function metrics(){const s=load(STATS,{topics:{}}),log=load(LOG,[]),cut=Date.now()-14*86400000,recent=log.filter(x=>x.at>=cut),topics=new Map();Object.entries(s.topics||{}).forEach(([topic,v])=>{if(!v?.total)return;topics.set(topic,{topic,overallTotal:v.total,overallCorrect:v.correct||0,overallAcc:Math.round((v.correct||0)/v.total*100),recentTotal:0,recentCorrect:0,recentAcc:null})});recent.forEach(x=>{const k=x.topic||'綜合';if(!topics.has(k))topics.set(k,{topic:k,overallTotal:0,overallCorrect:0,overallAcc:null,recentTotal:0,recentCorrect:0,recentAcc:null});const t=topics.get(k);t.recentTotal++;if(x.correct)t.recentCorrect++});for(const t of topics.values()){if(t.recentTotal)t.recentAcc=Math.round(t.recentCorrect/t.recentTotal*100);const o=t.overallAcc,r=t.recentAcc;t.delta=o!=null&&r!=null?r-o:null;if(t.recentTotal>=3&&t.delta>=15)t.state='improving';else if(t.recentTotal>=3&&t.delta<=-15)t.state='declining';else if((r!=null&&t.recentTotal>=3?r:o)!=null&&(r!=null&&t.recentTotal>=3?r:o)<70)t.state='weak';else t.state='stable'}return[...topics.values()].sort((a,b)=>{const rank={weak:0,declining:1,improving:2,stable:3};return rank[a.state]-rank[b.state]||(a.recentAcc??a.overallAcc??100)-(b.recentAcc??b.overallAcc??100)||b.overallTotal-a.overallTotal})}
 function startTopic(topic){const pool=qs().filter(q=>(q.topic||q.subject||'綜合')===topic);if(!pool.length)return;window.MusicTeacherExam?.startCustomQuiz(pool,`🩹 弱點追蹤｜${topic}`,Math.min(10,pool.length))}
 function mount(){const home=document.getElementById('homeView');if(!home||document.getElementById('mtWeakTraining'))return;const sec=document.createElement('section');sec.id='mtWeakTraining';sec.className='card section-card';sec.style.display='none';home.appendChild(sec);render();window.HomeCategoryOrganizer?.apply?.()}
 function badge(x){if(x.state==='improving')return'↗ 正在進步';if(x.state==='declining')return'↘ 最近下滑';if(x.state==='weak')return'🩹 目前弱點';return'→ 穩定'}
 function render(){const box=document.getElementById('mtWeakTraining');if(!box)return;const rows=metrics().filter(x=>x.overallTotal||x.recentTotal),hasRecent=load(LOG,[]).length>0;box.innerHTML=`<div class="section-title"><div><span class="eyebrow">整體表現 × 近 14 天</span><h3>🩹 弱點趨勢</h3></div></div><p class="muted">不再只看歷史累積正確率。近期表現會和整體表現一起判讀，避免早期失分讓一個已經進步的主題永遠被標成弱點。</p>${!hasRecent?'<div style="padding:11px;border:1px dashed var(--border);border-radius:11px;margin:10px 0" class="muted">近期趨勢會從新版開始累積；舊資料仍保留作為「整體表現」。再做幾題後，就會開始看得出變化。</div>':''}<div style="display:grid;gap:8px;margin-top:12px">${rows.slice(0,10).map(x=>`<div style="border:1px solid var(--line);border-radius:12px;padding:11px"><div style="display:flex;justify-content:space-between;gap:8px;align-items:center;flex-wrap:wrap"><b>${esc(x.topic)}</b><span class="pill">${badge(x)}</span></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:8px"><div><small class="muted">整體</small><div style="font-size:21px;font-weight:850">${x.overallAcc??'--'}%</div><small class="muted">${x.overallTotal} 題次</small></div><div><small class="muted">近 14 天</small><div style="font-size:21px;font-weight:850">${x.recentAcc??'--'}%</div><small class="muted">${x.recentTotal} 題次${x.delta!=null?`｜${x.delta>0?'+':''}${x.delta}%`:''}</small></div></div><button class="ghost small weak-topic-practice" data-topic="${esc(x.topic)}" style="margin-top:8px" type="button">🎯 練這個主題</button></div>`).join('')||'<p class="muted">作答後會開始分析。</p>'}</div>`;box.querySelectorAll('.weak-topic-practice').forEach(b=>b.onclick=()=>startTopic(b.dataset.topic))}
 function bind(){mount();const fb=document.getElementById('feedback');if(fb&&!fb.dataset.weakTrendObserved){fb.dataset.weakTrendObserved='1';new MutationObserver(()=>{if(!fb.classList.contains('hidden'))setTimeout(capture,30)}).observe(fb,{attributes:true,attributeFilter:['class']})}window.addEventListener('storage',e=>{if([STATS,LOG].includes(e.key))render()});window.addEventListener('musicExamLearningSynced',render)}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(bind,1100),{once:true});else setTimeout(bind,150);window.WeaknessTrend={metrics,render,startTopic};
})();