// 115 首頁｜最近7天學習節奏與後設認知
(function(){
 if(window.__WEEKLY_RHYTHM115__)return;window.__WEEKLY_RHYTHM115__=true;
 var KEY='musicTeacherExamWeeklyRhythm115V1';
 function load(){try{return JSON.parse(localStorage.getItem(KEY))||{days:{}}}catch(e){return{days:{}}}}function save(s){localStorage.setItem(KEY,JSON.stringify(s||{days:{}}))}
 function dateKey(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
 function today(){return dateKey(new Date())}
 function mark(type){var s=load();s.days=s.days||{};s.days[today()]=s.days[today()]||{};s.days[today()][type]=(s.days[today()][type]||0)+1;s.days[today()].updatedAt=Date.now();save(s);render()}
 var types={quiz:['🎯','做題'],battle:['👹','辨析'],speak:['🎙️','口述'],grid:['🧩','九宮格'],output:['✍️','作品輸出']};
 function seven(){var s=load(),out=[];for(var i=6;i>=0;i--){var d=new Date();d.setDate(d.getDate()-i);var k=dateKey(d),x=(s.days||{})[k]||{};out.push({key:k,label:(d.getMonth()+1)+'/'+d.getDate(),data:x,total:Object.keys(types).reduce(function(n,t){return n+(x[t]||0)},0)})}return out}
 function totals(){var z={quiz:0,battle:0,speak:0,grid:0,output:0};seven().forEach(function(d){Object.keys(z).forEach(function(k){z[k]+=d.data[k]||0})});return z}
 function advice(z){var active=Object.keys(z).filter(function(k){return z[k]>0}),sum=Object.values(z).reduce(function(a,b){return a+b},0);if(!sum)return'這7天還沒有足夠紀錄。今天從10題開始，先讓系統認識你的學習節奏。';if(active.length<=2)return'這週的學習方式比較集中。下一次可以刻意換一種方式，例如把「看懂」改成口述、辨析或自己出題。';var max=Object.keys(z).sort(function(a,b){return z[b]-z[a]})[0];if(z[max]>=Math.ceil(sum*.65))return'最近比較依賴「'+types[max][1]+'」。不是不好，但可以加入另一種輸出方式，確認自己不是只有熟悉感。';if(!z.output)return'這週已經有不錯的練習變化；下一步可以留下一個自己的定義、題目或教學說法，把理解轉成作品。';return'這週已經有做題、辨析與輸出的交替。維持這種節奏，不需要每天把所有類型都做一遍。'}
 function render(){var host=document.getElementById('hf115GuideStart');if(!host)return false;document.getElementById('hf115WeeklyRhythm')?.remove();var ds=seven(),z=totals(),box=document.createElement('div');box.id='hf115WeeklyRhythm';box.style.cssText='padding:14px;border:1px solid rgba(127,127,127,.16);border-radius:16px;background:rgba(127,127,127,.025);margin-top:12px';box.innerHTML='<span class="eyebrow">後設認知｜不是比誰打卡多</span><h3 style="margin:5px 0">🗓️ 最近7天，我是怎麼學的？</h3><div style="display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:5px;margin:12px 0">'+ds.map(function(d){var dots=Object.keys(types).filter(function(k){return d.data[k]>0}).map(function(k){return types[k][0]}).join('');return'<div style="text-align:center;padding:7px 2px;border-radius:10px;background:rgba(127,127,127,.06);min-height:58px"><small>'+d.label+'</small><div style="font-size:.85rem;margin-top:5px;word-break:break-all">'+(dots||'·')+'</div></div>'}).join('')+'</div><div class="hf115-badges">'+Object.keys(types).map(function(k){return'<span class="hf115-badge">'+types[k][0]+' '+types[k][1]+' '+z[k]+'</span>'}).join('')+'</div><p class="hf115-note" style="margin:10px 0 0"><b>學習提醒：</b>'+advice(z)+'</p>';host.appendChild(box);return true}
 function patchClicks(){[['hf115QuizBtn','quiz'],['hf115BattleBtn','battle'],['hf115OralBtn','speak'],['selfStudy115Btn','grid']].forEach(function(x){var b=document.getElementById(x[0]);if(b&&!b.dataset.rhythm115){b.dataset.rhythm115='1';b.addEventListener('click',function(){mark(x[1])})}});document.querySelectorAll('#selfStudy115 [data-mission]').forEach(function(b){if(!b.dataset.rhythmOut){b.dataset.rhythmOut='1';b.addEventListener('click',function(){var id=b.dataset.mission;if(['write','create','play','think','draw','teach','see','hear','read'].includes(id))mark('output')})}})}
 function boot(){var n=0,t=setInterval(function(){n++;patchClicks();render();if(n>40)clearInterval(t)},350)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();window.WeeklyRhythm115={load:load,mark:mark,seven:seven,totals:totals,render:render};
})();