(()=>{
 if(window.__WRONG_BOOK_VIEWS_V1__)return;window.__WRONG_BOOK_VIEWS_V1__=true;
 const STATS='musicTeacherExamStatsV1',SRS='musicTeacherExamSpacedReviewV1';
 const load=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}},qs=()=>window.MusicTeacherExam?.questions||[];
 function historyPool(){const s=load(STATS,{attempts:{}});return qs().filter(q=>{const a=s.attempts?.[q.id];return !!a&&((a.total||0)>(a.correct||0)||(a.unknown||0)>0)})}
 function currentPool(){const s=load(STATS,{attempts:{},wrong:[],unknown:[]}),r=load(SRS,{}),api=window.MusicTeacherSRS;return qs().filter(q=>{if(api?.effectiveRisk)return !!api.effectiveRisk(q,r,s);const x=r[q.id]||{},streak=x.correctStreak||0,id=String(q.id),unknown=new Set((s.unknown||[]).map(String)),wrong=new Set((s.wrong||[]).map(String));if(x.lastResult==='unknown'||unknown.has(id))return true;if(x.lastResult==='wrong')return true;if(streak>=2)return false;return wrong.has(id)})}
 function start(pool,label){if(!pool.length){alert(label.includes('目前')?'目前沒有需要補強的錯題 🎉':'目前還沒有歷史錯題紀錄。');return}window.MusicTeacherExam?.startCustomQuiz(pool,label,pool.length)}
 function refresh(){const current=currentPool(),history=historyPool(),count=document.getElementById('wrongCount');if(count)count.textContent=current.length;const label=count?.closest('.stat')?.querySelector('.label');if(label)label.textContent='目前需補強';const btn=document.querySelector('[data-mode="wrong"]');if(btn){btn.dataset.wrongView='current';btn.querySelector('b')&&(btn.querySelector('b').textContent='目前需補強');btn.querySelector('small')&&(btn.querySelector('small').textContent=`現在仍不穩 ${current.length} 題｜連對 2 次可畢業`);let hist=document.getElementById('wrongHistoryBtn');if(!hist){hist=document.createElement('button');hist.id='wrongHistoryBtn';hist.className='mode-card';hist.type='button';hist.innerHTML='<span class="mode-icon">🗃️</span><b>歷史曾錯</b><small></small>';btn.insertAdjacentElement('afterend',hist);hist.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();start(historyPool(),'🗃️ 歷史曾錯題')})}hist.querySelector('small').textContent=`保留曾經答錯／不知道的 ${history.length} 題`}}
 document.addEventListener('click',e=>{const b=e.target.closest('[data-mode="wrong"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();start(currentPool(),'❌ 目前需補強')},true);
 function watch(){refresh();window.addEventListener('storage',e=>{if([STATS,SRS].includes(e.key))refresh()});window.addEventListener('musicExamLearningSynced',refresh);const fb=document.getElementById('feedback');if(fb&&!fb.dataset.wrongViewsObserved){fb.dataset.wrongViewsObserved='1';new MutationObserver(()=>{if(!fb.classList.contains('hidden'))setTimeout(refresh,80)}).observe(fb,{attributes:true,attributeFilter:['class']})}}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(watch,250),{once:true});else setTimeout(watch,250);
 window.WrongBookViews={currentPool,historyPool,refresh};
})();